### ISSUE TITLE
支持混合推理后，中英文混合训练会有支持吗

### ISSUE THREAD

**Issue by WinterStraw** [RVC-Boss/GPT-SoVITS#1005]
训练的时候目前好像会自动忽视掉英文部分

**Comment by XXXXRT666** [comment]
单条语音只能有一种语言

**Comment by RVC-Boss** [comment]
目前训练还没支持混合语言，因为担心混合语言前端会有坑，推理阶段还好，发现提出来修改就行了，训练的话可能就得重训了，成本比较大，所以用的单语言保守的
