### ISSUE TITLE
合成的音频没有声音，可能是什么原因呢？

### ISSUE THREAD

**Issue by atfeel** [RVC-Boss/GPT-SoVITS#1006]
合成的音频没有声音，控制台没有显示异常，可能是什么原因呢？
![aa](https://github.com/RVC-Boss/GPT-SoVITS/assets/64597127/7aacc8d2-23b4-44cc-8b71-9967c3d526e8)

**Comment by atfeel** [comment]
![cc](https://github.com/RVC-Boss/GPT-SoVITS/assets/64597127/28a8b504-7afa-4eca-86c0-57da1197820d)
我用的显卡是 nvidia geforce gtx1660，我不训练，只是用于推理，用的自带模型，默认参数

**Comment by atfeel** [comment]
合成音频有长度，但没有波形，就一条直线

**Comment by XXXXRT666** [comment]
半精度，inference_webui中强制is_half=False

**Comment by RVC-Boss** [comment]
嗯
