### ISSUE TITLE
推理得到音频包含了参考音频

### ISSUE THREAD

**Issue by jax-explorer** [RVC-Boss/GPT-SoVITS#1007]
推理得到音频包含了参考音频部分。

**Comment by neoyxm** [comment]
请问如何解决了这个问题？ 是更新最新代码?

**Comment by FURYFOR** [comment]
我也遇到了相同的问题，请问是什么原因导致的呢？

**Comment by neoyxm** [comment]
> 我也遇到了相同的问题，请问是什么原因导致的呢？

临时解决办法，不要使用很短的文本， 一般一个字或两个字，很容易出问题

**Comment by Thinking80s** [comment]
遇到同样问题
