### ISSUE TITLE
Error Message: hipFFT doesn't support transforms of type: Half

### ISSUE THREAD

**Issue by GUUser91** [RVC-Boss/GPT-SoVITS#1009]
I followed the instruction from this link and I still get the same error message.
https://zhuanlan.zhihu.com/p/681958706
Edit: I copied the lines from the webui.py file and I still get the same error message.
https://pan.quark.cn/s/741c33f0cf30#/list/share/28d83a262377406e8b26dfbf6ec869ec-ubuntu_amd_gpt_sovits

**Comment by SapphireLab** [comment]
I compare the file with `webui.py` and find it doesn't set `is_half=False` explicitly.
So it will import the value from `config.py` and you should set `is_half=False` in `webui.py` or `config.py`

! Note that this file is not up to date with `main` branch.

**Comment by GUUser91** [comment]
@SapphireLab
I still get the same error message with the webui.py file from the main branch.

**Comment by SapphireLab** [comment]
> @SapphireLab
> I still get the same error message with the webui.py file from the main branch.

Have you set the `is_half＝False` in `config.py`?

**Comment by GUUser91** [comment]
Okay, I fixed the problem. I created a venv folder with python3.11. That must have caused the problem. I created a new venv folder with python3.10 and now I no longer get the error message.
