### ISSUE TITLE
api.py not work due to incorrect module path

### ISSUE THREAD

**Issue by qingyuan18** [RVC-Boss/GPT-SoVITS#1011]
Traceback (most recent call last): File "/opt/program/api.py", line 134, in <module> from feature_extractor import cnhubert
-- | --
  | 2024-04-24T09:23:04.195ZModuleNotFoundError: No module named 'feature_extractor'

the api.py is layed on top folder of GPT-SoVITS, but feature_extractor is layed on sub GPT_SoVITS
<img width="424" alt="image" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/35717759/e1ae9420-dc0b-458a-b98d-d4c290b0fb2d">

I'm trying to add the path into it :

current_dir = os.path.dirname(os.path.abspath(__file__))
sub_gpt_sovits_folder = os.path.join(current_dir, 'GPT_SoVITS')
sys.path.append(sub_gpt_sovits_folder)

**Comment by RVC-Boss** [comment]
好，欢迎pr

**Comment by RVC-Boss** [comment]
楼主看看这个pr？我已经合了，有没有解决你的问题

**Comment by qingyuan18** [comment]
谢谢啊，我已经在我的环境中解决了，呵呵



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 28, 2024 17:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [RVC-Boss/GPT-SoVITS] api.py not work due to incorrect modulepath (Issue #1011)




 
楼主看看这个pr？我已经合了，有没有解决你的问题

**Comment by 370281jay** [comment]
> 楼主看看这个pr？我已经合了，有没有解决你的问题

<img width="396" alt="屏幕截图 2024-04-28 230739" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/62932435/561077b7-8fa6-4437-a6a3-5f67a6ab5544">
<img width="470" alt="屏幕截图 2024-04-28 230815" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/62932435/520ad198-7f2e-4534-867e-5acfc46649b6">
没解决，还是不行

**Comment by XXXXRT666** [comment]
你的api就不应该在runtime里
