### ISSUE TITLE
No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by zericli090725** [RVC-Boss/GPT-SoVITS#1019]
Could someone help me with this issue
<img width="697" alt="Screenshot 2024-04-25 at 09 51 01" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/118988701/b2ea355b-19a5-41be-b38a-41e432e2011f">

**Comment by zericli090725** [comment]
I have followed the guide but i get this error in this step
<img width="885" alt="Screenshot 2024-04-25 at 09 52 58" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/118988701/a46e4dbc-bda1-4627-9009-adc8d86444de">

**Comment by zericli090725** [comment]
nevermind, it was stupid

**Comment by XXXXRT666** [comment]
I'm wondering why miniconda/env/GPT-SoVITS
