### ISSUE TITLE
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

### ISSUE THREAD

**Issue by aimarxjg** [RVC-Boss/GPT-SoVITS#102]
File "E:\GPT-SoVITS\tools\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "E:\GPT-SoVITS\runtime\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\GPT-SoVITS\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 92, in <module>
    name2go(wav_name)
  File "E:\GPT-SoVITS\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 60, in name2go
    tmp_audio = load_audio(wav_path, 32000)
  File "E:\GPT-SoVITS\tools\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

**Comment by benheinen** [comment]
If you haven't already take a look at the install file. 

Ensure you have installed FFmpeg:

`conda install ffmpeg cmake`

**Comment by lakerwe** [comment]
> File "E:\GPT-SoVITS\tools\my_utils.py", line 14, in load_audio ffmpeg.input(file, threads=0) File "E:\GPT-SoVITS\runtime\lib\site-packages\ffmpeg_run.py", line 325, in run raise Error('ffmpeg', out, err) ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "E:\GPT-SoVITS\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 92, in name2go(wav_name) File "E:\GPT-SoVITS\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 60, in name2go tmp_audio = load_audio(wav_path, 32000) File "E:\GPT-SoVITS\tools\my_utils.py", line 19, in load_audio raise RuntimeError(f"Failed to load audio: {e}") RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)

hey did you fix it, i meet the same problem

**Comment by hhucchenyixiao** [comment]
> > File "E:\GPT-SoVITS\tools\my_utils.py", line 14, in load_audio ffmpeg.input(file, threads=0) File "E:\GPT-SoVITS\runtime\lib\site-packages\ffmpeg_run.py", line 325, in run raise Error('ffmpeg', out, err) ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "E:\GPT-SoVITS\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 92, in name2go(wav_name) File "E:\GPT-SoVITS\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 60, in name2go tmp_audio = load_audio(wav_path, 32000) File "E:\GPT-SoVITS\tools\my_utils.py", line 19, in load_audio raise RuntimeError(f"Failed to load audio: {e}") RuntimeError: Failed to load audio: ffmpeg error (see stderr output for detail)
> 
> hey did you fix it, i meet the same problem

I have found the reason. If you forget to fill in the "Training Set Audio File Directory" in step "1A - Training Set Formatting Tool", this error will be reported.
我找到原因了，如果在"1A-训练集格式化工具"那一步忘了填写 "训练集音频文件目录" 就会报这个错误

**Comment by RVC-Boss** [comment]
whole trainset file path= Training Set Audio File Directory+the filename in the .list file

**Comment by juanram0n** [comment]
> If you haven't already take a look at the install file.
> 
> Ensure you have installed FFmpeg:
> 
> `conda install ffmpeg cmake`

It worked for me, thanks!!
