### ISSUE TITLE
API调用时，如何传参表达“Slice once every 4 sentences”这一选项？

### ISSUE THREAD

**Issue by zhangjh** [RVC-Boss/GPT-SoVITS#1025]
推理时，有选项“Slice once every 4 sentences”，如何在API调用时传递？看了下api.py貌似没有支持这一选项？
How to pass the option "Slice once every 4 sentences" when calling the API? I checked api.py and it doesn't seem to support this option?

**Comment by XXXXRT666** [comment]
没这个选项，支持标点符号切分，或者是也可以用gradio API，这个用法跟webUI一致

**Comment by zhangjh** [comment]
ok.Got it.
