### ISSUE TITLE
ASR cannot working

### ISSUE THREAD

**Issue by SimpleJoeie** [RVC-Boss/GPT-SoVITS#1032]
Running on local URL:  http://0.0.0.0:9874
"/opt/miniconda3/envs/GPTSoVits/bin/python" tools/asr/fasterwhisper_asr.py -i "output/denoise_opt" -o "output/asr_opt" -s large-v3 -l ja -p float32
loading faster whisper model: large-v3 large-v3
  0%|                                                                                                                                                       | 0/10 [00:00<?, ?it/s]/opt/miniconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
"/opt/miniconda3/envs/GPTSoVits/bin/python" tools/asr/fasterwhisper_asr.py -i "./output/denoise_opt" -o "output/asr_opt" -s large-v3 -l ja -p float32
loading faster whisper model: large-v3 large-v3
  0%|                                                                                                                                                       | 0/10 [00:00<?, ?it/s]/opt/miniconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
"/opt/miniconda3/envs/GPTSoVits/bin/python" tools/asr/fasterwhisper_asr.py -i "./output/denoise_opt" -o "output/asr_opt" -s small -l ja -p float32
loading faster whisper model: small small
config.json: 2.37kB [00:00, 371kB/s]                                                                                                                                               
vocabulary.txt: 460kB [00:00, 788kB/s] 
tokenizer.json: 2.20MB [00:00, 2.45MB/s]                                                                                                                | 0.00/484M [00:00<?, ?B/s]
model.bin: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 484M/484M [20:37<00:00, 391kB/s]
 10%|██████████████▎                                                                                                                                | 1/10 [00:04<00:41,  4.59s/it]/opt/miniconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by SimpleJoeie** [comment]
macos 12.6.3 
intel
ffmpeg 7.0

**Comment by XXXXRT666** [comment]
没看到报错，如果明确是warning导致的问题可以环境变量关闭这个warning

**Comment by SapphireLab** [comment]
did you install the miniconda in x86_64 way? check your `conda-info` info
if x86_64, it may cause problem in CTtranslated2 to stop the faster whisper.

**Comment by XXXXRT666** [comment]
> did you install the miniconda in x86_64 way? check your `conda-info` info
> 
> if x86_64, it may cause problem in CTtranslated2 to stop the faster whisper.

I think Intel Mac is X86_64, anyway,only macOS Sonoma support FFT, so there will be some error while training

**Comment by xtopass** [comment]
达摩的ASR 下载出现了问题。
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/59379446/6f4406cb-8bdf-421c-8b4e-412884b63128)

**Comment by xtopass** [comment]
<img width="1350" alt="pc_2024-04-28_20-43-26" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/59379446/0fe4e087-214d-4f4a-8d3a-14f6f1e4b7d1">

**Comment by SapphireLab** [comment]
> 达摩的ASR 下载出现了问题。有人和我出现了同样的问题吗？需要怎样解决

换个网络吧，能上modelscope的话直接访问然后下载也可以. 可能是api不太对劲.

**Comment by XXXXRT666** [comment]
https://github.com/SYSTRAN/faster-whisper/issues/345 this might help

**Comment by etdapt** [comment]
I have been facing same issue... I debug-stepped through fasterwhisper_asr.py and found that it is failing whiling looping through the segments returned from mode.transcribe()


> Running on local URL: http://0.0.0.0:9874 "/opt/miniconda3/envs/GPTSoVits/bin/python" tools/asr/fasterwhisper_asr.py -i "output/denoise_opt" -o "output/asr_opt" -s large-v3 -l ja -p float32 loading faster whisper model: large-v3 large-v3 0%| | 0/10 [00:00<?, ?it/s]/opt/miniconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d ' "/opt/miniconda3/envs/GPTSoVits/bin/python" tools/asr/fasterwhisper_asr.py -i "./output/denoise_opt" -o "output/asr_opt" -s large-v3 -l ja -p float32 loading faster whisper model: large-v3 large-v3 0%| | 0/10 [00:00<?, ?it/s]/opt/miniconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d ' "/opt/miniconda3/envs/GPTSoVits/bin/python" tools/asr/fasterwhisper_asr.py -i "./output/denoise_opt" -o "output/asr_opt" -s small -l ja -p float32 loading faster whisper model: small small config.json: 2.37kB [00:00, 371kB/s] vocabulary.txt: 460kB [00:00, 788kB/s] tokenizer.json: 2.20MB [00:00, 2.45MB/s] | 0.00/484M [00:00<?, ?B/s] model.bin: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 484M/484M [20:37<00:00, 391kB/s] 10%|██████████████▎ | 1/10 [00:04<00:41, 4.59s/it]/opt/miniconda3/envs/GPTSoVits/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d '

**Comment by RVC-Boss** [comment]
> 达摩的ASR 下载出现了问题。有人和我出现了同样的问题吗？需要怎样解决
> 
> ![image](https://private-user-images.githubusercontent.com/59379446/326258138-6f4406cb-8bdf-421c-8b4e-412884b63128.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDc0MjgsIm5iZiI6MTcxNDQ0NzEyOCwicGF0aCI6Ii81OTM3OTQ0Ni8zMjYyNTgxMzgtNmY0NDA2Y2ItOGJkZi00MjFjLThiNGUtNDEyODg0YjYzMTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAzMTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOGZjMWRhYzk0ODE1NzI2Mjc4YzlkOTVhMWMwYzQ3ZTQyZGU4ZTA5MGJiMjVmYjA2MWMxODc4Y2E0NjQ0YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h5UmdCRs5cqZqMholiN8XdKuil8WT0hIGoIs0F3PGSE)

他这个每格可能有好几百M，比如你全下完了甚至下了一半才会更新一个超长的大格。所以应该只是下得慢？

**Comment by xtopass** [comment]
> 他这个每格可能有好几百M，比如你全下完了甚至下了一半才会更新一个超长的大格。所以应该只是下得慢？
多谢回复，我挂了几个小时，没有进度。一个840M大小的文件

**Comment by xtopass** [comment]
> > 达摩的ASR 下载出现了问题。有人和我出现了同样的问题吗？需要怎样解决
> 
> 换个网络吧，能上modelscope的话直接访问然后下载也可以. 可能是api不太对劲.
modelscope能直连，我感觉也是。

**Comment by xtopass** [comment]
今天已经下载好了！关于FSR的文件
