### ISSUE TITLE
执行pip install -r requirements.txt报错

### ISSUE THREAD

**Issue by NO1FFF** [RVC-Boss/GPT-SoVITS#1039]
![Uploading 屏幕截图 2024-05-01 150005.png…]()

**Comment by NO1FFF** [comment]
![屏幕截图 2024-05-01 150005](https://github.com/RVC-Boss/GPT-SoVITS/assets/150890698/e4f3be9e-3252-4001-a228-b4dc004168d1)

**Comment by xenosaga** [comment]
建議使用conda建立隔離環境，我用virtualenv安裝也是常有錯誤，但用conda建立的隔離環境就不會報錯

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/issues/613
参考这里
