### ISSUE TITLE
what is the resource requirements for GPU or CPU?

### ISSUE THREAD

**Issue by 4t8dd** [RVC-Boss/GPT-SoVITS#1041]
Can I try this with my small 5G GPU?
Or I have a M2 Mac Pro 16 CPU. 
Not sure if all my resource is usable?

**Comment by xenosaga** [comment]
Is your GPU NVIDIA or AMD? 
AMD GPUs require the 7000 series to support PyTorch, while NVIDIA GPUs need PyTorch with CUDA installed. 
M2 can use MPS, but currently, PyTorch's support isn't good enough.

**Comment by XXXXRT666** [comment]
The minimum requirement is 6G. And Mac is currently using CPU for training and inferences.

**Comment by XXXXRT666** [comment]
MPS has problem in training and memory leaks

**Comment by 4t8dd** [comment]
Oh. pytorch is not good enough and MPS is not supported well. How should I play this? CPU in Intel/x86 ?

**Comment by Lion-Wu** [comment]
It’s usable, you can set up the environment as described in the README file.
Currently, GPU training on Mac is not good enough, you might encounter memory leak issues, and the quality of the trained models is not good. Therefore, it's recommended to use the CPU. We will support GPU training on Mac once the stability is confirmed.

**Comment by XXXXRT666** [comment]
well, MPS is supported, but its performance isn't as good as we supposed, so the develop teams choose CPU instead, as it has a faster speed

**Comment by XXXXRT666** [comment]
Both X86 and ARM64 are supported.

**Comment by XXXXRT666** [comment]
MPS may have some problem in attentions, I supposed.

**Comment by 4t8dd** [comment]
OK. Thanks for the detailed explanation.
