### ISSUE TITLE
ASR：RuntimeError: CUDA failed

### ISSUE THREAD

**Issue by Carey8175** [RVC-Boss/GPT-SoVITS#1048]
服务器环境
pve虚拟机装centos8
显卡：Tesla M40
Driver Version: 515.105.01   
CUDA Version: 11.7 
torch:2.1.1(通过install.sh安装)

ASR运行报错：
RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version

**Comment by SapphireLab** [comment]
安装的 CUDA 版本超过驱动所能支持的 CUDA 版本了，你的 CUDA Version是用 `nvcc -V` 确认的吗？
要么升级驱动要么降级 CUDA, 对照表在[此处](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id6)

**Comment by Carey8175** [comment]
谢谢

**Comment by Shiyao-Huang** [comment]
+1 也遇到了这个问题
