### ISSUE TITLE
ASR的时候提示版本不兼容

### ISSUE THREAD

**Issue by nbu2024** [RVC-Boss/GPT-SoVITS#1063]
"/home/diffusion/anaconda3/envs/GPTSoVits/bin/python3" tools/asr/fasterwhisper_asr.py -i "input/slicer_opt" -o "output/asr_opt" -s large-v3-local -l auto -p float16
Traceback (most recent call last):
  File "/home/diffusion/GPT-SoVITS/tools/asr/fasterwhisper_asr.py", line 9, in <module>
    from faster_whisper import WhisperModel
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/faster_whisper/__init__.py", line 2, in <module>
    from faster_whisper.transcribe import WhisperModel
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/faster_whisper/transcribe.py", line 10, in <module>
    import ctranslate2
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/ctranslate2/__init__.py", line 55, in <module>
    from ctranslate2 import converters, models, specs
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/ctranslate2/converters/__init__.py", line 8, in <module>
    from ctranslate2.converters.transformers import TransformersConverter
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/ctranslate2/converters/transformers.py", line 14, in <module>
    import transformers
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/__init__.py", line 33, in <module>
    from .generic import (
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/generic.py", line 478, in <module>
    _torch_pytree.register_pytree_node(
AttributeError: module 'torch.utils._pytree' has no attribute 'register_pytree_node'

*************
conda info

     active environment : GPTSoVits
    active env location : /home/diffusion/anaconda3/envs/GPTSoVits
            shell level : 2
       user config file : /home/diffusion/.condarc
 populated config files :
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __cuda=11.6=0
                          __linux=5.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/diffusion/anaconda3  (writable)
      conda av data dir : /home/diffusion/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/diffusion/anaconda3/pkgs
                          /home/diffusion/.conda/pkgs
       envs directories : /home/diffusion/anaconda3/envs
                          /home/diffusion/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.2 CPython/3.9.13 Linux/5.4.0-150-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1010:1010
             netrc file : None
           offline mode : False

******************************
 conda list
# packages in environment at /home/diffusion/anaconda3/envs/GPTSoVits:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   2.1.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
aiohttp                   3.9.5                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
aliyun-python-sdk-core    2.15.1                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.2                   pypi_0    pypi
altair                    5.3.0                    pypi_0    pypi
annotated-types           0.6.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     4.3.0                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
audioread                 3.0.1                    pypi_0    pypi
av                        12.0.0                   pypi_0    pypi
beartype                  0.18.5                   pypi_0    pypi
binutils_impl_linux-64    2.40                 ha885e6a_0    conda-forge
blas                      1.0                         mkl
brotli-python             1.0.9            py39h6a678d5_8
bzip2                     1.0.8                h5eee18b_6
c-ares                    1.19.1               h5eee18b_0
ca-certificates           2024.3.11            h06a4308_0
certifi                   2024.2.2         py39h06a4308_0
cffi                      1.16.0                   pypi_0    pypi
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cmake                     3.26.4               h96355d8_0
cn2an                     0.5.22                   pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              42.0.7                   pypi_0    pypi
ctranslate2               4.2.1                    pypi_0    pypi
cuda-cudart               11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cycler                    0.12.1                   pypi_0    pypi
cython                    0.29.37                  pypi_0    pypi
datasets                  2.19.1                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
distance                  0.1.3                    pypi_0    pypi
dnspython                 2.6.1                    pypi_0    pypi
editdistance              0.8.1                    pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
email-validator           2.1.1                    pypi_0    pypi
exceptiongroup            1.2.1                    pypi_0    pypi
expat                     2.6.2                h6a678d5_0
fastapi                   0.111.0                  pypi_0    pypi
fastapi-cli               0.0.2                    pypi_0    pypi
faster-whisper            1.0.2                    pypi_0    pypi
ffmpeg                    4.2.2                h20bf706_0
ffmpeg-python             0.2.0                    pypi_0    pypi
ffmpy                     0.3.2                    pypi_0    pypi
filelock                  3.14.0                   pypi_0    pypi
flatbuffers               24.3.25                  pypi_0    pypi
fonttools                 4.51.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.3.1                 pypi_0    pypi
funasr                    1.0.0                    pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
g2p-en                    2.1.0                    pypi_0    pypi
gast                      0.5.4                    pypi_0    pypi
gcc                       13.2.0               hc7bed06_7    conda-forge
gcc_impl_linux-64         13.2.0               h9eb54c0_7    conda-forge
gmp                       6.2.1                h295c915_3
gmpy2                     2.1.2            py39heeb90bb_0
gnutls                    3.6.15               he1e5248_0
gradio                    3.38.0                   pypi_0    pypi
gradio-client             0.8.1                    pypi_0    pypi
grpcio                    1.63.0                   pypi_0    pypi
gxx                       13.2.0               hc7bed06_7    conda-forge
gxx_impl_linux-64         13.2.0               h2a599c4_7    conda-forge
h11                       0.14.0                   pypi_0    pypi
hdbscan                   0.8.33                   pypi_0    pypi
httpcore                  1.0.5                    pypi_0    pypi
httptools                 0.6.1                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
huggingface-hub           0.23.0                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
idna                      3.7              py39h06a4308_0
importlib-metadata        7.1.0                    pypi_0    pypi
importlib-resources       6.4.0                    pypi_0    pypi
inflect                   7.2.1                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306
jaconv                    0.3.4                    pypi_0    pypi
jamo                      0.4.1                    pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
jieba-fast                0.53                     pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1
jsonschema                4.22.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
kaldiio                   2.18.0                   pypi_0    pypi
kernel-headers_linux-64   2.6.32              he073ed8_17    conda-forge
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.20.1               h143b758_1
lame                      3.100                h7b6447c_0
langsegment               0.3.3                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.40                 h55db66e_0    conda-forge
lerc                      3.0                  h295c915_0
libcublas                 11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufile                 1.9.1.3                       0    nvidia
libcurand                 10.3.5.147                    0    nvidia
libcurl                   8.5.0                h251f7ec_0
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libdeflate                1.17                 h5eee18b_1
libedit                   3.1.20230828         h5eee18b_0
libev                     4.33                 h7f8727e_1
libffi                    3.4.4                h6a678d5_1
libgcc-devel_linux-64     13.2.0             hceb6213_107    conda-forge
libgcc-ng                 13.2.0               h77fa898_7    conda-forge
libgomp                   13.2.0               h77fa898_7    conda-forge
libidn2                   2.3.4                h5eee18b_0
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
libnghttp2                1.57.0               h2d74bed_0
libnpp                    11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libopus                   1.3.1                h7b6447c_0
libpng                    1.6.39               h5eee18b_0
librosa                   0.10.2                   pypi_0    pypi
libsanitizer              13.2.0               h6ddb7a1_7    conda-forge
libssh2                   1.10.0               hdbd6064_3
libstdcxx-devel_linux-64  13.2.0             hceb6213_107    conda-forge
libstdcxx-ng              13.2.0               hc0a3c3a_7    conda-forge
libtasn1                  4.19.0               h5eee18b_0
libtiff                   4.5.1                h6a678d5_0
libunistring              0.9.10               h27cfd23_0
libuv                     1.44.2               h5eee18b_0
libvpx                    1.7.0                h439df22_0
libwebp-base              1.3.2                h5eee18b_0
lightning-utilities       0.11.2                   pypi_0    pypi
linkify-it-py             2.0.3                    pypi_0    pypi
llvm-openmp               14.0.6               h9e868ea_0
llvmlite                  0.42.0                   pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_1
markdown                  3.6                      pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.8.4                    pypi_0    pypi
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h213fc3f_46344
mkl-service               2.4.0            py39h5eee18b_1
mkl_fft                   1.3.8            py39h5eee18b_0
mkl_random                1.2.4            py39hdb19cb5_0
modelscope                1.10.0                   pypi_0    pypi
more-itertools            10.2.0                   pypi_0    pypi
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.2                hb69a4c5_1
mpmath                    1.3.0            py39h06a4308_0
msgpack                   1.0.8                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nettle                    3.7.3                hbbd107a_1
networkx                  3.2.1                    pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
numba                     0.59.1                   pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
numpy-base                1.26.4           py39hb5e798b_0
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
onnxruntime               1.17.3                   pypi_0    pypi
openh264                  2.1.1                h4ff587b_0
openjpeg                  2.4.0                h3ad879b_0
openssl                   3.0.13               h7f8727e_1
orjson                    3.10.3                   pypi_0    pypi
oss2                      2.18.5                   pypi_0    pypi
packaging                 24.0                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pillow                    10.3.0           py39h5eee18b_0
pip                       23.3.1           py39h06a4308_0
platformdirs              4.2.1                    pypi_0    pypi
pooch                     1.8.1                    pypi_0    pypi
pretty-errors             1.2.25                   pypi_0    pypi
proces                    0.1.7                    pypi_0    pypi
protobuf                  5.26.1                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
py3langid                 0.2.2                    pypi_0    pypi
pyarrow                   16.0.0                   pypi_0    pypi
pyarrow-hotfix            0.6                      pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pydantic                  2.7.1                    pypi_0    pypi
pydantic-core             2.18.2                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyopenjtalk               0.3.3                    pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pypinyin                  0.51.0                   pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0
python                    3.9.19               h955ad1f_1
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             1.0.1                    pypi_0    pypi
python-multipart          0.0.9                    pypi_0    pypi
pytorch                   2.1.1           py3.9_cuda11.8_cudnn8.7.0_0    pytorch
pytorch-cuda              11.8                 h7e8668a_5    pytorch
pytorch-lightning         2.2.4                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytorch-wpe               0.0.1                    pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1            py39h5eee18b_0
readline                  8.2                  h5eee18b_0
referencing               0.35.1                   pypi_0    pypi
regex                     2024.4.28                pypi_0    pypi
requests                  2.31.0           py39h06a4308_1
resampy                   0.4.3                    pypi_0    pypi
rhash                     1.4.3                hdbd6064_0
rich                      13.7.1                   pypi_0    pypi
rotary-embedding-torch    0.5.3                    pypi_0    pypi
rpds-py                   0.18.1                   pypi_0    pypi
safetensors               0.4.3                    pypi_0    pypi
scikit-learn              1.4.2                    pypi_0    pypi
scipy                     1.13.0                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentencepiece             0.2.0                    pypi_0    pypi
setuptools                69.5.1           py39h06a4308_0
shellingham               1.5.4                    pypi_0    pypi
simplejson                3.19.2                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
soxr                      0.3.7                    pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0
starlette                 0.37.2                   pypi_0    pypi
sympy                     1.12             py39h06a4308_0
sysroot_linux-64          2.12                he073ed8_17    conda-forge
tbb                       2021.8.0             hdb19cb5_0
tensorboard               2.16.2                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tk                        8.6.14               h39e8969_0
tokenizers                0.19.1                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
torch                     2.3.0                    pypi_0    pypi
torch-complex             0.4.3                    pypi_0    pypi
torchaudio                2.3.0                    pypi_0    pypi
torchmetrics              1.4.0                    pypi_0    pypi
torchtriton               2.1.0                      py39    pytorch
torchvision               0.16.1               py39_cu118    pytorch
tqdm                      4.66.4                   pypi_0    pypi
transformers              4.40.2                   pypi_0    pypi
triton                    2.3.0                    pypi_0    pypi
typeguard                 4.2.1                    pypi_0    pypi
typer                     0.12.3                   pypi_0    pypi
typing-extensions         4.11.0                   pypi_0    pypi
typing_extensions         4.9.0            py39h06a4308_1
tzdata                    2024.1                   pypi_0    pypi
uc-micro-py               1.0.3                    pypi_0    pypi
ujson                     5.9.0                    pypi_0    pypi
umap                      0.1.1                    pypi_0    pypi
urllib3                   2.2.1                    pypi_0    pypi
uvicorn                   0.29.0                   pypi_0    pypi
uvloop                    0.19.0                   pypi_0    pypi
watchfiles                0.21.0                   pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
werkzeug                  3.0.3                    pypi_0    pypi
wheel                     0.43.0           py39h06a4308_0
wordsegment               1.3.1                    pypi_0    pypi
x264                      1!157.20191217       h7b6447c_0
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.4.6                h5eee18b_1
yaml                      0.2.5                h7b6447c_0
yapf                      0.40.2                   pypi_0    pypi
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.18.1                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1
zstd                      1.5.5                hc292b87_2

***********
bash install 安装成功并无报错，可以启动webui, Audio slicer 运行并无问题。

**Comment by nbu2024** [comment]
看到有人说删除asr/model 就可以了，我删除后报错
"/home/diffusion/anaconda3/envs/GPTSoVits/bin/python" tools/asr/funasr_asr.py -i "input/slicer_opt" -o "output/asr_opt" -s large -l zh -p float16
/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/torch/distributed/_functional_collectives.py:22: UserWarning: Unable to import torchdynamo util `is_torchdynamo_compiling`, so won't support torchdynamo correctly
  warnings.warn(

tables:

-----------    ** dataset_classes **    --------------
| class name   | class location                               |
| AudioDataset | funasr/datasets/audio_datasets/datasets.py:7 |
-----------    ** index_ds_classes **    --------------
| class name   | class location                               |
| IndexDSJsonl | funasr/datasets/audio_datasets/index_ds.py:9 |
-----------    ** batch_sampler_classes **    --------------
| class name   | class location                               |
| BatchSampler | funasr/datasets/audio_datasets/samplers.py:7 |
-----------    ** frontend_classes **    --------------
| class name        | class location                       |
| WavFrontend       | funasr/frontends/wav_frontend.py:78  |
| WavFrontendOnline | funasr/frontends/wav_frontend.py:216 |
-----------    ** encoder_classes **    --------------
| class name            | class location                                        |
| BranchformerEncoder   | funasr/models/branchformer/encoder.py:294             |
| ConformerChunkEncoder | funasr/models/bat/conformer_chunk_encoder.py:315      |
| ConformerEncoder      | funasr/models/conformer/encoder.py:286                |
| DFSMN                 | funasr/models/fsmn_vad_streaming/encoder.py:232       |
| EBranchformerEncoder  | funasr/models/e_branchformer/encoder.py:177           |
| FSMN                  | funasr/models/fsmn_vad_streaming/encoder.py:161       |
| SANMEncoder           | funasr/models/sanm/encoder.py:161                     |
| SANMEncoderChunkOpt   | funasr/models/scama/encoder.py:162                    |
| SANMVadEncoder        | funasr/models/ct_transformer_streaming/encoder.py:148 |
| TransformerEncoder    | funasr/models/transformer/encoder.py:139              |
-----------    ** predictor_classes **    --------------
| class name     | class location                                     |
| CifPredictor   | funasr/models/paraformer/cif_predictor.py:15       |
| CifPredictorV2 | funasr/models/paraformer/cif_predictor.py:141      |
| CifPredictorV3 | funasr/models/bicif_paraformer/cif_predictor.py:95 |
-----------    ** model_classes **    --------------
| class name             | class location                                     |
| BiCifParaformer        | funasr/models/bicif_paraformer/model.py:37         |
| Branchformer           | funasr/models/branchformer/model.py:6              |
| CAMPPlus               | funasr/models/campplus/model.py:30                 |
| CTTransformer          | funasr/models/ct_transformer/model.py:30           |
| CTTransformerStreaming | funasr/models/ct_transformer_streaming/model.py:27 |
| Conformer              | funasr/models/conformer/model.py:8                 |
| ContextualParaformer   | funasr/models/contextual_paraformer/model.py:43    |
| EBranchformer          | funasr/models/e_branchformer/model.py:6            |
| Emotion2vec            | funasr/models/emotion2vec/model.py:34              |
| FsmnVADStreaming       | funasr/models/fsmn_vad_streaming/model.py:267      |
| MonotonicAligner       | funasr/models/monotonic_aligner/model.py:24        |
| Paraformer             | funasr/models/paraformer/model.py:26               |
| ParaformerStreaming    | funasr/models/paraformer_streaming/model.py:37     |
| SANM                   | funasr/models/sanm/model.py:13                     |
| SCAMA                  | funasr/models/scama/model.py:38                    |
| SeacoParaformer        | funasr/models/seaco_paraformer/model.py:45         |
| Transformer            | funasr/models/transformer/model.py:20              |
| UniASR                 | funasr/models/uniasr/model.py:26                   |
-----------    ** decoder_classes **    --------------
| class name                                 | class location                                     |
| ContextualParaformerDecoder                | funasr/models/contextual_paraformer/decoder.py:103 |
| DynamicConvolution2DTransformerDecoder     | funasr/models/transformer/decoder.py:588           |
| DynamicConvolutionTransformerDecoder       | funasr/models/transformer/decoder.py:527           |
| FsmnDecoder                                | funasr/models/sanm/decoder.py:198                  |
| FsmnDecoderSCAMAOpt                        | funasr/models/scama/decoder.py:197                 |
| LightweightConvolution2DTransformerDecoder | funasr/models/transformer/decoder.py:465           |
| LightweightConvolutionTransformerDecoder   | funasr/models/transformer/decoder.py:404           |
| ParaformerSANDecoder                       | funasr/models/paraformer/decoder.py:529            |
| ParaformerSANMDecoder                      | funasr/models/paraformer/decoder.py:204            |
| TransformerDecoder                         | funasr/models/transformer/decoder.py:355           |
-----------    ** normalize_classes **    --------------
| class name   | class location                             |
| GlobalMVN    | funasr/models/normalize/global_mvn.py:11   |
| UtteranceMVN | funasr/models/normalize/utterance_mvn.py:8 |
-----------    ** specaug_classes **    --------------
| class name | class location                       |
| SpecAug    | funasr/models/specaug/specaug.py:14  |
| SpecAugLFR | funasr/models/specaug/specaug.py:104 |
-----------    ** tokenizer_classes **    --------------
| class name    | class location                        |
| CharTokenizer | funasr/tokenizer/char_tokenizer.py:10 |


2024-05-08 15:52:52,615 - modelscope - INFO - PyTorch version 2.3.0 Found.
2024-05-08 15:52:52,615 - modelscope - INFO - Loading ast index from /home/diffusion/.cache/modelscope/ast_indexer
2024-05-08 15:52:52,633 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 e74dee23dad8b79b0a2f6c26e06fc3c8 and a total number of 946 components indexed
Traceback (most recent call last):
  File "/home/diffusion/GPT-SoVITS/tools/asr/funasr_asr.py", line 17, in <module>
    model = AutoModel(
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 92, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 143, in build_model
    kwargs = download_model(**kwargs)
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/download/download_from_hub.py", line 11, in download_model
    kwargs = download_from_ms(**kwargs)
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/download/download_from_hub.py", line 21, in download_from_ms
    model_or_path = get_or_download_model_dir(model_or_path, model_revision, is_training=kwargs.get("is_training"), check_latest=kwargs.get("kwargs", True))
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/funasr/download/download_from_hub.py", line 84, in get_or_download_model_dir
    from modelscope.hub.check_model import check_local_model_is_latest
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/modelscope/__init__.py", line 102, in <module>
    fix_transformers_upgrade()
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/modelscope/utils/automodel_utils.py", line 43, in fix_transformers_upgrade
    import transformers
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/__init__.py", line 33, in <module>
    from .generic import (
  File "/home/diffusion/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/transformers/utils/generic.py", line 478, in <module>
    _torch_pytree.register_pytree_node(
AttributeError: module 'torch.utils._pytree' has no attribute 'register_pytree_node'

**Comment by SapphireLab** [comment]
简单看了一下日志, 这个错误位置在判断了当前的 torch 版本大于 2.2. 时会调用 `register_pytree_node()` 函数，否则调用之前的版本的 `_register_pytree_node()`。
所以应该是识别到新版本但调用了旧版本的代码，所以没能找到新版本的函数导致错误。
考虑是存在多个 torch 版本。

然后从你的 conda list 里能看到有两个版本：
- `pytorch 2.1.1 py3.9_cuda11.8_cudnn8.7.0_0 pytorch` : conda 安装的 2.1.1.< 2.2.;
- `torch 2.3.0 pypi_0 pypi`，pip 安装的 2.3.0 >2.2;

同一个环境在 import torch 的时候会优先选择 conda 安装的，所以应该是出现冲突了，考虑卸载掉其中一个 torch 再进行尝试。
另: 显示的 2.3.0 的版本没有 cu118或cu121 后缀，要保留此版本需要验证一下能否使用 gpu (大概是不行的).

**Comment by nbu2024** [comment]
好的，我卸载2.3.0的torch 再试一下，谢谢

**Comment by nbu2024** [comment]
已经可以，再次感谢
