### ISSUE TITLE
有办法能得到最终单词发音的时间吗？

### ISSUE THREAD

**Issue by Huiyicc** [RVC-Boss/GPT-SoVITS#1064]
因为在做一个指读功能,需要标注每个单词在音频中的时间位置,目前实现是切分小段,然后使用faster-whisper慢慢预测,时间窗口算法去匹配单词所在的位置,然后根据这个位置去算发音应该在什么时间,这种方案极其复杂且鲁棒性较低，效率还不高，我想的是是否有办法能直接在生成阶段就拿到这个信息？

**Comment by BOCEAN-FENG** [comment]
没get到，最终单词发音时间是指某个单词在音频中的起始时间吗？

**Comment by Huiyicc** [comment]
> 没get到，最终单词发音时间是指某个单词在音频中的起始时间吗？

恩,是的,比如hello world,需要标注整句话中hello是从多少秒到多少秒,world是从第几秒到第几秒,现在可以拆分出hello与world的音素表,但是翻了一圈代码并没有找到能搞到一个完整单词发音总长的方法🤔

**Comment by pengzhendong** [comment]
> > 没get到，最终单词发音时间是指某个单词在音频中的起始时间吗？
> 
> 恩,是的,比如hello world,需要标注整句话中hello是从多少秒到多少秒,world是从第几秒到第几秒,现在可以拆分出hello与world的音素表,但是翻了一圈代码并没有找到能搞到一个完整单词发音总长的方法🤔

自回归不能得到时间戳，如果可以的话也就不担心漏字问题了。

**Comment by Huiyicc** [comment]
> > > 没get到，最终单词发音时间是指某个单词在音频中的起始时间吗？
> > 
> > 
> > 恩,是的,比如hello world,需要标注整句话中hello是从多少秒到多少秒,world是从第几秒到第几秒,现在可以拆分出hello与world的音素表,但是翻了一圈代码并没有找到能搞到一个完整单词发音总长的方法🤔
> 
> 自回归不能得到时间戳，如果可以的话也就不担心漏字问题了。

那好吧，看上去只能使用老方法或者MFA做后处理了

**Comment by Moonmore** [comment]
> > 没get到，最终单词发音时间是指某个单词在音频中的起始时间吗？
> 
> 恩,是的,比如hello world,需要标注整句话中hello是从多少秒到多少秒,world是从第几秒到第几秒,现在可以拆分出hello与world的音素表,但是翻了一圈代码并没有找到能搞到一个完整单词发音总长的方法🤔

自回归模型做不了时间戳功能，不像VITS模型能有时长预测，可以拿到每个发音单元的时长信息

**Comment by warkcod** [comment]
@Huiyicc 请问问题解决了么？有什么参考的解决方案？谢谢

**Comment by Huiyicc** [comment]
> @Huiyicc 请问问题解决了么？我也有类似的需求，有什么参考的解决方案？谢谢

我用的whisper转写+对齐 方案
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/10141057/2bb42d5d-3330-4fc0-84b5-37d228e1834f)
