### ISSUE TITLE
建议增加OpenAI API的兼容性接口

### ISSUE THREAD

**Issue by zhy844694805** [RVC-Boss/GPT-SoVITS#1068]
如果具备与 OpenAI API 的兼容性，其他应用的接入将变得无比便捷。
OpenAI API 的示例：
curl https://api.openai.com/v1/audio/speech
-H "Authorization: Bearer $OPENAI_API_KEY"
-H "Content-Type: application/json"
-d '{
"model": "tts-1",
"input": "敏捷的棕色狐狸跳过了懒狗。",
"voice": "alloy"
} '
--输出语音.mp3

参考文档：https://platform.openai.com/docs/api-reference/authentication

**Comment by mwnu** [comment]
附议

**Comment by CyberWon** [comment]
可以看下这个：https://www.bilibili.com/video/BV1Wr42157kd/?spm_id_from=333.999.list.card_archive.click

**Comment by CyberWon** [comment]
@wangyuanhao0918 笑死，就你不是弱智。你分得清MIT协议？还套壳，脑子没发育完全就回娘胎里重造一次。我给GPT-SoVITS做TTS的时候，你不知道还在那里。废物东西。有免费的不会用，自己就别在这人丢脸了

**Comment by wangyuanhao0918** [comment]
> @wangyuanhao0918 笑死，就你不是弱智。你分得清MIT协议？还套壳，脑子没发育完全就回娘胎里重造一次。我给GPT-SoVITS做TTS的时候，你不知道还在那里。废物东西。有免费的不会用，自己就别在这人丢脸了

哈哈，二道贩子急了，你这个逼养的也懂协议啊？把所有人的pr打个包就开始卖钱，是不是你这个傻逼干的事啊？还你做TTS，你长得跟你妈逼得TTS式得，用你做吗？舔着个B脸拿开源软件卖钱得不是你这个B养的唯一技能啊？哦，不对，还会用你那个母狗般的声音录视频，哈哈，你这种逼养的二道贩子估计也就会干这个了，哥可怜你，赏你一天的工资，你这个弱智别再卖别人代码了，丢人现眼的玩意。

**Comment by wangyuanhao0918** [comment]
> @wangyuanhao0918 笑死，就你不是弱智。你分得清MIT协议？还套壳，脑子没发育完全就回娘胎里重造一次。我给GPT-SoVITS做TTS的时候，你不知道还在那里。废物东西。有免费的不会用，自己就别在这人丢脸了

不要逼脸的东西，全社区谁舔着个b脸卖别人的代码？只有你这个杂碎，哈哈，你不仅卖GPT-SoVITS，你还把这位 @2DIPW 的DUB软件也拿出来卖钱，你这杂种是不是穷疯了啊？就算掉钱眼里也你这逼养的这么下贱啊喂！

**Comment by zhangshuhui241** [comment]
> 附议

附议

**Comment by RedwindA** [comment]
我已经写了一个简单的转换为openai tts的工具，欢迎使用：https://github.com/RedwindA/GPT-sovits-2-OpenAI

**Comment by VideoFX** [comment]
> I have written a simple tool to convert to openai tts, welcome to use: https://github.com/RedwindA/GPT-sovits-2-OpenAI

Do you think this will work with "Open WebUI"? Open WebUI uses an Openai API for TTS.

**Comment by RedwindA** [comment]
> > I have written a simple tool to convert to openai tts, welcome to use: https://github.com/RedwindA/GPT-sovits-2-OpenAI
> 
> Do you think this will work with "Open WebUI"? Open WebUI uses an Openai API for TTS.


@VideoFX I haven't used Open WebUI, but it works well in LibreChat (which also supports OpenAI TTS), so it's reasonable to assume it would function similarly in Open WebUI

**Comment by VideoFX** [comment]
> @VideoFX I haven't used Open WebUI, but it works well in LibreChat (which also supports OpenAI TTS), so it's reasonable to assume it would function similarly in Open WebUI (if OW supports custom tts base url)

Very nice work. I will test it. Thank you for sharing!

**Comment by a1558878** [comment]
> > [@VideoFX](https://github.com/VideoFX) I haven't used Open WebUI, but it works well in LibreChat (which also supports OpenAI TTS), so it's reasonable to assume it would function similarly in Open WebUI (if OW supports custom tts base url)
> 
> Very nice work. I will test it. Thank you for sharing!

what's the result?
