### ISSUE TITLE
一键三连报错

### ISSUE THREAD

**Issue by ihxkjggg** [RVC-Boss/GPT-SoVITS#1074]
![1715265385836.jpg](https://github.com/RVC-Boss/GPT-SoVITS/assets/69021797/fe1eb5de-351c-4c38-a011-55c3b161d5a7)

![1715265381161.jpg](https://github.com/RVC-Boss/GPT-SoVITS/assets/69021797/c3d84f47-404f-41ca-8ae2-b7130bc52c07)

1:为什么有显卡提示没法用？是这个不支持么

2:总是找不到txt文件，自己新建一个也不行

麻烦大佬们帮忙看看什么问题，是模型有问题还是哪里需要设置下！

**Comment by BOCEAN-FENG** [comment]
一键三连一步一步做，另外显卡识别不到这一块，可能是cuda问题，也可能是pytorch版本问题，我自己到ide里面一个一个试，出问题的更新或者换版本才弄好

**Comment by ihxkjggg** [comment]
> 一键三联出错了没生成txt文件，导致后面拿txt报错，你得找前面生成那一步

谢谢，这个三个显卡改成0-0就好了，能找到txt了

**Comment by ihxkjggg** [comment]
> 一键三连一步一步做，另外显卡识别不到这一块，可能是cuda问题，也可能是pytorch版本问题，我自己到ide里面一个一个试，出问题的更新或者换版本才弄好

谢谢，显卡不识别这个我在按照你的方式去找下问题，另一个好了！能识别就能跑通啦

**Comment by XXXXRT666** [comment]
更新驱动，不行就装cuda118

**Comment by ihxkjggg** [comment]
> 更新驱动，不行就装cuda118

谢谢，昨天更新驱动就好了！
