### ISSUE TITLE
你好，请问一下底膜s2D488k和s2G488k,与clean_D_320000、clean_G_320000有关联吗？

### ISSUE THREAD

**Issue by Vellstar** [RVC-Boss/GPT-SoVITS#1078]
这是clean_D_320000、clean_G_320000的文件地址：https://huggingface.co/datasets/ms903/sovits4.0-768vec-layer12/tree/main/sovits_768l12_pre_large_320k

**Comment by XXXXRT666** [comment]
这个项目目前是TTS，不是SVC

**Comment by 45xjh** [comment]
> 这个项目目前是TTS，不是SVC

那兄弟 这个s2D488k和s2G488k是作者自己训的吗

**Comment by RVC-Boss** [comment]
无

楼上：当然

**Comment by 45xjh** [comment]
> 无
> 
> 楼上：当然

您好作者，请问这个是用什么数据集训练的，用的什么GPU设备，训练了多久的呢，还有就是代码里面其他的预训练模型：Chinese-roberta和Chinese-hubert以及s1bert25hz的来源是哪里呢
