### ISSUE TITLE
使用fast_inference_分支的api.py进行推理在接收到API请求后遇到AttributeError: 'Text2SemanticDecoder' object has no attribute 'infer_panel'. Did you mean: 'infer_panel_0307'?

### ISSUE THREAD

**Issue by kingki663** [RVC-Boss/GPT-SoVITS#1083]
1. 配置了环境可以成功运行api.py监听http请求
2. 在接收到http请求后遇到AttributeError: 'Text2SemanticDecoder' object has no attribute 'infer_panel'. Did you mean: 'infer_panel_0307'?
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/102838978/ec64246d-cd7f-4016-b5b5-3a6457ab6fdb)
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/102838978/7ecbeb47-c0c1-4558-8ff4-83aea3ff54ca)

**Comment by einsqing** [comment]
@kingki663 同样的问题，你是怎么解决的？

**Comment by kingki663** [comment]
> @kingki663 同样的问题，你是怎么解决的？

到对应的地方修改为报错提示的0307方法即可，应该是该分支的api.py没怎么同步适应该分支的修改

**Comment by XXXXRT666** [comment]
新分支使用apiv2

**Comment by kingki663** [comment]
> 新分支使用apiv2

如果使用旧版的api，速度上会有差别么？

**Comment by XXXXRT666** [comment]
无法使用，后面还会有报错

**Comment by kingki663** [comment]
> 无法使用，后面还会有报错

我现在已经可以使用旧版api跑起来了

**Comment by XXXXRT666** [comment]
infer_panel0307返回的列表会产生

pred_semantic = pred_semantic[:, -idx:].unsqueeze(0)  # .unsqueeze(0)#mq要多unsqueeze一次
TypeError: bad operand type for unary -: 'list'

**Comment by XXXXRT666** [comment]
而且速度差别不小

**Comment by kingki663** [comment]
错误可以参考：[https://github.com/RVC-Boss/GPT-SoVITS/issues/828](url)解决
我只是很好奇速度是否跟api的调用方式有关，也就是说v2有进行优化？

**Comment by XXXXRT666** [comment]
哦，就我发的那个啊，新分支Batch inference对推理速度提升挺大，说以后后面api v2出来了我就把它关了
