### ISSUE TITLE
Permission denied : erno 13

### ISSUE THREAD

**Issue by mak996** [RVC-Boss/GPT-SoVITS#1089]
有谁可以帮忙吗？
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/169814490/7e003f81-d93e-4a31-a7d0-766591e7ef9d)

这个是我得到的代码

Traceback (most recent call last):
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\tools\subfix_webui.py", line 310, in <module>
    set_global(args.load_json, args.load_list, args.json_key_text, args.json_key_path, args.g_batch)
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\tools\subfix_webui.py", line 295, in set_global
    b_load_file()
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\tools\subfix_webui.py", line 274, in b_load_file
    b_load_list()
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\tools\subfix_webui.py", line 244, in b_load_list
    with open(g_load_file, 'r', encoding="utf-8") as source:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\GPT-SoVITS-beta\\GPT-SoVITS-beta0217\\output\\asr_opt\\slicer_opt'

请问是什么原因呢？
看的是说需要放  .list 在 file 的后面可是如果我把 slicer_opt的名改成slicer_opt.list 得到的代码是这个

ERROR: The process "8296" not found.
"D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\runtime\python.exe" tools/subfix_webui.py --load_list "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\output\asr_opt\slicer_opt" --webui_port 9871 --is_share False
Traceback (most recent call last):
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\tools\subfix_webui.py", line 310, in <module>
    set_global(args.load_json, args.load_list, args.json_key_text, args.json_key_path, args.g_batch)
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\tools\subfix_webui.py", line 295, in set_global
    b_load_file()
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\tools\subfix_webui.py", line 274, in b_load_file
    b_load_list()
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\tools\subfix_webui.py", line 244, in b_load_list
    with open(g_load_file, 'r', encoding="utf-8") as source:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\GPT-SoVITS-beta\\GPT-SoVITS-beta0217\\output\\asr_opt\\slicer_opt'
ERROR: The process "20912" not found.

**Comment by SapphireLab** [comment]
输入的标注文件路径应该是 `D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\output\asr_opt\slicer_opt.list`
文件不需要重命名，只是填入的时候少了后缀名, windows 应该 `查看`→`显示`→`文件扩展名`.

**Comment by mak996** [comment]
> 输入的标注文件路径应该是 `D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\output\asr_opt\slicer_opt.list` 文件不需要重命名，只是填入的时候少了后缀名, windows 应该 `查看`→`显示`→`文件扩展名`.

谢谢您的回答，我找找看怎么在windows调，可是在 1GPT-SOVITS-TTS 我看到GPU INFORMATION 是 （Unfortunately, there is no compatible GPU available to support your training.）会不会导致我不能使用呢？

**Comment by SapphireLab** [comment]
你没有 Nvidia GPU 吗 (或者不兼容)，那用 CPU 训练会很慢。可以考虑用云端 AutoDL 等训练，再将训练好的模型文件下载到本地推理。
可以访问本项目 Readme 的 [User Guide (中文)](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e)，里面有相应细节推荐先看一下。

**Comment by mak996** [comment]
> 你没有 Nvidia GPU 吗 (或者不兼容)，那用 CPU 训练会很慢。可以考虑用云端 AutoDL 等训练，再将训练好的模型文件下载到本地推理。 可以访问本项目 Readme 的 [User Guide (中文)](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e)，里面有相应细节推荐先看一下。

我的电脑是 nvidia@Geforce@MX50 2GBRAM ， 可能是不足够吧哈哈。谢谢您的推荐，我去了解一下。充值应该会有点问题因为我不是中国人

**Comment by jmaple12** [comment]
> > 你没有 Nvidia GPU 吗 (或者不兼容)，那用 CPU 训练会很慢。可以考虑用云端 AutoDL 等训练，再将训练好的模型文件下载到本地推理。 可以访问本项目 Readme 的 [User Guide (中文)](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e)，里面有相应细节推荐先看一下。
> 
> 我的电脑是 nvidia@Geforce@MX50 2GBRAM ， 可能是不足够吧哈哈。谢谢您的推荐，我去了解一下。充值应该会有点问题因为我不是中国人

不知道你有没有kaggle账号，使用在kaggle上训练，训练脚本是[gpt-sovits_kaggle.ipynb](https://github.com/RVC-Boss/GPT-SoVITS/blob/main/gpt-sovits_kaggle.ipynb)然后把训练好的模型下载到本地，或者如果你能上google的话，可以使用colab训练，脚本是[colab_webui.ipynb](https://github.com/RVC-Boss/GPT-SoVITS/blob/main/colab_webui.ipynb)
