### ISSUE TITLE
疑似bug

### ISSUE THREAD

**Issue by skcccc** [RVC-Boss/GPT-SoVITS#1098]
GPT_SoVITS/AR/data/dataset.py 代码中第67行是不是应该是`os.path.dirname(phoneme_path)`，目前写成` os.path.basename(phoneme_path)` 导致第227行的判断恒为false，无法读取bert_feature

<img width="303" alt="bug" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/20144043/ca7a107a-d4c2-458c-9533-d881ad5b8186">

[https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/AR/data/dataset.py](url)

**Comment by 45xjh** [comment]
你要一键三连之后才有这几个目录，也就是GPT_SoVITS下的prepare_dataset下的那几个

**Comment by skcccc** [comment]
> 你要一键三连之后才有这几个目录，也就是GPT_SoVITS下的prepare_dataset下的那几个

这个不是一键三连目录的问题，而是`os.path.basename(phoneme_path)`这种写法导致`self.path3 = '2-name2text.txt/3-bert'`,继而`path_bert = 2-name2text.txt/3-bert/xxx.pt`。导致227行的判断恒为False
```
#dataset.py 226-230行
path_bert = "%s/%s.pt" % (self.path3, item_name)
if os.path.exists(path_bert) == True:
        bert_feature = torch.load(path_bert, map_location="cpu")
else:
       flag = 1
```

**Comment by skcccc** [comment]
> 看下来无问题
按照下面这段代码，微调的时候` bert_feature = None`是设计就是如此吗，感谢！
```
        path_bert = "%s/%s.pt" % (self.path3, item_name)
        if os.path.exists(path_bert) == True:
            bert_feature = torch.load(path_bert, map_location="cpu")
        else:
            flag = 1
        if flag == 1:
            # bert_feature=torch.zeros_like(phoneme_ids,dtype=torch.float32)
            bert_feature = None
```

**Comment by XXXXRT666** [comment]
建议看完数据集准备代码再来看这段

**Comment by RVC-Boss** [comment]
预处理失败会是False的

**Comment by RVC-Boss** [comment]
是我理解错楼主意思了
bert路径寻错了，已修复，属于重大bug。建议之前用webui微调中文模型的同学都重训下。（训练量小的不太要紧，训得多的要紧。）
底模中文带bert，修复前微调中文训错bert路径未带bert，推理中文带bert。修复后微调训练中文正确带bert。

**Comment by 45xjh** [comment]
> 是我理解错楼主意思了 bert路径寻错了，已修复，属于重大bug。建议之前用webui微调中文模型的同学都重训下。（训练量小的不太要紧，训得多的要紧。） 底模中文带bert，修复前微调中文训错bert路径未带bert，推理中文带bert。修复后微调训练中文正确带bert。

需要怎么修复，在代码的哪里修改？
