### ISSUE TITLE
where is users.pth?

### ISSUE THREAD

**Issue by ywaby** [RVC-Boss/GPT-SoVITS#11]
colab run webui.py
```
/content/GPT-SoVITS
Traceback (most recent call last):
  File "/content/GPT-SoVITS/webui.py", line 17, in <module>
    with open("%s/users.pth"%(site_packages_root),"w")as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/GPT-SoVITS/runtime/Lib/site-packages/users.pth'
```
能给个colab notebook吗?

**Comment by RVC-Boss** [comment]
这个文件需要找到放到使用的python对应的site-packages目录下，相当于调包的时候自动能找到gpt_sovits和几个tools的根目录

**Comment by ywaby** [comment]
所以文件在哪里呢?是需要命令行先训练才能用webui吗?

**Comment by RVC-Boss** [comment]
@ywaby 我更新了代码，应该已经修复了，你再试试？

**Comment by elvizlai** [comment]
<img width="1032" alt="image" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/501861/adbebc90-6f29-4eab-9f45-82f1f9ba7a55">

Still not working with similar error
