### ISSUE TITLE
onnx_export并没有被用到

### ISSUE THREAD

**Issue by davidjia1972** [RVC-Boss/GPT-SoVITS#1100]
onnx_export 使用了 models_onnx 和 t2s_lightning_module_onnx，t2s_lightning_module_onnx 又使用了t2s_model_onnx和transformer_onnx，但目前看，这些代码在这个项目中都是多余的，因为没有见到任何地方使用了  onnx_export

**Comment by bfloat16** [comment]
有没有可能，导出的onnx就不是用本项目来推理的

**Comment by XXXXRT666** [comment]
建议去搜一下onnx用途哈

**Comment by RVC-Boss** [comment]
你说得对，确实没有用到。

**Comment by davidjia1972** [comment]
> 建议去搜一下onnx用途哈

不用搜，我可能比你还知道这是啥。我只是想确认一下，完全没用到的的东西为啥放在这里。
