### ISSUE TITLE
请问colab中一键三连部分的中间结果储存在哪里

### ISSUE THREAD

**Issue by jianshu-qin** [RVC-Boss/GPT-SoVITS#1103]
我尝试用colab训练，但是因为colab会断开所以要分几次训练，希望把预处理的时间节省下来。现在我保存了切割好的音频和对应标注，但是一键三连处理部分，即1a-text、1b-ssl、1c-semantic部分的预处理仍需要花费时间，希望有大佬告知这几部分的中间结果储存在哪里，谢谢。

**Comment by SapphireLab** [comment]
在 `GPT-SoVITS/logs/实验名` 文件夹里

**Comment by RVC-Boss** [comment]
楼上正解
