### ISSUE TITLE
出现诡异笑声，原来不是我一个人出现

### ISSUE THREAD

**Issue by wubangjunjava** [RVC-Boss/GPT-SoVITS#1110]
这个UP主也出现了跟我一样的问题，
#1022 
https://www.bilibili.com/video/BV1kV411X7Yu/?vd_source=527ee811d12ef342eff515a397bb5ccb#reply222557002368

大神们怎么解决这个问题

**Comment by HuanLinOTO** [comment]
请停止发布大量无关且重复的 issues 甚至是广告。这种行为不仅浪费了大家的时间，还影响了项目的正常管理。如果你有合理的问题或建议，请集中在一个 issue 中提出，并确保它与项目相关。感谢合作。

**Comment by wubangjunjava** [comment]
> 请停止发布大量无关且重复的 issues 甚至是广告。这种行为不仅浪费了大家的时间，还影响了项目的正常管理。如果你有合理的问题或建议，请集中在一个 issue 中提出，并确保它与项目相关。感谢合作。

我反馈的就是这个项目的bug，怎么是无关的呢？ 搞不懂，你看一下内容

**Comment by HuanLinOTO** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/issues/1108#issue-2307636540
https://github.com/RVC-Boss/GPT-SoVITS/issues/1022

难道不是重复？难道不是无关？

**Comment by wubangjunjava** [comment]
> [#1108 (comment)](https://github.com/RVC-Boss/GPT-SoVITS/issues/1108#issue-2307636540) #1022
> 
> 难道不是重复？难道不是无关？

你自己看看，与GPT-SOVITS项目有没有关系，出现诡异笑声，是不是有这个问题？

**Comment by HuanLinOTO** [comment]
你自己看看你重复发了多少 issues

你认为在开源项目的 issues 下面发广告合适？

issues 的用途是什么你知道吗？

**Comment by wubangjunjava** [comment]
> [#1108 (comment)](https://github.com/RVC-Boss/GPT-SoVITS/issues/1108#issue-2307636540) #1022
> 
> 难道不是重复？难道不是无关？

我觉得如果你有能力，尽快修复这个问题，才是重中之重，共同把项目完善。 因为我反馈的问题，确实存在。重复发一遍是因为一直没有解决，希望有能力的人能看到，尽快解决。

**Comment by HuanLinOTO** [comment]
你自己数据集的问题赖项目？

重复发你就没考虑过开发者追踪问题的繁琐？

**Comment by wubangjunjava** [comment]
> 你自己数据集的问题赖项目？
> 
> 重复发你就没考虑过开发者追踪问题的繁琐？

你是SB吗？ 我开始也觉得是我训练的问题，所以才想买一个别人训练好的模型。后面看到居然有大量用户出现这个问题，那就不是数据问题，是项目的bug。因为不是个例。

**Comment by RVC-Boss** [comment]
谁收了你钱你去找谁那找客服，不要到项目这来找客服

训练效果正常的人以及能把你数据训出不带笑声推理的人绝对比推出笑声的人多，只是他们不说话。

以解决问题的角度，你不公开训练集和训练方法训练参数，开发者也不可能定位问题。
