### ISSUE TITLE
一键三连也不生成6-name2semantic.tsv，另一个2-name2text有，不知道生成文件的代码在哪

### ISSUE THREAD

**Issue by zzk2021** [RVC-Boss/GPT-SoVITS#1111]
一键三连

_Originally posted by @XXXXRT666 in https://github.com/RVC-Boss/GPT-SoVITS/issues/432#issuecomment-2123714863_

**Comment by SapphireLab** [comment]
额, 发一下报错日志? 432 是环境配置有问题, 导入 numba 失败.

**Comment by zzk2021** [comment]
我操作失误

**Comment by 0002kgHg** [comment]
那一步操作失误了？我也是这样子

**Comment by Autisticrookat** [comment]
我也是这样子，把版本V2改成V1就好了

**Comment by codihuang** [comment]
我终于明白了，应该是go-api.command没按。

**Comment by XXXXRT666** [comment]
无关
