### ISSUE TITLE
Windows pre-packaged distribution can't do inference, showing "In construction, please wait"

### ISSUE THREAD

**Issue by CLQ6079** [RVC-Boss/GPT-SoVITS#1119]
When can this UI feature be available? Any workaround to use generated weights to do TTS without this UI feature?

**Comment by SapphireLab** [comment]
The `In construction, please wait.` refers to the Voice Conversion `2-GPT-SoVITS-Voice Changer`, 
**Not** the Text-to-Speech `1C-inference`.

**Comment by CLQ6079** [comment]
oh, you are absolutely right @SapphireLab . Thanks for pointing it out! I am going to close this issue.
