### ISSUE TITLE
我来报告几个问题

### ISSUE THREAD

**Issue by zengzikang** [RVC-Boss/GPT-SoVITS#112]
1、中英文混合不行，会跳过英文的部分。
2、会有漏读的情况，部分文字直接跳过了。
3、生成的语音，有概率会在前面一段生成范例的音频。
不完美的地方：
1、生成速度慢，cuda没有完全利用上，可以把gpu榨干。
2、生成不够稳定，有时候效果非常棒，有时候差点意思。

**Comment by RVC-Boss** [comment]
1、已经解决了
2、太长会漏字，需要先切分
3、已经大幅修复了

1、确实有这个问题，尤其是A100这种半精度很强的GPU，只能占用20%，后续可能需要硬件推理深度优化
2、需要耐心挑好参考音频，之后每次抽卡都是很好的。

**Comment by junwang152** [comment]
生成的文字全部是乱码，是哪里出现问题了

**Comment by succulen-plants** [comment]
我也遇到中文全是乱码的问题， 这个怎么解决呢 @junwang152
