### ISSUE TITLE
训练英文模型的时候的一点问题 

### ISSUE THREAD

**Issue by Qing20240129** [RVC-Boss/GPT-SoVITS#1120]
大佬们 真是一个非常的工程； 
我想训练一个说 英文的模型 ，
1. 在 6-name2semantic.tsv 这个文件里，看了几个issue ，预期就是空的 对吧 ；
2. 在训练s1 的时候会读dataframe 这个文件 ；
会报错 因为是空 ，我把他改成了空的dataframe 但是也有div 0 的错误 ； 想请教一下 ，英文训练怎么做 
是不是前面有些步骤做错了

**Comment by XXXXRT666** [comment]
预期不是空的
