### ISSUE TITLE
训练显卡排名 l20快还是4090快？

### ISSUE THREAD

**Issue by cucci666** [RVC-Boss/GPT-SoVITS#1126]

**Comment by cucci666** [comment]
有训练显卡排名嘛？

**Comment by cucci666** [comment]
有训练显卡排名嘛？

**Comment by RVC-Boss** [comment]
转载自https://www.autodl.com/home
4090 单精 82.58 TFLOPS / 半精 165.2 Tensor TFLOPS
L20  单精 59.35 TFLOPS / 半精 119.5 Tensor TFLOPS
