### ISSUE TITLE
How do we decide the semantic frame rate?

### ISSUE THREAD

**Issue by cnlinxi** [RVC-Boss/GPT-SoVITS#114]
Thank you for your contribution!

How do we decide the semantic frame rate? Is it a training hyper-parameter, or is it a parameter associated with HuBERT, like in the pre-trained model where the semantic frame rate needs be set to 25Hz?

https://github.com/RVC-Boss/GPT-SoVITS/blob/48da30c4af3a67d8aee9b1d25477f4472b157e1b/webui.py#L246
https://github.com/RVC-Boss/GPT-SoVITS/blob/48da30c4af3a67d8aee9b1d25477f4472b157e1b/GPT_SoVITS/AR/data/dataset.py#L244
https://github.com/RVC-Boss/GPT-SoVITS/blob/48da30c4af3a67d8aee9b1d25477f4472b157e1b/GPT_SoVITS/module/models.py#L886

Thanks for your reply.

**Comment by RVC-Boss** [comment]
The frequency of Hubert is 50Hz. According to experimental experience, GPT with a frequency of 25Hz exhibits better stability than 50hz and is more convenient to obtain by downsampling from Hubert's 50Hz.
