### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.i18n'

### ISSUE THREAD

**Issue by liuzj288** [RVC-Boss/GPT-SoVITS#1149]
windows下出现这个问题，已经安装了tools

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/13833404/7ce3494a-1ba4-49a8-9d45-c48edbb1eb43)

**Comment by XXXXRT666** [comment]
为什么要安装tools，又不是pypi库

**Comment by liuzj288** [comment]
> 为什么要安装tools，又不是pypi库

不安装也提示错误啊
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/13833404/d1501b0b-af15-4f33-8ab7-1ebc2f4cd5c5)

**Comment by XXXXRT666** [comment]
sys.path手动加一下当前目录

**Comment by RVC-Boss** [comment]
楼上正解

**Comment by cpken** [comment]
```python
# tools/i18n/i18n.py
# tools/uvr5/webui.py
sys.path.append(os.getcwd())
from tools.i18n.i18n import I18nAuto
i18n = I18nAuto()
```

问题就解决了。

**Comment by Ntraveler94** [comment]
我也遭遇一樣的問題，請問要在哪裡輸入樓上的代碼呢?因為我在此視窗中無法打字，我不確定這是否為正常現象?
![螢幕擷取畫面 2024-08-18 235659](https://github.com/user-attachments/assets/8901c61d-af64-4a46-9066-eb786b14bfe5)

**Comment by cpken** [comment]
我现在使用的是项目的罪行代码，不会出现此问题，也不需要像前面我回复的那样，添加那些代码纠正错误。
