### ISSUE TITLE
生成的音频开头静音时间太短了

### ISSUE THREAD

**Issue by fangg2024** [RVC-Boss/GPT-SoVITS#1174]
哪位知道如何设置能让开头静音变长，而不是一开始播放音频立马有声音，要是生成后再处理就太麻烦了。

**Comment by Separatee** [comment]
并不清楚这个项目能设置开头静音。但是我还是给出我的方案:
首先确保你已经安装了**ffmpeg**,如果你使用整合包,那么项目根目录里应该有ffmpeg.exe.
如果不是，还请自行搜索ffmpeg。
命令如下:
````
ffmpeg -i 输入名.wav -f lavfi -t 静音时长 -i anullsrc=r=44100:cl=stereo -filter_complex "[1][0]concat=n=2:v=0:a=1[a]" -map "[a]" 输出名.wav
````
这里有三个变量:
1. 输入名.wav
2. 静音时长
3. 输出名.wav

格式不限你可以用.mp3 .flac .m4a等等来代替.wav
我再给个示例:
````
ffmpeg -i input.mp3 -f lavfi -t 114514 -i anullsrc=r=44100:cl=stereo -filter_complex "[1][0]concat=n=2:v=0:a=1[a]" -map "[a]" Output.mp3
````
这将在开头为input.mp3创建一个114514秒的静音()

**Comment by uone-1** [comment]
有個更簡單的做法
只需修改 **get_tts_wav** 函數最後的部分:

> **get_tts_wav** 原代碼中你會看到

    audio_opt.append(audio)
    audio_opt.append(zero_wav)

> 修改成以下這樣

    audio_opt.append(zero_wav) # 在前面也添加zero_wav
    audio_opt.append(audio)
    audio_opt.append(zero_wav)

官方預設zero_wav為 0.3 秒，可按自己需求更改

**Comment by fangg2024** [comment]
感谢各位给出的方法，我试了一下，在前面加个逗号之类的也能起到一定的效果，但还是 @uone-1 的方法更好。
