### ISSUE TITLE
如何用新的训练集重新训练或者微调底模？

### ISSUE THREAD

**Issue by csu-roycheng** [RVC-Boss/GPT-SoVITS#1178]
我这边有一批多说话人的中文语音数据，想重新训练或者微调现有底模。可以按照webui上面的流程训练吗？如果可以的话训练参数应该如何选择。

**Comment by Separatee** [comment]
仅为个人看法。
通常你可以提交给其他developer进行处理。
并非通过简单的webui便能够微调原本的底模。
对于[底模](https://huggingface.co/lj1995/GPT-SoVITS/tree/main),想要预处理，你可能需要
1. 使用Pytorch Transformers的库编写代码
2. 对数据格式化预处理
3. 利用Transformers API定义或多或少的参数，开始微调。

即使你懂得如果为它写一份代码，这里可能还有许多坑，比如数据可能需要重采样到44100kHz或者其他，否则模型不会适当的学习;还有处理解码器不同，参考SoVITS-svc中文文档,光是解码器就有5种，各有优缺，这可能会导致解析token出现严重问题。
抄录一份至 @RVC-Boss:关于底模更新的问题.

**Comment by RVC-Boss** [comment]
写了个wiki供参考
https://github.com/RVC-Boss/GPT-SoVITS/wiki/%E4%BB%8E%E9%9B%B6%E8%AE%AD%E7%BB%83(train-from-scratch)

**Comment by csu-roycheng** [comment]
> 写了个wiki供参考 https://github.com/RVC-Boss/GPT-SoVITS/wiki/%E4%BB%8E%E9%9B%B6%E8%AE%AD%E7%BB%83(train-from-scratch)

感谢大佬回复。
我还想请教一下，在用大量多说话人数据微调模型的过程中有必要解冻 VQ 量化器吗？

**Comment by RVC-Boss** [comment]
> > 写了个wiki供参考 https://github.com/RVC-Boss/GPT-SoVITS/wiki/%E4%BB%8E%E9%9B%B6%E8%AE%AD%E7%BB%83(train-from-scratch)
> 
> 感谢大佬回复。 我还想请教一下，在用大量多说话人数据微调模型的过程中有必要解冻 VQ 量化器吗？

不微调GPT的话，必须冻结
如果GPT也会微调，可以解冻。
