### ISSUE TITLE
数据准备中的3-get-semantic环节

### ISSUE THREAD

**Issue by zhiqiuiyiye** [RVC-Boss/GPT-SoVITS#1181]
按照我的理解，这是对hubert提取到的语义特征进行VQ量化的环节，那么这个VQ量化器是开源训练好的，还是跟着sovits一起训练的呢？

**Comment by RVC-Boss** [comment]
我训底模的时候会联训，微调是冻结的，你也可以调整参数让他不冻结（s2.json里面有个freeze）。如果冻结，s1和s2微调顺序随意，如果不冻结，必须先s2再s1。

**Comment by zhiqiuiyiye** [comment]
好的，感谢
