### ISSUE TITLE
使用api进行短文本生成时会生成失败，生成内容变为参考音频

### ISSUE THREAD

**Issue by KaerMorh** [RVC-Boss/GPT-SoVITS#1190]
使用api进行短文本生成时生成失败，生成音频变为参考音频。 **而在相同参考与gpt参数情况下，webui均能正确生成。**

生成失败的测试例子（相同字数时普遍存在）：
1. 中文
“你是谁” 生成为 _参考音频_
“你究竟是谁” 生成正常
2. 英文
“I know” 生成为 _参考音频_
“I don't know” 生成正常
3. 日文
“アイ ハブ ” 生成为 _参考音频_
“アイ ハブ コントロール” 生成正常

---
其他信息：
- 参考音频：日文，训练数据集中摘出，4s。
- GPT参数 ：top_k=5,top_p=1,temperature=1。
以下为生成时使用的程序
```python
import requests


def synthesize_audio(
        generated_text, generated_text_language, output_path,
        refer_wav_path, prompt_text, prompt_language,
        api_url="http://127.0.0.1:9880"
):
    """
    调用API生成音频并保存到指定路径

    :param generated_text: 要生成的音频文本
    :param generated_text_language: 生成的音频文本的语言
    :param output_path: 输出路径
    :param refer_wav_path: 参考音频路径
    :param prompt_text: 参考音频的文本
    :param prompt_language: 参考音频的语言
    :param api_url: API的URL
    """
    payload = {
        "refer_wav_path": refer_wav_path,
        "prompt_text": prompt_text,
        "prompt_language": prompt_language,
        "text": generated_text,
        "text_language": generated_text_language
    }

    response = requests.post(api_url, json=payload)

    if response.status_code == 200:
        with open(output_path, 'wb') as f:
            f.write(response.content)
        print(f"Audio has been saved to {output_path}")
    else:
        print(f"Failed to generate audio: {response.status_code}, {response.json()}")


# 示例调用
synthesize_audio(
    generated_text="你究竟是谁",
    generated_text_language="zh",
    output_path=r"H:\ayre\output.wav",
    refer_wav_path=r"H:\ayre\あなたの火は、ここで終わります.wav",
    prompt_text="あなたの火は、ここで終わります",
    prompt_language="ja"
)

```

**Comment by KaerMorh** [comment]
api_v2可以解决，结题

**Comment by Thinking80s** [comment]
遇到同样问题

**Comment by chfenglv** [comment]
> api_v2可以解决，结题

我今天测试的api_v2，还是会有生成的音频里有参考音频的内容。虽然是偶现，但测试个10次，也有个2~3次。我用的post请求：data = {
        "text":"11月12日，国内黄金珠宝品牌金饰价格也应声跟跌。周生生报价为788元/克，较前一日802元/克一夜下跌14元；老庙黄金报价787元/克，下跌12元/克；周大福足金饰品报价为788元/克，下跌11元/克。",
        "text_lang":"zh",
        "ref_audio_path":"ref_audio/input-10s.wav", 
        "prompt_lang":"zh", 
        "prompt_text":"从博弈论的定义中我们知道，双方或者多方进行博弈的最终目的，都是为自己争取最大利益。", #  参考音频ref_audio_path对应的文本。
        "streaming_mode": True,
        "parallel_infer": True,
        "batch_size":1, 
        "text_split_method":"cut5",
        "speed_factor": 1.5  
    }   
而且好像batch_size>1时出现的频率高些。

请教下，这个问题要怎么解决啊

**Comment by Chi8wah** [comment]
和GPT weight轮次、参考音频、种子、微调素材都有关系。我自己目前是只能自己去找稳定的搭配，api_v2 无法彻底解决问题。
