### ISSUE TITLE
GPT-SoVITS的质量上限怎么样

### ISSUE THREAD

**Issue by Shapaper233** [RVC-Boss/GPT-SoVITS#1194]
我希望使用GPT-SoVITS来训练一个模型，我根据Bilibili的视频发现这个模型只需要很短时间的素材就可以提供几乎远超同类产品的效果。
但是我想知道随着更多数据的训练，他的语音质量会随着样本的提升而上升吗？
是否会有明显的效果？更多的素材能不能带来更好的准确性和质量？

**Comment by 1044690543** [comment]
能提高，但是提高的并不是很明显

**Comment by RVC-Boss** [comment]
先确保质量

主要还是为了音色能和训练集命中的音色更像

另外就是样本量大了更容易有长样本短样本等等，覆盖更全重复漏字啥的也更容易规避

但是归根结底，扩大了训练集，质量还是需要保证的

ps：GPT的scale up性能是很高的，欢迎扩大
