### ISSUE TITLE
在SSL自监督特征提取控制台输出内容正常吗?

### ISSUE THREAD

**Issue by lowyyh** [RVC-Boss/GPT-SoVITS#1207]
SSL自监督特征提取控制台输出:
![QQ截图20240619093723](https://github.com/RVC-Boss/GPT-SoVITS/assets/118085432/73cf2cb4-c819-49a4-a8f6-d06b288c11bc)
此外SoVITS训练时报错控制台输出如下:
![QQ截图20240619094159](https://github.com/RVC-Boss/GPT-SoVITS/assets/118085432/f3605cbf-21a7-4713-9bc9-af8d7725220e)
GPT训练报错:
![QQ截图20240619094406](https://github.com/RVC-Boss/GPT-SoVITS/assets/118085432/28be6e64-f99d-4b03-8f35-dfda9d971b0b)

**Comment by SapphireLab** [comment]
第一个图不完整看不出什么，后面的一个是分batch出错，另一个是缺 6~.tsv文件，看起来应该是一键三连没做好，建议一步一步来看终端信息。

**Comment by XXXXRT666** [comment]
浮点数batchsize害人

**Comment by RVC-Boss** [comment]
> 浮点数batchsize害人

浮点的问题最新代码应该已经修了
