### ISSUE TITLE
推理的时候GPU才用到30%左右，有办法全部吃满GPU吗？

### ISSUE THREAD

**Issue by tuoerye** [RVC-Boss/GPT-SoVITS#1211]
如题，求教，推理时想用满GPU提高生成速度，有什么办法吗？

**Comment by RVC-Boss** [comment]
1、fast inference分支会高一些，batch size加大了占用率也会更高
2、需要找工程大佬利用TensorRT（我随便举例一个）等特定硬件上的加速框架进行加速提高利用率
3、torch.compile也许可以提升一点利用率
4、CPU的延时也有可能是瓶颈

**Comment by tuoerye** [comment]
> 1、fast inference分支会高一些，batch size加大了占用率也会更高 2、需要找工程大佬利用TensorRT（我随便举例一个）等特定硬件上的加速框架进行加速提高利用率 3、torch.compile也许可以提升一点利用率 4、CPU的延时也有可能是瓶颈

谢谢大佬，感恩，我试试
