### ISSUE TITLE
跪求大佬回复-->【从零训练GPT无法生成正常语音的问题】

### ISSUE THREAD

**Issue by mondorysix** [RVC-Boss/GPT-SoVITS#1212]
想自己从零单独训练下GPT，基于12h的中文单说话人标贝数据集，其中S2 SoVits部分直接使用预训练模型，模型训练了400epoch，loss已经降到很低了，acc 也达到了0.9+，但是推理时合成的语音 完全听不懂，不知道哪里出问题了。
<img width="1045" alt="image" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/36984768/d03114f2-8843-4b25-a7fa-4a62c04b832a">

- 怀疑是数据集太少太单一的问题，但后面换了85h的多说话人数据集，训练后测试依然还是这个现象。
- 这部分训练，我直接使用的是:s1_train.py 代码训练的，去掉load s1 pretrained model部分。
- 在几十条数据上finetune时，发现 loss挺大，acc 在0.2左右，但是合成的语音特别好（这是为什么啊）
<img width="1020" alt="image" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/36984768/ec8c3801-69b4-44d4-aa89-df0151119668">

跪求大佬，帮忙指点下这是哪里出问题了，困扰我很久了 [respect]

**Comment by RVC-Boss** [comment]
1、我这边底模第一版是从400h开始训的，标贝的量肯定不够
2、400epoch太多了
3、根据我的经验，训练acc太高不是件好事，train的acc和loss曲线对最终合成效果的意义不大
4、你说的finetune是根据你的训练了很久的85h小时模型基础上吗，还是从我开源的底模？
5、我的建议：
（1）标贝的实验不用做了，太少
（2）85h的可以试试，但是zero shot效果不用太指望。可以根据zero shot的结果，选一个epoch区间，均匀选几个ckpt（假定这些ckpt你都存下来了），试听效果，选几个zero shot效果没那么好但是已经是最好的
（3）基于这几个ckpt分别finetune，挑一个few shot finetune后效果最好的

**Comment by mondorysix** [comment]
> 你说的finetune是根据你的训练了很久的85h小时模型基础上吗，还是从我开源的底模？
感谢大佬回复，非常感谢，我是基于你开源的底模，我直接训练s1_train.py 就会导致loss很低，前面一直在想是否是需要 s1与s2联合训练

**Comment by Sarracen1a** [comment]
> > 你说的finetune是根据你的训练了很久的85h小时模型基础上吗，还是从我开源的底模？ 感谢大佬回复，非常感谢，我是基于你开源的底模，我直接训练s1_train.py 就会导致损失很低，前面一直在想是否是需要 s1与s2联合训练

好哥哥，你那个85小时的用的什么卡？大概训练了多久？

**Comment by mondorysix** [comment]
> > > 你说的finetune是根据你的训练了很久的85h小时模型基础上吗，还是从我开源的底模？
> > > 感谢大佬回复，非常感谢，我是基于你开源的底模，我直接训练s1_train.py 就会导致loss很低，前面一直在想是否是需要 s1与s2联合训练
> 
> 联合不了，2个反向传播之间没有关联

明白了， 感谢大佬指点

**Comment by mondorysix** [comment]
> > > 你说的finetune是根据你的训练了很久的85h小时模型基础上吗，还是从我开源的底模？ 感谢大佬回复，非常感谢，我是基于你开源的底模，我直接训练s1_train.py 就会导致损失很低，前面一直在想是否是需要 s1与s2联合训练
> 
> 好哥哥，你那个85小时的用的什么卡？大概训练了多久？

2张2080ti 2天左右，GPT部分训练还是比较快，SoVits3张卡要训练一周

**Comment by 45xjh** [comment]
> 1、我这边底模第一版是从400h开始训的，标贝的量肯定不够 2、400epoch太多了 3、根据我的经验，训练acc太高不是件好事，train的acc和loss曲线对最终合成效果的意义不大 4、你说的finetune是根据你的训练了很久的85h小时模型基础上吗，还是从我开源的底模？ 5、我的建议： （1）标贝的实验不用做了，太少 （2）85h的可以试试，但是zero shot效果不用太指望。可以根据zero shot的结果，选一个epoch区间，均匀选几个ckpt（假定这些ckpt你都存下来了），试听效果，选几个zero shot效果没那么好但是已经是最好的 （3）基于这几个ckpt分别finetune，挑一个few shot finetune后效果最好的

你好请问Sovits底膜S和D以及GPT底膜都是用什么数据训的，多少h的中文吗
