### ISSUE TITLE
更多的语言

### ISSUE THREAD

**Issue by sillyluna** [RVC-Boss/GPT-SoVITS#1222]
感谢作者的开发，这是一项十分有用和有意义的项目。
但语言类型稍微不足，我想加入泰语和越南语，请问有解决方案的文档吗？

**Comment by qjcwxohgb** [comment]
韩语也加

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/wiki/%E8%AE%AD%E7%BB%83%E6%96%B0%E8%AF%AD%E8%A8%80(how-to-train-the-models-with-other-languages)

**Comment by wxj127** [comment]
泰语和越南语

**Comment by monkeycc** [comment]
希望增加越南语
