### ISSUE TITLE
Need help for adding other languages

### ISSUE THREAD

**Issue by GeleiaComPepino** [RVC-Boss/GPT-SoVITS#1226]
I've been debugging this code for making GPT SoVits works with portuguese and other languages, i modified the code to adapt the Bert and hubert, but for adding other phonemes to the code i need to add on symbols, and to add on symbols.py, a people said for me that need to retrain a pretrain s2G, but i don't know how to work with this pretrain, how to train this pretrain again because i don't know what classification it uses

**Comment by GeleiaComPepino** [comment]
Sorry for the inconvenient, i've founded the code for pretrain the s2
For anyone that don't know, to train the s2 you need use the [https://github.com/innnky/ar-vits](url) repository

**Comment by 1044690543** [comment]
> 我一直在调试此代码，以使 GPT SoVits 适用于葡萄牙语和其他语言，我修改了代码以适应 Bert 和 hubert，但是为了在代码中添加其他音素，我需要添加符号，并添加 symbol.py，有人对我说需要重新训练一个预训练 s2G，但我不知道如何使用这个预训练，如何再次训练这个预训练，因为我不知道它使用什么分类

请问您训练成功了吗，使用了多少数据呢

**Comment by GeleiaComPepino** [comment]
I haven't done any training yet, but I thought it might be the way I'm going to do it. There's the ar-vits project that has s2 training, but I still don't have enough datasets for the training.

**Comment by 1044690543** [comment]
> I haven't done any training yet, but I thought it might be the way I'm going to do it. There's the ar-vits project that has s2 training, but I still don't have enough datasets for the training.

I am currently planning to try training a small language. If you also have the same plan recently, we might be able to discuss it together.

**Comment by GeleiaComPepino** [comment]
Well that would be really cool, I'm currently trying train Portuguese (the language of Brazil), it is not small, but it does not have a strong community on artificial intelligence, it would be great to have help.

**Comment by Hotelhoster** [comment]
> Well that would be really cool, I'm currently trying train Portuguese (the language of Brazil), it is not small, but it does not have a strong community on artificial intelligence, it would be great to have help.

Hi, how did the train went ?

**Comment by erickvlr** [comment]
Opa gente tem alguém que conseguiu Treinar o GPT-SoVITS Em PT-Br? ta muito dificil.
