### ISSUE TITLE
Why does Chinese use word2p and other languages ​​do not?

### ISSUE THREAD

**Issue by chunping-xt** [RVC-Boss/GPT-SoVITS#1230]
I noticed that when processing Chinese language, word2ph is used, but for other languages, it is not (word2ph=None)? What is the reason, if my language phoneme has only 2 or 3 phonemes, should I process the data like for Chinese?

**Comment by RVC-Boss** [comment]
After experimental verification, adding BERT as input to Chinese TTS can improve prosodic performance, but there is currently no evidence to support this in other languages.
