### ISSUE TITLE
已解决：出现这个原因是由于cpu不支持fp16类型，在config.py中改掉

### ISSUE THREAD

**Issue by scwhcn** [RVC-Boss/GPT-SoVITS#1237]
已解决：出现这个原因是由于cpu不支持fp16类型，在config.py中改掉
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/92665988/ec8889d6-de40-48ae-ad94-8b18e06b2d5c)

_Originally posted by @FURYFOR in https://github.com/RVC-Boss/GPT-SoVITS/issues/770#issuecomment-2114651701_
          
谢谢，终于有人回答了，是删掉箭头所指的那一行吗？

**Comment by Separatee** [comment]
CPU如果不支持半精度的话 就改成false 变成全精度
