### ISSUE TITLE
每次训练完每个音色对应200m的模型文件，怎么让这200m的文件支持多个音色？

### ISSUE THREAD

**Issue by yangcunning1** [RVC-Boss/GPT-SoVITS#1239]
1：有300个用户，需要300多的音色需要克隆，而且，每克隆一个音色就增加200的模型文件
2：这占用了很大的存储空间
3：并发量大的时候，都加载进显存，显存吃紧
有什么方法，让着200m的模型文件支持300+的音色呢

**Comment by RVC-Boss** [comment]
把这些音色分为几大类相似的音色，每个类一个模型，这样模型个数是类的个数。每个音色分别留一些参考音频引导音色。

**Comment by yangcunning1** [comment]
非常感谢大神回复，这真是解决了我的大麻烦，看了整合包教程，情感分类用Emotion2Vec，音色分类用ColorSplitter，这样没有问题吧

**Comment by yangcunning1** [comment]
> 把这些音色分为几大类相似的音色，每个类一个模型，这样模型个数是类的个数。每个音色分别留一些参考音频引导音色。

非常感谢大神回复，这真是解决了我的大麻烦，看了整合包教程，情感分类用Emotion2Vec，音色分类用ColorSplitter，这样没有问题吧

**Comment by xipingL** [comment]
> > 把这些音色分为几大类相似的音色，每个类一个模型，这样模型个数是类的个数。每个音色分别留一些参考音频引导音色。
> 
> 非常感谢大神回复，这真是解决了我的大麻烦，看了整合包教程，情感分类用Emotion2Vec，音色分类用ColorSplitter，这样没有问题吧

你好，我最近在看怎么将项目里的音色保存成文件 下次零克隆时直接使用，请问这一块方便分享下吗？
