### ISSUE TITLE
GPT训练这步的日志文件有人知道在哪吗？loss的数值应当控制在多少？

### ISSUE THREAD

**Issue by jiekemt** [RVC-Boss/GPT-SoVITS#1243]
因为训练过程中这些数据跳动地很快来不及看，我在log文件夹里找了很久都没找到GPT训练的日志，希望大家能帮下忙！

**Comment by RVC-Boss** [comment]
logs里面没有保留GPT步骤的日志，只能在控制台复制了

**Comment by XXXXRT666** [comment]
tensorboard看events file可以看一看大概的

**Comment by Separatee** [comment]
不必过于关注loss数值，唯一要注意的就是训练参数。通常情况下不建议改动epoch。其余要根据训练数据的多少进行调整。如果训练数据有点点多，就尽量调大batch size(上限显存一半) 。在调整完batch size的"_前提下_"可以增加learning_rate (0.05为增量)
如果不清楚改动它们有什么影响，请保持一切默认进行训练

**Comment by RVC-Boss** [comment]
楼上均正解。
