### ISSUE TITLE
长文本生成语音问题

### ISSUE THREAD

**Issue by hkh1012** [RVC-Boss/GPT-SoVITS#1246]
文本如下：
大家好，\n\n欢迎大家来到今天的演讲。我是[您的名字]，非常荣幸能够在这里与大家分享关于“数据库字段加密与模糊查询”的最新研究和实践应用。\n\n在我们的屏幕左侧，大文字突显了今天的主题：数据库字段加密与模糊查询，当然也有相应的英文翻译“Database Field Encryption and Fuzzy Query”。在技术飞速发展的背景下，数据安全和高效查询已经成为每个企业和开发者关注的焦点。\n\n看向我们右侧的图片，您会看到一幅现代化的办公室，它象征着我们时代对专业性和数据管理的不断追求。正如这些干净整洁的办公桌和高效的显示器，我们的数据库管理也需要类似的精确和安全。\n\n在今天的演讲中，我将与大家详细探讨如何利用先进的加密技术保护数据库字段，同时进行高效的模糊查询。我们将分享一些实际案例和切实可行的解决方案，希望能为在座的每一位带来新的思考和灵感。\n\n让我们一起走进这个富有挑战而又充满机遇的领域，共同探索数据安全与查询的无限可能。\n\n谢谢大家！\n\n（日期为2024年6月）

生成语音如下：

https://github.com/RVC-Boss/GPT-SoVITS/assets/10290010/959f8cf1-f2c2-4dea-b4b8-bfa2b4cce298

正常的音色如下：

https://github.com/RVC-Boss/GPT-SoVITS/assets/10290010/0f8a218a-2071-4fbc-8b00-2d456af50af7

请问出现这种现状的原因是什么？我可以从哪些方面改进？

**Comment by ChiaLinz** [comment]
把換行拿掉、選 "按標點符號切" 去生成、使用epoch較低的 GPT 模型，看看斷句、重複及吃字的問題有沒有改善。

**Comment by hkh1012** [comment]
> 把換行拿掉、選 "按標點符號切" 去生成、使用epoch較低的 GPT 模型，看看斷句、重複及吃字的問題有沒有改善。

感谢，修改之后确实好多了。

**Comment by hkh1012** [comment]
close
