### ISSUE TITLE
使用”语音降噪工具“运行到一半报错停止

### ISSUE THREAD

**Issue by langhaidian** [RVC-Boss/GPT-SoVITS#1248]
1. 环境：
mac 、cpu类型
2. 具体报错信息：
![WX20240627-180203@2x](https://github.com/RVC-Boss/GPT-SoVITS/assets/5392727/ae6e0331-1d3b-4902-86a9-4c46b7951eb1)
3. 情况介绍：
更新到了今天到代码仓库之后运行降噪工具报错，没更新代码仓库之前(一个礼拜之前版本)都还是可以的，已经更新或者重新安装过soundfile，还是无法解决跟处理，也多次尝试运行每次都是到14%报错，求回复。

**Comment by XXXXRT666** [comment]
去自查一下是哪个文件出问题了

**Comment by langhaidian** [comment]
好像找到问题了， 不知为何生成的文件夹下会有 .DS_Store 隐藏文件，执行的时候也会被读取，导致读取格式问题运行失败。

**Comment by XXXXRT666** [comment]
不要更改那个文件夹的排序设置等设置

**Comment by langhaidian** [comment]
应该只是进了下文件夹，自动生成的那个文件，我觉得还是排除下这个隐藏文件较好？

**Comment by XXXXRT666** [comment]
之前发的PR没被合并,我再发一个吧

**Comment by RVC-Boss** [comment]
合了，更新下代码，会跳过不可降噪的文件

**Comment by Lion-Wu** [comment]
> 应该只是进了下文件夹，自动生成的那个文件，我觉得还是排除下这个隐藏文件较好？

这是macOS的资源文件，一般不删除
