### ISSUE TITLE
推理进度条只跑一点就结束

### ISSUE THREAD

**Issue by youzibigg** [RVC-Boss/GPT-SoVITS#1250]
控制台截图
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/162673854/32209f51-d10d-4357-819d-2a3ae297daf2)

**Comment by youzibigg** [comment]
换别的文本输入也这样

**Comment by youzibigg** [comment]
用的0217版的整合包，笔记本cpu12700h gpu3070laptop

**Comment by youzibigg** [comment]
别的文本输入也这样，硬件3070laptop

**Comment by RVC-Boss** [comment]
跑完了
