### ISSUE TITLE
当使用唱歌数据或音乐数据进行训练时，我需要替换 Hubert 吗？

### ISSUE THREAD

**Issue by chunping-xt** [RVC-Boss/GPT-SoVITS#1255]
我用我的语言语音数据训练没有问题，它很好。但是用歌唱数据训练时，我感觉它像语音一样非常平坦，因为歌唱的音高范围更大，f0 加上滑音、颤音……它会与语音不同。我想知道这是否是由于用 Hubert 进行预训练造成的？如果不是，您对歌唱和音乐训练有什么建议？

**Comment by JunityZhan** [comment]
如果你替换hubert，那么对预训练的模型会有灾难性打击，你几乎需要重新预训练。所以不推荐。
至于是否是因为hubert，有可能，因为cnhuebrt的训练基于wenet10000h的中文说话音频，没有歌声数据。
如果你真要换hubert后重新训练，最有可能的是w2v-bert-2.0因为他数据集足够大（4.6M h）与此同时模型架构也需要做出更改以适应w2v-bert-2.0的1024的维度。

**Comment by RVC-Boss** [comment]
楼上正解。建议替换自己训一个，因为hubert没见过歌声

**Comment by 45xjh** [comment]
> 楼上正解。建议替换自己训一个，因为hubert没见过歌声

你好请问用于TTS，把hubert换成wav2vec2是否也要重新预训练了
