### ISSUE TITLE
【求助】不能分割音频，WebUI错误，一键三连报错

### ISSUE THREAD

**Issue by peterZHZ** [RVC-Boss/GPT-SoVITS#1259]
感谢大佬分享，我遇到以下问题：
1、上传了一个两分钟的音频，分割出来还是一个文件；
2、能转文本，但不分段，WebUI打开也显示错误；
3、数据格式化的时候一直报错。

哪位大佬帮忙看看是哪里搞错了？

![微信截图_20240629035454](https://github.com/RVC-Boss/GPT-SoVITS/assets/117995577/d6caf700-fff1-4b7b-9460-01c1aa750f75)

![微信截图_20240629131850](https://github.com/RVC-Boss/GPT-SoVITS/assets/117995577/977f99af-de79-4b6b-aad7-53982405d70d)

![微信截图_20240629035657](https://github.com/RVC-Boss/GPT-SoVITS/assets/117995577/a9d6b781-2507-4bfb-8663-506c475f96e2)

![微信截图_20240629035712](https://github.com/RVC-Boss/GPT-SoVITS/assets/117995577/2371cdde-e426-4a23-bf80-209b51e6a71b)

**Comment by SapphireLab** [comment]
嗯...先打开ASR出来的list文件，看看里面有没有数据？

**Comment by peterZHZ** [comment]
有数据，能转文档，但是不分段，打标工具也显示错误。。。就出来这样一个文件

![微信截图_20240629132321](https://github.com/RVC-Boss/GPT-SoVITS/assets/117995577/209f4ae0-f8e6-4237-a497-94f802752d25)

![微信截图_20240629131850](https://github.com/RVC-Boss/GPT-SoVITS/assets/117995577/7a18c035-ff5c-4834-8c51-4617598ce346)

**Comment by SapphireLab** [comment]
方便的话传一下音频我做一下复现？

**Comment by RVC-Boss** [comment]
1、可能是底噪很高也有可能是没有气口本来就分割不了
2、webui打开错误error这张图应该是位置路径没对上  
3、850这张图是因为训练集里有一句话文本太长了（因为切割失败了所以全部到一起去了吧）
