### ISSUE TITLE
Emotional/Style TTS

### ISSUE THREAD

**Issue by WinterStraw** [RVC-Boss/GPT-SoVITS#127]
Thank you for your contributions to the open-source community,
I would like to know if you are considering adding emotional TTS function to models in the future.

**Comment by Kamikadashi** [comment]
![chrome_WQ4cyrlgnb](https://github.com/RVC-Boss/GPT-SoVITS/assets/90068423/f0a2a1a3-2568-41fb-8483-ff577e0245e4)
