### ISSUE TITLE
docker build 到下载模型这一步总是报错，是因为网不好？

### ISSUE THREAD

**Issue by Song367** [RVC-Boss/GPT-SoVITS#1275]
1210.8 07/05 02:37:50 [NOTICE] Download complete: /workspace/GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large/pytorch_model.bin
1210.8
1210.8 Download Results:
1210.8 gid   |stat|avg speed  |path/URI
1210.8 ======+====+===========+=======================================================
1210.8 e8d30f|OK  |   707KiB/s|/workspace/GPT_SoVITS/pretrained_models/chinese-hubert-base/config.json
1210.8 1a8cad|OK  |   103KiB/s|/workspace/GPT_SoVITS/pretrained_models/chinese-hubert-base/preprocessor_config.json
1210.8 7bb9ea|OK  |   470KiB/s|/workspace/GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large/config.json
1210.8 70959e|OK  |   244KiB/s|/workspace/GPT_SoVITS/pretrained_models/s2D488k.pth
1210.8 990095|OK  |   285KiB/s|/workspace/GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large/tokenizer.json
1210.8 eb0108|OK  |   269KiB/s|/workspace/GPT_SoVITS/pretrained_models/s2G488k.pth
1210.8 907f11|OK  |   227KiB/s|/workspace/tools/uvr5/uvr5_weights/HP3_all_vocals.pth
1210.8 ec8f54|OK  |   198KiB/s|/workspace/tools/uvr5/uvr5_weights/HP2_all_vocals.pth
1210.8 f6408f|OK  |   222KiB/s|/workspace/GPT_SoVITS/pretrained_models/chinese-hubert-base/pytorch_model.bin
1210.8 bdc95e|ERR |       0B/s|/workspace/tools/uvr5/uvr5_weights/VR-DeEchoDeReverb.pth
1210.8 36518d|ERR |       0B/s|/workspace/tools/uvr5/uvr5_weights/VR-DeEchoNormal.pth
1210.8 13e513|ERR |       0B/s|/workspace/tools/uvr5/uvr5_weights/onnx_dereverb_By_FoxJoy/vocals.onnx
1210.8 44d5a6|OK  |   177KiB/s|/workspace/GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt
1210.8 382657|OK  |   305KiB/s|/workspace/tools/uvr5/uvr5_weights/VR-DeEchoAggressive.pth
1210.8 e09d85|OK  |   225KiB/s|/workspace/tools/uvr5/uvr5_weights/HP5_only_main_vocal.pth
1210.8 a216cb|OK  |   526KiB/s|/workspace/GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large/pytorch_model.bin
1210.8
1210.8 Status Legend:
1210.8 (OK):download completed.(ERR):error occurred.
1210.8
1210.8 aria2 will resume download if the transfer is restarted.
1210.8 If there are any errors, then see the log file. See '-l' option in help/man page for details.
------
Dockerfile:33
--------------------
  32 |     # elite 类型的镜像里面不包含额外的模型
  33 | >>> RUN if [ "$IMAGE_TYPE" != "elite" ]; then \
  34 | >>>         chmod +x /workspace/Docker/download.sh && \
  35 | >>>         /workspace/Docker/download.sh && \
  36 | >>>         python /workspace/Docker/download.py && \
  37 | >>>         python -m nltk.downloader averaged_perceptron_tagger cmudict; \
  38 | >>>     fi
  39 |
--------------------
ERROR: failed to solve: process "/bin/sh -c if [ \"$IMAGE_TYPE\" != \"elite\" ]; then         chmod +x /workspace/Docker/download.sh &&         /workspace/Docker/download.sh &&         python /workspace/Docker/download.py &&         python -m nltk.downloader averaged_perceptron_tagger cmudict;     fi" did not complete successfully: exit code: 1

**Comment by RVC-Boss** [comment]
nltk data的下载在墙外
