### ISSUE TITLE
修改 symbol.py 以支持新语言

### ISSUE THREAD

**Issue by lpscr** [RVC-Boss/GPT-SoVITS#1279]
感谢您的报告。

我想在 symbol.py 文件中添加一种新语言。我需要引入新的键，而不仅仅是替换现有的11个键。但是，添加这些新键导致问题，因为它会影响其他部分并引发错误。

您能指导我如何添加新的符号并调整长度吗？我应该在代码的哪里进行这些更改？

调整后，我是否可以对模型进行微调，还是需要从头开始训练？

感谢您的帮助。

**Comment by RVC-Boss** [comment]
> 感谢您的报告。
> 
> 我想在 symbol.py 文件中添加一种新语言。我需要引入新的键，而不仅仅是替换现有的11个键。但是，添加这些新键导致问题，因为它会影响其他部分并引发错误。
> 
> 您能指导我如何添加新的符号并调整长度吗？我应该在代码的哪里进行这些更改？
> 
> 调整后，我是否可以对模型进行微调，还是需要从头开始训练？
> 
> 感谢您的帮助。

@lpscr 参考
https://huggingface.co/AkitoP/GPT-SoVITS-JA-ProsodyControl_model/blob/main/insert_symbol.ipynb

**Comment by lpscr** [comment]
@RVC-Boss 非常感谢！你是最棒的!
