### ISSUE TITLE
切片时RuntimeError: Failed to load audio: module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by yiyan32** [RVC-Boss/GPT-SoVITS#129]
1、开的虚拟环境，win11，requirements列表也拉取了，ffmpeg也放在指定路径了，python3.9，所有模型都下载了，不知道问题出在哪里。

2、运行uvr的时候报错，UnboundLocalError: local variable 'pre_fun' referenced before assignment

**Comment by RVC-Boss** [comment]
pre_fun的报错能否截下全部报错信息

**Comment by yiyan32** [comment]
> pre_fun的报错能否截下全部报错信息

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/31955141/c860121b-9583-4770-bbde-d1e724551e98)
报错的两个问题用分别两个框框表示了，感谢！

**Comment by BlacknoSheep** [comment]
`Failed to load audio: {e}` 可能是”训练集音频文件目录“造成的，我用相对路径也会报这个错，换音频文件夹的绝对路径就行了

**Comment by VINK77aaaa** [comment]
![jie](https://github.com/RVC-Boss/GPT-SoVITS/assets/157553859/1cb0b73a-70de-4dfa-8232-1b7336d31a1b)
同样的问题

**Comment by yiyan32** [comment]
> `Failed to load audio: {e}` 可能是”训练集音频文件目录“造成的，我用相对路径也会报这个错，换音频文件夹的绝对路径就行了

文件夹和音频文件的相对路径、绝对路径都尝试了依然报错，还是用整合去了

**Comment by VINK77aaaa** [comment]
我已经成功解决了此问题，下面是chatgpt总结的内容
问题发现
初始问题：您在使用 Python 脚本处理音频文件时遇到了一个错误，提示 ffmpeg 模块没有 input 属性。

代码审查：您提供了相关的 Python 脚本代码，包括使用 ffmpeg 的部分。初步检查代码没有发现明显的错误。

确认安装情况：您确认了已经安装了 ffmpeg 命令行工具，并且还尝试安装和卸载了 ffmpeg-python 库。

模块导入测试：在尝试直接在 Python 环境中导入 ffmpeg 时，遇到了 ModuleNotFoundError，表明 Python 环境中没有找到 ffmpeg 模块。

解决过程
环境检查与重装：首先建议您确认 Python 解释器版本，并在正确的环境中重新安装 ffmpeg-python 库。

路径和语法检查：建议您在 Python 代码中使用原始字符串或适当的转义来表示文件路径，避免语法错误。

成功测试：您使用 ffmpeg-python 成功获取了音频文件的信息，这表明 ffmpeg-python 已正确安装并可以正常工作。

结论
这个问题主要是由于 Python 环境中 ffmpeg-python 库的安装问题导致的。通过确认 Python 环境、正确安装 ffmpeg-python 库，并确保使用正确的语法和路径格式，最终成功解决了问题。您现在可以使用 ffmpeg-python 进行音频文件的处理。


重装完ffmpeg-python 库后，可以用此代码测试你的ffmpeg是否安装完成：
import ffmpeg

try:
    probe = ffmpeg.probe(r"C:\Users\13720\Desktop\cs.wav_0_120320.wav")
    print(probe)
except ffmpeg.Error as e:
    print(e.stderr.decode())

**Comment by VINK77aaaa** [comment]
重新安装 ffmpeg-python：
有时重新安装可以解决兼容性或损坏的安装问题。使用以下命令来重新安装 ffmpeg-python：

pip uninstall ffmpeg-python
pip install ffmpeg-python

**Comment by VINK77aaaa** [comment]
刚解决完input的问题，现在又出现了新问题了
![jie](https://github.com/RVC-Boss/GPT-SoVITS/assets/157553859/778b477d-d49b-4024-a541-aaf1554b5af1)

**Comment by VINK77aaaa** [comment]
如果上面还不行，可是再检查一下训练集的路径是否设置错了
尝试在命令行中手动运行 ffmpeg 命令来处理该文件，以验证路径是否正确。例如：
ffmpeg -i "D:\AI\GPT-SoVITS\output\slicer_opt\XYPS\cs.wav_99880640_100035840.wav" -f wav output.wav
确定 ffmpeg 能否正确访问和处理该文件。

**Comment by RVC-Boss** [comment]
解决了就好~
