### ISSUE TITLE
asr output_folder 参数传递错误

### ISSUE THREAD

**Issue by dvdcjw** [RVC-Boss/GPT-SoVITS#1290]
100%|████████████████████████████████████████████████████████████████████████████████| 526/526 [02:09<00:00,  4.08it/s]
Traceback (most recent call last):
  File "F:\AI\GPT-SoVITS-beta0706\tools\asr\funasr_asr.py", line 72, in <module>
    execute_asr(
  File "F:\AI\GPT-SoVITS-beta0706\tools\asr\funasr_asr.py", line 50, in execute_asr
    os.makedirs(output_folder, exist_ok=True)
  File "os.py", line 225, in makedirs
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'F:\\Dataset\\auditory\\_******_" -s large -l zh -p float16'

报错可见output_folder字符串后方多了" -s large -l zh -p float16导致报错。我用的整合包，没有ide的debug工具没能确定是哪里导致的错误。重复了多次，可复现。
![tmpC78A](https://github.com/RVC-Boss/GPT-SoVITS/assets/97785943/32058ab6-f58b-4bff-81d6-5744a904ec4e)

**Comment by XXXXRT666** [comment]
路径多了个斜杠

**Comment by RVC-Boss** [comment]
嗯，输出文件夹路径结尾带了一个\

**Comment by RVC-Boss** [comment]
@XXXXRT666 my_utils里找找，有个clean_path函数，可以对webui前端里面所有路径clean一下，strip("\")，测完可以提个pr

**Comment by RVC-Boss** [comment]
已修复
