### ISSUE TITLE
Numpy conflicting dependencies

### ISSUE THREAD

**Issue by ReZeroE** [RVC-Boss/GPT-SoVITS#1304]
I'm encountering an issue with conflicting dependencies while installing the requirements.txt from python3.10 on windows.

To replicate the issue, run pip install from vir env:
```
$ py -3.10 -m venv venv
$ ./venv/Script/activate
$ pip install -r requirements.txt
```

Error:
```
INFO: pip is looking at multiple versions of librosa to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r .\requirements.txt (line 4), -r .\requirements.txt (line 5) and numpy==1.26.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.26.4
    librosa 0.9.2 depends on numpy>=1.17.0
    numba 0.56.4 depends on numpy<1.24 and >=1.18

```

Notice that in `requirements.txt`, the requested versions are:

```
numpy==1.26.4
numba==0.56.4
```

**Comment by XXXXRT666** [comment]
Please have a look at requirements.txt again

**Comment by RVC-Boss** [comment]
> Please have a look at requirements.txt again

↑ it's right

**Comment by ReZeroE** [comment]
Ah, sorry for not clarifying this in advance. 

> If you are a Windows user (tested with win>=10), you can [download the integrated package](https://huggingface.co/lj1995/GPT-SoVITS-windows-package/resolve/main/GPT-SoVITS-beta.7z?download=true) and double-click on go-webui.bat to start GPT-SoVITS-WebUI.

I was referring to the integrated package downloaded from hugging face (using the url above from the readme). I didn't notice that the main branch has an updated version of the requirements.txt.

Anyhow, thanks for the heads up!

**Comment by XXXXRT666** [comment]
You should not doing anything on the integrated packages environment, just double clicking bat to start
