### ISSUE TITLE
Mac M1 一键安装的时候报错

### ISSUE THREAD

**Issue by ipconfiger** [RVC-Boss/GPT-SoVITS#1305]
```
ffmpeg 已安装.
安装virtualenv...
xattr: [Errno 1] Operation not permitted: './runtime/.Python'
xattr: [Errno 1] Operation not permitted: './runtime/bin/python3'
xattr: [Errno 1] Operation not permitted: './runtime/bin/python'
xattr: [Errno 1] Operation not permitted: './runtime/bin/python3.9'
An error occurred.
```

**Comment by XXXXRT666** [comment]
这写文件应该放置在mac里,你的这些文件在哪?

**Comment by ipconfiger** [comment]
╰─$ whereis python                                                          1 ↵
python: /Users/alex/.pyenv/shims/python

**Comment by XXXXRT666** [comment]
我说的是./runtime在哪里,他前面的路径长啥样

**Comment by XXXXRT666** [comment]
这个一键包不需要你电脑上有python,装了也不会用

**Comment by ipconfiger** [comment]
我看脚本里应该是这里报错
···
CommandlineToolPath=$(xcode-select -p)
PYTHON1 = "${CommandlineToolPath}/Library/Frameworks/Python3.framework/Versions/3.9/Python3"
PYTHON2 = "${CommandlineToolPath}/Library/Frameworks/Python3.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python"

ln -sfn $PYTHON1 ./runtime/.Python
ln -sfn $PYTHON2 ./runtime/bin/python
ln -sfn $PYTHON2 ./runtime/bin/python3
ln -sfn $PYTHON2 ./runtime/bin/python3.9
···

$PYTHON1 就是 /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Python3

./runtime 就是在执行目录下的runtime目录吧，我的是在 /Users/alex/Projects/testspace/GPT-SoVITS

**Comment by XXXXRT666** [comment]
什么系统，报错的不是这里

**Comment by ipconfiger** [comment]
MacOS Sonoma 14.5

**Comment by ipconfiger** [comment]
那就是后面
sudo /usr/bin/xattr -dr com.apple.quarantine "./runtime"
这句报错了 runtime目录应该是脚本创建的吧

**Comment by ipconfiger** [comment]
我加了一句echo查到了 ./runtime  目录就是  /Users/alex/Projects/testspace/GPT-SoVITS/runtime

**Comment by ipconfiger** [comment]
![WeChata127accb21f94715124e0195046cd7a1](https://github.com/user-attachments/assets/5fbfd2e3-2e6a-49af-abd9-22fcbc29bb8d)
![WeChat33de78858bf64cf401af5b20801bbdab](https://github.com/user-attachments/assets/144af981-1c9e-417c-a3bd-9ce26e666c1b)

**Comment by XXXXRT666** [comment]
更新了一版,现在解决了,这个权限问题不知道怎么回事,直接跳过了

**Comment by ipconfiger** [comment]
直接git pull 更新文件就行了么？还是直接注释这一行？

**Comment by XXXXRT666** [comment]
重新下一键包

**Comment by ipconfiger** [comment]
我是git clone下来的

**Comment by XXXXRT666** [comment]
git clone下来的根本就没这个sh

**Comment by ipconfiger** [comment]
嗯？直接install.sh  ?

**Comment by XXXXRT666** [comment]
???这个sh就是我自己写的,配合一键包使用,install.sh就不是给Mac用的

**Comment by ipconfiger** [comment]
那重新下的一键包能够给个链接？

**Comment by XXXXRT666** [comment]
GitHub Readme中文教程链接里的Mac教程里有

**Comment by ipconfiger** [comment]
O了，3KS
