### ISSUE TITLE
ConnectionResetError: [WinError 10054]

### ISSUE THREAD

**Issue by WhatchOutLemar** [RVC-Boss/GPT-SoVITS#1307]
# 运行环境信息
- win11
- GPT-SoVITS-beta0706
- Google Chrome

# 报错信息
```
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
```
![Snipaste_2024-07-15_08-38-56](https://github.com/user-attachments/assets/2ecaa448-d3e3-4622-b83d-7754ec53a1a9)
![Snipaste_2024-07-15_08-44-15](https://github.com/user-attachments/assets/5d555b1d-dbdb-4b79-b056-5cfe076f972b)

> 这个问题出现在打标阶段，看着报错有点慌，但不知道是否会有影响，看了类似的Issues好像是没有影响？

通过命令检查了对应的端口，也关闭了所有的防火墙服务，https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e/pgah3gvetrdy8ryt#dNntg
里让刷新，刷新完还是会报相同的错
```
curl http://localhost:9871
curl http://localhost:9874
```
都返回正常结果

**Comment by SapphireLab** [comment]
之前查过好像没什么办法，应该是 gradio 的问题，不影响使用就行。

**Comment by RVC-Boss** [comment]
楼上正解，目前没有发现什么好办法，但是不影响使用
