### ISSUE TITLE
Which of the two integrated packages GPT SoVITS beta0706 and GPT SoVITS beta0306fix2 works better

### ISSUE THREAD

**Issue by hjj-lmx** [RVC-Boss/GPT-SoVITS#1308]

**Comment by RVC-Boss** [comment]
0706=0217=better than 0306 bs>1
speed:
    0706 double speed compared with 0217
    0306 at least double speed compared with 0217, but faster when bs>1

0217 == 0306_bs=1？ This needs to be verified
