### ISSUE TITLE
为什么会依赖sqlite3

### ISSUE THREAD

**Issue by steeveen** [RVC-Boss/GPT-SoVITS#1309]
这个项目为什么会依赖数据库呀。
我启动的时候报缺少sqlite3，看报错是从english.py中的from g2p_en import G2p 进而导致依赖到sqlite3的
感觉解耦一些，只保留关键功能就好

**Comment by SapphireLab** [comment]
G2p 应该没有明显引入 sqlite3， python 是有一个内置模块，但不确定你说的是不是它。
有没有更详细的日志？

**Comment by steeveen** [comment]
有的，在另一台电脑上，明天去看下

**Comment by RVC-Boss** [comment]
g2p_en也是引用的别人的库

**Comment by RVC-Boss** [comment]
其实比较疑惑的是为啥有不自带sqlite3的python环境
