### ISSUE TITLE
请问训练好的模型是可以用在其他软件上吗？下面细说

### ISSUE THREAD

**Issue by yunmonth** [RVC-Boss/GPT-SoVITS#1315]
7月16日左右安装的GPT-soviets，请问训练好的模型是可以用在其他软件上吗，比如replay和sovits的变声整合包，训练之后保存的文件貌似只有.pth，和.ckpt为后缀的，而没有.index。

**Comment by SapphireLab** [comment]
面向的问题不同，模型架构不同，并不能直接迁移。

**Comment by RVC-Boss** [comment]
rvc训练出来的可以兼容replay，其他不兼容。
