### ISSUE TITLE
batch_size计算问题

### ISSUE THREAD

**Issue by zhiqiuiyiye** [RVC-Boss/GPT-SoVITS#1318]
相同的数据训练s1，相同的batch_size
使用双卡训练，得到的batch_num 是单卡的1/4, 如果使用三卡，得到的batch_num是单卡的1/9，请问这个现象正常吗？
![微信截图_20240717155918](https://github.com/user-attachments/assets/0a99aea1-4c26-4341-bbd9-812467e558b6)
![微信截图_20240717155905](https://github.com/user-attachments/assets/c51f1413-2fc2-46c5-b7df-f21497ba32d3)
单卡训练的情况

![微信截图_20240717155733](https://github.com/user-attachments/assets/285b5fda-f1b8-4722-a152-0eb09d4e3f63)
![微信截图_20240717155757](https://github.com/user-attachments/assets/2cd94836-e08e-43c3-8750-58603e929c5e)
双卡训练的情况

**Comment by RVC-Boss** [comment]
楼主试下这个https://github.com/RVC-Boss/GPT-SoVITS/pull/756
加上这行再看看step对了吗

**Comment by zhiqiuiyiye** [comment]
> 楼主试下这个#756 加上这行再看看step对了吗

改过之后是正常的，感谢~
