### ISSUE TITLE
Feature request: Is singing voice conversion possible?

### ISSUE THREAD

**Issue by luckui** [RVC-Boss/GPT-SoVITS#1320]
Feature request: Is singing voice conversion possible?

**Comment by Lin-Silver** [comment]
I think you can use So-vits-SVC or RVC
https://github.com/svc-develop-team/so-vits-svc
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI

**Comment by luckui** [comment]
> I think you can use So-vits-SVC or RVC https://github.com/svc-develop-team/so-vits-svc https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI
Thanks! I have tried the so-vits svc, but it requires large amount of data to train. What is RVC? Can I directly use the weights I trained with gpt sovits? What are the differences between the RVC and the so-vits svc?
