### ISSUE TITLE
can not find  cleaned_text_to_sequence  in  GPT_SoVITS/text

### ISSUE THREAD

**Issue by dshwei** [RVC-Boss/GPT-SoVITS#1321]
from text import chinese, japanese, cleaned_text_to_sequence, symbols, english

in this project ,the cleaned_text_to_sequence function  can not be found

**Comment by SapphireLab** [comment]
the function is in the `text/__init__.py`

![748bcd17-df7c-46b5-9e12-d31054ae0071](https://github.com/user-attachments/assets/dbbef74f-7c09-4c23-9344-24e56f711518)

**Comment by RVC-Boss** [comment]
↑ that's right
