### ISSUE TITLE
如何英文字母漏音问题如何解决

### ISSUE THREAD

**Issue by yitingss** [RVC-Boss/GPT-SoVITS#1322]
使用中文数据微调模型，如果合成的英文中包含类似A,I时，会出现漏音的问题。比如app读成pp，ai读成a或者i，提取的音素是正常的，但是有一定概率出现漏音，要如何优化呢

**Comment by RVC-Boss** [comment]
得等新底模了，因为初版底模训练的时候是没优化过英文的。虽然后面推理优化了
