### ISSUE TITLE
請問串接pyvideotrans API時 都會顯示 "GET / HTTP/1.1" 500 Internal Server Error ERROR: 請問有前輩可以解決嗎^^

### ISSUE THREAD

**Issue by Hungchenyao** [RVC-Boss/GPT-SoVITS#1326]
請問串接pyvideotrans API時 都會顯示 "GET / HTTP/1.1" 500 Internal Server Error ERROR: 請問有前輩可以解決嗎^^

**Comment by KamioRinn** [comment]
pyvideotrans使用的是自己写的api，请咨询pyvideotrans

**Comment by RVC-Boss** [comment]
嗯，建议你去他们的issue区问呢
