### ISSUE TITLE
trendshift.io GitHub Tread

### ISSUE THREAD

**Issue by KakaruHayate** [RVC-Boss/GPT-SoVITS#1333]
<a href="https://trendshift.io/repositories/7033" target="_blank"><img src="https://trendshift.io/api/badge/repositories/7033" alt="RVC-Boss%2FGPT-SoVITS | Trendshift" style="width: 250px; height: 55px;" width="250" height="55"/></a>

**Comment by RVC-Boss** [comment]
啊？

**Comment by RVC-Boss** [comment]
done
