### ISSUE TITLE
有相关论文或者模型介绍吗，比较感兴趣想了解下下具体模型结构和思路。

### ISSUE THREAD

**Issue by zhuangzhuangliu2345** [RVC-Boss/GPT-SoVITS#134]
rt

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/issues/67
具体模型结构和训练阶段参照这个issue

**Comment by RVC-Boss** [comment]
以及https://github.com/innnky/ar-vits/tree/mqvits/AR
