### ISSUE TITLE
tone_sandhi中的变调问题

### ISSUE THREAD

**Issue by LonelyTaker** [RVC-Boss/GPT-SoVITS#1361]
_merge_yi 函数尝试把 x一x 这种形式的分词拼接到一起
但是有个条件是 x为动词（v），但有些时候可能会出现 动语素（vg）的情况，如：炫一炫
这个时候出来的结果就会有问题：
input：[('炫', 'vg'), ('一', 'm'), ('炫', 'v')]
output：[['炫', 'vg'], ['一', 'm']]

原因在于下方的代码将最后一个字continue了

```python
if (
  i - 2 >= 0
  and seg[i - 1][0] == "一"
  and seg[i - 2][0] == word
  and pos == "v"
):
  continue
else:
  new_seg.append([word, pos])
```

如果是为了忽略已被捕获的情况，改成：

```python
if (
  i - 2 >= 0
  and seg[i - 1][0] == "一"
  and seg[i - 2][0] == word
  and pos == "v"
  and seg[i - 2][1] == "v"
):
  continue
else:
  new_seg.append([word, pos])
```

会不会更好？
但是这样 output 就会变成[['炫', 'vg'], ['一炫', 'm']]，这是否满足预期？
因为我不太理解 动语素（vg） 的概念，不清楚它在这个函数中是否应该和动词（v）相同处理

**Comment by LonelyTaker** [comment]
#1362

**Comment by RVC-Boss** [comment]
合并了，后面持续观察
