### ISSUE TITLE
DPO逻辑中，随机选择重复读和漏读的random是不是有问题，torch.randint(0, 1, size=(1, ))获取的永远是0只能进重复读分支

### ISSUE THREAD

**Issue by deryy** [RVC-Boss/GPT-SoVITS#1375]
上限为1则不包含1， 请问是特意这么设计的么，还是需要改成torch.randint(0, 2, size=(1, ))呢
这样的话是不是DPO逻辑其实并没有对漏读起到作用

**Comment by XXXXRT666** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/issues/950
