### ISSUE TITLE
version `GLIBCXX_3.4.32' not found

### ISSUE THREAD

**Issue by csdY123** [RVC-Boss/GPT-SoVITS#138]
Traceback (most recent call last):
  File "/ML-A100/team/mm/chen/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 28, in <module>
    from text.cleaner import clean_text
  File "/ML-A100/team/mm/chen/GPT-SoVITS/GPT_SoVITS/text/cleaner.py", line 1, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "/ML-A100/team/mm/chen/GPT-SoVITS/GPT_SoVITS/text/japanese.py", line 5, in <module>
    import pyopenjtalk
  File "/ML-A100/team/mm/chen/anaconda3/envs/GPTSoVITS/lib/python3.10/site-packages/pyopenjtalk/__init__.py", line 21, in <module>
    from .openjtalk import OpenJTalk
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /ML-A100/team/mm/chen/anaconda3/envs/GPTSoVITS/lib/python3.10/site-packages/pyopenjtalk/openjtalk.cpython-310-x86_64-linux-gnu.so)

Has anyone encountered this problem?

**Comment by selfboot** [comment]
You can use ldd find so file:

```
ldd /ML-A100/team/mm/chen/anaconda3/envs/GPTSoVITS/lib/python3.10/site-packages/pyopenjtalk/openjtalk.cpython-310-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007fff616fa000)
        /$LIB/libonion_block.so => /lib64/libonion_block.so (0x00007ff20f9fc000)
        /$LIB/libonion.so => /lib64/libonion.so (0x00007ff20ff26000)
        libstdc++.so.6 => /data/home/miniconda3/envs/GPTSoVits/lib/libstdc++.so.6 (0x00007ff20f819000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ff20f497000)
        libgcc_s.so.1 => /data/home/miniconda3/envs/GPTSoVits/lib/libgcc_s.so.1 (0x00007ff20ff01000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff20f277000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ff20eeb2000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ff20ecae000)
        librt.so.1 => /lib64/librt.so.1 (0x00007ff20eaa6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff20fe01000)
```

If you find so path in conda , then can change the LD_LIBRARY_PATH to fix ti.

```
export LD_LIBRARY_PATH=/data/home//miniconda3/envs/GPTSoVits/lib:$LD_LIBRARY_PATH
```

**Comment by lorsonblair** [comment]
Hi guys. So I was having this issue also. I was able to install with conda install -c conda-forge libstdcxx-ng and GLIBCXX_3.4.32 is listed when I run the string ... grep command, however, I'm still getting the error.

**Comment by XXXXRT666** [comment]
use install.sh

**Comment by lorsonblair** [comment]
Could you explain? I do not have sudo privileges on the machine so I have to work in conda. I am getting the error with libstdc++.so.6+. I changed the LD path to point to my conda env where glibcxx is listed, but I'm still getting the error. I'm using triton. Triton is trying to import the GLIBCXX 3.4.32.

**Comment by XXXXRT666** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/blob/main/install.sh

**Comment by lorsonblair** [comment]
This is not software I'm having issues with. I'm having issues with triton 3.4 trying to find GLIBCXX 3.4.32. The error is below:

` File "/gpfs/u/home/.../miniconda3/envs/low-precision/lib/python3.11/site-packages/triton/backends/amd/compiler.py", line 2, in <module>
    from triton._C.libtriton import ir, passes, llvm, amd
ImportError: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /gpfs/u/home/.../miniconda3/envs/low-precision/lib/python3.11/site-packages/triton/_C/libtriton.so)`

**Comment by XXXXRT666** [comment]
> This is not software I'm having issues with. 

Then you should go ask in Triton’s issue section.
