### ISSUE TITLE
增加一个类似于腾讯智影的数字人播报中关于数字字符的读法处理

### ISSUE THREAD

**Issue by originwufish** [RVC-Boss/GPT-SoVITS#1383]
三种读法：
(12321312)电话读法：幺二三二幺三幺二
(12321312)数值读法：一千二百三十二万一千三百一十二
(12321312)序列读法：一二三二一三一二 

>def convert_to_chinese_value(num):
>    num_map = {
>        '0': '零', '1': '一', '2': '二', '3': '三', '4': '四',
>        '5': '五', '6': '六', '7': '七', '8': '八', '9': '九'
>    }
>    unit_map = {
>        1: '', 2: '十', 3: '百', 4: '千', 5: '万', 6: '亿'
>    }
>
>    def convert(n):
>        result = ''
>        for i, digit in enumerate(str(n)[::-1]):
>            if digit == '0':
>                if result or (i < len(str(n)) - 1 and str(n)[len(str(n)) - i - 1] != '0'):
>                    result += '零'
>            else:
>                result = num_map[digit] + (unit_map[i + 1] if i < len(unit_map) - 1 else '') + result
>        return result.strip()
>
>    if isinstance(num, int):
>        return convert(num)
>    else:
>        raise ValueError("Input must be an integer.")
>
>def replace_numbers_with_chinese(text):
>    phone_dict = {
>        '1': '幺', '2': '二', '3': '三', '4': '四',
>        '5': '五', '6': '六', '7': '七', '8': '八',
>        '9': '九', '0': '零'
>    }
>    sequence_dict = {
>        '1': '一', '2': '二', '3': '三', '4': '四',
>        '5': '五', '6': '六', '7': '七', '8': '八',
>        '9': '九', '0': '零'
>    }
>
>    pattern = re.compile(r'(\d+)\[(phone|value|sequence):(\d+)\]')
>
>    def replace_match(match):
>        num = match.group(1)  # 保持不变，提取数字序列
>        type = match.group(2)  # 从标签中提取类型
>        num_chars = int(match.group(3))  # 提取要读取的数字字符数量
>        if type == 'phone':
>            return num[:-num_chars] + ''.join(phone_dict[n] for n in num[-num_chars:])
>        elif type == 'value':
>            return num[:-num_chars] + convert_to_chinese_value(int(num[-num_chars:]))
>        elif type == 'sequence':
>            return num[:-num_chars] + ''.join(sequence_dict[n] for n in num[-num_chars:])
>        else:
>            return match.group(0)  # 如果没有匹配到类型，返回原字符串
>
>    new_text = text
>    for key, value in roman_dict.items():
>        new_text = re.sub(r'(?<![a-zA-Z])' + key + r'(?![a-zA-Z])', value, new_text)
>
>    for key, value in replace_dict.items():
>        new_text = new_text.replace(key, value)
>
>    return pattern.sub(replace_match, new_text)

**Comment by KamioRinn** [comment]
当前版本代码中对中文模式下数字已经有以上规则的自动判断了

**Comment by originwufish** [comment]
是的大佬，但是我测试的时候某些词会不准，比如100年读的是一零零年，所以我就写了一个通过标志位手动插入改变读法的逻辑，这样就可以100[value:3]年就可以读为一百年了

**Comment by KamioRinn** [comment]
是的，对于数字/量词有时候读法会有歧义，这个可以考虑以后做个面向专业用户的模式，灵活介入调整文字格式化的结果。

**Comment by originwufish** [comment]
好的，感谢两位大佬的开源以及解答
