### ISSUE TITLE
ModuleNotFoundError: No module named 'loguru' 

### ISSUE THREAD

**Issue by Leo868123** [RVC-Boss/GPT-SoVITS#1392]
While I running in Colab, an error occur.
![Screenshot 2024-08-04 122247](https://github.com/user-attachments/assets/de0c4682-5839-4743-9b0a-81d1cd8c95e7)

**Comment by KamioRinn** [comment]
so-vits-svc is not this project

**Comment by Leo868123** [comment]
> so-vits-svc is not this project
what is the true project

**Comment by Leo868123** [comment]
> so-vits-svc is not this project
sorry, I made a mistake.
