### ISSUE TITLE
1Aa-文本内容 出现错误

### ISSUE THREAD

**Issue by dvdcjw** [RVC-Boss/GPT-SoVITS#1394]
如下

> "E:\GPT-SoVITS\.venv\Scripts\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
> "E:\GPT-SoVITS\.venv\Scripts\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
> you have to install eunjeon. "pip install eunjeon"
> Traceback (most recent call last):
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\eunjeon\_mecab.py", line 101, in __init__
>     self.tagger = Tagger('--rcfile %s' % dicpath)
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\eunjeon\mecab.py", line 528, in __init__
>     this = _MeCab.new_Tagger(*args)
> RuntimeError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\eunjeon\_mecab.py", line 104, in __init__
>     self.tagger = Tagger('--rcfile %s' % dicpath)
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\eunjeon\mecab.py", line 528, in __init__
>     this = _MeCab.new_Tagger(*args)
> RuntimeError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\g2pk2\g2pk2.py", line 88, in get_mecab
>     return m.Mecab()
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\eunjeon\_mecab.py", line 106, in __init__
>     raise Exception('The MeCab dictionary does not exist at "%s". Is the dictionary correctly installed?\nYou can also try entering the dictionary path when initializing the Mecab class: "Mecab(\'/some/dic/path\')"' % dicpath)
> Exception: The MeCab dictionary does not exist at "E:\GPT-SoVITS\.venv\Lib\site-packages\eunjeon\data\mecabrc". Is the dictionary correctly installed?
> You can also try entering the dictionary path when initializing the Mecab class: "Mecab('/some/dic/path')"
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\GPT-SoVITS\GPT_SoVITS\prepare_datasets\1-get-text.py", line 19, in <module>
>     from text.cleaner import clean_text
>   File "E:\GPT-SoVITS\GPT_SoVITS\text\cleaner.py", line 1, in <module>
>     from text import japanese, cleaned_text_to_sequence, english,korean,cantonese
>   File "E:\GPT-SoVITS\GPT_SoVITS\text\korean.py", line 227, in <module>
>     _g2p=G2p()
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\g2pk2\g2pk2.py", line 30, in __init__
>     self.mecab = self.get_mecab()
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\g2pk2\g2pk2.py", line 90, in get_mecab
>     raise print(f'you have to install eunjeon. "pip install eunjeon"')
> TypeError: exceptions must derive from BaseException
> you have to install eunjeon. "pip install eunjeon"
> Traceback (most recent call last):
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\eunjeon\_mecab.py", line 101, in __init__
>     self.tagger = Tagger('--rcfile %s' % dicpath)
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\eunjeon\mecab.py", line 528, in __init__
>     this = _MeCab.new_Tagger(*args)
> RuntimeError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\eunjeon\_mecab.py", line 104, in __init__
>     self.tagger = Tagger('--rcfile %s' % dicpath)
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\eunjeon\mecab.py", line 528, in __init__
>     this = _MeCab.new_Tagger(*args)
> RuntimeError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\g2pk2\g2pk2.py", line 88, in get_mecab
>     return m.Mecab()
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\eunjeon\_mecab.py", line 106, in __init__
>     raise Exception('The MeCab dictionary does not exist at "%s". Is the dictionary correctly installed?\nYou can also try entering the dictionary path when initializing the Mecab class: "Mecab(\'/some/dic/path\')"' % dicpath)
> Exception: The MeCab dictionary does not exist at "E:\GPT-SoVITS\.venv\Lib\site-packages\eunjeon\data\mecabrc". Is the dictionary correctly installed?
> You can also try entering the dictionary path when initializing the Mecab class: "Mecab('/some/dic/path')"
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\GPT-SoVITS\GPT_SoVITS\prepare_datasets\1-get-text.py", line 19, in <module>
>     from text.cleaner import clean_text
>   File "E:\GPT-SoVITS\GPT_SoVITS\text\cleaner.py", line 1, in <module>
>     from text import japanese, cleaned_text_to_sequence, english,korean,cantonese
>   File "E:\GPT-SoVITS\GPT_SoVITS\text\korean.py", line 227, in <module>
>     _g2p=G2p()
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\g2pk2\g2pk2.py", line 30, in __init__
>     self.mecab = self.get_mecab()
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\g2pk2\g2pk2.py", line 90, in get_mecab
>     raise print(f'you have to install eunjeon. "pip install eunjeon"')
> TypeError: exceptions must derive from BaseException
> Traceback (most recent call last):
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\gradio\routes.py", line 442, in run_predict
>     output = await app.get_blocks().process_api(
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\gradio\blocks.py", line 1389, in process_api
>     result = await self.call_function(
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\gradio\blocks.py", line 1108, in call_function
>     prediction = await utils.async_iteration(iterator)
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\gradio\utils.py", line 346, in async_iteration
>     return await iterator.__anext__()
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\gradio\utils.py", line 339, in __anext__
>     return await anyio.to_thread.run_sync(
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
>     return await get_async_backend().run_sync_in_worker_thread(
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
>     return await future
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
>     result = context.run(func, *args)
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\gradio\utils.py", line 322, in run_sync_iterator_async
>     return next(iterator)
>   File "E:\GPT-SoVITS\.venv\lib\site-packages\gradio\utils.py", line 691, in gen_wrapper
>     yield from f(*args, **kwargs)
>   File "E:\GPT-SoVITS\webui.py", line 443, in open1a
>     with open(txt_path, "r", encoding="utf8") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'logs/xxx/2-name2text-0.txt'

python3.9.13，符合requirements.txt，torch安装无误，cudacuddn无误，ffmpeg无误。

**Comment by KamioRinn** [comment]
pip install eunjeon。
或者将代码退回到https://github.com/RVC-Boss/GPT-SoVITS/commit/4c8b7612206536b8b4435997acb69b25d93acb78

**Comment by KamioRinn** [comment]
windows端安装eunjeon还需要vs2017环境（更高环境暂无测试）

**Comment by dvdcjw** [comment]
> pip install eunjeon。 或者将代码退回到[4c8b761](https://github.com/RVC-Boss/GPT-SoVITS/commit/4c8b7612206536b8b4435997acb69b25d93acb78)

eunjeon已经安装了。pip install eunjeon显示requirement already satisfied

**Comment by KamioRinn** [comment]
> eunjeon已经安装了。pip install eunjeon显示requirement already satisfied

拉取最新的代码先用回V1版本吧。
eunjeon的话pip show eunjeon有显示吗。

**Comment by dvdcjw** [comment]
我有eunjeon，找到了对应代码，在
Lib\site-packages\g2pk2\g2pk2.py

```python
            if platform.system() == 'Windows':
                try:
                    m = self.load_module_func('eunjeon')
                    return m.Mecab()
                except Exception as e:
                    raise print(f'you have to install eunjeon. "pip install eunjeon"')
```

return m.Mecab()出错了。我这里
```
...s\eunjeon\_mecab.py", line 106, in __init__
    raise Exception('The MeCab dictionary does not exist at "%s". Is the dictionary correctly installed?\nYou can also try entering the dictionary path when initializing the Mecab class: "Mecab(\'/some/dic/path\')"' % dicpath)
Exception: The MeCab dictionary does not exist at "...\GPT-SoVITS\.venv\Lib\site-packages\eunjeon\data\mecabrc". Is the dictionary correctly installed?
You can also try entering the dictionary path when initializing the Mecab class: "Mecab('/some/dic/path')"
```
但是的确是有这个文件的
![tmp538F](https://github.com/user-attachments/assets/d1d79899-8f97-4470-812f-bac67d99a23e)

**Comment by KamioRinn** [comment]
> g2pk2 任何报错都直接except成you have to install eunjeon. "pip install eunjeon"这一句...

更新到最新代码

**Comment by dvdcjw** [comment]
> .venv前是不是还有中文路径

肯定没有啊 谁项目文件夹放中文路径里。

**Comment by dvdcjw** [comment]
路径里倒是有个空格，当时不知道咋想的...
