### ISSUE TITLE
多音字问题

### ISSUE THREAD

**Issue by ueiyang2** [RVC-Boss/GPT-SoVITS#1395]
“至于世界第二的塞尔维亚选手(德约科维奇)，将以男单头号种子的身份”
这句话中的“种子”, pypinyin是['zhong3', 'zi']，子应该是轻声，为什么生成的音频总是读成['zhong3', 'zi3']呢？

**Comment by KamioRinn** [comment]
下个版本修复，近期会更新

**Comment by RVC-Boss** [comment]
先用v2吧。后面v1也会更新到多音字支持。

**Comment by hjj-lmx** [comment]
> 先用v2吧。后面v1也会更新到多音字支持。

v2怎么使用多音字纠正
