### ISSUE TITLE
推理阶段，通过get_first函数判断一个标点的位置，并在句子一开始加上句号的作用是什么

### ISSUE THREAD

**Issue by yitingss** [RVC-Boss/GPT-SoVITS#1397]
在推理阶段，有一段代码是
` if (text[0] not in splits and len(get_first(text)) < 4): text = "。" + text if text_language != "en" else "." + text`
 会判断文本第一个标点的位置，如果起始的汉字小于4个，会在最开始加一个句号，比如
“一、这是一段测试。”会变成“。一、这是一段测试”，这个操作的原因是什么呢？

**Comment by RVC-Boss** [comment]
提升效果trick
