### ISSUE TITLE
今天更新代码后三连第三步爆模型加载失败

### ISSUE THREAD

**Issue by HsiangLeekwok** [RVC-Boss/GPT-SoVITS#1400]
没更新前是正常的……

![QYWX_20240805220822](https://github.com/user-attachments/assets/89413c8e-9e37-4899-8cf8-d026366ce96d)

```cmd
"D:\ProgramData\anaconda3\envs\sovits\python.exe" GPT_SoVITS/prepare_datasets/3-get-semantic.py
D:\ProgramData\anaconda3\envs\sovits\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "E:\backup\github\GPT-SoVITS\GPT_SoVITS\prepare_datasets\3-get-semantic.py", line 65, in <module>
    vq_model.load_state_dict(
  File "D:\ProgramData\anaconda3\envs\sovits\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for enc_p.text_embedding.weight: copying a param with shape torch.Size([322, 192]) from checkpoint, the shape in current model is torch.Size([732, 192]).
        size mismatch for ref_enc.spectral.0.fc.weight: copying a param with shape torch.Size([128, 1025]) from checkpoint, the shape in current model is torch.Size([128, 704]).
Traceback (most recent call last):
  File "E:\backup\github\GPT-SoVITS\webui.py", line 680, in open1abc
    with open(semantic_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/peter/6-name2semantic-0.tsv'
错误: 没有找到进程 "17916"。
```

**Comment by HsiangLeekwok** [comment]
知道问题在哪了(改回来就正常了)：
models里面所有的类都默认了version="v2"

**Comment by XXXXRT666** [comment]
下一个commit中会修复

**Comment by HsiangLeekwok** [comment]
> 下一个commit中会修复

好的，大佬辛苦了。
后续训练的时候还会报 not in self.phoneme_data ，导致后续训练全部出错。

**Comment by KamioRinn** [comment]
> 好的，大佬辛苦了。 后续训练的时候还会报 not in self.phoneme_data ，导致后续训练全部出错。

同个原因，下一次合并中修复

**Comment by RVC-Boss** [comment]
修复了，试试看

**Comment by HsiangLeekwok** [comment]
> 修复了，试试看

可以了。Good！！

(❤️ ω ❤️)

**Comment by bigbigtooth** [comment]
我修改了文件中的version为v1，问题依然存在，求解决办法！

**Comment by JosenJin** [comment]
在运行api_v2.py时这个问题依然存在？请问怎么解决呀？

Traceback (most recent call last):
  File "D:\ai\josencomfyui\GPT-SoVITS\api_v2.py", line 144, in <module>
    tts_pipeline = TTS(tts_config)
                   ^^^^^^^^^^^^^^^
  File "D:\ai\josencomfyui\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TTS.py", line 252, in __init__
    self._init_models()
  File "D:\ai\josencomfyui\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TTS.py", line 278, in _init_models
    self.init_vits_weights(self.configs.vits_weights_path)
  File "D:\ai\josencomfyui\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TTS.py", line 337, in init_vits_weights
    vits_model.load_state_dict(dict_s2["weight"], strict=False)
  File "D:\ai\anaconda3\envs\comfyui\Lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for enc_p.text_embedding.weight: copying a param with shape torch.Size([732, 192]) from checkpoint, the shape in current model is torch.Size([322, 192]).
        size mismatch for ref_enc.spectral.0.fc.weight: copying a param with shape torch.Size([128, 704]) from checkpoint, the shape in current model is torch.Size([128, 1025]).

**Comment by XXXXRT666** [comment]
> 在运行api_v2.py时这个问题依然存在？请问怎么解决呀？
> 

使用V2

**Comment by kevinlee819** [comment]
---------------------------------------------TTS Config---------------------------------------------
device              : cuda
is_half             : True
version             : v2
t2s_weights_path    : GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt
vits_weights_path   : GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s2G2333k.pth
bert_base_path      : GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
cnhuhbert_base_path : GPT_SoVITS/pretrained_models/chinese-hubert-base
----------------------------------------------------------------------------------------------------

Loading Text2Semantic weights from GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmp3y2bv3u0
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmp3y2bv3u0/_remote_module_non_scriptable.py
Loading VITS weights from GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s2G2333k.pth
Traceback (most recent call last):
  File "/home/api_v2.py", line 143, in <module>
    tts_pipeline = TTS(tts_config)
  File "/home/GPT_SoVITS/TTS_infer_pack/TTS.py", line 252, in __init__
    self._init_models()
  File "/home/GPT_SoVITS/TTS_infer_pack/TTS.py", line 278, in _init_models
    self.init_vits_weights(self.configs.vits_weights_path)
  File "/home/GPT_SoVITS/TTS_infer_pack/TTS.py", line 336, in init_vits_weights
    vits_model.load_state_dict(dict_s2["weight"], strict=False)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for enc_p.text_embedding.weight: copying a param with shape torch.Size([732, 192]) from checkpoint, the shape in current model is torch.Size([322, 192]).
        size mismatch for ref_enc.spectral.0.fc.weight: copying a param with shape torch.Size([128, 704]) from checkpoint, the shape in current model is torch.Size([128, 1025]).
        
        


        我是用的是最新代码，基于
        commit 6d82050b9cce3cd42c573b2179975a25ab5467af (HEAD -> main, origin/main, origin/HEAD)
Author: 刘悦 <zcxey2911@hotmail.com>
Date:   Wed Oct 30 16:38:05 2024 +0800
，但还是出现了这个问题，请问要怎么解决啊，大佬说要使用V2代码是什么意思，能详细解释一下吗，感激不尽
