### ISSUE TITLE
The latest update breaks onnxruntine

### ISSUE THREAD

**Issue by justinjohn0306** [RVC-Boss/GPT-SoVITS#1401]
<img width="979" alt="image" src="https://github.com/user-attachments/assets/0a5f3cfa-d50f-4535-8c10-a667a6bf3957">

**Comment by justinjohn0306** [comment]
running ``conda install conda-forge::vs2015_runtime`` fixed the onnx runtime error but a new issue arises in the webui 
<img width="1919" alt="image" src="https://github.com/user-attachments/assets/85256ba9-5132-4eed-bd3c-cb024f80c92a">

basically the --version arg is missing

**Comment by justinjohn0306** [comment]
The inference webui is looking for a 32k model now? Is it an updated model or am I missing something?

<img width="1916" alt="image" src="https://github.com/user-attachments/assets/0de214b0-d4e1-443c-b9e3-3b65e6768dd1">

**Comment by XXXXRT666** [comment]
wait for the V2 model release
