### ISSUE TITLE
各位大牛，帮忙看下怎么回事，我上个月用的时候还是好的，现在就不行了。（已确保路径都填对了）

### ISSUE THREAD

**Issue by Lkunlong** [RVC-Boss/GPT-SoVITS#1402]
"/usr/local/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
"/usr/local/bin/python" GPT_SoVITS/prepare_datasets/1-get-text.py
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package cmudict to /root/nltk_data...
[nltk_data] Downloading package cmudict to /root/nltk_data...
[nltk_data]   Unzipping corpora/cmudict.zip.
[nltk_data]   Unzipping corpora/cmudict.zip.
mecab installed
mecab installed
当前使用g2pw进行拼音推理
当前使用g2pw进行拼音推理
Downloading g2pw model...
Downloading g2pw model...
Extracting g2pw model...
Extracting g2pw model...
/usr/local/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
Traceback (most recent call last):
  File "/content/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 19, in <module>
    from text.cleaner import clean_text
  File "/content/GPT-SoVITS/GPT_SoVITS/text/cleaner.py", line 13, in <module>
    from text import chinese2 as chinese_v2
  File "/content/GPT-SoVITS/GPT_SoVITS/text/chinese2.py", line 29, in <module>
    g2pw = G2PWPinyin(model_dir="GPT_SoVITS/text/G2PWModel",model_source="GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large",v_to_u=False, neutral_tone_with_five=True)
  File "/content/GPT-SoVITS/GPT_SoVITS/text/g2pw/g2pw.py", line 22, in __init__
    self._g2pw = G2PWOnnxConverter(
  File "/content/GPT-SoVITS/GPT_SoVITS/text/g2pw/onnx_api.py", line 80, in __init__
    uncompress_path = download_and_decompress(model_dir)
  File "/content/GPT-SoVITS/GPT_SoVITS/text/g2pw/onnx_api.py", line 70, in download_and_decompress
    os.rename(extract_dir, extract_dir_new)
OSError: [Errno 39] Directory not empty: 'GPT_SoVITS/text/G2PWModel_1.1' -> 'GPT_SoVITS/text/G2PWModel'
WuLuXun_RuXian_01.mp3
WuLuXun_RuXian_01.mp3 儒道尚仁而有礼，贤者知命而独悟。 Traceback (most recent call last):
  File "/content/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 86, in process
    phones, word2ph, norm_text = clean_text(
TypeError: clean_text() missing 1 required positional argument: 'version'

WuLuXun_XiongMu_01.mp3
WuLuXun_XiongMu_01.mp3 步步为营者，定无后顾之虞。 Traceback (most recent call last):
  File "/content/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 86, in process
    phones, word2ph, norm_text = clean_text(
TypeError: clean_text() missing 1 required positional argument: 'version'

WuLuXun_ZhangCai_01.mp3
WuLuXun_ZhangCai_01.mp3 今提墨笔绘乾坤，湖海添色山永春。 Traceback (most recent call last):
  File "/content/GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py", line 86, in process
    phones, word2ph, norm_text = clean_text(
TypeError: clean_text() missing 1 required positional argument: 'version'

Traceback (most recent call last):
  File "/content/GPT-SoVITS/webui.py", line 613, in open1abc
    with open(txt_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/wuluxun/2-name2text-0.txt'

**Comment by HsiangLeekwok** [comment]
> TypeError: clean_text() missing 1 required positional argument: 'version'

方法调用的地方缺少参数 version

**Comment by XXXXRT666** [comment]
等待下一个commit

**Comment by 1044690543** [comment]
我也这样

**Comment by RVC-Boss** [comment]
修复了，试试看

**Comment by Lkunlong** [comment]
谢谢，今天可以了。

**Comment by AdamPlatin123** [comment]
https://www.123pan.com/s/UHp9-ofL8H.html试试这个里面安装依赖的bat文件，我修复之后好了
