### ISSUE TITLE
api短词无法生成

### ISSUE THREAD

**Issue by selfnat** [RVC-Boss/GPT-SoVITS#1403]
http://[127.0.0.1:9880/?text=Ready?&text_language=en](http://127.0.0.1:9880/?text=Ready?&text_language=en)

这样调用，没有返回声音，请求修复问题

**Comment by KamioRinn** [comment]
启动参数？

**Comment by selfnat** [comment]
./runtime/bin/python api.py -s "SoVITS_weights/xh_e24_s600.pth" -g "GPT_weights/xh-e50.ckpt" -dr "output/denoise_opt/vocal_vocal_xh.wav_main_vocal.wav_10.wav_0001643840_0001768000.wav" -dt "Everyone loves the library"  -dl en -mt wav

**Comment by selfnat** [comment]
> ./runtime/bin/python api.py -s "SoVITS_weights/xh_e24_s600.pth" -g "GPT_weights/xh-e50.ckpt" -dr "output/denoise_opt/vocal_vocal_xh.wav_main_vocal.wav_10.wav_0001643840_0001768000.wav" -dt "Everyone loves the library" -dl en -mt wav

**Comment by KamioRinn** [comment]
我测试了没问题，你按F12看一下返回值？后台那边有报错吗？有无推理进度条

**Comment by selfnat** [comment]
> 我测试了没问题，你按F12看一下返回值？后台那边有报错吗？有无推理进度条

<img width="1415" alt="image" src="https://github.com/user-attachments/assets/8d64add9-10ee-440b-bfdc-e1335a6f8666">
 有推理，但是返回的是一个0时间的音频 

<img width="409" alt="image" src="https://github.com/user-attachments/assets/c7f5e7c8-9e47-49e0-88f7-3e559535a8f0">

**Comment by KamioRinn** [comment]
这个音频可以播放吗，长音频有试过吗

**Comment by selfnat** [comment]
> 这个音频可以播放吗，长音频有试过吗

http://[127.0.0.1:9880/?text=Ready?&text_language=en](http://127.0.0.1:9880/?text=Ready?&text_language=en)
这种不可以，其他的都可以

Ready? + 其他句子，“Ready?” 读不出来
其他句子+Ready? ，“Ready?” 可以读取出
只有“Ready?” 读不出来， 感觉是断句哪里逻辑把内容丢弃了

**Comment by KamioRinn** [comment]
今天会发布新版模型，到时候你更新下模型和代码再测试下

**Comment by selfnat** [comment]
> 今天会发布新版模型，到时候你更新下模型和代码再测试下

<img width="1380" alt="image" src="https://github.com/user-attachments/assets/02743e08-b911-40a7-b3fd-dac0eb5c34c6">
同样的模型在web和api中返回的结果不一样， “Ready?” 在api中无声音，但是在web是正常的，使用的模型是一个参数也是一样的
感觉不是模型问题，在使用新模型训练。


今天更新了新的模型看到config.py 中的一些参数没有升级,

**Comment by selfnat** [comment]
是api.py 做分割的逻辑和web代码有些出入，导致一些独立的单词+符号处理丢失

**Comment by KamioRinn** [comment]
对于这个case，api和webui切割没有区别。

**Comment by KamioRinn** [comment]
初步定位是因为phones太短引发的

**Comment by selfnat** [comment]
但是如果太短应该api和web都会发生一样的问题

**Comment by selfnat** [comment]
实际上web都是正常的

**Comment by selfnat** [comment]
非常感谢[KamioRinn](https://github.com/KamioRinn)，问题已经修复。
