### ISSUE TITLE
今天更新后报错，模型路径报错

### ISSUE THREAD

**Issue by Kw0k** [RVC-Boss/GPT-SoVITS#1406]
![WX20240806-130313@2x](https://github.com/user-attachments/assets/02431cd4-4f67-4f3f-aef6-57870e938fbd)

**Comment by vip68** [comment]
+1
v2模型缺失

**Comment by RVC-Boss** [comment]
你们
python webui.py v1  zh_CN
先 

代码还没合完呢

**Comment by Kw0k** [comment]
> 你们 python webui.py v1 zh_CN 先
> 
> 代码还没合完呢

python webui.py v1 zh_CN也无法启动，需要将webui.py的126到132行注释掉才可以。
![WX20240806-152449@2x](https://github.com/user-attachments/assets/73b71a00-7391-4a84-b009-80bf351b42e5)

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/commit/8869b11eedefa80649770d3917c3556b1e254a66
修了，用这个吧
