### ISSUE TITLE
下模型出错

### ISSUE THREAD

**Issue by dvdcjw** [RVC-Boss/GPT-SoVITS#1409]
```
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Use `repo_type` argument if needed.

OSError: Incorrect path_or_model_id: 'GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

```
python 3.10
\GPT-SoVITS>pip freeze
absl-py==2.1.0
addict==2.4.0
aiofiles==23.2.1
aiohappyeyeballs==2.3.4
aiohttp==3.10.1
aiosignal==1.3.1
aliyun-python-sdk-core==2.15.1
aliyun-python-sdk-kms==2.16.3
altair==5.3.0
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.4.0
async-timeout==4.0.3
attrs==24.1.0
audioread==3.0.1
av==12.3.0
certifi==2022.12.7
cffi==1.16.0
chardet==5.2.0
charset-normalizer==2.1.1
click==8.1.7
cn2an==0.5.22
colorama==0.4.6
coloredlogs==15.0.1
contourpy==1.2.1
crcmod==1.7
cryptography==43.0.0
ctranslate2==4.3.1
cycler==0.12.1
datasets==2.20.0
decorator==5.1.1
dill==0.3.8
Distance==0.1.3
editdistance==0.8.1
einops==0.8.0
eunjeon==0.4.0
exceptiongroup==1.2.2
fastapi==0.112.0
faster-whisper==1.0.3
ffmpeg-python==0.2.0
ffmpy==0.4.0
filelock==3.13.1
flatbuffers==24.3.25
fonttools==4.53.1
frozenlist==1.4.1
fsspec==2024.5.0
funasr==1.0.27
future==1.0.0
g2p-en==2.1.0
g2pk2==0.0.3
gast==0.6.0
gradio==3.38.0
gradio_client==0.8.1
grpcio==1.65.4
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
huggingface-hub==0.24.5
humanfriendly==10.0
hydra-core==1.3.2
idna==3.4
importlib_metadata==8.2.0
inflect==7.3.1
jaconv==0.4.0
jamo==0.4.1
jieba==0.42.1
jieba-fast==0.53
Jinja2==3.1.3
jmespath==0.10.0
joblib==1.4.2
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
kaldiio==2.18.0
kiwisolver==1.4.5
ko-pron==1.3
LangSegment==0.3.3
librosa==0.9.2
lightning-utilities==0.11.6
linkify-it-py==2.0.3
llvmlite==0.39.1
Markdown==3.6
markdown-it-py==2.2.0
MarkupSafe==2.1.5
matplotlib==3.9.0
mdit-py-plugins==0.3.3
mdurl==0.1.2
modelscope==1.10.0
more-itertools==10.3.0
mpmath==1.3.0
multidict==6.0.5
multiprocess==0.70.16
networkx==3.2.1
nltk==3.8.1
numba==0.56.4
numpy==1.23.4
omegaconf==2.3.0
onnxruntime==1.18.1
onnxruntime-gpu==1.18.1
openai-whisper==20231117
OpenCC==1.1.8
orjson==3.10.6
oss2==2.18.6
packaging==24.1
pandas==2.2.2
pillow==10.2.0
platformdirs==4.2.2
pooch==1.8.2
proces==0.1.7
protobuf==4.25.4
psutil==6.0.0
py3langid==0.2.2
pyarrow==17.0.0
pyarrow-hotfix==0.6
pycparser==2.22
pycryptodome==3.20.0
pydantic==2.8.2
pydantic_core==2.20.1
pydub==0.25.1
pyjyutping==1.0.0
pynndescent==0.5.13
pyopenjtalk==0.3.4
pyparsing==3.1.2
pypinyin==0.52.0
pyreadline3==3.4.1
python-dateutil==2.9.0.post0
python-multipart==0.0.9
pytorch-lightning==2.3.3
pytorch-wpe==0.0.1
pytz==2024.1
PyYAML==6.0.1
referencing==0.35.1
regex==2024.7.24
requests==2.32.3
resampy==0.4.3
rotary-embedding-torch==0.6.4
rpds-py==0.19.1
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.13.1
semantic-version==2.10.0
sentencepiece==0.2.0
simplejson==3.19.2
six==1.16.0
sniffio==1.3.1
sortedcontainers==2.4.0
soundfile==0.12.1
starlette==0.37.2
sympy==1.12
tensorboard==2.17.0
tensorboard-data-server==0.7.2
tensorboardX==2.6.2.2
threadpoolctl==3.5.0
tiktoken==0.7.0
tokenizers==0.19.1
tomli==2.0.1
toolz==0.12.1
torch==2.0.0+cu118
torch-complex==0.4.4
torchaudio==2.0.1+cu118
torchmetrics==1.4.1
torchvision==0.15.1+cu118
tqdm==4.66.5
transformers==4.43.4
typeguard==4.3.0
typing_extensions==4.12.2
tzdata==2024.1
uc-micro-py==1.0.3
umap-learn==0.5.6
urllib3==1.26.13
uvicorn==0.30.5
websockets==11.0.3
Werkzeug==3.0.3
wordsegment==1.3.1
xxhash==3.4.1
yapf==0.40.2
yarl==1.9.4
zipp==3.19.2

**Comment by HsiangLeekwok** [comment]
特殊地区用户建议用特殊方式下载

```shell
pip install -U huggingface_hub
export HF_ENDPOINT=https://hf-mirror.com
```

然后再下载 huggingface 中的内容就可以了

**Comment by RVC-Boss** [comment]
你没有提前把模型下载到指定的地方，仔细阅读readme则不会发生该问题。
