### ISSUE TITLE
大佬们，下载整合包多久更新呀0.0

### ISSUE THREAD

**Issue by DeepAichemist** [RVC-Boss/GPT-SoVITS#1418]

**Comment by RVC-Boss** [comment]
[huggingface](https://huggingface.co/lj1995/GPT-SoVITS-windows-package/resolve/main/GPT-SoVITS-v2-240807.7z)

**Comment by DeepAichemist** [comment]
谢谢大佬
![1723018170103(1)](https://github.com/user-attachments/assets/e5d63b83-a12d-4847-b930-e0385a4801ab)
