### ISSUE TITLE
whisper转funasr存在bug

### ISSUE THREAD

**Issue by yuys0602** [RVC-Boss/GPT-SoVITS#1419]
看代码`tools/asr/fasterwhisper_asr.py`中，存在逻辑
```python
            if info.language == "zh":
                print("检测为中文文本, 转 FunASR 处理")
                if("only_asr"not in globals()):
                    from tools.asr.funasr_asr import \
                        only_asr  # #如果用英文就不需要导入下载模型
                text = only_asr(file_path)
```

但实际使用时，报错，在`funasr_asr.py", line 14, in only_asr`中，`text = model.generate(input=input_file)[0]["text"]`报错为`NameError: name 'model' is not defined`

**Comment by SapphireLab** [comment]
最近修改的代码挪动了 model，已经反馈了，稍等一下修复。

**Comment by yuys0602** [comment]
修改后还是有bug，此时应该是调用`cmd.language=="zh"`的，结果调用了else的东西了
