### ISSUE TITLE
V2版本怎么是cpu训练啊？

### ISSUE THREAD

**Issue by jiekemt** [RVC-Boss/GPT-SoVITS#1425]
![image](https://github.com/user-attachments/assets/7053c7a4-e4e8-4b7d-8258-0093ad13a0ca)
![image](https://github.com/user-attachments/assets/9efceda0-44a1-4b46-9b4e-ea6451de0753)

**Comment by jiekemt** [comment]
貌似是没识别出这张显卡，4060ti 16g

**Comment by jiekemt** [comment]
![image](https://github.com/user-attachments/assets/7b2472af-1a95-4542-9a8c-85a860621ca3)

**Comment by RVC-Boss** [comment]
试试老版本能识别到吗？7月的整合包

**Comment by jiekemt** [comment]
> 试试老版本能识别到吗？7月的整合包

老版本是可以的

**Comment by RVC-Boss** [comment]
介不介意加个qq我给你远程排查下

**Comment by jiekemt** [comment]
> 介不介意加个qq我给你远程排查下

找到原因了，是torch和cuda不匹配导致的

**Comment by jiekemt** [comment]
> 介不介意加个qq我给你远程排查下

抱歉，麻烦大佬了

**Comment by mythzhang8** [comment]
> > 介不介意加个qq我给你远程排查下
> 
> 找到原因了，是torch和cuda不匹配导致的

什么意思呢？我也是用conda安装requirements.txt运行后无法识别到显卡，但是下载的整合包运行能识别到
