### ISSUE TITLE
关于v2推理速度

### ISSUE THREAD

**Issue by mondorysix** [RVC-Boss/GPT-SoVITS#1428]
<img width="906" alt="image" src="https://github.com/user-attachments/assets/fc855950-e146-4ad1-982d-c22da3f047a3">
看到release note里提到了v2推理速度翻倍，请教下大佬，这部分主要是哪部分导致的翻倍？ 是前端部分吗，G2pw？

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/pull/672
