### ISSUE TITLE
请问如何训练方言

### ISSUE THREAD

**Issue by 1044690543** [RVC-Boss/GPT-SoVITS#1432]
佬，比如我要在底模基础上训练一个上海方言，我需要哪些前置准备呢。
比如

1. 需要多少小时的方言数据才能达到比较好的效果
2. 音素符合需要找一套方言的吗
3. 需要自备新的G2P吗

万分感谢！！！

**Comment by KamioRinn** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/wiki/%E4%BB%8E%E9%9B%B6%E8%AE%AD%E7%BB%83(train-from-scratch)

1. 需要自备对应G2P
2. 音素根据你的G2P进行添加

**Comment by RVC-Boss** [comment]
楼上正解
1、100h+
2、yes
3、yes

**Comment by thekingofcity** [comment]
想问一下您后来有继续下去吗？也想为方言添加做些贡献，方便交流下吗？

**Comment by gzwine** [comment]
同问，有进展吗？
