### ISSUE TITLE
识别不到显卡

### ISSUE THREAD

**Issue by OuYanggggg** [RVC-Boss/GPT-SoVITS#1434]
我的显卡是2070S驱动是560.70 CUDA是12.6.32，可以正常使用训练和推理就是识别不到GPU只能用CPU来进行训练和推理

**Comment by RVC-Boss** [comment]
有可能是cuda太新了不支持老版本pytorch？你自己有手工装过系统cuda驱动吗

**Comment by Qreac** [comment]
你可以查看一下你的驱动版本，顺便查看一下torch版本，确保安装对应的版本的torch，或者直接在控制台查看一下cuda是否可用，如果是false那就重装一下版本的torch
