### ISSUE TITLE
webui微调的保存模型的小问题

### ISSUE THREAD

**Issue by Zi-Gao** [RVC-Boss/GPT-SoVITS#1436]
我使用MacBook Pro上微调模型，SoVITS_weights GPT_weights目录下只有save_every_epoch保存的检查点，训练完成不会有最终模型的保存。希望添加在训练完成后保存一个最终模型的小功能。

**Comment by XXXXRT666** [comment]
logs中保存了，自取

**Comment by RVC-Boss** [comment]
那确实没有，因为需要存那个有啥用，我不太明白
