### ISSUE TITLE
打开webui的时候卡Loading...

### ISSUE THREAD

**Issue by Gardevoir-mega** [RVC-Boss/GPT-SoVITS#1440]
运行webui打开网页只会一直卡Loading，命令行界面没有报错。
![image](https://github.com/user-attachments/assets/9065f2fd-4cef-4958-be15-26533c4eee49)

通过浏览器的开发者工具看，有两个访问“https://fonts.googleapis.com”域名的疑似字体文件在加载，但是我这里访问不到这个地址，一直是挂起状态。
![image](https://github.com/user-attachments/assets/c24ec97d-044a-41a5-976c-f8dd203cf28b)
![image](https://github.com/user-attachments/assets/df9698c4-5cc5-4d38-b27f-27e3eccba1c5)

这要如何处理（除了挂梯子）。能把文件下载下来在本地加载吗？

**Comment by RVC-Boss** [comment]
离谱，看看有没有网友知道怎么解的

**Comment by selfnat** [comment]
dns.google 给这个域名一个梯子

**Comment by Lin-Silver** [comment]
I think this situation is quite common in mainland China, and the main issue is related to the internet. You can try changing the following routing mode to ‘blacklist’. At least for accessing other websites, this is what I do.
Of course, it could also be a font loading issue… You can try downloading the fonts.

**Comment by RVC-Boss** [comment]
原来是前端卡资源下载问题

**Comment by Gardevoir-mega** [comment]
@RVC-Boss 我知道是前端卡资源下载问题，但我想问的是如何让它从本地加载，不要让它再去访问外网了……

**Comment by XXXXRT666** [comment]
因为本地没有才去google fonts加载吧, 去theme里手动设置字体
