### ISSUE TITLE
单词丢失

### ISSUE THREAD

**Issue by selfnat** [RVC-Boss/GPT-SoVITS#1442]
http://127.0.0.1:9880/?text=But Biscuit is still chewing his towel&text_language=en

第一次生成is 没有发音后面几次发音了

Woof发音异常第二次正确 

output_32.wav
output_31.wav

这是其中两次的发音

“Fetch the ball” 重复，但是第二次正常

output_44.wav

“Biscuit”  偶尔不发音

output_64.wav

音频参考附件
[wav.zip](https://github.com/user-attachments/files/16569031/wav.zip)

请帮忙修复这些问题，因为不清楚完整的代码流程，不知道从哪里排查，如果有需要可以配合debug

**Comment by selfnat** [comment]
启动参数

./runtime/bin/python api.py -s "SoVITS_weights_v2/xh2_e24_s600.pth" -g "GPT_weights_v2/xh2-e50.ckpt" -dr "output_xh/denoise_opt/vocal_vocal_xh.wav_main_vocal.wav_10.wav_0001643840_0001768000.wav" -dt "Everyone loves the library"  -dl "en" -mt wav

**Comment by KamioRinn** [comment]
控制dpo参数

**Comment by selfnat** [comment]
> 控制dpo参数


## 执行参数:

`-s` - `SoVITS模型路径, 可在 config.py 中指定`
`-g` - `GPT模型路径, 可在 config.py 中指定`

调用请求缺少参考音频时使用
`-dr` - `默认参考音频路径`
`-dt` - `默认参考音频文本`
`-dl` - `默认参考音频语种, "中文","英文","日文","韩文","粤语,"zh","en","ja","ko","yue"`

`-d` - `推理设备, "cuda","cpu"`
`-a` - `绑定地址, 默认"127.0.0.1"`
`-p` - `绑定端口, 默认9880, 可在 config.py 中指定`
`-fp` - `覆盖 config.py 使用全精度`
`-hp` - `覆盖 config.py 使用半精度`
`-sm` - `流式返回模式, 默认不启用, "close","c", "normal","n", "keepalive","k"`
·-mt` - `返回的音频编码格式, 流式默认ogg, 非流式默认wav, "wav", "ogg", "aac"`
·-cp` - `文本切分符号设定, 默认为空, 以",.，。"字符串的方式传入`

`-hb` - `cnhubert路径`
`-b` - `bert路径`
 dpo 具体是哪个参数啊？

**Comment by KamioRinn** [comment]
推理的时候右侧参数调节

**Comment by selfnat** [comment]
> 推理的时候右侧参数调节

还是存在短padding在api.py中不发音问题，参数api和web调整的一样的，但是web可以发音 api不可以，
demo http://[127.0.0.1:9880/?text=reference&text_language=en](http://127.0.0.1:9880/?text=reference&text_language=en)

**Comment by KamioRinn** [comment]
api top_k默认是20

**Comment by selfnat** [comment]
有传递参数data = {
        "text": text,
        "text_language": "en",
        "top_k": 15,
        "top_p": 1,
        "temperature": 1,
        "speed": 1,
    }。两侧是一样的时候也一样的， api不出结果的次数概率多，web很少

**Comment by KamioRinn** [comment]
生成的结果本来就是随机的，只能通过DPO控制，web和api没有什么差别的

**Comment by selfnat** [comment]
有什么方式控制在一个随机值上吗？就是控制一个单词，每次发音都是一样的

<img width="560" alt="image" src="https://github.com/user-attachments/assets/0bcbf4b1-8079-4631-a82b-04e0edbaeded">
 这个参数是否是控制这个随机的
