### ISSUE TITLE
多次请求，生成结果不一样

### ISSUE THREAD

**Issue by selfnat** [RVC-Boss/GPT-SoVITS#1450]
为什么参数都一样，多次请求结果不一样，有的是发音不一样，有的是返回错误的结果，是有什么隐藏参数可以控制吗

**Comment by selfnat** [comment]
在web端看到有“是否直接对上次合成结果调整语速和音色。防止随机性。” 这个描述， api没有看到相关控制，是这个控制的吗

**Comment by AkagawaTsurunaki** [comment]
模型的生成结果受多种因素影响，貌似从理论上很难保证两次生成的结果完全的一样。因为对一段文字的拼音解释的模型，其拼音结果也具有一定的随机性。

**Comment by selfnat** [comment]
我使用的是英文场景，按理说是标准的英语，我说的发音不同指的是错误读音一个单词读另一个单词的发音

**Comment by selfnat** [comment]
是否可以理解为底层标注的数据有可能出错，或者关联的时候出错了

**Comment by Polaris231** [comment]
VITS架构的生成过程是有几个randn操作的，可以看看models.py文件

**Comment by XXXXRT666** [comment]
GPT

**Comment by XXXXRT666** [comment]
指望VITS的随机性还不如去看看GPT的采样参数
