### ISSUE TITLE
测试v2版本对比v1推理速度差距

### ISSUE THREAD

**Issue by limujun** [RVC-Boss/GPT-SoVITS#1451]
# 描述
    跑了api.py在同一台3090机器上推理，参考音频一样，环境一样。只修改了config.py文件里面的pretrained_sovits_path和pretrained_gpt_path分别为v1和v2版本的模型，测试结果，通过get请求返回的音频时间几乎一样。
# 测试文本
    先帝创业未半而中道崩殂，今天下三分，益州疲弊，此诚危急存亡之秋也。
# 测试结果
    v1版本：2.7s-3.4s
    v2版本：2.7s-3.2s
#  询问
   文档描述v2版本比v1版本推理速度上有翻倍的提升，请问api.py是否是否哪里还需要修改代码？

**Comment by limujun** [comment]
# 描述
    跑了api.py在同一台3090机器上推理，参考音频一样，环境一样。只修改了config.py文件里面的pretrained_sovits_path和pretrained_gpt_path分别为v1和v2版本的模型，测试结果，通过get请求返回的音频时间几乎一样。
# 测试文本
    先帝创业未半而中道崩殂，今天下三分，益州疲弊，此诚危急存亡之秋也。
# 测试结果
    v1版本：2.7s-3.2s
    v2版本：2.7-3.4s
#  询问
   文档描述v2版本比v1版本推理速度上有翻倍的提升，请问api.py是否是否哪里还需要修改代码？

**Comment by limujun** [comment]
# 测试选用的基准模型
pretrained_sovits_path = "GPT_SoVITS/pretrained_models/s2G488k.pth"
pretrained_gpt_path = "GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt"

**Comment by SapphireLab** [comment]
文档说的 v1 标注了一月份，是那个时候的推理代码，而不是指 v1 v2 模型在现有代码下的推理速度差距。

**Comment by RVC-Boss** [comment]
楼上正解
