### ISSUE TITLE
handle error when word isn't found in cmu dict

### ISSUE THREAD

**Issue by cwjacklin** [RVC-Boss/GPT-SoVITS#1457]
File "/home/jack/ai/GPT-SoVITS/GPT_SoVITS/text/english.py", line 343, in qryword
    phones.extend(self.cmu[w][0])
KeyError: '-'

because 
>>> LangSegment.getTexts("SAINT-DENISE, France.")
[{'lang': 'en', 'text': 'S A I N T-D E N I S E, France. ', 'score': 1.0}]

and "t-d" isn't found.

**Comment by XXXXRT666** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/pull/1454
