### ISSUE TITLE
使用api.py接口，调用后，返回的是引用的声频（ref_wav）文件的内容，不是text文本的内容。

### ISSUE THREAD

**Issue by wxzz** [RVC-Boss/GPT-SoVITS#1458]
我启动api.py接口后，使用接口调用：http://127.0.0.1:9880/?refer_wav_path=123.wav&prompt_text=%E5%A4%A7%E4%BD%A0%E5%A5%BD&prompt_language=zh&text=%E4%BD%A0%E5%A5%BD%E3%80%82&text_language=zh&cut_punc=,

![image](https://github.com/user-attachments/assets/6d134ba5-60ff-4679-88fe-f8c6a3aaec25)

**但是返回的音频文件始终是：refer_wav_path=123.wav 的内容。而不是text=音频内容，是接口返回的问题？**

当我使用webui，生成自己内容的音频是正常的。如下图：
![image](https://github.com/user-attachments/assets/76a143a9-9be9-4054-8d9a-e4ff89502375)

**Comment by SapphireLab** [comment]
我有一个问题是你使用 api 的时候就是用的第一行的链接吗？
像文本部分 `text=%E4%BD%A0%E5%A5%BD%E3%80%82` 就是这么输入的吗？
如果是这样输入的话，中文模式下会因为输入内容不是中文而被过滤掉，导致没有可解码的内容。
（这一点可复现，若不是，则需进一步反馈。）

**Comment by wxzz** [comment]
> 我有一个问题是你使用 api 的时候就是用的第一行的链接吗？ 像文本部分 `text=%E4%BD%A0%E5%A5%BD%E3%80%82` 就是这么输入的吗？ 如果是这样输入的话，中文模式下会因为输入内容不是中文而被过滤掉，导致没有可解码的内容。 （这一点可复现，若不是，则需进一步反馈。）

@SapphireLab 输入的确实是中文，refer_wav_path=123.wav这个也是中文语音。不太清楚为什么出现这个情况。有办法解决吗？

**Comment by wxzz** [comment]
解决的过程，我把训练好的模型，在启动接口的时候就加载上。如下：
python api.py -s SoVITS_weights_v2\myself_sound_20240812_e8_s104.pth -g GPT_weights_v2\myself_sound_20240812-e15.ckpt

另外，调用api接口的时候，如下：
http://127.0.0.1:9880?refer_wav_path=zh.wav&prompt_text=太祖是怎么评价秦朝宰相李斯的&prompt_language=zh&text=先帝创业未半而中道崩殂，今天下三分，益州疲弊，此诚危急存亡之秋也&text_language=zh

注意，prompt_text和text的文本，在&符号前不能有标点符号
