### ISSUE TITLE
onnx_export模型导入错误

### ISSUE THREAD

**Issue by Polaris231** [RVC-Boss/GPT-SoVITS#1461]
好奇怪，v2版本finetune模型，转onnx时，运行onnx_export.py发现vq_model加载checkpoints出现形状不匹配问题，但inference_webui.py里没问题，是哪儿参数需要更改嘛
 File "/mnt/GPT-SoVITS/GPT_SoVITS/onnx_export.py", line 208, in __init__
    self.vq_model.load_state_dict(dict_s2["weight"], strict=False)
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for ref_enc.spectral.0.fc.weight: copying a param with shape torch.Size([128, 704]) from checkpoint, the shape in current model is torch.Size([128, 1025]).

**Comment by XXXXRT666** [comment]
没更新,根据V2模型load逻辑自己把shape改一下

**Comment by XXXXRT666** [comment]
或者传入version

**Comment by Polaris231** [comment]
两个加载的文件不同，一个是models.py，一个是models_onnx.py，models_onnx.py还没改
