### ISSUE TITLE
文本获取时报错

### ISSUE THREAD

**Issue by acolasialiuliu** [RVC-Boss/GPT-SoVITS#1464]
pyopenjtalk.mecab_dict_index(USERDIC_CSV_PATH, USERDIC_BIN_PATH)
AttributeError: module 'pyopenjtalk' has no attribute 'mecab_dict_index'

从v1更新到v2

**Comment by RVC-Boss** [comment]
pyopenjtalk要更新到0.3.4才有该功能，我给req.txt更新了

**Comment by acolasialiuliu** [comment]
> pyopenjtalk要更新到0.3.4才有该功能，我给req.txt更新了

req没规定版本，默认会拉取最新吧，我后来下了整合包看也是用的.3版本
