### ISSUE TITLE
Mac克隆语音后没有地方下载

### ISSUE THREAD

**Issue by FallenAngels520** [RVC-Boss/GPT-SoVITS#1465]
![WechatIMG106](https://github.com/user-attachments/assets/b5399f7e-a85e-4d78-bd2b-d995f8b563db)
![WechatIMG107](https://github.com/user-attachments/assets/800cec00-cb92-4cc5-b213-973530b1296f)
请问下，下载按钮在哪？

**Comment by XXXXRT666** [comment]
右键

**Comment by RVC-Boss** [comment]
楼上正解
