### ISSUE TITLE
 音频变换的疑问

### ISSUE THREAD

**Issue by NiHaoUCAS** [RVC-Boss/GPT-SoVITS#1467]
在提取音频semantic code中，对音频做了如下的变换：
tmp_audio32b = (tmp_audio / tmp_max * (maxx * alpha*1145.14)) + ((1 - alpha)*1145.14) * tmp_audio
请问这么做的目的是什么？ 有两个疑问：
1. 为什么有一部分做最大值归一化而另一部分不做？
2. 这么做了之后音频最大值只能是1145.14，远小于32768，会不会影响hubert提特征？
3. tmp_audio的采样率是32kHz，而最终又要变回16kHz，为什么不直接用16k？
原始代码：https://github.com/RVC-Boss/GPT-SoVITS/blob/13e0faab72594298ada2e7353d740992f670fda5/GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py#L76

**Comment by RVC-Boss** [comment]
1、和原始混合保留多少alpha比例的动态
2、音量不影响hubert特征，只要不fp32数值爆炸即可
3、不要在意这些细节，没意义

**Comment by xiezheng-cs** [comment]
> 在提取音频semantic code中，对音频做了如下的变换： tmp_audio32b = (tmp_audio / tmp_max * (maxx * alpha*1145.14)) + ((1 - alpha)*1145.14) * tmp_audio 请问这么做的目的是什么？ 有两个疑问：
> 
> 1. 为什么有一部分做最大值归一化而另一部分不做？
> 2. 这么做了之后音频最大值只能是1145.14，远小于32768，会不会影响hubert提特征？
> 3. tmp_audio的采样率是32kHz，而最终又要变回16kHz，为什么不直接用16k？
>    原始代码：https://github.com/RVC-Boss/GPT-SoVITS/blob/13e0faab72594298ada2e7353d740992f670fda5/GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py#L76

+1，没明白

**Comment by wzy3650** [comment]
问题3：因为vits部分需要32k采样率的音频
