### ISSUE TITLE
如何再次微调一个自己微调过的模型？

### ISSUE THREAD

**Issue by NadekoShiro** [RVC-Boss/GPT-SoVITS#1468]
如题，我已经微调好了一个模型，过了一段时间想再加入新的声音，如果是这样的话如何设定微调模型的路径？我尝试过保留相同实验名，但是没看到训练读条，进程就直接结束了。

**Comment by chow-q** [comment]
加入了新的声音要全部重新训练，或者你加我地球号showtim2007，免费训练

**Comment by RVC-Boss** [comment]
> 如题，我已经微调好了一个模型，过了一段时间想再加入新的声音，如果是这样的话如何设定微调模型的路径？我尝试过保留相同实验名，但是没看到训练读条，进程就直接结束了。

拉更高训练epoch

**Comment by Bobchenyx** [comment]
> > 如题，我已经微调好了一个模型，过了一段时间想再加入新的声音，如果是这样的话如何设定微调模型的路径？我尝试过保留相同实验名，但是没看到训练读条，进程就直接结束了。
> 
> 拉更高训练epoch

您好我想问一下, 如果没保存log, 只留了GPT和SoVITS文件夹下面的weight/checkpoint, 有办法在此之上进行微调么?
