### ISSUE TITLE
为什么要限制训练轮数啊？

### ISSUE THREAD

**Issue by martjay** [RVC-Boss/GPT-SoVITS#147]
之前不是200轮训练限制吗？而且之前webui那个创建目录的页面也不见了，本来那个就挺方便，把数据放一个文件夹里。还有就是训练的时候不显示当前正在训练的轮数了，不方便。

![111](https://github.com/RVC-Boss/GPT-SoVITS/assets/44982189/7b57460e-9d90-4bfc-8bc7-8ef8a032cdfd)

**Comment by quicksandznzn** [comment]
自己改下代码就可以了

**Comment by RVC-Boss** [comment]
限制轮数确保大众体验，防止有人乱拉高降低效果。
格式问题：已回滚。
