### ISSUE TITLE
发现一个比较奇怪的问题，推理有时候得到的音频时长很长，说话间隔很大

### ISSUE THREAD

**Issue by Hwangkop** [RVC-Boss/GPT-SoVITS#1474]
使用最新代码和以前的模型推理
我这边的同一个模型输入 “亲爱的！起床啦” ，“当然会啦！宝宝~”  ，“真的吗！太酷啦”
都会得到20多秒的音频，然后说话间隔很长
[g_audio_1723686868092-0.zip](https://github.com/user-attachments/files/16620540/g_audio_1723686868092-0.zip)
当使用逗号而不是感叹号的时候，输出是正常的
使用新代码推理以前的模型我这边是容易出现说话间隔比较长的现象

**Comment by g39088902** [comment]
遇到相同问题，“啊哦嗯额呃”这些语气词单字接特殊符号时特别容易出现，感觉是底模问题，要加个防重复。麻烦 @Hwangkop 把issue重新打开一下，让作者能看到。

**Comment by Hwangkop** [comment]
> 遇到相同问题，“啊哦嗯额呃”这些语气词单字接特殊符号时特别容易出现，感觉是底模问题，要加个防重复。麻烦 @Hwangkop 把issue重新打开一下，让作者能看到。

我这边更改了 top_k=5, top_p=1, temperature=1 就正常了
