### ISSUE TITLE
`fast_interference_` branch does not support GPT-Sovits v2 models. (fast_interference_` 分支不支持 GPT-Sovits v2 模型。)

### ISSUE THREAD

**Issue by WhaleFell** [RVC-Boss/GPT-SoVITS#1483]
as shown, when I send the request as before:

![image](https://github.com/user-attachments/assets/65cc41a8-9d6a-4c4f-b66c-8e7258ac0f49)

**Comment by ChasonJiang** [comment]
等main分支稳定了，就支持

**Comment by ChasonJiang** [comment]
fast_interference_分支现已合并入main分支，且支持了v2模型

**Comment by RVC-Boss** [comment]
楼上正解，已经合入main了
