### ISSUE TITLE
inference_cli.py运行出错，1.参考库路径错误，2调用inference_webui.py参数错误

### ISSUE THREAD

**Issue by harry-git-hub** [RVC-Boss/GPT-SoVITS#1492]
**1.参考库路径错误：**

https://github.com/RVC-Boss/GPT-SoVITS/blob/b3e8eb40c25bea1b9977195a380d40c941040419/GPT_SoVITS/inference_cli.py#L5

此时tools是在inference_cli.py的上一层目录，因此会提示找不到tools库：

**2.调用inference_webui.py参数错误：**

https://github.com/RVC-Boss/GPT-SoVITS/blob/b3e8eb40c25bea1b9977195a380d40c941040419/GPT_SoVITS/inference_cli.py#L24-L28
此处调用了inference_webui.py，但未填写inp_refs参数，因此inp_refs为默认的123，
https://github.com/RVC-Boss/GPT-SoVITS/blob/b3e8eb40c25bea1b9977195a380d40c941040419/GPT_SoVITS/inference_webui.py#L395
导致如下行出现TypeError: 'int' object is not iterable
https://github.com/RVC-Boss/GPT-SoVITS/blob/b3e8eb40c25bea1b9977195a380d40c941040419/GPT_SoVITS/inference_webui.py#L508

**Comment by atfa** [comment]
同样遇到 TypeError: 'int' object is not iterable 这个错误，期待解决。

**Comment by RVC-Boss** [comment]
1、因为是当做你在根目录下跑的python GPT_SoVITS/inference.py
2、不用多参考音频的话，你要手工传None

**Comment by harry-git-hub** [comment]
> 1、因为是当做你在根目录下跑的python GPT_SoVITS/inference.py 2、不用多参考音频的话，你要手工传None

感谢解答，已解决。
参考inference_cli.py，在根目录下手动写了python脚本，调用inference_webui.py并传入None，运行顺利。
真是令人惊叹的工作！
