### ISSUE TITLE
No runtime file

### ISSUE THREAD

**Issue by WinterStraw** [RVC-Boss/GPT-SoVITS#15]
Thanks for your open-source sharing. It is a greatness project!
However, It might not be the correct version because some critical files are missing.

**Comment by RVC-Boss** [comment]
what files are missing?

**Comment by hatrd** [comment]
This project route all python to "runtime\python". But sometimes we use python in the env directly. Is there a solution?

**Comment by WinterStraw** [comment]
> This project route all python to "runtime\python". But sometimes we use python in the env directly. Is there a solution?此项目将所有 python 路由到“runtime\python”。但有时我们直接在 env 中使用 python。有解决办法吗？

Yes, if we change the code in the .bat file, it will work. But I'm not sure if this is because the project uploaded the wrong version or if it was done intentionally.

**Comment by WinterStraw** [comment]
> what files are missing?缺少哪些文件？

I just noticed that the.bat code refers to the runtime folder. Although it is possible to modify the code to avoid this path error problem, I am unsure if this is a problem with the uploaded version or other causes.

**Comment by hatrd** [comment]
I have run `python go-webui.bat` directly. Webui started. But when I slice audios, 
```
"runtime\python" tools/slice_audio.py "D:\Videos\data\gpt" "output/slicer_opt" -34 4000 300 10 500 0.9 0.25 3 4
系统找不到指定的路径。
系统找不到指定的路径。
```
So "runtime\python" is hard coded into this project. It's not okay to just modify the go-webui.bat

**Comment by WinterStraw** [comment]
> I have run `python webui.py` directly. Webui started. But when I slice audios,
> 
> ```
> "runtime\python" tools/slice_audio.py "D:\Videos\data\gpt" "output/slicer_opt" -34 4000 300 10 500 0.9 0.25 3 4
> 系统找不到指定的路径。
> 系统找不到指定的路径。
> ```
> 
> So "runtime\python" is hard coded into this project. It's not okay to just modify the go-webui.bat

same problem.

**Comment by hatrd** [comment]
A workaround in the `config.py`. 
```
python_exec="runtime\python"if platform.system()=="Windows"else "python"
```
Python_exec path for windows is set to runtime.

**Comment by RVC-Boss** [comment]
Fixed now.
