### ISSUE TITLE
本地有一张p40，无法被webui识别到

### ISSUE THREAD

**Issue by ibukikawayi** [RVC-Boss/GPT-SoVITS#150]
![e8d0325f49c5ca469ee94d2fb065b516](https://github.com/RVC-Boss/GPT-SoVITS/assets/71491168/5dd17dd2-18e7-4859-ac9e-95f2c2526e40)
![{EBBE00F1-4093-4e82-B92B-596CD83603FF}](https://github.com/RVC-Boss/GPT-SoVITS/assets/71491168/c4bcfacc-9f73-42f7-b0d2-e2a2e213abee)

**Comment by RVC-Boss** [comment]
如果你是pip安装而非整合包，可能是因为pytorch装了CPU版本。
