### ISSUE TITLE
fast inference推理效果变差，疑似mask策略不佳

### ISSUE THREAD

**Issue by AnonymousmousCoder** [RVC-Boss/GPT-SoVITS#1501]
fast_inference我拉了最新的commit之后，感觉效果比之前差了，更不稳定了

**Comment by ChasonJiang** [comment]
变慢倒是有可能，但是变差按理说应该不会，你能提供一下详细的对比吗？顺便，同seed是没有可比性的，只能根据大量采样算一下质量差的音频出现的频率
