### ISSUE TITLE
[BUG] 文本是 "虐一虐" 就會報錯

### ISSUE THREAD

**Issue by 911218sky** [RVC-Boss/GPT-SoVITS#1502]
## 報錯代碼
![報錯代碼](https://github.com/user-attachments/assets/bece2af2-4d5a-4eda-a7c6-5768f8e4c120)

## 報錯內容
![報錯內容](https://github.com/user-attachments/assets/85d145c2-88d9-4fb6-9248-7ad603444bc1)

## WebUI 執行內容
![WebUI 執行內容](https://github.com/user-attachments/assets/f0f3606b-954e-41ba-a75b-e687b118cea8)

**Comment by g39088902** [comment]
请问代码是最新版吗？还是整合包？

**Comment by g39088902** [comment]
看路径好像不是当前的最新版
