### ISSUE TITLE
数字加英文状态下拆分会停顿 as：3D这个单词会被拆分为3，D

### ISSUE THREAD

**Issue by FG488V8** [RVC-Boss/GPT-SoVITS#1505]
数字加英文状态拆分停顿明显，列如我想看3D电影这句话，它会拆分为‘’我想看三‘’    ‘’D电影‘’
会默认的将‘我想看三’识别为zh   ‘D’识别为en

**Comment by KamioRinn** [comment]
单个英文字发音太短，去掉停顿容易被吞掉。

**Comment by FG488V8** [comment]
我想让3D人脸识别这句话练起来读有什么办法么

**Comment by g39088902** [comment]
字母改成汉字或者音素，例如“三低电影”

**Comment by FG488V8** [comment]
> 字母改成汉字或者音素，例如“三低电影”

您好，可以问问你如何修改音素么？

**Comment by RVC-Boss** [comment]
2楼正解
