### ISSUE TITLE
🎉很多人要的【SSML 标签】 已初步支持！

### ISSUE THREAD

**Issue by juntaosun** [RVC-Boss/GPT-SoVITS#1508]
Deprecated, please pull git .

**Comment by haohao667788** [comment]
inference_webui里好像不行？

**Comment by RVC-Boss** [comment]
> inference_webui里好像不行？

要升级langsegment库

**Comment by haohao667788** [comment]
升级了，看了下源码，这里language in {"zh", "ja", "ko", "yue", "auto", "auto_yue"} 才生效

**Comment by Alex-Li2018** [comment]
这种023-63940410 怎么处理，加了还是不对

**Comment by flymorn** [comment]
请问 支持 拼音的多音字标注么

**Comment by flymorn** [comment]
看了下您的关于拼音多音字的说明：

`# 汉字拼音指定示例：以下句子，括号中的拼音，均识别为中文。
text = "这个字的读音是角(jue2)色，而不是角(jiao3)色"  `

这个写法不是规范的SSML，建议适配标准的SSML写法：
比如  
`<tone as="jiao3">角</tone>色`

**Comment by viryaka** [comment]
> 🎉很多人要的【SSML 标签】 已初步支持！简单使用示例如下：
> 
> ```python
> # 支持中文数字/货币/日期/时间。随意切换！  
> text = "最大数字：<number>65535</number>" 
> # 最大数字：六五五三五
> 
> text = "你的收入：<currency>120000美元</currency>" 
> # 你的收入：十二万美元
> 
> text = "电话号码：<telephone>+8613800138000</telephone>" 
> # 电话号码：幺三八零零幺三八零零零
> 
> text = "版本号码：<number>0.3.5</number>" 
> # 版本号码：零点三点五
> 
> text = "<date>每天20:30</date>记得按时吃饭哦！" 
> # 每天二十点三十分记得按时吃饭哦！
> 
> text = "入库日期：<date>2024/08/06</date>" 
> # 入库日期：二零二四年八月六日
> ```
> 
> 初次安装：（使用 pip 或 pip3）
> 
> ```
> pip install LangSegment>=0.3.5 -i https://pypi.org/simple
> ```
> 
> 或者，直接使用以下命令在线升级：
> 
> ```
> pip install LangSegment -i  https://pypi.org/simple --upgrade
> ```

我在inference_webui里，用中英混合，生成是正确的；用中文生成就不对；langsegment库已经升级最新的了
例如：<date>每天20:30</date>记得按时吃饭哦！
中英混合： 前端处理后的文本(每句): ['每天二十点三十分记得按时吃饭哦!']
中文：前端处理后的文本(每句): ['D A T E 每天二十点半每D A T E 记得按时吃饭哦!']

**Comment by viryaka** [comment]
> > 🎉很多人要的【SSML 标签】 已初步支持！简单使用示例如下：
> > ```python
> > # 支持中文数字/货币/日期/时间。随意切换！  
> > text = "最大数字：<number>65535</number>" 
> > # 最大数字：六五五三五
> > 
> > text = "你的收入：<currency>120000美元</currency>" 
> > # 你的收入：十二万美元
> > 
> > text = "电话号码：<telephone>+8613800138000</telephone>" 
> > # 电话号码：幺三八零零幺三八零零零
> > 
> > text = "版本号码：<number>0.3.5</number>" 
> > # 版本号码：零点三点五
> > 
> > text = "<date>每天20:30</date>记得按时吃饭哦！" 
> > # 每天二十点三十分记得按时吃饭哦！
> > 
> > text = "入库日期：<date>2024/08/06</date>" 
> > # 入库日期：二零二四年八月六日
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 初次安装：（使用 pip 或 pip3）
> > ```
> > pip install LangSegment>=0.3.5 -i https://pypi.org/simple
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 或者，直接使用以下命令在线升级：
> > ```
> > pip install LangSegment -i  https://pypi.org/simple --upgrade
> > ```
> 
> 我在inference_webui里，用中英混合，生成是正确的；用中文生成就不对；langsegment库已经升级最新的了 例如：<date>每天20:30</date>记得按时吃饭哦！ 中英混合： 前端处理后的文本(每句): ['每天二十点三十分记得按时吃饭哦!'] 中文：前端处理后的文本(每句): ['D A T E 每天二十点半每D A T E 记得按时吃饭哦!']

看了下代码，原来zh是指中英文混合，中文是all_zh，所以all_zh下就是不生效的

**Comment by femis** [comment]
m

**Comment by yb9241** [comment]
不行，下了0821整合包，还是把<number>65535</number> 逐字符给我念出来了。。麻了

**Comment by XXXXRT666** [comment]
整合包不支持

**Comment by WinSure** [comment]
升级了LangSegment库， 且也已经按照上面其他同学的问题改成了中英文混合，但是还是把标签里的内容给我读出来了，
