### ISSUE TITLE
UnboundLocalError: local variable 'i' referenced before assignment

### ISSUE THREAD

**Issue by menghan465** [RVC-Boss/GPT-SoVITS#1510]
在进行一键三连的时候报的错
<img width="1157" alt="1724176078309" src="https://github.com/user-attachments/assets/1d52131a-67d6-4371-b890-ddc8bb166f6c">
<img width="719" alt="1724176059153" src="https://github.com/user-attachments/assets/1f5f0faa-d358-46e0-9b7f-6cfe9e85087c">
该怎么解决

**Comment by SapphireLab** [comment]
第一个图只看到了 Error 没有终端信息。
第二个图是训练时没有检测到第一个图中一键三连准备的数据集。
建议检查数据。

注：这部分代码已经完全修改了，可以更新一下代码。
