### ISSUE TITLE
瑟读音错误，(se4)会读成(sai4)

### ISSUE THREAD

**Issue by Cxywzx** [RVC-Boss/GPT-SoVITS#1512]
基于v2(gsv-v2final-pretrained)的模型，瑟读音错误，(se4)会读成(sai4)。v1模型则没这个问题。

文本：“泽连斯基在与乌武装部队总司令瑟尔斯基视频通话后，在社交平台上发文称，尽管战斗艰难而激烈，但乌军仍在库尔斯克地区继续推进，乌方的“谈判筹码”正在增加。瑟尔斯基向泽连斯基通报说，截至12日，乌军已控制俄罗斯约1000平方公里领土。”

https://github.com/user-attachments/assets/e1c45dd8-f729-450a-825d-49f81e07094f

https://github.com/user-attachments/assets/6fde69b9-7b98-460e-9ccf-c2088927bd90

**Comment by RVC-Boss** [comment]
试试多推几次抽一个
口音
