### ISSUE TITLE
opencc包要求高版本的GLIBC_2.29，但是这个不好安装，有没有其它的代替方法

### ISSUE THREAD

**Issue by CreepJoye** [RVC-Boss/GPT-SoVITS#1513]
OSError: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29' not found (required by /.../.conda/envs/GPTSoVits/lib/python3.9/site-packages/opencc/clib/lib/libopencc.so.1.1)
在一键三连的时候遇到了这个报错，请问可以怎么解决呢，网上搜索GLIBC_2.29不好安装容易导致系统崩溃就没有尝试更新

**Comment by KamioRinn** [comment]
安装低版本OPENCC可用

**Comment by CreepJoye** [comment]
> 安装低版本OPENCC可用
谢谢大佬，刚才去下载了一个1.10版本的安装包然后可以使用了。但是在下一个步骤“开启SSL提取”中，报错如下
`OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory GPT_SoVITS/pretrained_models/chinese-hubert-base.`
我参照https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e/pgah3gvetrdy8ryt这个教程文档把对应的模型文件下载到GPT_SoVITS/pretrained_models/chinese-hubert-base这个文件夹了，如下图
![image](https://github.com/user-attachments/assets/db18d965-3e16-4c83-8e65-8a3862f0b393)
下载的文件和hugging face文件夹中的一样而且也只有这三个文件，并没有`model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack`，请问这个怎么解决呢

**Comment by KamioRinn** [comment]
在运行一次，还有这个报错吗？

**Comment by CreepJoye** [comment]
> 在运行一次，还有这个报错吗？
重新运行了一次。还是在“开启SSL提取”中报错
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory GPT_SoVITS/pretrained_models/chinese-hubert-base.

**Comment by KamioRinn** [comment]
GPT_SoVITS文件夹不是放有webui.py的那个哦，会不会放错位置了

**Comment by CreepJoye** [comment]
> GPT_SoVITS文件夹不是放有webui.py的那个哦，会不会放错位置了
犯了一个低级错误，对不起！
我直接下载的那几个文件，然后需要重命名，在重命名GPT_SoVITS/pretrained_models/chinese-hubert-base/pytorch_model.bin文件的时候，原来的多了一个空格变成了pytorch_model .bin，所以报错了。
感谢大佬的帮助，实在抱歉！

**Comment by haohao667788** [comment]
同样的错，opencc==1.1.0有效

**Comment by daocodedao** [comment]
看opencc介绍，升级到  1.1.1.post1 也行，专门修复了这个问题
