### ISSUE TITLE
日语推理提取文本bert特征时卡住

### ISSUE THREAD

**Issue by kli017** [RVC-Boss/GPT-SoVITS#1514]
利用微调的模型进行推理（api_v2），文本中混有英文时在提取bert特征时卡住，参数如下：
{
    "text": "こんにちは！お元気ですか？(Konnichiwa!Ogenki desu ka?)",
    "text_lang": "ja",
    "ref_audio_path": "prompt_wav/jp1.wav",
    "aux_ref_audio_paths": ["prompt_wav/jp2.wav"],
    "prompt_text": "あんまり知らなかったから今まで結構こう何だろう有名どころというかさ沖縄北海道とか。",
    "prompt_lang": "ja",
    "text_split_method": "cut3"
}

**Comment by ChasonJiang** [comment]
我没能复现，能提供详细的日志吗？

**Comment by kli017** [comment]
已解决，网络不好nltk没下下来
