### ISSUE TITLE
请问继续预训练或者微调的数据可以不带说话人信息吗

### ISSUE THREAD

**Issue by asf2013** [RVC-Boss/GPT-SoVITS#1515]
您好，请问继续预训练或者微调的数据可以不带说话人信息吗？

**Comment by asf2013** [comment]
就比如100条数据，有100个说话人这样

**Comment by thom802311** [comment]
不clone同一个说话人的声音，用底膜就行，不用训练和微调的。

**Comment by asf2013** [comment]
感谢回答，我想的是拿几千小时数据，继续预训练或者微调来改善一下短句生成的问题。

**Comment by RVC-Boss** [comment]
支持多说话人微调不带说话人信息
