### ISSUE TITLE
infer_panel_batch_infer爆显存问题

### ISSUE THREAD

**Issue by thom802311** [RVC-Boss/GPT-SoVITS#1516]
`Traceback (most recent call last):
  File "/root/GPT-SoVITS/ttt.py", line 272, in <module>
    pred_semantic_list, idx_list = t2s_model.model.infer_panel_batch_infer(
  File "/root/GPT-SoVITS/GPT_SoVITS/AR/models/t2s_model.py", line 681, in infer_panel_batch_infer
    xy_dec, k_cache, v_cache = self.t2s_transformer.decode_next_token(xy_pos, k_cache, v_cache,
  File "/root/GPT-SoVITS/GPT_SoVITS/AR/models/t2s_model.py", line 259, in decode_next_token
    x, k_cache[i], v_cache[i] = self.blocks[i].decode_next_token(x, k_cache[i], v_cache[i], attn_mask,
  File "/root/GPT-SoVITS/GPT_SoVITS/AR/models/t2s_model.py", line 215, in decode_next_token
    attn = F.linear(attn, self.out_w, self.out_b)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB. GPU 0 has a total capacity of 23.68 GiB of which 2.69 MiB is free. Process 951046 has 23.68 GiB memory in use. Of the allocated memory 22.52 GiB is allocated by PyTorch, and 609.17 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)`

有什么好的思路来解决这个问题吗？

**Comment by XXXXRT666** [comment]
用A100

**Comment by RVC-Boss** [comment]
降低推理batch size？增大切分频率使每句生成文本量降低？用更大显存的显卡？
因为不知道你写的啥所以
