### ISSUE TITLE
新版本Windows Package "GPT-SoVITS-v2-240821.7z"微调时出现错误

### ISSUE THREAD

**Issue by XiaoQiu2451** [RVC-Boss/GPT-SoVITS#1526]
问题文件:
https://huggingface.co/lj1995/GPT-SoVITS-windows-package/commit/a97d2d22fe6ea0b913117b06875037589dc27eec
[GPT-SoVITS-v2-240821.7z](https://huggingface.co/lj1995/GPT-SoVITS-windows-package/commit/a97d2d22fe6ea0b913117b06875037589dc27eec#d2h-933396)
环境:
OS:Windows 11 with CUDA 12.1
Runtime: 3.9（Package自带）

问题日志：
![QQ20240822-211412](https://github.com/user-attachments/assets/9f252bfc-36f3-4207-8279-f28bf96b1dc0)

推测原因：
runtime安装的pyopenjtalk版本为0.3.3，但是pyopenjtalk.mecab_dict_index只有在0.3.4才有

**Comment by XXXXRT666** [comment]
自己更新一下，这个是整合包问题

**Comment by RVC-Boss** [comment]
已经上传了新的整合包了，可以重新下载
或者已经下过错误包的可以用
https://github.com/RVC-Boss/GPT-SoVITS/issues/1518
里面的办法
