### ISSUE TITLE
inference_webui.py推理，样本音频是否可以突破10s的限制

### ISSUE THREAD

**Issue by steeveen** [RVC-Boss/GPT-SoVITS#1529]
各位开发者，我在使用inference_webui.py进行推理（传入参考音频、参考音频的对应文本，需要播报的文本，这个应该叫做0样本推理吧？）时，发现参考音频最多只能传10s的。想问下有没有什么办法可以增加参考音频允的时长上限呢，按照我的理解，参考音频越长，提取到的特征越准确，播报出的音色也会更加贴合意图吧。

期待各位开发者的回复

**Comment by RVC-Boss** [comment]
效果会下降，不建议
