### ISSUE TITLE
资源包找不到

### ISSUE THREAD

**Issue by qingtianmazi** [RVC-Boss/GPT-SoVITS#1530]
Resource averaged_perceptron_tagger_eng not found.

请问老师，这个错误，nltk_data包里面确实没有这个，但是之前运行的时候没有这个错误信息
esource averaged_perceptron_tagger_eng not found.
Please use the NLTK Downloader to obtain the resource:
>> import nltk
>> nltk. download('averaged_perceptron_tagger_eng')
For more information see: https: /www.nltk.org/data.html
Attempted to load taggers/averaged_perceptron_tagger_eng/
Searched in:
-'/home/work/aipic-panpan-tts/model/nltk_data'
-'/home/work/nltk_data'
-'/usr/nltk_data'
-/usr/share/nltk data'
-'/usr/lib/nltk_data'
-'/usr/share/nltk_data'
'/usr/local/share/nltk_data'
'/usr/lib/nltk data'
'/usr/local/lib/nltk_data'
./model/nltk data'
'./model/nltk_data'
'./model/nltk_data'
'./model/nltk_data'
'./model/nltk_data'
'./model/nltk_ data'
'./model/nltk_data'
'./model/nltk data'

**Comment by yangchendoit** [comment]
run `python -m nltk.downloader averaged_perceptron_tagger_eng` can fix it

**Comment by RVC-Boss** [comment]
这个资源在墙外所以…可能得手工下载一下然后手工放置
