### ISSUE TITLE
从头训练模型及添加新语言（设置）

### ISSUE THREAD

**Issue by lpscr** [RVC-Boss/GPT-SoVITS#1532]
你好，

感谢你提供的精彩代码库！我正在准备从头开始训练模型或为新语言进行微调。我已经按照 Wiki 中的说明进行操作，但我需要确认我的设置是否正确。

对于 S2 训练，我使用了所有默认设置，只更改了以下几项。请你确认这些设置是否正确：

    "freeze_quantizer": false
    "text_low_lr_rate": 1.0
    "learning_rate": 0.0001
    "use_spectral_norm": false

对于 S1 (GPT) 训练，我是否需要做任何更改，还是保持现有设置不变？

此外，如果你有任何其他关于使用新语言训练模型的建议或技巧，我将非常感激你的指导。

谢谢！

**Comment by RVC-Boss** [comment]
后2个不需要更改
前2个正确
s1不需要更改

**Comment by lpscr** [comment]
> 后2个不需要更改 前2个正确 s1不需要更改

非常感谢您的快速回复！

所以，只需要更改以下设置：

从头开始训练模型：

    "freeze_quantizer": false
    "text_low_lr_rate": 1.0

还有最后一个问题：

对于微调模型：

    "freeze_quantizer": true
    "text_low_lr_rate": 0.5

这些设置是否适用于添加新语言，还是从头开始训练模型更好？

**Comment by wangdefours** [comment]
+1，大佬，新手，我也是有想法对新语言进行微调，已经按照 Wiki 中的说明进行操作，是否还需要进行其他的修改，以及两个模型训练的轮数需要怎么设置，是否会破坏原有语种的tts合成能力

**Comment by wangdefours** [comment]
+1，大佬，新手，我想添加新语言，已经按照 Wiki 中的说明进行操作。
s1-s2这些是否还需要进行其他的修改，
以及两个模型训练的轮数需要怎么设置，我这边有大概100h的音频数据，
训练后是否会破坏原有语种的tts合成能力
