### ISSUE TITLE
主分支api_v2无法合成粤语

### ISSUE THREAD

**Issue by kirbykirby** [RVC-Boss/GPT-SoVITS#1535]
text_lang设置为auto_yue时，前端处理后的文本显示为空。设置为auto则完全没有问题。
![image](https://github.com/user-attachments/assets/a5b6eabf-a7d4-4051-a4dc-57bfc889184e)

**Comment by ChasonJiang** [comment]
是拉的最新main分支嘛？不是的话，请同步一下

**Comment by kirbykirby** [comment]
> 是拉的最新main分支嘛？不是的话，请同步一下

已经同步最新的main分支，问题仍然存在

**Comment by kirbykirby** [comment]
> > > 是拉的最新main分支嘛？不是的话，请同步一下
> > 
> > 
> > 已经同步最新的main分支，问题仍然存在
> 
> 再检查一下模型是不是都是v2版本的，v1版本不支持粤语

确认是v2版本，使用webui合成粤语没有问题。

**Comment by ChasonJiang** [comment]
> > > > 是拉的最新main分支嘛？不是的话，请同步一下
> > > 
> > > 
> > > 已经同步最新的main分支，问题仍然存在
> > 
> > 
> > 再检查一下模型是不是都是v2版本的，v1版本不支持粤语
> 
> 确认是v2版本，使用webui合成粤语没有问题。

好的，应该是个bug，我回头修复一下

**Comment by ChasonJiang** [comment]
另外，方便发一下推理参数嘛？

**Comment by kirbykirby** [comment]
> 另外，方便发一下推理参数嘛？

`data = {
    "text": "宜家唔系一定要你讲，你有权保持沉默，但你所讲嘅每一句说话，从宜家开始，都会成为呈堂证供。",
    "text_lang": "auto_yue",
    "ref_audio_path": refer_wav_path,
    "prompt_text": refer_text,
    "prompt_lang": "auto",
    "top_k": 15,
    "top_p": 1,
    "temperature": rand_temp,
    "text_split_method": "cut5",
    "batch_size": 20,
    "batch_threshold": 0.75,
    "split_bucket":True,
    "return_fragment": False,
    "speed_factor":speed_factor,
    "streaming_mode": False,
    "seed": -1,
    "parallel_infer": True,
    "repetition_penalty": 1.35
}`

**Comment by ChasonJiang** [comment]
> > 另外，方便发一下推理参数嘛？
> 
> `data = { "text": "宜家唔系一定要你讲，你有权保持沉默，但你所讲嘅每一句说话，从宜家开始，都会成为呈堂证供。", "text_lang": "auto_yue", "ref_audio_path": refer_wav_path, "prompt_text": refer_text, "prompt_lang": "auto", "top_k": 15, "top_p": 1, "temperature": rand_temp, "text_split_method": "cut5", "batch_size": 20, "batch_threshold": 0.75, "split_bucket":True, "return_fragment": False, "speed_factor":speed_factor, "streaming_mode": False, "seed": -1, "parallel_infer": True, "repetition_penalty": 1.35 }`

我刚测试了一下，没有复现呢。检查一下tts_infer.yaml中custom.version是不是v2

**Comment by kirbykirby** [comment]
> > > 另外，方便发一下推理参数嘛？
> > 
> > 
> > `data = { "text": "宜家唔系一定要你讲，你有权保持沉默，但你所讲嘅每一句说话，从宜家开始，都会成为呈堂证供。", "text_lang": "auto_yue", "ref_audio_path": refer_wav_path, "prompt_text": refer_text, "prompt_lang": "auto", "top_k": 15, "top_p": 1, "temperature": rand_temp, "text_split_method": "cut5", "batch_size": 20, "batch_threshold": 0.75, "split_bucket":True, "return_fragment": False, "speed_factor":speed_factor, "streaming_mode": False, "seed": -1, "parallel_infer": True, "repetition_penalty": 1.35 }`
> 
> 我刚测试了一下，没有复现呢。检查一下tts_infer.yaml中custom.version是不是v2

检查过了，tts_infer.yaml中custom.version是v2。只有api_v2会出现这个问题，api和webui都没问题。另外传入“yue”也是一样的问题。

**Comment by ChasonJiang** [comment]
> > 我刚测试了一下，没有复现呢。检查一下tts_infer.yaml中custom.version是不是v2
> 
> 检查过了，tts_infer.yaml中custom.version是v2。只有api_v2会出现这个问题，api和webui都没问题。另外传入“yue”也是一样的问题。

可是我用api_v2.py没有复现呢，建议在TTS.run()里打印一下version看看是不是v2。结合目前的信息我很难判断是什么情况

**Comment by XXXXRT666** [comment]
看看`git log -1`
