### ISSUE TITLE
SSL特征

### ISSUE THREAD

**Issue by zhiqiuiyiye** [RVC-Boss/GPT-SoVITS#1541]
Hi，大佬有尝试过使用whisper encoder提取到的特征做SSL训练模型吗？和Hubert训练出来的结果会有很大的差异吗？

**Comment by bfloat16** [comment]
whisper要强制切片或者pad到30秒，不能用

**Comment by RVC-Boss** [comment]
音色：2个方法漏得都挺多，
whisper：丢了音高所以音高预测效果会变差，得注入音高进whisper特征，但是问题来了，语音音高提取也可能有很多地方不准的，所以不能注入音高。那么丢了音高怎么办呢，靠后面的text注入，把vits当做一个TTS模型而不是重建模型，那zero shot就没戏了，大量数据（比如半小时以上数据）微调可能还有戏

**Comment by zhiqiuiyiye** [comment]
我用whisper的特征训练了一版模型，在其他的语种上的，目前zero-shot的结果挺起来还算正常，但是TTS的韵律情感没有原始说话人的强烈，不知道是不是这个原因

**Comment by RVC-Boss** [comment]
vits重建音高重建不出来太强的起伏，得往whisper特征上加音高，把音高预测交给GPT
