### ISSUE TITLE
api_v2.py ogg 音频处理

### ISSUE THREAD

**Issue by rouVling** [RVC-Boss/GPT-SoVITS#1547]
版本信息：release 中 20240821v2 

`api_v2.py` 中，使用 一个 45 k 的 ogg文件作为参考音频，会在 `librosa.load(ref_wav_path, sr=16000)` 中报错 `ValueError: array is too big; arr.size * arr.dtype.itemsize is larger than the maximum possible size.` （该语句单行测试运行中依旧报错）

但是同样的音频文件可以在 `inference_webui.py` 中正常使用

**Comment by XXXXRT666** [comment]
使用my_utils中的load_audio

**Comment by rouVling** [comment]
感谢~
已通过设置请求参数  media_type 解决
