### ISSUE TITLE
RTF

### ISSUE THREAD

**Issue by LiuMingYy** [RVC-Boss/GPT-SoVITS#1549]
请问一下，当前版本的模型推理时RTF能达到多少呢

**Comment by RVC-Boss** [comment]
3090每秒推7秒（batch1）
是否能组batch看你文本切割情况，但是这个会影响效果的，组batch推理最多可以在此基础上再加速10倍（超过10倍也有可能但是可能是特别强的显卡）
然后同样的文本生成的长度不是确定的所以只能根据生成的音频时长来换算速度
