### ISSUE TITLE
环境变量TEMP和AMD显卡冲突

### ISSUE THREAD

**Issue by bbhood** [RVC-Boss/GPT-SoVITS#155]
AMD显卡会在环境变量TEMP声明的目录生成临时文件，和生成的文件造成冲突，导致异常
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'

需要将两个webui的TEMP替换下
[diff.txt](https://github.com/RVC-Boss/GPT-SoVITS/files/14013226/diff.txt)

**Comment by RVC-Boss** [comment]
这个diff.txt有点抽象，能否具体描述下是哪个文件冲突了，你有什么解决方案

**Comment by you-can-do-it** [comment]
AMD显卡能识别出来吗？

**Comment by bbhood** [comment]
amd显卡到训练会报错，我后面还N卡了
