### ISSUE TITLE
开启SoVITS训练卡住了

### ISSUE THREAD

**Issue by Mr-Hongan** [RVC-Boss/GPT-SoVITS#1552]
![snipaste_20240828_225234](https://github.com/user-attachments/assets/eba475e1-6cae-4a91-95ae-4626aa58529e)
开启SoVITS训练卡住了，也没有报错，卡了20多分钟，还是不有反应

**Comment by SapphireLab** [comment]
问一下是什么设备

**Comment by Mr-Hongan** [comment]
win10的系统，显卡是2080ti，显存22g
