### ISSUE TITLE
请问V2版本训练里，vq encoder2k小时，剩余5k小时的原因是什么呢，为什么没有都用5k小时的数据呢？

### ISSUE THREAD

**Issue by asf2013** [RVC-Boss/GPT-SoVITS#1556]
请问V2版本训练里，vq encoder2k小时，剩余5k小时的原因是什么呢，为什么没有都用5k小时的数据呢？
为什么GPT只用了2.5k小时训练呢？
请问这其中是有什么原因吗？

**Comment by RVC-Boss** [comment]
1、只用2k小时训vq encoder：因为加到5k小时联合训练vq encoder，GPT效果变差了，还不然老版vq encoder，所以先用祖传vq encoder替一替
2、GPT用2.5k小时：+500h是为了支持韩语和粤语，加到5k小时：同样是因为效果下降了，不过原因现在已经找到了，后面的新版本会带清洗更好的数据加到1w小时

**Comment by ZongWei-HUST** [comment]
> 1、只用2k小时训vq encoder：因为加到5k小时联合训练vq encoder，GPT效果变差了，还不如老版vq encoder，所以先用祖传vq encoder替一替 2、GPT用2.5k小时：+500h是为了支持韩语和粤语，加到5k小时：同样是因为效果下降了，不过原因现在已经找到了，后面的新版本会带清洗更好的数据加到1w小时

请问加到5k小时训练效果下降的原因是啥？另外，可以使用其他的模型（例如T5）替换现在的GPT模型吗，有什么要注意的吗？

**Comment by asf2013** [comment]
同楼上，求问
