### ISSUE TITLE
關於粵語不能生成

### ISSUE THREAD

**Issue by andrewtangcm** [RVC-Boss/GPT-SoVITS#1558]
你好!本人是用整合包的GPT-SoVITS-v2-240821版本
我嘗試用英文或其他語言是沒有任何事的
但用粵語就不成功
GPT-SoVITS-v2-240807版本沒有問題的
到底是我那個步驟做錯了
推理空白了

粵語的是
实际输入的目标文本(切句后):
['你到底明唔明白?']
############ 提取文本Bert特征 ############
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 249.97it/s]
############ 推理 ############
前端处理后的文本(每句): [' ']
  0%|                                                                                 | 1/1500 [00:00<05:55,  4.22it/s]T2S Decoding EOS [117 -> 119]
  0%|                                                                                 | 1/1500 [00:00<06:13,  4.02it/s]
0.000   0.007   0.254   0.071

英文的是
实际输入的目标文本:
what are you doing?
实际输入的目标文本(切句后):
['what are you doing?']
############ 提取文本Bert特征 ############
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.03s/it]
############ 推理 ############
前端处理后的文本(每句): ['what are you doing? ']
  2%|█▊                                                                              | 33/1500 [00:00<00:17, 82.90it/s]T2S Decoding EOS [117 -> 154]
  2%|█▉                                                                              | 36/1500 [00:00<00:19, 75.77it/s]
1.633   2.035   0.501   0.594

![image](https://github.com/user-attachments/assets/66d167cb-dcf2-4261-bf07-19e9d4cc810d)

![image](https://github.com/user-attachments/assets/5f605d99-3b1e-4b3b-91ed-fdc6115b796b)

**Comment by SapphireLab** [comment]
直接使用预训练权重也不行是吗?

**Comment by Atopona** [comment]
240821版本相同
除了中日英其他均无法生成

**Comment by Atopona** [comment]
已修复
详见：https://github.com/RVC-Boss/GPT-SoVITS/pull/1528

解决方法
下载仓库最新的源码覆盖至整合包内

**Comment by RVC-Boss** [comment]
ok，感谢楼上回答

**Comment by andrewtangcm** [comment]
謝謝你們!
