### ISSUE TITLE
It is XTTS

### ISSUE THREAD

**Issue by d3on4pcsm** [RVC-Boss/GPT-SoVITS#156]
This model is basically same as XTTS. Am I missing something?

**Comment by RVC-Boss** [comment]
You can get model architecture and training steps in this url:
https://github.com/RVC-Boss/GPT-SoVITS/issues/67

**Comment by d3on4pcsm** [comment]
Yes I read that and it is the same as XTTS v1. 

You should give a reference to them. Else it goes to plagiarism.
