### ISSUE TITLE
请问有打算添加情感、语气等方面的控制功能吗？

### ISSUE THREAD

**Issue by smileshy777** [RVC-Boss/GPT-SoVITS#1561]
这个项目我觉得做得非常棒！
在实际使用的过程中，我认为一些时候有必要加入一些情感和语气。
但是我看你们的开发计划里面，原本有这一项打算，然后又划掉了，请问这是出于什么样的考虑呢？后续还有这方面的打算吗？

**Comment by RVC-Boss** [comment]
实验失败了，哈哈 T_T

看需求吧，embedding肯定是不好用了，但是可以看看用情感数据特化训练下GPT，然后情感、sovits用不同参考音频之类的办法

**Comment by recombiOOO** [comment]
不同语气，我是通过自己录不同的音频做的

**Comment by RVC-Boss** [comment]
后面我试试直接加入情感训练集训GPT

**Comment by xiezheng-cs** [comment]
> 后面我试试直接加入情感训练集训GPT

您好，请问情绪控制您这边尝试实验和思路是怎么样的呢？目前我也在看这一块

**Comment by QWXL** [comment]
> 后面我试试直接加入情感训练集训GPT

怎么说，目前的进度如何？
