### ISSUE TITLE
funasr离线批量ASR时出现报错

### ISSUE THREAD

**Issue by gyhmuuki** [RVC-Boss/GPT-SoVITS#1563]
Traceback (most recent call last):                                                               | 0/1 [00:00<?, ?it/s]
  File "C:\Users\Administrator\PycharmProjects\GPT-SoVITS\tools\asr\funasr_asr.py", line 31, in execute_asr
    text = model.generate(input=file_path)[0]["text"]
IndexError: list index out of range
使用的路径是默认的output\denoise_opt，使用Faster Whisper可以正常读取到中文然后转funasr但是正确率几乎为零，音频质量没问题

**Comment by gyhmuuki** [comment]
model.generate(input=file_path)[0]["text"]返回的是个空数组

**Comment by yangyazhou97** [comment]
同样遇到“list index out of range”的问题，用多线程进行funasr报错

**Comment by yangyazhou97** [comment]
这里说到vad的python版本不支持并发
https://github.com/modelscope/FunASR/issues/865

**Comment by XXXXRT666** [comment]
bad case呢,funasr只有碰到无法识别的东西才会返回空数组

**Comment by gyhmuuki** [comment]
> bad case呢，funasr只有碰到无法识别的东西才会返回空数组


应该是环境有问题，同一个音频在另一台电脑上可以正常跑，而且很奇怪的一点是用faster whisper转funasr之后居然可以跑通但是直接用funasr就有问题

**Comment by gyhmuuki** [comment]
相同的依赖版本，用的同一个requirements，并且一一对比了各个第三方库的版本，目前测试的是其他电脑可以，我的电脑不行，唯一的区别就是别人是3.10.14，我的是3.10.8   cuda这些配置都是同一个人配置的，版本都是一样的，我先试试是不是python小版本导致的。

**Comment by gyhmuuki** [comment]
发现问题了，之前报错是用pip安装的cuda版本的torch，改成conda装就没问题了
