### ISSUE TITLE
请问如何让Gpt-sovits支持更多语言呢？

### ISSUE THREAD

**Issue by phdhorse41** [RVC-Boss/GPT-SoVITS#1565]
你好，我是一名声学工作者，也是个语言学爱好者，很感谢贵项目对于语言学习者的重要帮助以及贡献者们的无私付出，期待后续的更新。 **请问能否提供一个方法能让我们去训练更多的语言呢？** 例如泰语、印尼语、高棉语、或者一些其他可被large-v3识别并分析的其他小语种（我试过了，现在large-v3可以准确识别印尼语）。我手里有足够多的音频文件和对应的文本（大概不同人不同内容，但同一语言，共10个小时左右），很希望也能通过gpt-sovits的加持，实现在这些语言上的合成。

**Comment by XXXXRT666** [comment]
见项目wiki

**Comment by phdhorse41** [comment]
> 见项目wiki

那个我看过了，但是好像里面没有提到如图所示的“文字”到“语音”映射关系的具体方法，以及在wiki里给了两个一样的链接，这个到底是怎么弄的？我看到里面参考的别的韩语TTS
![image](https://github.com/user-attachments/assets/2443f558-3817-43ba-8c6d-80dc379bc5f9)
![image](https://github.com/user-attachments/assets/17696528-0962-4c47-a47b-4b689f2eb88f)

**Comment by XXXXRT666** [comment]
自备g2p

**Comment by RVC-Boss** [comment]
> > 见项目wiki
> 
> @XXXXRT666 那个我看过了，但是好像里面没有提到如图所示的“文字”到“发音”（IPA或者别的）映射关系的具体方法，以及在wiki里给了两个一样的链接，这个到底是怎么弄的？我看到里面参考的别的韩语TTS ![image](https://private-user-images.githubusercontent.com/22786182/363470871-2443f558-3817-43ba-8c6d-80dc379bc5f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzM3OTEsIm5iZiI6MTcyNTMzMzQ5MSwicGF0aCI6Ii8yMjc4NjE4Mi8zNjM0NzA4NzEtMjQ0M2Y1NTgtMzgxNy00M2JhLThjNmQtODBkYzM3OWJjNWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzMTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmYzM3ZDkwNjhlYjU5M2ViZjBkZmFjZjRhODE1NGI5ODRkM2U3MTdmNzM3YjcyNTlmMTViZTk1N2I2MTJmNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6uhGOQHXUyuJkWZLrjNFOQqh0BGjgsqmVzZFtlBJFxI) ![image](https://private-user-images.githubusercontent.com/22786182/363471441-17696528-0962-4c47-a47b-4b689f2eb88f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzM3OTEsIm5iZiI6MTcyNTMzMzQ5MSwicGF0aCI6Ii8yMjc4NjE4Mi8zNjM0NzE0NDEtMTc2OTY1MjgtMDk2Mi00YzQ3LWE0N2ItNGI2ODlmMmViODhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzMTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZWY5MzhkYTE1MjUwNjA3YzJiOGZiNzc4NTlkNWRjZjY5OTY1YWNkN2NmNDg3NjdlZWE3OGQyZjVmMjdhZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7A8hCxe6tTMSwe0fT9iiSkvLOZcEH9rx8-hN8i7nwtc)

对的，这玩意需要你自己准备   你是  语言学爱好者    应该知道怎么写““文字”到“发音”（IPA或者别的）映射关系的具体方法”

**Comment by XXXXRT666** [comment]
> > 见项目wiki
> 
> @XXXXRT666 那个我看过了，但是好像里面没有提到如图所示的“文字”到“发音”（IPA或者别的）映射关系的具体方法，以及在wiki里给了两个一样的链接，这个到底是怎么弄的？我看到里面参考的别的韩语TTS ![image](https://private-user-images.githubusercontent.com/22786182/363470871-2443f558-3817-43ba-8c6d-80dc379bc5f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzU3NzMsIm5iZiI6MTcyNTMzNTQ3MywicGF0aCI6Ii8yMjc4NjE4Mi8zNjM0NzA4NzEtMjQ0M2Y1NTgtMzgxNy00M2JhLThjNmQtODBkYzM3OWJjNWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzNTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZDgzYTlmMWU2M2JmNzQ2N2FmZjMwZjE1MzFkOTExNzI5ZjNkMjI0MjE3OTUyZmFkNzhjMmY1Yzg1NzJjYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bJhw3L_JGWwevkiIEIMzdS1CuTuxcNYqCxJ1cZByDkg) ![image](https://private-user-images.githubusercontent.com/22786182/363471441-17696528-0962-4c47-a47b-4b689f2eb88f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzU3NzMsIm5iZiI6MTcyNTMzNTQ3MywicGF0aCI6Ii8yMjc4NjE4Mi8zNjM0NzE0NDEtMTc2OTY1MjgtMDk2Mi00YzQ3LWE0N2ItNGI2ODlmMmViODhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzNTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ODRmZTlhNzAwZWMxMjk1OGY2ZWM1OTEzNGEzM2Q1N2I0MTViNjJmYjljOTAxMGIxODA5MDJjYzE2NjZjMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.REuPwMSNpOpfYLZvKnZb-3XBGqINd0Hf_FzwZrUsmKk)

对于中文来说就是准备字典和分词器以及查字典的逻辑,详见pypinyin
