### ISSUE TITLE
G2PWModel 的路径有缓存吗？

### ISSUE THREAD

**Issue by BobReal0822** [RVC-Boss/GPT-SoVITS#1570]
在同一 conda 环境下，多个项目的 G2PWModel 路径貌似会相互影响；启动一个项目后，再启动另一个项目的 webui.py，重启前者后会导致前者从后者的路径找 G2PWModel，报错信息如下：

` "Exception": "[Errno 2] No such file or directory: 'GPT_SoVITS/text/G2PWModel_1.1.zip'"`

是因为 G2PWModel 的路径有缓存吗？或者共享路径？或者路径和环境绑定？

**Comment by RVC-Boss** [comment]
对的就在报错的这个路径里
或者你可以把工程代码全局搜索G2PWModel_1.1这个关键词替换成你想要的

**Comment by XXXXRT666** [comment]
GSV建议单独开环境用,两个GSV都不要共用环境

**Comment by XXXXRT666** [comment]
因为你不知道你import的是哪个GSV代码,这有可能就是import的另一个项目的onnx api
