### ISSUE TITLE
Local URL没有自动弹出窗口，复制到浏览器窗口报错打不开

### ISSUE THREAD

**Issue by recombiOOO** [RVC-Boss/GPT-SoVITS#1574]
![image](https://github.com/user-attachments/assets/dc754ba6-dcec-4222-ae63-c214fe1f0836)
INFO:     127.0.0.1:60440 - "GET / HTTP/1.1" 400 Bad Request
INFO:     127.0.0.1:60440 - "GET / HTTP/1.1" 400 Bad Request
![image](https://github.com/user-attachments/assets/eba838ba-5904-4032-85db-54e6bfbc816e)

**Comment by recombiOOO** [comment]
已解决。全部删了。重新下载，又按步骤安装一遍可以打开了。
![image](https://github.com/user-attachments/assets/234895d6-4266-4d8c-ae0f-30c297e1802e)

**Comment by XXXXRT666** [comment]
本来API就不是网页

**Comment by recombiOOO** [comment]
> 本来API就不是网页

启动本地服务器后，虽然显示 Running on local URL: http://0.0.0.0:9874，但浏览器未自动打开该 URL。尝试手动将 URL 复制到浏览器地址栏后，页面仍无法打开。确认服务器正在运行，且端口号正确。 这样描述可以了吗？

**Comment by XXXXRT666** [comment]
这是webUI而不是API

**Comment by XXXXRT666** [comment]
而且gradio4不会显示 Running on local URL,如果浏览器未打开就是没开,使用localhost或者127.0.0.1而不是0.0.0.0访问

**Comment by XXXXRT666** [comment]
如果没成功打开,那就是有报错,多半是hosts无法解析localhost

**Comment by XXXXRT666** [comment]
你怎么确定服务在运行?使用`netstat -an | grep LISTEN`来查看端口是否被监听
