### ISSUE TITLE
有个问题想问一下

### ISSUE THREAD

**Issue by tobeornottoer** [RVC-Boss/GPT-SoVITS#1578]
Set seed to 3626764237
100%|██████████| 1/1 [00:05<00:00,  5.86s/it]
  8%|▊         | 122/1500 [00:01<00:18, 72.95it/s]
T2S Decoding EOS [164 -> 287]
转语音的过程中，第二条进度的性能跟什么有关呢？
因为我同样是在4090的GPU上面跑，只是python的版本不一样
之前的第二个进度能够达到300多，新的机器只有70多了

**Comment by thom802311** [comment]
那1500是最大的抽卡次数，抽到合适的就结束，122那个数字就是抽到了。72.95那个是性能指标。

**Comment by tobeornottoer** [comment]
搜嘎，大佬再问下，有什么方法可以直观的比较到两个机器之间的那个性能指标吗？我想知道新的机器上到底是差了点什么，性能差这么多，都是4090的卡，cuda版本也一样，只是驱动一个是550.100，新的是 550.107.02 ，然后就是python版本，一个是3.9，新的是3.10。torch都是2.4.0的 。

**Comment by thom802311** [comment]
看这2个值，5.86s/it  72.95it/s

**Comment by tobeornottoer** [comment]
大佬，我问下，这个性能会跟CPU有关吗？同样的显卡，13th Gen Intel(R) Core(TM) i7-13700K 会比 Intel(R) Xeon(R) Platinum 8352V CPU @ 2.10GHz在同样的场景下，性能会高很多
