### ISSUE TITLE
请问在服务器上安装不上pyopenjtalk这个包，是什么原因呢？

### ISSUE THREAD

**Issue by ymmbb8882ymmbb** [RVC-Boss/GPT-SoVITS#158]
请问在服务器上安装不上pyopenjtalk这个包，是什么原因呢？

**Comment by BlacknoSheep** [comment]
1. 使用代理或镜像，或手动下载并安装。（推荐用代理，因为pyopenjtalk还会从github下载语言包）
2. 如果出现 permission denied ，修改相应文件夹的权限。

**Comment by RVC-Boss** [comment]
如果你的服务器连不上github，只能手动下载传到指定位置了。

**Comment by ChrisGitHubIcon** [comment]
宿主机没有cmake吧
