### ISSUE TITLE
試行api_v2 成功了 但400 Bad Request 導致ai 音頻沒法回饋到網頁

### ISSUE THREAD

**Issue by NoMoodCodeMachine** [RVC-Boss/GPT-SoVITS#1580]
排查了半天都沒找到原因 求助各路大神

報錯:
![圖片](https://github.com/user-attachments/assets/4edd7de1-e61d-47fb-ac23-092afae7417d)
![圖片](https://github.com/user-attachments/assets/7c8dcd3b-a9f6-41df-8e33-f33a73673a07)

Request body:
{
  "text": "你好你好我是測試員零一",
  "text_lang": "all_zh",
  "ref_audio_path": "C:/Users/Desktop/你好你好我是測試員零一.wav",
  "aux_ref_audio_paths": [],
  "prompt_lang": "all_zh",
  "prompt_text": "我早上不能空腹吃早餐",
  "top_k": 5,
  "top_p": 1,
  "temperature": 1,
  "text_split_method": "cut5",
  "batch_size": 1,
  "batch_threshold": 0.75,
  "split_bucket": true,
  "return_fragment": false,
  "speed_factor": 1,
  "seed": -1,
  "streaming_mode": false,
  "parallel_infer": true,
  "repetition_penalty": 1.35
}

已排除音頻檔案位置錯誤 | 同一音頻在api_v1可正常操作
已排除json 格式錯誤 | 以chatGPT 驗證過
重開api_v2 乃至重開電腦皆有嘗試
ip與接口使用 127.0.0.1:9880

有修改少部份代碼:
原code:
text_lang: str = None
prompt_lang: str = None
改:
text_lang: str = ""
prompt_lang: str = ""

這是為了避開 str.lower() 與 None 的衝突 相信與400Error無關

**Comment by NoMoodCodeMachine** [comment]
已解決問題

**Comment by YQS1777** [comment]
> 已解決問題

怎么搞的兄弟，现在我也遇到这个问题了

**Comment by LymtIcsh** [comment]
> 已解決問題 已解决问题
怎么搞的呀大佬，这边也遇到同样问题

**Comment by YQS1777** [comment]
> > 已解決問題 已解决问题
> > 怎么搞的呀大佬，这边也遇到同样问题

一般是请求参数有问题，自己打开fastapi网页查看查看请求参数和格式就行了，我的问题是这样得到解决的，你可以试试

**Comment by LymtIcsh** [comment]
> > > 已解決問題 已解决问题
> > > 怎么搞的呀大佬，这边也遇到同样问题
> 
> 一般是请求参数有问题，自己打开fastapi网页查看查看请求参数和格式就行了，我的问题是这样得到解决的，你可以试试
好的，谢谢大佬回复

**Comment by gaord** [comment]
这个问题我也遇到了，弄了几个小时才搞定。大概注意以下2点：
1，参考音频的长度要小于10秒。v1版的12秒可以工作，v2版不行。
2，v1和v1的json参数名称有变化，仔细查看文档，别弄错了
