### ISSUE TITLE
fastapi 0.113.0 搞崩了所有gradio应用， gradio官方最新版本已更新临时修复4.43.0, 请更新这个项目里requirement.txt

### ISSUE THREAD

**Issue by neoyxm** [RVC-Boss/GPT-SoVITS#1587]
gradio官方在最新版本4.43.0里把fastapi版本限制在 < 0.113.0, 
但gpt-sovits当前requirements.txt里gradio限制在<4.24.0, 无法得到gradio最新修复，导致推理页面无法打开。
请放开gradio的版本限制。

**Comment by XXXXRT666** [comment]
fastapi未使用这个版本

**Comment by neoyxm** [comment]
> 如果安装req，fastapi不会超过0.113

gpt-sovits是没有直接引用fastapi,  fastapi是gradio带进来的。 

刚刚gradio官方出了新版本，把fastapi的版本钉在 <0.113.0来解决。

但req里的gradio版本被限制在<=4.24.0,   无法获取最新gradio 4.43.0. 而gradio<=4.24.0会去引用最新版本的fastapi，导致推理页面打不开。

**Comment by XXXXRT666** [comment]
装了fastapi 0.113.0, gradio 4.24.0,无法复现

**Comment by neoyxm** [comment]
好吧.

close it.

**Comment by XXXXRT666** [comment]
重新开了一个环境测试，未能复现，暂且认为4.24以下无问题，如出问题自行降级`Pydantic-cor`e

**Comment by eureka6** [comment]
不知道有没有帮助：#1589

**Comment by neoyxm** [comment]
> 不知道有没有帮助：#1589

1589就是复现我所说的问题，但上面那个哥们坚持说无法发现，我也没办法。

**Comment by XXXXRT666** [comment]
> 重新开了一个环境测试，未能复现，暂且认为4.24以下无问题，如出问题自行降级`Pydantic-core`

我理解错了,webUI能开但是不能用,有问题就降级fastapi

**Comment by XXXXRT666** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/commit/3488cffd68752ce72f91d581585770ff18c9a1b3

**Comment by neoyxm** [comment]
> 我理解错了,webUI能开但是不能用,有问题就降级fastapi==0.112.0

我的锅，我没描述清楚，我描述成了推理页没法打开，其实是推理失败。
