### ISSUE TITLE
请问在点击一键三连时遇到这个错误，FileNotFoundError: [Errno 2] No such file or directory: 'logs/wzj1/2-name2text-0.txt'

### ISSUE THREAD

**Issue by ymmbb8882ymmbb** [RVC-Boss/GPT-SoVITS#159]
请问在点击一键三连时遇到这个错误，FileNotFoundError: [Errno 2] No such file or directory: 'logs/wzj1/2-name2text-0.txt'

**Comment by xiaoliliu99** [comment]
可以在项目路径logs/wzj1/下创建文件：2-name2text-0.txt 后再次尝试一键三连

> 请问在点击一键三连时遇到这个错误，FileNotFoundError: [Errno 2] No such file or directory: 'logs/wzj1/2-name2text-0.txt'

**Comment by potatoker** [comment]
> 可以在项目路径logs/wzj1/下创建文件：2-name2text-0.txt 后再次尝试一键三连
> 
> > 请问在点击一键三连时遇到这个错误，FileNotFoundError: [Errno 2] No such file or directory: 'logs/wzj1/2-name2text-0.txt'

然后会继续报错找不到2-name2text-0.txt

**Comment by potatoker** [comment]
> 可以在项目路径logs/wzj1/下创建文件：2-name2text-0.txt 后再次尝试一键三连
> 
> > 请问在点击一键三连时遇到这个错误，FileNotFoundError: [Errno 2] No such file or directory: 'logs/wzj1/2-name2text-0.txt'

然后回继续报错找不到2-name2text-1.txt'

**Comment by Liu-yixi** [comment]
尝试将网页端pretrain_models的三个路径，改为./GPTSoVits...，改为相对路径

**Comment by RVC-Boss** [comment]
能否截图控制台，以及下载的包是哪天的

**Comment by wavetao2010** [comment]
> > 可以在项目路径logs/wzj1/下创建文件：2-name2text-0.txt 后再次尝试一键三连
> > > 请问在点击一键三连时遇到这个错误，FileNotFoundError: [Errno 2] No such file or directory: 'logs/wzj1/2-name2text-0.txt'
> 
> 然后回继续报错找不到2-name2text-1.txt'

我也遇到了同样的问题

**Comment by winterwd** [comment]
> 可以在项目路径logs/wzj1/下创建文件：2-name2text-0.txt 后再次尝试一键三连
> 
> > 请问在点击一键三连时遇到这个错误，FileNotFoundError: [Errno 2] No such file or directory: 'logs/wzj1/2-name2text-0.txt'

一键三连的时候，他会删除这个文件

**Comment by wavetao2010** [comment]
> 能否截图控制台，以及下载的包是哪天的

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/45758593/e9704a62-b35c-483b-b3da-975d071d0ebb)
这个是控制台截图，我下载的包是1月23号克隆的

**Comment by potatoker** [comment]
不过确实，每报一个No such file就手动创建一个也是可以解决的。。。

**Comment by Hardwell99** [comment]
我今早也遇到了问题，有人说是显卡问题，仔细看一下发现有显示“没有可用的显卡”
现在解决了
1：安装支持 cuda 的torch、torchvision、torchaudio：
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

2：查看 GPT_SoVits/pretrained_models 下是否有下载好的模型，这是下载完成的：
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/104831430/78995090-06b2-4e10-93b3-da9b0eb35bfe)
我是从预打包文件复制过来的
https://huggingface.co/lj1995/GPT-SoVITS-windows-package/resolve/main/GPT-SoVITS-beta.7z?download=true

**Comment by wavetao2010** [comment]
> 我今早也遇到了问题，有人说是显卡问题，仔细看一下发现有显示“没有可用的显卡” 现在解决了 1：安装支持 cuda 的torch、torchvision、torchaudio： pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> 
> 2：查看 GPT_SoVits/pretrained_models 下是否有下载好的模型，这是下载完成的： ![image](https://private-user-images.githubusercontent.com/104831430/299239028-78995090-06b2-4e10-93b3-da9b0eb35bfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTUwNzUsIm5iZiI6MTcwNjA5NDc3NSwicGF0aCI6Ii8xMDQ4MzE0MzAvMjk5MjM5MDI4LTc4OTk1MDkwLTA2YjItNGUxMC05M2IzLWRhOWIwZWIzNWJmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQxMTEyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YWFlOWU2MTMxNjc5MTJhOTM1ZmE3YzYwMThhZDRmOTRhY2UxZDBhMzQ5MTc3YmQwZTMwZDI2YTQ4YTQ0OTM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.loHlvNWqBybIpvT-Eg6tPifJdPDlkuktSl4E1gMmqRg) 我是从预打包文件复制过来的 https://huggingface.co/lj1995/GPT-SoVITS-windows-package/resolve/main/GPT-SoVITS-beta.7z?download=true

按照你的方法，我找到了原因，是因为下载的时候
<img width="410" alt="image" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/45758593/17be7af8-989d-42a9-953c-52117e19e5de">
这两个模型文件夹中的文件  config.json 和tokenziner.json 莫名其妙的加了文件夹名字的前缀导致的无法找到，然后我修改一下名称就不再报错了

**Comment by AX686XXX** [comment]
> 看看报错信息，有没有说是因为模型相关的文件加载错误？我刚刚也遇到了这个问题，然后看前面提示有“OSError： GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large does not seem to have a file named config.json.Checkout 'https://huggingface.co/GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large/None' for available files“，是因为我下载模型相关文件的时候，命名错了，导致模型无法加载，于是无法正确生成2-name2text-%s.txt这种文件。 2-name2text-%s.txt文件是在GPT-SoVITS/GPT_SoVITS/prepare_datasets/1-get-text.py这个文件生成的，在 webui.py 的505行 cmd = '“%s” GPT_SoVITS/prepare_datasets/1-get-text.py'%python_exec对这个文件进行了调用，从而生成了2-name2text-%s.txt文件。

原理明白了，如何解决

**Comment by Cold-Noodle** [comment]
我是下载的prezip包，运行平台是windows10，一键三连时也是报错。
![err](https://github.com/RVC-Boss/GPT-SoVITS/assets/27951846/463f495c-953d-448a-9e28-b70a51d3b6a8)

**Comment by Hardwell99** [comment]
> 我是下载的prezip包，运行平台是windows10，一键三连时也是报错。 ![err](https://private-user-images.githubusercontent.com/27951846/299862740-463f495c-953d-448a-9e28-b70a51d3b6a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDk0NzksIm5iZiI6MTcwNjI0OTE3OSwicGF0aCI6Ii8yNzk1MTg0Ni8yOTk4NjI3NDAtNDYzZjQ5NWMtOTUzZC00NDhhLTllMjgtYjcwYTUxZDNiNmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA2MDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlODJjMWNjNGIzMmRhYjdiODhhYzk2NjRmZDY2OGJhNzZlYzU3OTRmOWRjNDAxNGU1ZDJiOTIyZjUyNTA4MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9AoZSIGQ5vIueMXlCZsJHmDx2n_pyjEyRJS4Hzy1dZc)

1、预打包版本可能不是最新版本
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/104831430/0d10fd47-dc8d-40ce-b5b8-32a24ca7b204)

2、看看你的显卡能不能加载到，不能就安装支持cuda的torch、torchvision、torchaudio版本
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/104831430/410192c9-5e18-49e2-8f3d-89697b0e236f)

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/104831430/66b81c7f-56c7-4295-838f-76b7443b9214)

**Comment by RVC-Boss** [comment]
程序自身的问题已经解决了。后续你尝试下更新版本再一键三连试试，如果2456文件夹\文件里有全空的，很可能是数据或者格式问题了。

**Comment by FuckerLinda** [comment]
我是因为没有下载完整的pretrained_models，并把它替换掉GPT_SoVITS文件夹下的pretrained_models，所以我报错

**Comment by menphy905** [comment]
![微信截图_20240329082707](https://github.com/RVC-Boss/GPT-SoVITS/assets/165292999/c1bc7942-09b6-4834-b275-0edf708baf40)
我的也是这样报错，我是新手小白。 请问有大神教我嘛

**Comment by menphy905** [comment]
> 程序自身的问题已经解决了。后续你尝试下更新版本再一键三连试试，如果2456文件夹\文件里有全空的，很可能是数据或者格式问题了。

可以帮忙看下我的问题吗？
![微信截图_20240329082707](https://github.com/RVC-Boss/GPT-SoVITS/assets/165292999/1d383026-da0f-4512-95f2-46e28507dd55)
谢谢你了

**Comment by hhh315xxx** [comment]
我是重新下载了chinese-roberta-wwm-ext-large模型换上去得以解决，应该是之前模型安装有文件缺失。比如config，和pytorch_model这个文件不对，所以老是报错，可以在huggingface或者镜像https://hf-mirror.com/hfl/chinese-roberta-wwm-ext-large/tree/main下载正解的模型。而且重试时候，要把对应logs文件夹里原来生成的删除掉，重新生成最好，不删除也会报错。
