### ISSUE TITLE
使用自带的UVR5处理音频时，没有model_bs_roformer_ep_317_sdr_12.9755这个选项

### ISSUE THREAD

**Issue by topshu** [RVC-Boss/GPT-SoVITS#1592]
使用autodl，官方最新的v14镜像，打开webui
使用自带的UVR5处理音频时，没有model_bs_roformer_ep_317_sdr_12.9755这个选项
![1111](https://github.com/user-attachments/assets/41c6e56b-de5b-4861-b9b3-37e4ac0ace68)
只有附件截图这3个模型可以x选择，是需要自己去下载吗？

**Comment by RVC-Boss** [comment]
要先自己下载模型到指定路径

**Comment by yikeqingli** [comment]
![image](https://github.com/user-attachments/assets/a84d610a-5802-4921-b458-279eaf8f15f7)链接里没有这个模型

**Comment by yikeqingli** [comment]
> 要先自己下载模型到指定路径

![image](https://github.com/user-attachments/assets/c0417c2b-5530-4f46-9dbf-aa871526a7aa)
链接里没有这个模型
