### ISSUE TITLE
关于用API调用它的问题

### ISSUE THREAD

**Issue by beenlee14** [RVC-Boss/GPT-SoVITS#1597]
当它被用API调用时，能不能使用声音融合的功能？如果能用，应该怎么用呢？需要在CONFIG.PY里改些什么吗？

**Comment by XXXXRT666** [comment]
可以,发请求时传入多个inp_refs

**Comment by beenlee14** [comment]
> 可以,发请求时传入多个inp_refs

请教, 具体需要怎么操作呢？在什么地方输入？

**Comment by KamioRinn** [comment]
> > 可以,发请求时传入多个inp_refs
> 
> 请教, 具体需要怎么操作呢？在什么地方输入？

Api.py中有

**Comment by RVC-Boss** [comment]
楼上正解
