### ISSUE TITLE
[bug] Bad output when reference audio length > generated audio length

### ISSUE THREAD

**Issue by BlacknoSheep** [RVC-Boss/GPT-SoVITS#160]
当参考音频长度 > 生成音频长度时，输出结果会忽视目标文本，最终结果类似于参考音频+噪音。

When the reference audio length is greater than the generated audio length, the output will disregard the target text, resulting in a final outcome resembling the reference audio with added noise.

**Comment by RVC-Boss** [comment]
Is "bad zero prediction" in cmd?

**Comment by BlacknoSheep** [comment]
> Is "bad zero prediction" in cmd?

Yes.

**Comment by RVC-Boss** [comment]
When did you clone the github codes?
Try updating the latest codes, it's fixed now.

**Comment by BlacknoSheep** [comment]
> When did you clone the github codes? Try updating the latest codes, it's fixed now.

solved.
