### ISSUE TITLE
api.py无法输出中英混杂或英文语音

### ISSUE THREAD

**Issue by Lwx1203** [RVC-Boss/GPT-SoVITS#1600]
中文可以正常输出，英文加其他语种（非英文）也可以正常输出，但是内容是纯英文或包括英文就不行，选了en或zh都不可以，有没有大佬知道为什么？

**Comment by kkkwjr** [comment]
> 中文可以正常输出，英文加其他语种（非英文）也可以正常输出，但是内容是纯英文或包括英文就不行，选了en或zh都不可以，有没有大佬知道为什么？

+1同问
