### ISSUE TITLE
关于去掉vits部分text输入导致咬字发音问题

### ISSUE THREAD

**Issue by vincentspeech** [RVC-Boss/GPT-SoVITS#1601]
感谢您分享这个优秀的项目
我看v2支持了无文本参考的模式，但是看代码vits只有在推理阶段通过test参数控制是否输入text，如果只在推理阶段将vits中的text置0的话测下来会出现**部分语音咬字的音调或者清音错误**，请问v2还有其他操作避免这个问题吗？

**Comment by RVC-Boss** [comment]
不能丢掉text
