### ISSUE TITLE
牦 字读音有问题

### ISSUE THREAD

**Issue by xipingL** [RVC-Boss/GPT-SoVITS#1602]
text: 你知道不，在草原上骑牦牛的时候，我特别喜欢抽上一口电子烟，那感觉就像是在雪豹的领地里自由驰骋一样，灵感四溢，说不定下一首歌的旋律就来了呢！

phones: ['n', 'i3', 'zh', 'ir1', 'd', 'ao4', 'b', 'u4', ',', 'z', 'ai4', 'c', 'ao3', 'y', 'van2', 'sh', 'ang4', 'q', 'i2', 'l', 'i2', 'n', 'iu2', 'd', 'e5', 'sh', 'ir2', 'h', 'ou5', ',', 'w', 'o3', 't', 'e4', 'b', 'ie2', 'x', 'i3', 'h', 'uan5', 'ch', 'ou1', 'sh', 'ang4', 'y', 'i4', 'k', 'ou3', 'd', 'ian4', 'z', 'i03', 'y', 'En1', ',', 'n', 'a4', 'g', 'an3', 'j', 've2', 'j', 'iu4', 'x', 'iang4', 'sh', 'ir4', 'z', 'ai4', 'x', 've3', 'b', 'ao4', 'd', 'e5', 'l', 'ing3', 'd', 'i5', 'l', 'i3', 'z', 'i04', 'y', 'ou2', 'ch', 'ir2', 'ch', 'eng3', 'y', 'i2', 'y', 'ang4', ',', 'l', 'ing2', 'g', 'an3', 's', 'i04', 'y', 'i4', ',', 'sh', 'uo1', 'b', 'u5', 'd', 'ing4', 'x', 'ia4', 'y', 'i4', 'sh', 'ou3', 'g', 'e1', 'd', 'e5', 'x', 'van2', 'l', 'v4', 'j', 'iu4', 'l', 'ai2', 'l', 'e5', 'n', 'e5', '!']
 牦牛 phones: 'l', 'i2', 'n', 'iu2'

**Comment by xipingL** [comment]
这边好像是pypinyin生成pinyin的问题，不确定...如果是的话，我就close了

**Comment by KamioRinn** [comment]
Fix https://github.com/RVC-Boss/GPT-SoVITS/pull/1605

**Comment by xipingL** [comment]
> Fix #1605

@KamioRinn 
你好，想知道 polyphonic.pickle 是怎么生成的，如果下次再遇到，我可以尝试自己改

**Comment by KamioRinn** [comment]
> 
> @KamioRinn 你好，想知道 polyphonic.pickle 是怎么生成的，如果下次再遇到，我可以尝试自己改

删掉就行了
