### ISSUE TITLE
数字例如5000，会被念成五零零零，而不是五千

### ISSUE THREAD

**Issue by viryaka** [RVC-Boss/GPT-SoVITS#1606]
例如：
5000骑兵，3500步兵，1800侍从，征战5年

前端处理后的文本(每句): ['五零零零骑兵,', '三五零零步兵,', '幺八零零侍从,征战五年.']

但是我修改为“5000名骑兵，3500名步兵，1800名侍从，征战5年”，又是正常的
前端处理后的文本(每句): ['五千名骑兵,', '三千五百名步兵,', '一千八百名侍从,征战五年.']

版本[20240821v2]

**Comment by KamioRinn** [comment]
前后量词会影响数字播报

**Comment by viryaka** [comment]
有没有更智能一点的判断方法，中文数字不带量词的情况还挺多的，特别是古籍里面

**Comment by viryaka** [comment]
有没有更智能一点的判断方法，中文数字不带量词的情况还挺多的

**Comment by KamioRinn** [comment]
> 有没有更智能一点的判断方法，中文数字不带量词的情况还挺多的

古籍里带阿拉伯数字不太合适吧

**Comment by k12795g** [comment]
嘗試自己使用詞性標註改變文本，數字後面接著一個名詞的，數字改為量詞念法。

**Comment by RVC-Boss** [comment]
暂时按照楼上的解法来吧
