### ISSUE TITLE
英文和韩文输出不行，是哪里出了问题？

### ISSUE THREAD

**Issue by kingsi01** [RVC-Boss/GPT-SoVITS#1607]
生成音频时，只有英文和韩文不可以。是哪里不对？我是用整合包，然后下载的最新代码覆盖的。
![1122](https://github.com/user-attachments/assets/cd9923e3-270a-4b41-983e-a02fc63c3a14)
![2222](https://github.com/user-attachments/assets/02526d15-5eb9-4d8a-8d21-703b7ce72afd)
![2313213](https://github.com/user-attachments/assets/fa46daa4-8efe-49f0-9c67-0d31a662ab80)

**Comment by SapphireLab** [comment]
你不会是待合成文本写的中文, 然后选择英文/韩文合成吧?
这会被文本前端自动过滤掉无法合成的文本. 
本项目不自带翻译功能.

**Comment by RVC-Boss** [comment]
语种没写对

**Comment by Jicheng-han** [comment]
项目本身没有翻译功能
你如果选择英语，那就把要输出的文本，翻译成英文放在文本框里面

**Comment by kingsi01** [comment]
> 项目本身没有翻译功能
> 
> 你如果选择英语，那就把要输出的文本，翻译成英文放在文本框里面

谢谢，明白了！
