### ISSUE TITLE
使用conda命令安装GPTSovits以后，找不到install.sh文件呢，bash install.sh没办法运行

### ISSUE THREAD

**Issue by zjypp** [RVC-Boss/GPT-SoVITS#161]
conda create -n GPTSoVits python=3.9
conda activate GPTSoVits
bash install.sh

<img width="611" alt="image" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/4704158/4fb5218e-3d5d-44ce-9c4e-2dfaefa58ec5">

/Users/zhangjunying/miniconda3/envs/GPTSoVits
在这个文件夹下面找不到

**Comment by zjypp** [comment]
我使用的Python是3.11版本

**Comment by BlacknoSheep** [comment]
先克隆仓库
```bash
git clone https://github.com/RVC-Boss/GPT-SoVITS.git
```
然后依次运行
```bash
cd GPT-SoVITS
bash install.sh
```

**Comment by zjypp** [comment]
谢谢，安装成功了。
但是咋没见弹出操作的webui呢？
