### ISSUE TITLE
数字2的发音问题

### ISSUE THREAD

**Issue by flymorn** [RVC-Boss/GPT-SoVITS#1612]
·首先，'2+序数'时读作二，如二佰、二姑、二哥、二老(有第二或两位之意)。总之，作序数词时，如第二排、第二点都读作二。
·当'2+量词'时读作两，如2个苹果、2匹马、2只手、2辆车。在一长串的大数中，2的位置不同，读音也有变化。
·在千位以上的'2'读作两，百位以下的'2'读作二。如两万两千二百二拾二。

请问这个需要如何修改能适配呢？

**Comment by XXXXRT666** [comment]
用汉字

**Comment by KamioRinn** [comment]
不错的提议，已优化https://github.com/RVC-Boss/GPT-SoVITS/pull/1613
```python
text = "2佰、2姑、2哥、2老"
print(text,text_normalize(text))
#2佰、2姑、2哥、2老 二佰,二姑,二哥,二老
text = "2个苹果、2匹马、2只手、2辆车"
print(text,text_normalize(text))
#2个苹果、2匹马、2只手、2辆车 两个苹果,两匹马,两只手,两辆车
text = "22222个"
print(text,text_normalize(text))
#22222个 二万二千二百二十二个
```

**Comment by flymorn** [comment]
收入 2000 万，这里读成了 二千万，正确的应该读：两千万吧
这个也能适配下么

**Comment by KamioRinn** [comment]
> 收入 2000 万，这里读成了 二千万，正确的应该读：两千万吧； text = "22222个" print(text,text_normalize(text)) #22222个 二万二千二百二十二个 ----> 应该读成 两万两千二百二拾二
> 
> 这个也能适配下么

数字开头按照中文规则的话“二”和“两”都是合法的吧，但是数字中间是不会冒出“两”的才对，现在这个修改后的读法也是合法的。

**Comment by RVC-Boss** [comment]
已合并
