### ISSUE TITLE
在批量ASR时出现报错：funasr-pipeline is not in the pipelines registry group auto-speech-recognition

### ISSUE THREAD

**Issue by antlulu** [RVC-Boss/GPT-SoVITS#162]
ModelScope 库已经被正确地升级到最新版本，我也尝试降到pip install modelscope==1.8.0仍然报错

**Comment by kexul** [comment]
+1

**Comment by LauraGPT** [comment]
Please update with this pr:

https://github.com/RVC-Boss/GPT-SoVITS/pull/135

**Comment by antlulu** [comment]
修改后依然如故

**Comment by Chaunice** [comment]
貌似是版本不匹配的问题，我尝试：
pip install funasr==0.8.7
pip install modelscope==1.10.0
后，可以正常运行了。

**Comment by Lion-Wu** [comment]
实测pip install funasr==0.8.7可以解决问题

**Comment by cugb1004101218** [comment]
第25行改成即可：
text = inference_pipeline(input="%s/%s"%(dir,name))[0]["text"]

**Comment by LauraGPT** [comment]
Solution : https://github.com/RVC-Boss/GPT-SoVITS/issues/194#issuecomment-1910205929
