### ISSUE TITLE
AutoDL打开TTS推理时出现RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory报错

### ISSUE THREAD

**Issue by AndySterling** [RVC-Boss/GPT-SoVITS#1622]
用的是v14版本，GPU是Tesla T4
![image](https://github.com/user-attachments/assets/e9bb8a37-750c-4eb2-9377-dbb029be4ebd)
![image](https://github.com/user-attachments/assets/5a36a113-273e-48a0-afaf-7859f409ede2)

**Comment by RVC-Boss** [comment]
训练存的模型文件没存全，建议检查硬盘剩余空间，然后接着上次（相同实验名，保存了logs文件夹没删东西就行）进度往后训一个epoch吧
