### ISSUE TITLE
Need help exporting model for new language

### ISSUE THREAD

**Issue by justinjohn0306** [RVC-Boss/GPT-SoVITS#1626]
@RVC-Boss @XXXXRT666  I've trained the Spanish model by fine-tuning the base model on a 24-hour single-speaker dataset. I want to know how to export the GPT and SoVITS models so that they can be used as base models for future fine-tuning. I've attached the outcomes of the model as well, just  in case. 

Input Audio: http://sndup.net/xgzbs

Result: http://sndup.net/ydtmm     <----  Navy seals copypasta translated in Spanish 

Edit: Also, during the inference I noticed that cross-language synthesis is no longer supported. What did I miss here?

**Comment by justinjohn0306** [comment]
I think I wanna save the ``scaler_state_dict`` for the SoVITS model

**Comment by justinjohn0306** [comment]
Seems like the model has lost previous info from the base model, meaning you won't get a decent sounding model with a small dataset.

**Comment by RVC-Boss** [comment]
You can use torch.load to read the keys of the pretrained model and the finetuned model, and then manipulate the keys to align the keys of the finetuned model with the format of the pretrained model's keys.
The weights file is just a python ordereddict.

pretrained:
torch.load("s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt",map_location="cpu").keys()
torch.load("s2G2333k.pth",map_location="cpu").keys()
fine tuned:
torch.load("logs/logs_s2/G_233333333333.pth,map_location="cpu").keys()
torch.load("logs/logs_s2/D_233333333333.pth,map_location="cpu").keys()
torch.load("logs/logs_s1/ckpt/epoch=14-step=45.ckpt,map_location="cpu").keys()
torch.load("SoVITS_weights_v2/e16_s224.pth,map_location="cpu").keys()
torch.load("GPT_weights_v2/e15.ckpt,map_location="cpu").keys()
