### ISSUE TITLE
请大佬们帮忙看看，日语训练文本内容，无中文绝对路径怎么还是RuntimeError: Failed to initalize Mecab报错

### ISSUE THREAD

**Issue by ac96917** [RVC-Boss/GPT-SoVITS#1631]
![c74b798e91a29ebeee25587854f8028d](https://github.com/user-attachments/assets/c75d35a6-00cb-4463-bfed-736b033bcf85)

**Comment by XXXXRT666** [comment]
注释掉user_dict的加载

**Comment by ac96917** [comment]
> 注释掉user_dict的加载

![e59b6f0098bf76284b28fc4146e0150d](https://github.com/user-attachments/assets/c14a00b4-d42f-4325-8268-a5c9803fb452)
![862a61b63f1274ee868e50623336a2f1](https://github.com/user-attachments/assets/e699781d-3d8e-4f0e-a56e-809be6473be7)
请问是这样吗？感觉我弄错了，又报错别的了

**Comment by ac96917** [comment]
> 注释掉user_dict的加载

好了好了，谢谢大佬

**Comment by IgnatAy** [comment]
求助，问题是怎么解决的？

**Comment by yangyanglamb** [comment]
感谢

**Comment by yangyanglamb** [comment]
> 求助，问题是怎么解决的？

vs code打开项目，搜japanese.py文件，文件内搜上面提到的user_dict ，把这两行if语句开头都加上井号（#），显示绿色就是注释掉了。ctrl s保存，重启程序

**Comment by wooo123** [comment]
> > 求助，问题是怎么解决的？
> 
> vs code打开项目，搜 japanese.py 文件，文件内搜上面提到的user_dict ，把这两行if语句开头都加上井号（#），显示绿色就是注释掉了。ctrl s保存，重启程序

求助，这样还是不行啊大佬，显示IndentationError:unexpected indent 而且我这里user_dict 前面有三行if开头的，我都加了井号注释掉了

**Comment by wooo123** [comment]
求助，这样还是不行啊大佬，显示IndentationError:unexpected indent
