### ISSUE TITLE
训练用的语音，如果每条都有很多好几秒的静音，会造成影响吗？

### ISSUE THREAD

**Issue by douxuebuhui** [RVC-Boss/GPT-SoVITS#1632]
训练用的语音，如果每条都有很多好几秒的静音，会造成影响吗？

如果使用“语音切割”把文本切乱了，会影响最终效果吗？

如果切的语音太零散呢？

**Comment by RVC-Boss** [comment]
你切割了文本，原有的长文本就没用了，重新asr或者打标吧
如果整体很长并且有静音：需要切
