### ISSUE TITLE
训练结果和采样率有关系吗

### ISSUE THREAD

**Issue by katana8188** [RVC-Boss/GPT-SoVITS#1636]
我看到默认都会把音频改成32000，单声道，如果使用高一些的采样率音频进行训练，比如44100 48000会不会影响模型的效果？

昨天训练了一个模型，使用纯手动切分的，响度统一，双声道44100。结果训练出来的模型每句话都会有破音，是不是和采样率有关系呢？ 还是双声道的原因。

**Comment by XXXXRT666** [comment]
训练方法？

**Comment by katana8188** [comment]
> 训练方法？

就是正常的训练，没有用slicer，用au标记片段直接导出的，，，我把片段都改成单声道，重新训练了一下就没有了。

**Comment by katana8188** [comment]
> 那不还是32k

嗯呐
