### ISSUE TITLE
使用Webui无法推理合成粤语文本

### ISSUE THREAD

**Issue by ViceAdmiralGrafSpee** [RVC-Boss/GPT-SoVITS#1646]
![aa2d18b3-01fe-4ba7-8493-b2f5646e487f](https://github.com/user-attachments/assets/00b90b6b-0fc0-4912-bb46-faa39327b5a8)
如图所示，前端处理后的文本显示为空，最后会直接输出参考文本内容（甚至是以日语合成一遍而不是粤语），我知道之前有个issue（主分支api_v2无法合成粤语 #1535）是类似的问题，不过他好像启动方式和我不一样，而且他的webui是正常的
我本人对代码一类的一窍不通，也不知道还需要上传其他什么东西，还望大佬解决问题时能讲明白一些我需要提供什么东西，在此先行谢过

**Comment by ViceAdmiralGrafSpee** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/issues/1535#issue-2485733318
和我问题类似但又不完全相同的issue是这一条

**Comment by XXXXRT666** [comment]
不会改代码就先别用快速推理

**Comment by ViceAdmiralGrafSpee** [comment]
> 不会改代码就先别用快速推理

多翻了下之前的issue，是我没更新的问题，检查#1558之后解决问题了
我没用快速推理，这个是用的webui界面
不过还是感谢大佬拨冗解答

**Comment by XXXXRT666** [comment]
这个就是快速推理

**Comment by ViceAdmiralGrafSpee** [comment]
> 这个就是快速推理

是指勾选的那个并行推理版本吗
