### ISSUE TITLE
希望可以增加训练结果的保存

### ISSUE THREAD

**Issue by ZDY321** [RVC-Boss/GPT-SoVITS#1649]
每次花费了时间训练完魔性，希望可以把模型结果保存，方便下次直接使用。不然每次都要重复训练使用，挺浪费时间的。（感谢作者，效果真的很好）

**Comment by XXXXRT666** [comment]
？？？
建议再看看

**Comment by ZDY321** [comment]
> ？？？ 建议再看看

是有这个功能我没找到吗？在哪里啊，望告知下[笑哭]

**Comment by XXXXRT666** [comment]
推理
