### ISSUE TITLE
默认生成的是32000采样率 16位 单通道的音频，请问需要调节哪些内容可以让生成16000采样率的音频

### ISSUE THREAD

**Issue by CnYiXiaoNaiHe** [RVC-Boss/GPT-SoVITS#1650]

**Comment by neuxys** [comment]
生成好音频了做个重采样不就好了

**Comment by mzdk100** [comment]
他的意思可能是觉得直接生成16K的音频可能速度更快。

**Comment by XXXXRT666** [comment]
不支持原生16k

**Comment by XXXXRT666** [comment]
> 他的意思可能是觉得直接生成16K的音频可能速度更快。

不会有显著差别

**Comment by mzdk100** [comment]
其实我也挺想要原生16k，这样在网络传输也占优势，不需要重新采样。

**Comment by RVC-Boss** [comment]
问下chatgpt，关键词“重采样”

**Comment by CnYiXiaoNaiHe** [comment]
> 其实我也挺想要原生16k，这样在网络传输也占优势，不需要重新采样。

我们两个所需的需求是一样的 ，我就是这个意思，原生16000减少生成数据，减小系统引用延迟
