### ISSUE TITLE
二次训练每次都要增加轮数，但是作者说轮数有上限，那么进行多次累加训练，肯定会超过最大轮数的

### ISSUE THREAD

**Issue by neuxys** [RVC-Boss/GPT-SoVITS#1651]
https://github.com/RVC-Boss/GPT-SoVITS/wiki/%E4%BA%8C%E6%AC%A1%E8%AE%AD%E7%BB%83(continue-training-using-another-dataset)
作者在上文中说的：

> （4）调整比上次更高的s1和s2的epoch训练轮数点击训练，会接着上次训练的A模型的检查点继续往下训练到更大的轮数。

这里说调整比上次更高训练轮数，但是在第二点里说到：

> （1）除非的训练集非常多的情况下才会需要用到更大的轮数，如果训练集比较少，训练比默认上限更大的轮数效果可能会下降；

这里说轮数超过上限性能会下降。

所以，如果多次累加训练，总有一天会超过最大轮数的啊。是不是我理解错误了？？

**Comment by SapphireLab** [comment]
第一句说的是如何继续训练。
WebUI 有一个预置了上限的 Epoch 数比如 15，也就是通过滑块调节的地方。
假设你之前训练模型使用的 Epoch = 10：
- 如果调高到大于原来的训练 Epoch 数，比如 15，训练轮数会从 10 开始到达 15，而不是从 10 开始增加 15 变成 25；
- 如果调低到小于原来的训练 Epoch 数，比如 5，那就会跳过训练过程，因为模型已经训练过这么多轮了。

第二句说的是为什么预设了训练轮数的上限，这主要是从数据量的角度考虑的。
而且这里的用词不是你写的“轮数超过上限性能就会下降”，是“可能”。更多的需要自行对比多个检查点组合。
这个看具体实践，如果低 Epoch 就能达到你想要的效果，那也就不必训练更多。
当你需要突破这个上限的时候，例如训练集非常大，那你需要自己改一下 WebUI 的代码以提高滑块的上限。

**Comment by RVC-Boss** [comment]
![image](https://github.com/user-attachments/assets/6245a6d4-5e8b-442b-8484-d1fa516a0a2f)

这里说轮数超过上限性能会下降：训练集小才会下降，你的阅读理解出现了偏差。
多次累加训练，总有一天会超过最大轮数的：你可以设置一个大到完全不可能训完的滑块最大值，因此可以不超过。

**Comment by neuxys** [comment]
是我的理解出现了偏差
