### ISSUE TITLE
利用云端生成好的模型,然后在本地生成文件到语音,需要GPU强大的电脑吗?

### ISSUE THREAD

**Issue by topmask** [RVC-Boss/GPT-SoVITS#1662]
利用云端生成好的模型,然后在本地生成文件到语音,需要GPU强大的电脑吗?电脑性能不好

我想知道,生成模型需要一个强大的GPU.那么,利用生成好的模型在生成语音也需要强大的GPU,还是不需要.

**Comment by RVC-Boss** [comment]
N卡强大推理速度更快，推荐2060起步。
