### ISSUE TITLE
我导入参考音频,却无法播放,哪里的问题??

### ISSUE THREAD

**Issue by kawae0709** [RVC-Boss/GPT-SoVITS#1664]
我导入参考音频,却无法播放,哪里的问题??

**Comment by SapphireLab** [comment]
<img src="https://github.com/user-attachments/assets/965fe8da-38ad-44d8-a277-eeaed0830dcf" width="300">

**Comment by XXXXRT666** [comment]
> <img src="https://github.com/user-attachments/assets/965fe8da-38ad-44d8-a277-eeaed0830dcf" width="300">
> 
> 

草
