### ISSUE TITLE
api.py接口文件中，inp_refs参数的作用

### ISSUE THREAD

**Issue by Downupanddownup** [RVC-Boss/GPT-SoVITS#1677]
![image](https://github.com/user-attachments/assets/363c2aec-ea08-41ce-920f-24ad2e142e39)
请问inp_refs这个参数是起什么作用的？我看接口上没什么说明

**Comment by einsqing** [comment]
多个参考音频

**Comment by Downupanddownup** [comment]
> 多个参考音频

是指可以将多个参考音频融合为一个参考音频，然后引导生成？还是指别的？每个参考音频各自起什么作用呢？和单个参考音频相比，有什么好处吗？

**Comment by luxiongx** [comment]
原本参考音频是10s内，切割后使用这个参数可以完成上传10s以上音频的目的

**Comment by XXXXRT666** [comment]
音色融合,跟参考音频长度无关,多余参考不经过AR

**Comment by Downupanddownup** [comment]
> 音色融合,跟参考音频长度无关,多余参考不经过AR

好的，明白了
