### ISSUE TITLE
version:GPT-SoVITS-v2-240821,无法使用uvr5

### ISSUE THREAD

**Issue by yusakutaon** [RVC-Boss/GPT-SoVITS#1684]
错误信息：Traceback (most recent call last):
  File "D:\Program Files\GPT-SoVITS-v2-240821\tools\uvr5\webui.py", line 47, in uvr
    elif model_name == "Bs_Roformer" or "bs_roformer" in model_name.lower():
AttributeError: 'list' object has no attribute 'lower'
[使用的是懒人包，改转wav文件仍然是这个报错，未安装python，文档上没找到
![螢幕擷取畫面 2024-10-11 171032](https://github.com/user-attachments/assets/874bfed0-1a8f-4c65-95b8-de6fd09876ac)

**Comment by RVC-Boss** [comment]
![image](https://github.com/user-attachments/assets/0545f98e-92f1-4f5d-a2e3-9063a2d0a342)

模型没选
