### ISSUE TITLE
请问模型微调训练到底训练的是什么？

### ISSUE THREAD

**Issue by douxuebuhui** [RVC-Boss/GPT-SoVITS#1692]
请问模型微调训练到底训练的是什么？

训练素材不可能全是标准普通话，里面有字音不准确，但不是每次读那个字的时候都不准。
所以我打标到底应该写对的字，还是换成发音不准确的同音字？

**Comment by fuxiao-zhang** [comment]
不是专业搞语音这块的
我的理解是：微调的模型是学习素材中的发音方式，比如，素材中 “福建人”的语音都是“hu建人”，那么你合成的语音肯定也是按照“hu建人”这么发音。这种情况你不能把”福建人“的文本改成“胡建人“。

**Comment by douxuebuhui** [comment]
> 不是专业搞语音这块的 我的理解是：微调的模型是学习素材中的发音方式，比如，素材中 “福建人”的语音都是“hu建人”，那么你合成的语音肯定也是按照“hu建人”这么发音。这种情况你不能把”福建人“的文本改成“胡建人“。

如果素材在某些句子的读音是标准的“福建人”，有些句子是“hu建人”怎么办？

**Comment by fuxiao-zhang** [comment]
> > 不是专业搞语音这块的 我的理解是：微调的模型是学习素材中的发音方式，比如，素材中 “福建人”的语音都是“hu建人”，那么你合成的语音肯定也是按照“hu建人”这么发音。这种情况你不能把”福建人“的文本改成“胡建人“。
> 
> 如果素材在某些句子的读音是标准的“福建人”，有些句子是“hu建人”怎么办？

要是人工筛选数据集成本高，那就多轮训练后，选个效果好的就ok了

**Comment by Chi8wah** [comment]
个人理解，微调就是让模型学习这个人的音色和说话方式。对于问题来说：如果你希望他时准时不准，那就不删除不准的音频，在打标时输入对的字。如果你希望他总是不准，那就删掉准的音频，打标时输入对的字。如果你希望他总是准，那就删掉不准的音频。

**Comment by douxuebuhui** [comment]
> > > 不是专业搞语音这块的 我的理解是：微调的模型是学习素材中的发音方式，比如，素材中 “福建人”的语音都是“hu建人”，那么你合成的语音肯定也是按照“hu建人”这么发音。这种情况你不能把”福建人“的文本改成“胡建人“。
> > 
> > 
> > 如果素材在某些句子的读音是标准的“福建人”，有些句子是“hu建人”怎么办？
> 
> 要是人工筛选数据集成本高，那就多轮训练后，选个效果好的就ok了

如果训练素材不包含某些拼音，会造成读这些拼音时音色音调不准确吗？
如果我增加不包含这些拼音的素材时长，还有意义吗？

**Comment by douxuebuhui** [comment]
> 个人理解，微调就是让模型学习这个人的音色和说话方式。对于问题来说：如果你希望他时准时不准，那就不删除不准的音频，在打标时输入对的字。如果你希望他总是不准，那就删掉准的音频，打标时输入对的字。如果你希望他总是准，那就删掉不准的音频。



还有想问下如果中文素材里出现英文单词或者英文字母，打标的时候是要标英文吗？训练的时候能不能正常识别？

**Comment by Chi8wah** [comment]
> > 个人理解，微调就是让模型学习这个人的音色和说话方式。对于问题来说：如果你希望他时准时不准，那就不删除不准的音频，在打标时输入对的字。如果你希望他总是不准，那就删掉准的音频，打标时输入对的字。如果你希望他总是准，那就删掉不准的音频。
> 
> 还有想问下如果中文素材里出现英文单词或者英文字母，打标的时候是要标英文吗？训练的时候能不能正常识别？

你还真问倒我了，应该能识别吧。这我就不确定了

**Comment by RVC-Boss** [comment]
训练你目标说话人的音色，让他更加接近。不训练那只有90%的底子，基于这个底子微调就能很快达到非常像的你需要的音色。
