### ISSUE TITLE
为什么我的ASR任务已经完成但是文件夹里面就是没有没有list文件呢

### ISSUE THREAD

**Issue by sharzoy** [RVC-Boss/GPT-SoVITS#1695]
为什么我的ASR任务已经完成但是文件夹里面就是没有没有list文件呢
![6aab9ef380e5b3ec14fe1934b72fe1a](https://github.com/user-attachments/assets/38b1df94-36ec-42e9-94b0-6952aea8dd98)

**Comment by XXXXRT666** [comment]
subfix webUI接受一个list路径

**Comment by sharzoy** [comment]
> subfix webUI接受一个list路径

emmmmm。。。。咋接受呢。。。对于代码完全小白TAT

**Comment by RVC-Boss** [comment]
路径写错了，确保文本框输入的结尾是.list

**Comment by sharzoy** [comment]
> 路径写错了，确保文本框输入的结尾是.list

![屏幕截图 2024-10-18 231635](https://github.com/user-attachments/assets/ddaa06ed-ef42-4ea8-b544-9de15619a7fb)
尝试过了，还是不行TAT

**Comment by XXXXRT666** [comment]
说明没有这个文件

**Comment by XXXXRT666** [comment]
你的ASR模型有问题，解压出问题了吧

**Comment by sharzoy** [comment]
> 你的ASR模型有问题，解压出问题了吧

谢谢谢，重新解压了一遍，解决了~
