### ISSUE TITLE
日语音源一键三连总是报错

### ISSUE THREAD

**Issue by AkebiKomichi** [RVC-Boss/GPT-SoVITS#1698]
![image](https://github.com/user-attachments/assets/c47fff65-bd9f-47b8-b87b-e548e9c65fb9)

花儿不哭大佬，如图所示，我使用纯日语音源，在asr中选择largev3模型，float32精度，无论选择日语还是自动识别语种，都会在一键三连时出现报错。asr运行时没有报错。反复运行asr，和重新解压软件之后，还是出现相同的结果，麻烦您有空处理一下》

![image](https://github.com/user-attachments/assets/89e08c03-473d-49ed-92eb-bde29104b905)
![image](https://github.com/user-attachments/assets/fe05dbd2-b705-47e1-9830-e0872fa6cba1)

如上图所示，一键三连每次都复现1a文本获取进程失败，每次报缺少两个文件的错误，每次进程数字名字都不一样。
系统配置：r9000p，7945hx，4060,96g双通道内存。win10 专业版X64.

**Comment by AkebiKomichi** [comment]
只有日语音源会出现这个问题，普通话、英文不会出现

**Comment by AkebiKomichi** [comment]
只有日文音源会出现这个问题，普通话，英文使用同样的asr设置不会出现

**Comment by AkebiKomichi** [comment]
只有日文音源才会出现这个问题，普通话，英文使用同样的asr设置不会出现

**Comment by XXXXRT666** [comment]
中文路径

**Comment by AkebiKomichi** [comment]
中英文音源也使用了中文路径，能顺利导出音频，这是咋回事？

**Comment by RVC-Boss** [comment]
> 中英文音源也使用了中文路径，能顺利导出音频，这是咋回事？

有个日文库不支持，中英的没用这个日文库

**Comment by XXXXRT666** [comment]
而且中文路径删掉之后还要更新代码

**Comment by AkebiKomichi** [comment]
> 还有中文删掉之后更新代码

感谢大佬，已经可以正常使用了，日语音源用纯中文路径功能也能正常，我用最新的main替换了花儿不哭大佬度盘20240821程序中所有文件，就能无bug正常推理了

**Comment by AkebiKomichi** [comment]
> > 中英文音源也使用了中文路径，能顺利恢复音频，这是咋回事？
> 
> 有一个日文库不支持，中英的没用这个日文库

好的大佬

**Comment by AkebiKomichi** [comment]
> > 中英文音源也使用了中文路径，能顺利恢复音频，这是咋回事？
> 
> 有一个日文库不支持，中英文的没用这个日文库

好的，谢谢大佬
