### ISSUE TITLE
Colab meet FileNotFoundError

### ISSUE THREAD

**Issue by huangjch0** [RVC-Boss/GPT-SoVITS#17]
I have installed all the environment dependencies, which can be used on ubuntu system, It works well on ubuntu, but it can't be used on colab. I found that it can't find users.pth, but in the ubuntu, it is in the directory of python.

> this is the error information in colab, how can i fix it. 

```
    with open("%s/users.pth"%(site_packages_root),"w")as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/GPT-SoVITS/runtime/Lib/site-packages/users.pth'
```

**Comment by RVC-Boss** [comment]
Fixed now.
