### ISSUE TITLE
关于 GPT-SoVITS 模型原理的询问

### ISSUE THREAD

**Issue by CamellIyquitous** [RVC-Boss/GPT-SoVITS#1701]
大家好，我是一名目前在研究 TTS 的学生。
请问 GPT-SoVITS 哪里有相关的模型结构或者实现细节的原理介绍呢？之前看到有人说 GPT-SoVITS ≈ VITS + VALL-E 是否正确呢？
由于我个人水平有限，只看代码可能无法完全理解一些设计。个人想深入学习一下原理，非常感谢！

**Comment by Chi8wah** [comment]
可以看下作者[花佬](https://space.bilibili.com/5760446)的视频？还有另一个up做了一个简短的[分析](https://www.bilibili.com/video/BV1p1421r7mZ)。仅供参考

**Comment by CamellIyquitous** [comment]
> 可以看下作者[花佬](https://space.bilibili.com/5760446)的视频？还有另一个up做了一个简短的[分析](https://www.bilibili.com/video/BV1p1421r7mZ)。仅供参考

感谢感谢，但是这两个我都看过了QAQ~

**Comment by Chi8wah** [comment]
> > 可以看下作者[花佬](https://space.bilibili.com/5760446)的视频？还有另一个up做了一个简短的[分析](https://www.bilibili.com/video/BV1p1421r7mZ)。仅供参考
> 
> 感谢感谢，但是这两个我都看过了QAQ~

那我也没其他建议了，毕竟我也只是个小白用户hh

**Comment by XXXXRT666** [comment]
[1](https://www.icloud.com/iclouddrive/061am03ZJsG7OYulBOJd4eSwg#GPT-Sovits)

可供参考，别人写的

**Comment by XXXXRT666** [comment]
可以去看看项目的credits

**Comment by CamellIyquitous** [comment]
> [1](https://www.icloud.com/iclouddrive/061am03ZJsG7OYulBOJd4eSwg#GPT-Sovits)
> 
> 可供参考，别人写的

感谢！！！

**Comment by XXXXRT666** [comment]
https://github.com/NaruseMioShirakana/DragonianVoice/blob/master/libdlvoicecodec/analyse/GptSoVits.md

**Comment by CamellIyquitous** [comment]
> https://github.com/NaruseMioShirakana/DragonianVoice/blob/master/libdlvoicecodec/analyse/GptSoVits.md

感谢大佬！辛苦~

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/wiki/%E4%BB%8E%E9%9B%B6%E8%AE%AD%E7%BB%83(train-from-scratch)
全有

**Comment by hxypqr** [comment]
VQ+AR+SoVits

VQ是用来编码的，相当于得到一个发音表
把内容和音色结合起来的是AR，因为用的是transformer架构所以用的gpt代指，这个部分是可以优化的，一个人的音色在不同的场景下会有变化，可以用一个low rank数据流形而不是一个向量刻画会更逼真
SoVits是用来解码的把中间特征实现成一段音频

和下面这篇经典之作原理非常类似，核心之处就在于如何给出没见过的信息的合理的采样
https://arxiv.org/abs/1308.0850

**Comment by XXXXRT666** [comment]
这不是transformer吗？不是RNN
