### ISSUE TITLE
两步训练的疑惑

### ISSUE THREAD

**Issue by MLrookie** [RVC-Boss/GPT-SoVITS#1702]
作者大佬你好，感谢大佬对开源tts做出的贡献！

我在训练微调gpt-sovits时有一些疑惑，烦请大佬帮忙解答一下。

就是在训练过程中，gpt和sovits模型是分开独立训练的，但是gpt的音频token是基于sovits里的rvq模块去获取的，这样两个模型之间会存在着耦合，分开独立训练是否会有影响呢？

比方说，我现在有GPT和vits的预训练参数gpt.pt和vits.pt，然后我在训练gpt模型的时候用的是vits.pt里的RVQ提取音频token,同时我又基于vits.pt去训练新的vits模型，这里新的vits模型里的RVQ应该跟原始的vits.pt里的RVQ对应不上了，所以我觉得分开训练应该是会有影响的，不知道这样理解对不对？

**Comment by XXXXRT666** [comment]
RVQ不训练

**Comment by XXXXRT666** [comment]
即使训练影响也不算大，以前没有把rvq完全freeze

**Comment by MLrookie** [comment]
> RVQ不训练

感谢大佬，懂了懂了。

**Comment by RVC-Boss** [comment]
默认配置是冻结vq encoder的，你可以在s2.json里面的freeze设置为False开启训练vq
