### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'logs/xxx/2-name2text-0.txt

### ISSUE THREAD

**Issue by boyin3** [RVC-Boss/GPT-SoVITS#1705]
电脑配置：
<img width="492" alt="image" src="https://github.com/user-attachments/assets/3b2c2c72-f83a-4f3d-9d45-5b4e92969612">

页面效果：
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/577a4bb7-8e5a-4bf2-b178-cd6b71d6d26e">

点击一键三连出现报错：
<img width="609" alt="image" src="https://github.com/user-attachments/assets/c87f8b0d-6b92-467e-abce-229ce012d448">

请问这个该如何解决？

**Comment by zhouying3** [comment]
怎么解决的？
