### ISSUE TITLE
请问如果训练素材里不包含某些音素，训练出来的模型能发出相应读音吗？

### ISSUE THREAD

**Issue by douxuebuhui** [RVC-Boss/GPT-SoVITS#1708]
请问如果训练素材里不包含某些音素，训练出来的模型能发出相应读音吗？

比如训练素材里没有“sou”这个音素，
我想通过增加不含这个音素的训练素材，让模型发出的这个音素的音，并且音色与训练素材很像，能行吗？

或者说，只要训练素材里没有“sou”这个音素，无论增加多少素材都没用？

**Comment by L-jasmine** [comment]
音素表里面没有 sou 这个音素。如果是拼音的话，它是会被分成 s 和 ou 两个音。你的素材里面应该会有这两个音

**Comment by RVC-Boss** [comment]
一个素材有su，另一个素材有kou，也行
