### ISSUE TITLE
关于在VCTK数据集上评估 GPT-SoVITS 性能指标的咨询

### ISSUE THREAD

**Issue by CamellIyquitous** [RVC-Boss/GPT-SoVITS#1709]
大家好，我是
----
我的使用环境是Windows连接linux服务器。
我下载好了VCTK数据集，有很多ground truth参考音频文件，同时也有参考音频的对应text。
----
我现在想直接采用GPT-SoVITS v2的预训练模型，采用数据集中的ground truth音频作为参考音频，对应的ground truth文本作为参考文本和目标文本，进行zero-shot推理，生成predicted的目标音频。
----
我的目的是比较GPT-SoVITS生成的音频和数据集中的原ground truth音频之间的相似性，从而在VCTK数据集上评估GPT-SoVITS模型的指标。
----
请问哪位大佬可以提供一下思路我该怎么做吗（在官方仓库里我好像没有找到可以批量推理的功能）？

**Comment by XXXXRT666** [comment]
调API

**Comment by CamellIyquitous** [comment]
api_url = "http://127.0.0.1:9880/tts"
# 准备推理请求参数
params = {
    "text": text_content,  # 使用文本作为输入
    "text_lang": "en",  # 假设是英语文本
    "ref_audio_path": audio_file,  # 参考音频路径
    "prompt_lang": "en",  # 假设是英语音频
    "prompt_text": text_content,  # 使用同样的文本作为提示语
    "text_split_method": "cut5",
    "batch_size": 1,
    "media_type": "wav",
    "streaming_mode": "false"
}

try:
    # 发送 GET 请求到 API，并设置超时时间为 30 秒
    response = requests.get(api_url, params=params, timeout=30)
    



解决了，非常感谢！
