### ISSUE TITLE
sovits 模型和 gpt 模型有什么差别

### ISSUE THREAD

**Issue by SGneil** [RVC-Boss/GPT-SoVITS#1711]
我最近在做研究，想寻找sovits及gpt模型分别要用几次的epoch和多长的训练素材时长可以得到最佳的效果，但网上都找不到sovits模型代表什么，gpt模型又代表什么

**Comment by RVC-Boss** [comment]
sovits：嗓门发声维度音色
gpt：语调、韵律停顿等说话习惯维度的音色
