### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/zono50/nltk_data/taggers/averaged_perceptron_tagger_eng/averaged_perceptron_tagger_eng.weights.json'

### ISSUE THREAD

**Issue by zono50** [RVC-Boss/GPT-SoVITS#1715]
I'm trying to perform inference. I have installed NLTK and it is seeing it, but now i'm getting an error saying it can't find the weights.json file. What is the best way to install this? I installed it using Conda and it seems to run well, but can't perform inference.

我试图进行推论。 我安装了NLTK 它正在看到它 但现在我得到一个错误 说它找不到重量。 json档案. 安装这个的最佳方法是什么? 我用Conda安装了它 看起来运行良好 但无法进行推断.

**Comment by papuSpartan** [comment]
did you try this from the exception?
```
  import nltk
  nltk.download('averaged_perceptron_tagger_eng')
 ```

**Comment by zono50** [comment]
That did it, thank you
