### ISSUE TITLE
fast_inference_ 什么时候合并一下 main 呀, 这两个是分支是什么关系?

### ISSUE THREAD

**Issue by femis** [RVC-Boss/GPT-SoVITS#1731]
两个分支差异比较大, 
我想使用的 api_v3.py 在 fast_inference_分支里,
但是我看 main 是主分支, 切换分支后两边代码都不兼容!
fast_inference_ 什么时候合并一下 main 呀!

**Comment by XXXXRT666** [comment]
该分枝已废弃，早已合并

**Comment by femis** [comment]
> 该分枝已废弃，早已合并

我是在使用
api_v3.py 里面的
"tts_infer_yaml_path": “GPT_SoVITS/configs/tts_infer.yaml”  # str.(optional) tts infer yaml path
目前的 main 分支没有这个, 
所以我不确定~

**Comment by RVC-Boss** [comment]
已经合了，所以这个老分支后面不会维护了

**Comment by femis** [comment]
> 已经合了，所以这个老分支后面不会维护了

api_v3.py 是废弃了吗~
主分支上没有了
里面有个很实用的功能 
"tts_infer_yaml_path": “GPT_SoVITS/configs/tts_infer.yaml” # str.(optional) tts infer yaml path
😅

**Comment by femis** [comment]
> 已经合了，所以这个老分支后面不会维护了

在并发使用的时候, 那如何动态的修改加载的模型呢!
调用 set_sovits_weights 和 set_gpt_weights 看上去是全局的
我是新手不太懂, 请大佬解惑一下!
