### ISSUE TITLE
各位大佬，音频的时长有办法控制么？

### ISSUE THREAD

**Issue by zeushera140** [RVC-Boss/GPT-SoVITS#1737]
用的默认参数，偶尔会有产出的音频时长远远超出预期时长（本身字幕对应的时长是4秒，它你能到60多秒，肯定是有bug里面，而且speed factor没用，不能有效调节）。

我应该怎么修改参数？或者改什么其他地方？用的api_v2

` "top_k": 20,
        "top_p": 0.6,
        "temperature": 0.6,
        "text_split_method": "cut0",
        "batch_size": 1,
        "batch_threshold": 0.75,
        "split_bucket": True,
        "fragment_interval": 0.3,
        "seed": -1,
        "streaming_mode": False,
        "parallel_infer": True,
        "repetition_penalty": 1.35,`

**Comment by XXXXRT666** [comment]
speed factor

**Comment by XXXXRT666** [comment]
如果一直1500说明参考或者模型有问题

**Comment by zeushera140** [comment]
> 如果一直1500说明参考或者模型有问题

我换个参考试试看。也不是一直都有问题，我本想把一个英文视频的中文字幕文件转录为普通话版本，字幕被我分段处理，大部分分段正常生成普通话版本，但是个别有问题，时间超长。

**Comment by zeushera140** [comment]
> speed factor

谢谢，但面对这个情况，speed factor基本不能生效了，无法缩短时长。

**Comment by XXXXRT666** [comment]
模型和参考问题,我本地推理100次无任何问题

**Comment by zeushera140** [comment]
> 模型和参考问题,我本地推理100次无任何问题

参考文件有什么要求么？我用webui做了分割和降噪（无背景音乐的课程视频），但问题还是比较大。只用了官方提供的预训练模型，没自己另外训练，所以应该是参考音频的问题。
