### ISSUE TITLE
这软件收费多少钱啊？

### ISSUE THREAD

**Issue by dragonvsmagic** [RVC-Boss/GPT-SoVITS#1738]
刚开始试，然后现在需要邀请码？F5_AI社区是官方组织吗？是的话麻烦问下邀请码怎么收费？

**Comment by SapphireLab** [comment]
项目开源（没有邀请码这种东西，第三方自己改的。
直接看用户手册学习整合包教程就行。

**Comment by HuanLinOTO** [comment]
你从哪里购买的？麻烦提供相关信息

**Comment by XXXXRT666** [comment]
建议删了

**Comment by HuanLinOTO** [comment]
![image](https://github.com/user-attachments/assets/61912789-ae5f-4623-8810-23c37427ab99)
done

**Comment by dragonvsmagic** [comment]
不好意思，还以为那个是官方组织，不敢得罪，所以在这里问一下，等大大看到我的回复我就删掉

**Comment by RVC-Boss** [comment]
是免费的
楼主提到的这边不认识呢
