### ISSUE TITLE
运行api_v2.py 报错，模型权重文件和当前模型结构的尺寸不匹配

### ISSUE THREAD

**Issue by kevinlee819** [RVC-Boss/GPT-SoVITS#1748]
---------------------------------------------TTS Config---------------------------------------------
device              : cuda
is_half             : True
version             : v2
t2s_weights_path    : GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt
vits_weights_path   : GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s2G2333k.pth
bert_base_path      : GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
cnhuhbert_base_path : GPT_SoVITS/pretrained_models/chinese-hubert-base
----------------------------------------------------------------------------------------------------

Loading Text2Semantic weights from GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmp3y2bv3u0
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmp3y2bv3u0/_remote_module_non_scriptable.py
Loading VITS weights from GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s2G2333k.pth
Traceback (most recent call last):
  File "/home/api_v2.py", line 143, in <module>
    tts_pipeline = TTS(tts_config)
  File "/home/GPT_SoVITS/TTS_infer_pack/TTS.py", line 252, in __init__
    self._init_models()
  File "/home/GPT_SoVITS/TTS_infer_pack/TTS.py", line 278, in _init_models
    self.init_vits_weights(self.configs.vits_weights_path)
  File "/home/GPT_SoVITS/TTS_infer_pack/TTS.py", line 336, in init_vits_weights
    vits_model.load_state_dict(dict_s2["weight"], strict=False)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for enc_p.text_embedding.weight: copying a param with shape torch.Size([732, 192]) from checkpoint, the shape in current model is torch.Size([322, 192]).
        size mismatch for ref_enc.spectral.0.fc.weight: copying a param with shape torch.Size([128, 704]) from checkpoint, the shape in current model is torch.Size([128, 1025]).
        
        

我是用的是最新代码，基于
![image](https://github.com/user-attachments/assets/bc8e3804-ea07-4213-a249-1db68e3670e1)

，但还是出现了这个问题，请问要怎么解决啊，大佬说要使用V2代码是什么意思，能详细解释一下吗，感激不尽

**Comment by Alannikos** [comment]
请问你解决了吗？我也遇到这个问题了

**Comment by Alannikos** [comment]
请问你解决了吗？我也遇到这个问题了 @kevinlee819

**Comment by kevinlee819** [comment]
> 请问你解决了吗？我也遇到这个问题了 @kevinlee819

@Alannikos 解决了。出现这个问题的根源在于源代码里使用了过多的动态模块路径添加，这会让代码处于Python 的模块搜索路径（sys.path）中。我使用docker的时候，workspace下是没有git的，于是我在另一个目录下clone了一份代码，老代码并没有删掉。你把老代码全部删掉，重新clone就行了

**Comment by Alannikos** [comment]
@kevinlee819 好的，谢谢你
