### ISSUE TITLE
推理时，个别参考音频会导致 GPU 爆掉

### ISSUE THREAD

**Issue by BobReal0822** [RVC-Boss/GPT-SoVITS#1759]
推理的时候，同一段1500 字的文本，使用不同的参考音频，个别参考音频会导致 GPU 使用暴增，从而导致任务失败；

请问这是什么原因，有什么解决方案吗？

**Comment by RVC-Boss** [comment]
参考音频太长输出可能会异常不停生成重复的也不按照给到的文本来，同时参考音频本身的长度也消耗资源
因此webui会限制参考音频在10s以下
如果还不行继续降低参考音频时长
