### ISSUE TITLE
微调sovits，参数的含义

### ISSUE THREAD

**Issue by yc930401** [RVC-Boss/GPT-SoVITS#1761]
各位大佬好，感谢开源gptsovits这么优秀的项目！！！我在微调sovits模型，想加入更多的音色调一个通用的模型，目前感觉5-10秒音色克隆，有些人的音色还不是那么满意。目前用了800多人的音色进行微调，g total loss 不降反升，mel loss 和 fm loss也是升高的趋势。想问一下除了学习率，还需要调节哪些参数呢？图上画红框的参数是什么意思呢？调大还是调小呢？
![image](https://github.com/user-attachments/assets/856e7344-5031-462f-b728-6b92c02a08e2)
![image](https://github.com/user-attachments/assets/759d031b-cfe8-4683-90c6-d8f7cb9de922)
![image](https://github.com/user-attachments/assets/79fe2218-7e3b-4da3-a6bc-794860dcb209)
xia![image](https://github.com/user-attachments/assets/614e652a-3296-4fc0-8b20-d4ef055ab175)

**Comment by yc930401** [comment]
补充：我总共训练了200个epoch，虽然loss不降反升，但是sovits的音色生成效果还是有提升的，大概在192个epoch的时候感觉音色最像。

**Comment by XXXXRT666** [comment]
通用模型请用底膜

**Comment by RVC-Boss** [comment]
不用看loss，训练足够多的epoch，每隔一段时间听下测试集效果才是选epoch的正解。
c是2个loss的权重
第三个是微调用的，降低文本编码模块的权重
