### ISSUE TITLE
一键三连报错，求解

### ISSUE THREAD

**Issue by tntczx** [RVC-Boss/GPT-SoVITS#1772]
一键三连文本获取那一步报错，求解，报错如下：
<img width="718" alt="屏幕截图 2024-11-11 134101" src="https://github.com/user-attachments/assets/5017b890-fda0-46e2-854e-76c7ea8f09eb">

**Comment by XXXXRT666** [comment]
安装[VS运行库](https://aka.ms/vs/16/release/vc_redist.x64.exe)试试看

**Comment by tntczx** [comment]
> 安装[VS运行库](https://aka.ms/vs/16/release/vc_redist.x64.exe)试试看

成功了，谢谢大佬
