### ISSUE TITLE
这应该是个不小的问题，V2分段时会导致音频头尾部分被暴力切割掉。

### ISSUE THREAD

**Issue by jiekemt** [RVC-Boss/GPT-SoVITS#1773]
使用的是官方最新的整合包GPT-SoVITS-v2-240821

我发现生成的音频波形和频谱在分段的位置会出现断崖般的变化，比较频繁。
![image](https://github.com/user-attachments/assets/96cd6b8b-dd29-463c-91c7-1e219b84b4c0)

下图才是正常的波形变化。
![image](https://github.com/user-attachments/assets/5a6bbc9f-df5a-4de0-b2a3-7460e820e9a0)

### 播放后也能明显感觉出来，是一个音被从中截断了，每次都是切掉一点点，十分难受。

---------------------------------------------------------------------------------------------------
### 音频信息被删除，会在频谱图上有所体现。

![image](https://github.com/user-attachments/assets/8b7ab449-5f89-436d-a426-d787e10fb116)
_看这段音频的频谱图，箭头所指的位置，能发现一根细细的白色亮线。_

**我可以很简单的复现一下这种亮线，只需要使用框选工具选中频谱图，然后删除选中区域的音频信息，效果如下图。**
![image](https://github.com/user-attachments/assets/11c56f80-a8e9-4a88-9698-efaf09c48a18)
_在被删除选区的右侧生成了一根亮线，这根亮线更粗更亮，因为被删除区域原本的响度就很高。
播放这段音频，会听到一声比较刺耳的爆裂声，便是那根细线。_

**到此，基本可以判断，推理音频在分段处出现的截断和异响，要么是因为，程序在音频结尾处加入一段固定的空白分段时，会覆盖掉一部分有效信息；要么就是在插入空白分段之前，推理出的音频信息就因为某些原因被截掉了一部分。**

**感觉后者的可能性比较大，因为我发现，很多音频的最开头，也会出现一部分信息被截掉的情况。**

我想求助大佬们，如何解决这个问题？

**Comment by jiekemt** [comment]
> 使用的是官方最新的整合包GPT-SoVITS-v2-240821
> 
> 我发现生成的音频波形和频谱在分段的位置会出现断崖般的变化，比较频繁。 ![image](https://private-user-images.githubusercontent.com/171939818/384858383-31ebde7c-f335-49fb-92a4-c865cfd57e24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjAzMzksIm5iZiI6MTczMTMyMDAzOSwicGF0aCI6Ii8xNzE5Mzk4MTgvMzg0ODU4MzgzLTMxZWJkZTdjLWYzMzUtNDlmYi05MmE0LWM4NjVjZmQ1N2UyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMDEzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWVmYmY1YWM3ZjY2ZDZhOTQ0NmQ2YTc0MmQ5NGIzYjEzM2IzOTQ2ZTcyNzBlZDcxMGZlZjFhMDMwNTJlNWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SBiYBHufyIhPad8XBaPhc_he074mgH4p0_C8596uiY0) ![image](https://private-user-images.githubusercontent.com/171939818/384859361-7336a8d5-9762-486c-8c78-b8da076140b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjAzMzksIm5iZiI6MTczMTMyMDAzOSwicGF0aCI6Ii8xNzE5Mzk4MTgvMzg0ODU5MzYxLTczMzZhOGQ1LTk3NjItNDg2Yy04Yzc4LWI4ZGEwNzYxNDBiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMDEzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTJjNWY3NGMyOTFhZDgwYjYyZTZlM2YxMTdmOGMyM2U4NGZjZGQwYzE5MWI4OWI4NmNlYWZiZmVhYTFiMDBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kqG57CsT4tDFRPVp9iiVJr8g8mEdB-pStJ018GWWDXU)
> 
> 播放后也能明显感觉出来，是一个音被从中截断了，每次都是切掉一点点，十分难受。
> 
> ![image](https://private-user-images.githubusercontent.com/171939818/384862673-8b7ab449-5f89-436d-a426-d787e10fb116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjAzMzksIm5iZiI6MTczMTMyMDAzOSwicGF0aCI6Ii8xNzE5Mzk4MTgvMzg0ODYyNjczLThiN2FiNDQ5LTVmODktNDM2ZC1hNDI2LWQ3ODdlMTBmYjExNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMDEzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzczYzZjODczZjUzOGZmMTdiY2I1ZWUwYjVlNzc3ZWNiNmZjMTIyOTdjMjExZTFjMmY0ODdlZjdjMmU5ZjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u2G5DHt-e7mTdYeHDSIg_kkzxcbn30ubUyYd93MG0m0) 看这段音频的频谱图，箭头所指的位置，能发现一根细细的白色亮线。 我可以很简单的复现一下这种亮线，只需要使用框选工具选中频谱图，然后删除选中区域的音频信息，效果如下图。 ![image](https://private-user-images.githubusercontent.com/171939818/384866536-11c56f80-a8e9-4a88-9698-efaf09c48a18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjAzMzksIm5iZiI6MTczMTMyMDAzOSwicGF0aCI6Ii8xNzE5Mzk4MTgvMzg0ODY2NTM2LTExYzU2ZjgwLWE4ZTktNGE4OC05Njk4LWVmYWYwOWM0OGExOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMDEzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTk3Y2EyZGViZmM3OTMwMDg0ZjMyYTk5NjNjYzc5NzM4MzBkOTZkYzJhMTQ5MDEzNGRhN2NlMjM0YjQ5NGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SOiUKvEeZCtcvwDTAxZ7Nd_vn0NU--T1gjClbbd8LTA) 在被删除选区的右侧生成了一根亮线，这根亮线更粗更亮，因为被删除区域原本的响度就很高。 播放这段音频，会听到一声比较刺耳的爆裂声，便是那根细线。
> 
> 到此，基本可以判断，推理音频在分段处出现的截断和异响，要么是因为，程序在音频结尾处加入一段固定的空白分段时，会覆盖掉一点点有效信息；要么就是在插入空白分段之前，推理出的音频信息就因为某些原因被截掉了一部分。
> 
> 感觉后者的可能性比较大，因为我发现，很多音频的最开头，也会出现一部分信息被截掉的情况。 这种断崖状的波形变化是绝对不正常的，如下图。 ![image](https://private-user-images.githubusercontent.com/171939818/384873978-edc19020-4c0b-4a46-aeae-822042bdc9a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjAzMzksIm5iZiI6MTczMTMyMDAzOSwicGF0aCI6Ii8xNzE5Mzk4MTgvMzg0ODczOTc4LWVkYzE5MDIwLTRjMGItNGE0Ni1hZWFlLTgyMjA0MmJkYzlhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMDEzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjYxN2I5NjUwMmUwY2E0MjBlMWI1MDhiNDQwZjVlYTAzODNhOTNiY2IwNzVkZDhhY2RiMWU4MGExOTY2MDI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QNoLveflWI0EE5VRy3v-pvmDha0ZNoiAxKQnyICDDt4)
> 
> 下图才是推理音频正常的波形变化，取自一段音频分段前的部分。 ![image](https://private-user-images.githubusercontent.com/171939818/384876244-c01ca671-8988-4f5c-b6b1-2ac7f540d0d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjAzMzksIm5iZiI6MTczMTMyMDAzOSwicGF0aCI6Ii8xNzE5Mzk4MTgvMzg0ODc2MjQ0LWMwMWNhNjcxLTg5ODgtNGY1Yy1iNmIxLTJhYzdmNTQwZDBkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMDEzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDgwNWY3ZGRhYjk0OGU2MjI3MDY5YmY5MmYwY2YwOTVjYjM2YWQxZWNhMzQ2ZTk1Y2I2ZDA0NGNlMmJmMzVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.v7t2HgTvbfhOdyWg26V65QxlXGF89xr70HO8BuSY0pE)
> 
> 我想求助大佬们，如何解决这个问题？

**Comment by Chi8wah** [comment]
我是自己接了个 sileroVAD 来做切割，然后调整参数来让切割效果尽量好。whisper 的时间戳经常有莫名其妙的偏移导致一大段文字被切成一批截断的音频。。。

**Comment by Calen-J** [comment]
> 我是自己接了个 sileroVAD 来做切割，然后调整参数来让切割效果尽量好。whisper 的时间戳经常有莫名其妙的偏移导致一大段文字被切成一批截断的音频。。。 还有你这为啥开开关关的

大佬这里具体怎么操作的可以告知一下步

**Comment by Chi8wah** [comment]
> > 我是自己接了个 sileroVAD 来做切割，然后调整参数来让切割效果尽量好。whisper 的时间戳经常有莫名其妙的偏移导致一大段文字被切成一批截断的音频。。。 还有你这为啥开开关关的
> 
> 大佬这里具体怎么操作的可以告知一下步

我小白hh... 而且我这样做效率未必高，仅供参考哈。我目前是没有使用仓库自带的切分和转录能力的(虽然现在仓库貌似也是用上了  vad + whisper, 但是我原流程效果挺好我就懒得再试仓库这套流程了)

我整体流程是这样的：
收集好素材之后，会先用 silero_vad 给说话内容进行时间戳的打标，通过打标临时切割出一段段说话内容，(这里还可以接入降噪的大模型降噪之类的)，然后再逐段转码一下丢给 faster-whisper 只使用它的转文字功能进行转录，将转录后的文本和时间戳一起记录下来。
最后再通过记录的时间戳对素材进行切割存到 slicer_opt 里，再同时构造 .list 文件存到 asc_opt 里就完事了。

- 这里我有其他需求所以分了两步来搞，当然你可以合成到一起完成，效率会更高
- 另外 faster-whisper 其实自带 vad 切割，不用它自带的 vad 能力的原因主要是我发现用了 vad 之后经常出现连续好几个音频出现时间戳偏移，但我看了下 vad 的输出是准的，主要是因为 faster-whisper 合并时间戳的源码写得不好导致的(个人拙见哈，反正我是觉得迷惑代码)，所以我干脆就摘出来自己切音频了。
