### ISSUE TITLE
输出成果后没有声音。

### ISSUE THREAD

**Issue by Snowyang666** [RVC-Boss/GPT-SoVITS#1785]
可以输出结果，过程无报错，但是音频结果无声音。报错是这个，ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。系统环境：win10.NAVDIA,MX450 1G

**Comment by SapphireLab** [comment]
这卡应该和 1060 1660 之类的情况类似，把 `config.py` 文件里的半精度选项 `is_half` 设为 `False` 试试

![image](https://github.com/user-attachments/assets/09ed8232-5d13-4d32-be27-eff60109b6c1)

**Comment by Snowyang666** [comment]
没错，就是这个办法，我按照之前其他博主的处理办法解决了，但依然非常感谢你的回复。
