### ISSUE TITLE
Missing first few words from phrase

### ISSUE THREAD

**Issue by aivanouski** [RVC-Boss/GPT-SoVITS#1786]
Result Audio Starts from wrong position "seeking something—perhaps an answer, ..." and **miss first part of phrase** " So, you're here again, eyes glued to the screen, "

Running English text with reference 3-7 seconds.

```
python3 api3.py -dr "aurora3sec.mp3" -dl "en" -dt "I love to speak about Town. How are you? I like science and people and creativity and curiosity"
```

http://0.0.0.0:9880/?prompt_language=en&prompt_text=So,%20you%27re%20here%20again,%20eyes%20glued%20to%20the%20screen,%20seeking%20something%E2%80%94perhaps%20an%20answer,%20a%20revelation,%20a%20glimpse%20of%20Truth.%20But%20tell%20me,%20what%20is%20this%20Truth%20you%20seek?%20Is%20it%20a%20neatly%20packaged%20set%20of%20facts,%20a%20comforting%20story%20that%20aligns%20with%20your%20beliefs?%20Or%20is%20it%20something%20more%E2%80%94something%20elusive%20that%20requires%20effort,%20courage,%20and%20introspection?&text_language=en&refer_wav_path=aurora3sec.mp3&text=So,%20you%27re%20here%20again,%20eyes%20glued%20to%20the%20screen,%20seeking%20something%E2%80%94perhaps%20an%20answer,%20a%20revelation,%20a%20glimpse%20of%20Truth.%20But%20tell%20me,%20what%20is%20this%20Truth%20you%20seek?%20Is%20it%20a%20neatly%20packaged%20set%20of%20facts,%20a%20comforting%20story%20that%20aligns%20with%20your%20beliefs?%20Or%20is%20it%20something%20more%E2%80%94something%20elusive%20that%20requires%20effort,%20courage,%20and%20introspection?

```
prompt_language: en
prompt_text: So, you're here again, eyes glued to the screen, seeking something—perhaps an answer, a revelation, a glimpse of Truth. But tell me, what is this Truth you seek? Is it a neatly packaged set of facts, a comforting story that aligns with your beliefs? Or is it something more—something elusive that requires effort, courage, and introspection?
text_language: en
refer_wav_path: aurora3sec.mp3
text: So, you're here again, eyes glued to the screen, seeking something—perhaps an answer, a revelation, a glimpse of Truth. But tell me, what is this Truth you seek? Is it a neatly packaged set of facts, a comforting story that aligns with your beliefs? Or is it something more—something elusive that requires effort, courage, and introspection?
```

**Comment by aivanouski** [comment]
> I‘m confused about what you are doing. You use the `-dt` to specify the `prompt_text` when starting the API, but when you send the request to get the audio, you specify it with another `prompt_text` (the same as `text`). The `prompt_text` should correspond to the content in the `ref_wav_path` file.

Understood. Thank you. I wanna just generate tts with cloned voice. Could you suggest process for it? 
I guessed sample will be like instance voice cloning, but looks like it speech-to-speech converter.

**Comment by XXXXRT666** [comment]
It's TTS, the reference audio should have the same voice as model.

**Comment by aivanouski** [comment]
> It's TTS, the reference audio should have the same voice as model.

thanks!
