### ISSUE TITLE
微调sovits模型n_speaker的问题

### ISSUE THREAD

**Issue by yc930401** [RVC-Boss/GPT-SoVITS#1787]
作者您好呀，我想尝试微调一个大概几千人音色的sovits模型。前面做了5人和50人音色实验，在大概100-200个epoch就能把训练集覆盖到的音色学得很像了。但是我目前我在训练800+人音色的sovits模型，到了700个epoch，训练集的音色都还没有学得很像。不清楚是epoch还要继续增加的原因，还是s2_train中有个参数n_speakers=300这个的原因。想请教一下，是不是底模用了300人的音色训练呢？如果我想用更多人的音色，是直接改s2_train.json中的n_speakers再微调就管用嘛？还是需要重新用vits代码 https://github.com/jaywalnut310/vits 训练一个底模呢？或者用别的什么代码嘛？

**Comment by XXXXRT666** [comment]
要是我没记错的话,n_speakers没有任何用

**Comment by XXXXRT666** [comment]
用vits的代码必定报错,用这个仓库的代码,wiki里有写怎么做

**Comment by RVC-Boss** [comment]
你的情况是，人多但是样本少，不够训底模，多人一起训练也没法依赖已经训好的底模的性能
根据你的经验，建议50个人一起一个模型，训多个模型

**Comment by Chi8wah** [comment]
Hi, 请问你训50人音色的时候是怎么训的呢，是50个人的数据集全部放到一起，然后一次性训一个大的epoch；还是每个人在前一个人的基础上进行[二次训练](https://github.com/RVC-Boss/GPT-SoVITS/wiki/%E4%BA%8C%E6%AC%A1%E8%AE%AD%E7%BB%83(continue-training-using-another-dataset))，然后每个人训几十个 epoch 呀

**Comment by yc930401** [comment]
> Hi, 请问你训50人音色的时候是怎么训的呢， 是50个人的数据集全部放到一起，然后一次性训一个大的epoch； 还是每个人在前一个人的基础上进行[二次训练](https://github.com/RVC-Boss/GPT-SoVITS/wiki/%E4%BA%8C%E6%AC%A1%E8%AE%AD%E7%BB%83(continue-training-using-another-dataset))，然后每个人训几十个 epoch 呀？ 以及想请教一下你50个人的数据集里每个人的时长有多长呀？

50个人一起，每个人5分钟，训练到240轮时效果不错。

**Comment by youisan** [comment]
可以多语种一起放到一个模型里吗

**Comment by youisan** [comment]
> 作者您好呀，我想尝试微调一个大概几千人音色的sovits模型。前面做了5人和50人音色实验，在大概100-200个epoch就能把训练集覆盖到的音色学得很像了。但是我目前我在训练800+人音色的sovits模型，到了700个epoch，训练集的音色都还没有学得很像。不清楚是epoch还要继续增加的原因，还是s2_train中有个参数n_speakers=300这个的原因。想请教一下，是不是底模用了300人的音色训练呢？如果我想用更多人的音色，是直接改s2_train.json中的n_speakers再微调就管用嘛？还是需要重新用vits代码 https://github.com/jaywalnut310/vits 训练一个底模呢？或者用别的什么代码嘛？

你好，多人音色模型时，修改音色只要改动参考音频就行吗
