### ISSUE TITLE
Singing, Beatboxing and Additional Sounds

### ISSUE THREAD

**Issue by yukiarimo** [RVC-Boss/GPT-SoVITS#1789]
Hey there! I’m wondering if it’s possible to make the GPT-SoVITS-V2 sing. Specifically, I wonder if it would work if I simply input raw singing audio (without any reverb or other effects) in the same tempo and train a model on it. Could it potentially replicate the singing but with different lyrics?

Additionally, is it possible to incorporate tokens like <breathing>, <laugh>, or <scream> that can mimic non-verbal sounds?

**Comment by XXXXRT666** [comment]
You'd better look at RVC or Sovits-SVC. Most of SVC project needs F0.

**Comment by yukiarimo** [comment]
1. Yes, I know it, and I’m already doing it! But it is like making a cover of a song, but I want my TTS to sing by herself, not covering!
2. About the f0 I have a question from my Reddit post: The RVC (Retrieval-based Voice Conversion) is using something called RMVPE for the pitch extraction/guidance (also called f0). So, is it possible to make a custom f0 or extract it from audio and apply it as pitch guidance to another audio, for example, singing audio, without any voice conversion at all, just RMVPE?

**Comment by yukiarimo** [comment]
1. What about something that runs on macOS or at least not diffusion?
2. How? And is it possible for Logic Pro, too?

**Comment by XXXXRT666** [comment]
1. ACE Studio, VOCALOID, I prefer OpenUtau as it's free
2. I don’t use Logic Pro often, but I believe `Flex Pitch` or `Pitch Shifter` could be what you’re looking for.

**Comment by yukiarimo** [comment]
1. I tried, but I need something AI. Cause, it is impossible to single with a custom voice there (all voice banks are Japanese and not customizable)
2. Okay, I'll try!

**Comment by RVC-Boss** [comment]
XXXXRT666 is right

**Comment by RVC-Boss** [comment]
XXXXRT666 is right
