### ISSUE TITLE
如果我想把电视剧生成对应的英文版，训练多人模型还是单人模型更佳？

### ISSUE THREAD

**Issue by Calen-J** [RVC-Boss/GPT-SoVITS#1797]
背景：最近想将一些中文短剧用GPT来翻译成对应的英文版，采用了如下问题：
1.将每集标注角色，采用多人训练的方式，但是与基础模型相比其实提升不大？
2.我将原剧集中对应的中文语句来当参考音频，但是当存在多人说话场景、电话场景等，即使使用单人模型训练，但是还是会受到参考音频的影响，生成鬼音、噪音、中文等杂音？
3.排除2中杂音的问题，单人模型和多人模型相比似乎没有太大的提升，可能受参考音频影响太大（因为想获取原句的情绪，参考音频替换之后会导致丢失情绪）？
————————————————————————————

**Comment by XXXXRT666** [comment]
没有spk_emb，不建议多人训练

**Comment by Calen-J** [comment]
> 没有spk_emb，不建议多人训练

针对我上面说的场景，那如果我只进行单人训练的话，输出还是更多的会受到参考音频的影响，那模型微调的意义是不是就没那么大了？

**Comment by RVC-Boss** [comment]
每个角色分别单人训练每个模型吧，你的场景估计没多少样本，那么需要更多依赖底模，多人一起训练性能偏离底模更大
你音色如果需要非常非常像，那就必须微调，否则不需要
