### ISSUE TITLE
Does my data has only Chinese can few shot learning support both Chinese and English?

### ISSUE THREAD

**Issue by lucasjinreal** [RVC-Boss/GPT-SoVITS#18]
Does my data has only Chinese can few shot learning support both Chinese and English?

About 1min voice.

**Comment by RVC-Boss** [comment]
Yes you can have a try.
1min is enough, but 5min may be better

**Comment by WinterStraw** [comment]
> Does my data has only Chinese can few shot learning support both Chinese and English?
> 
> About 1min voice.

May I ask how you managed to achieve the mixed output of Chinese and English? I noticed that when I used English words the model would skip them.

**Comment by lucasjinreal** [comment]
@WinterStraw  You say **not using English words**?

**Comment by WinterStraw** [comment]
I expect to be able to do mixed output of languages. That is, a sentence contains both English and Chinese.
While doing interface work, I found that the English part was automatically skipped, and only the Chinese part was read.
Thanks a lot.

**Comment by WinterStraw** [comment]
> @WinterStraw You say **not using English words**?

I expect to be able to do mixed output of languages. That is, a sentence contains both English and Chinese.
While doing interface work, I found that the English part was automatically skipped, and only the Chinese part was read.
Thanks a lot.

**Comment by lucasjinreal** [comment]
This is unexpected @RVC-Boss

**Comment by RVC-Boss** [comment]
> > 难道我的数据只有中文，少数镜头学习可以同时支持中文和英文吗？
> > 语音约1分钟。
> 
> 请问你是如何实现中英文混合输出的？我注意到，当我使用英语单词时，模型会跳过它们。

Now it's supported now. Chinese mixing English inference.
