### ISSUE TITLE
Support for Korean language fine-tuning

### ISSUE THREAD

**Issue by Typhoon0303** [RVC-Boss/GPT-SoVITS#1807]
First of all, thank you for sharing such a good reference.

I'm wondering if Korean language fine-tuning is supported in this project. I see that Chinese (zh) language fine-tuning is supported, but I'm not certain about Korean support.

If Korean is not yet supported, would it be possible to add support for Korean language fine-tuning as well? I believe expanding the language coverage would be beneficial for Korean users who want to fine-tune models with Korean datasets.

I might have missed existing documentation or implementation about Korean support. If it's already supported, could you point me to the relevant documentation?

**Comment by XXXXRT666** [comment]
It is supported. Just do the same steps as other languages. 
And for languages except Chinese we do not extract Bert features, so 3-bert will be an empty folder

**Comment by Typhoon0303** [comment]
I couldn't proceed with the training due to my misunderstanding of the guide, but now the issue has been resolved and I've confirmed it's working properly. Thank you.
