### ISSUE TITLE
运行api_v2.py时报错CUDA不可用

### ISSUE THREAD

**Issue by pgz100** [RVC-Boss/GPT-SoVITS#1809]
运行api_v2.py时报了如下错误，但我在创建容器时，已经加上了 --gpus all 这个参数了。
Loading Text2Semantic weights from GPT_SoVITS/pretrained_models/gsv-v2final-pretrained/s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt

XXX\api_v2.py", line 151, in
tts_pipeline = TTS(tts_config)

raise RuntimeError(
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by XXXXRT666** [comment]
驱动更新一下看看?

**Comment by pgz100** [comment]
我是下载的docker镜像部署的，刚才发现本机安装的cuda版本是12.4，但docker容器里面自带的cuda版本是11.8，不知道是不是因为这两个版本不一致导致的？如果要更新驱动，应该把本地的cuda降为11.8，还是把容器里的cuda升为12.4？

**Comment by pgz100** [comment]
好的，驱动更新为12.3之后，不报这个错了
