### ISSUE TITLE
进行GPT训练或者sovits训练报“零除错误”

### ISSUE THREAD

**Issue by Hermit591** [RVC-Boss/GPT-SoVITS#181]
按照B站UP主们的教程制作好了数据集和标注以后进行训练，我制作的是灰原哀的声音模型，照着B站某位up主发布的gakki视频跟步学习。
制作数据集和文本标注用的是bert-vits2
系统是win10
python是3.10，各项依赖也都安装了
到了1B微调训练部分，不管是点击GPT训练还是sovits训练都会报错，报错内容如图所示
![零除错误](https://github.com/RVC-Boss/GPT-SoVITS/assets/58174150/97979064-d43b-4309-980a-fee55e89e947)
把报错信息发给AI，AI说是零除错误，但是这就刺穿了我的知识盲区了，我不懂。换过整合包试过，同样报这个错误。

请大佬指点

**Comment by BlacknoSheep** [comment]
如果训练语音是日语，看看标注文件（xxx.list）里第三列的“ZH”有没有改成“JA”或“ja”。

**Comment by Hermit591** [comment]
> 如果训练语音是日语，看看标注文件（xxx.list）里第三列的“ZH”有没有改成“JA”或“ja”。

是日语的训练语音，但是第三列也全都是JP了，在这种情况下报错的

**Comment by Hermit591** [comment]
> 如果训练语音是日语，看看标注文件（xxx.list）里第三列的“ZH”有没有改成“JA”或“ja”。

我在想会不会是一键三连的时候用的模型是chinese的原因，但是别人发布的视频，gakki训练的时候一键三连也是同样的默认模型，我现在就很迷茫😳

**Comment by Hardwell99** [comment]
这个问题23号已经修复，检查代码是不是最新的或是用的旧的预发布包
如果一键三连后 logs/XXX/6-name2semantic.tsv 文件没有内容，没有内容就会导致“零除错误”，就是一键三连数据集格式化阶段出错，可以仔细检查该阶段的报错信息以定位问题
另：
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/104831430/b333b294-5ad3-4628-b1f5-bc0d4f5ffa57)
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/104831430/796efa03-03de-427c-84b7-fe19606a1808)
加载不出显卡也会导致无法加载模型

**Comment by Hermit591** [comment]
> 这个问题23号已经修复，检查代码是不是最新的或是用的旧的预发布包
> 如果一键三连后 logs/XXX/6-name2semantic.tsv 文件没有内容，没有内容就会导致“零除错误”，就是一键三连数据集格式化阶段出错，可以仔细检查该阶段的报错信息以定位问题
> 另：
> ![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/104831430/b333b294-5ad3-4628-b1f5-bc0d4f5ffa57)
> ![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/104831430/796efa03-03de-427c-84b7-fe19606a1808)
> 加载不出显卡也会导致无法加载模型

有用！谢谢您的指点，我现在开始琢磨一键三连时候的问题了

**Comment by Hermit591** [comment]
一键三连阶段报错内容如图
![一键三连阶段报错](https://github.com/RVC-Boss/GPT-SoVITS/assets/58174150/5a2f6cc6-8ee0-410a-965f-27d3b9b83d30)
但是检查了“ logs/XXX/6-name2semantic.tsv ”内容，好像没啥问题，有内容，
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/58174150/bfe62fee-006e-4aa9-b4c0-9079fa29e9aa)
我还是找找最新的整合包看看

**Comment by BlacknoSheep** [comment]
@Hermit591 是“JA”或“ja”，不是“JP”

**Comment by RVC-Boss** [comment]
楼上正解。语种字符字典在readme里找。一键三连后要在logs-实验名下确认2456文件和文件夹均非空，如果为空说明前面步骤有问题。否则后续训练数据集缺文件报错除零。
