### ISSUE TITLE
如何精确控制输出音频的长度？

### ISSUE THREAD

**Issue by MonolithFoundation** [RVC-Boss/GPT-SoVITS#1813]
发现默认配置下，生成的音频长度远远大于prompt音频。

因为做字幕翻译，希望时长保持一致，现在2s的原始prompt音频， 会生成8s的目标音频。咋弄

**Comment by SiliconYC** [comment]
你是说他读太慢了，还是前后的静音部分太多了？

**Comment by MonolithFoundation** [comment]
就是指定输出音频的长度，并且严格按照这个长度输出

**Comment by RVC-Boss** [comment]
1、下载v2版本（8月起）
2、抽卡一次，符合大致的时长范围。如果距离目标时长很远就一直收或者调整预期。
3、抽完语气效果（除语速外）满意后，勾选“是否直接对上次合成结果调整语速和音色。防止随机性。”
4、调整语速
