### ISSUE TITLE
训练sovits底模，数据量问题

### ISSUE THREAD

**Issue by yc930401** [RVC-Boss/GPT-SoVITS#1820]
作者您好，请问v2模型的sovits底模：
1、您用了多少人的音色？
2、每个音色的平均时长大概多久呢？
3、sovits模型是不是跟语种没有关系？只用中文训练音色是不是也可以用于其他语言（gpt模型不训练）。
4、wiki中写的”webui微调训练微操降低了SoVITS模块文本编码器的lr，底模训练没有“，所以训练底模的话，是不是webui界面中，文本模块学习率权重从默认的0.4改为1？

**Comment by RVC-Boss** [comment]
1、未统计，多多益善
2、目前总计2kh，平均未统计
3、需要带上文本信息因此语种需要
4、对
