### ISSUE TITLE
api_v2无法生成中文外的语音

### ISSUE THREAD

**Issue by tuhang** [RVC-Boss/GPT-SoVITS#1821]
**版本号:**
commitID:5d126f98b2b1702f7e26f438c1912d13f1832a90

**请求参数:**
curl --location --request POST 'http://localhost:9880/tts' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--header 'Host: localhost:9880' \
--header 'Connection: keep-alive' \
--data-raw '{
    "text": "测试文本",
    "text_lang": "zh",
    "ref_audio_path": "xxx.wav",
    "prompt_text": "xxx.wav对应的文本内容(都是中文)",
    "prompt_lang": "zh"
}'

text_lang为zh和text不包含英文时,正常导出;

**报错请求-JSON:**
{
    "text": "test test test",
    "text_lang": "en",
    "ref_audio_path": "xxx.wav",
    "prompt_text": "xxx.wav对应的文本内容(都是中文)",
    "prompt_lang": "zh"
}

**报错栈打印:**
{
    "message": "tts failed",
    "Exception":"\n**********************************************************************\n  Resource [93maveraged_perceptron_tagger_eng[0m not found.\n  Please use the NLTK Downloader to obtain the resource:\n\n  [31m>>> import nltk\n  >>> nltk.download('averaged_perceptron_tagger_eng')\n  [0m\n  For more information see: https://www.nltk.org/data.html\n\n  Attempted to load [93mtaggers/averaged_perceptron_tagger_eng/[0m\n\n  Searched in:\n    - 'C:\\\\Users\\\\myUserName/nltk_data'\n    - 'C:\\\\Users\\\\myUserName\\\\.conda\\\\envs\\\\SoVITS\\\\nltk_data'\n    - 'C:\\\\Users\\\\myUserName\\\\.conda\\\\envs\\\\SoVITS\\\\share\\\\nltk_data'\n    - 'C:\\\\Users\\\\myUserName\\\\.conda\\\\envs\\\\SoVITS\\\\lib\\\\nltk_data'\n    - 'C:\\\\Users\\\\myUserName\\\\AppData\\\\Roaming\\\\nltk_data'\n    - 'C:\\\\nltk_data'\n    - 'D:\\\\nltk_data'\n    - 'E:\\\\nltk_data'\n**********************************************************************\n",
    "traceback":"Traceback (most recent call last):\n  File \"F:\\GPT-SoVITS\\v2\\GPT-SoVITS-v2-240821\\api_v2.py\", line 353, in tts_handle\n    sr, audio_data = next(tts_generator)\n  File \"C:\\Users\\myUserName\\.conda\\envs\\SoVITS\\lib\\site-packages\\torch\\utils\\_contextlib.py\", line 35, in generator_context\n    response = gen.send(None)\n  File \"F:\\GPT-SoVITS\\v2\\GPT-SoVITS-v2-240821\\GPT_SoVITS\\TTS_infer_pack\\TTS.py\", line 763, in run\n    data = self.text_preprocessor.preprocess(text, text_lang, text_split_method)\n  File \"F:\\GPT-SoVITS\\v2\\GPT-SoVITS-v2-240821\\GPT_SoVITS\\TTS_infer_pack\\TextPreprocessor.py\", line 65, in preprocess\n    phones, bert_features, norm_text = self.segment_and_extract_feature_for_text(text, lang, version)\n  File \"F:\\GPT-SoVITS\\v2\\GPT-SoVITS-v2-240821\\GPT_SoVITS\\TTS_infer_pack\\TextPreprocessor.py\", line 117, in segment_and_extract_feature_for_text\n    return self.get_phones_and_bert(text, language, version)\n  File \"F:\\GPT-SoVITS\\v2\\GPT-SoVITS-v2-240821\\GPT_SoVITS\\TTS_infer_pack\\TextPreprocessor.py\", line 143, in get_phones_and_bert\n    phones, word2ph, norm_text = self.clean_text_inf(formattext, language, version)\n  File \"F:\\GPT-SoVITS\\v2\\GPT-SoVITS-v2-240821\\GPT_SoVITS\\TTS_infer_pack\\TextPreprocessor.py\", line 208, in clean_text_inf\n    phones, word2ph, norm_text = clean_text(text, language, version)\n  File \"F:\\GPT-SoVITS\\v2\\GPT-SoVITS-v2-240821\\GPT_SoVITS\\text\\cleaner.py\", line 46, in clean_text\n    phones = language_module.g2p(norm_text)\n  File \"F:\\GPT-SoVITS\\v2\\GPT-SoVITS-v2-240821\\GPT_SoVITS\\text\\english.py\", line 365, in g2p\n    phone_list = _g2p(text)\n  File \"F:\\GPT-SoVITS\\v2\\GPT-SoVITS-v2-240821\\GPT_SoVITS\\text\\english.py\", line 272, in __call__\n    tokens = pos_tag(words)  # tuples of (word, tag)\n  File \"C:\\Users\\myUserName\\.conda\\envs\\SoVITS\\lib\\site-packages\\nltk\\tag\\__init__.py\", line 168, in pos_tag\n    tagger = _get_tagger(lang)\n  File \"C:\\Users\\myUserName\\.conda\\envs\\SoVITS\\lib\\site-packages\\nltk\\tag\\__init__.py\", line 110, in _get_tagger\n    tagger = PerceptronTagger()\n  File \"C:\\Users\\myUserName\\.conda\\envs\\SoVITS\\lib\\site-packages\\nltk\\tag\\perceptron.py\", line 183, in __init__\n    self.load_from_json(lang)\n  File \"C:\\Users\\myUserName\\.conda\\envs\\SoVITS\\lib\\site-packages\\nltk\\tag\\perceptron.py\", line 273, in load_from_json\n    loc = find(f\"taggers/averaged_perceptron_tagger_{lang}/\")\n  File \"C:\\Users\\myUserName\\.conda\\envs\\SoVITS\\lib\\site-packages\\nltk\\data.py\", line 579, in find\n    raise LookupError(resource_not_found)\nLookupError: \n**********************************************************************\n  Resource [93maveraged_perceptron_tagger_eng[0m not found.\n  Please use the NLTK Downloader to obtain the resource:\n\n  [31m>>> import nltk\n  >>> nltk.download('averaged_perceptron_tagger_eng')\n  [0m\n  For more information see: https://www.nltk.org/data.html\n\n  Attempted to load [93mtaggers/averaged_perceptron_tagger_eng/[0m\n\n  Searched in:\n    - 'C:\\\\Users\\\\myUserName/nltk_data'\n    - 'C:\\\\Users\\\\myUserName\\\\.conda\\\\envs\\\\SoVITS\\\\nltk_data'\n    - 'C:\\\\Users\\\\myUserName\\\\.conda\\\\envs\\\\SoVITS\\\\share\\\\nltk_data'\n    - 'C:\\\\Users\\\\myUserName\\\\.conda\\\\envs\\\\SoVITS\\\\lib\\\\nltk_data'\n    - 'C:\\\\Users\\\\myUserName\\\\AppData\\\\Roaming\\\\nltk_data'\n    - 'C:\\\\nltk_data'\n    - 'D:\\\\nltk_data'\n    - 'E:\\\\nltk_data'\n**********************************************************************\n\n",
    "request": {
        "text": "test test test",
        "text_lang": "en",
        "prompt_lang": "all_zh",
        "text_split_method": "cut5"
    }
}

用AI尝试修复,和WebUI 对比,它反馈是可能的原因包括几个
1. BERT 模型预加载
2. 词典映射
3. nltk数据缺失

---

代码是基于v2整合包下,直接pycharm在api_v2下使用debug模式运行

**Comment by XXXXRT666** [comment]
建议直接用整合包环境运行

**Comment by tuhang** [comment]
整合包环境;

**Comment by tuhang** [comment]
这种情况属于环境冲突导致nltk找不到数据吗?

**Comment by tuhang** [comment]
> 建议直接用整合包环境运行

这种情况属于环境冲突导致nltk找不到数据吗?
