### ISSUE TITLE
训练的数据集有什么要点

### ISSUE THREAD

**Issue by QWXL** [RVC-Boss/GPT-SoVITS#1827]
想问一下在录制数据集的时候有什么要点吗，除了众所周知的降噪降杂之外还有别的需要注意的吗，比如阅读的文本是否要特别准备之类的？翻了翻issues和文档似乎没看到类似的，感激不尽！

**Comment by ztdf123** [comment]
声音尽量清晰，喷麦，呼吸声，口水音尽量去一去，文本没什么讲究，数据集还是讲究宁缺勿滥。

**Comment by RVC-Boss** [comment]
以及口齿清晰，不要口吃，说话流利中气足
