### ISSUE TITLE
No module named 'tools.my_utils'

### ISSUE THREAD

**Issue by GlowingBrick** [RVC-Boss/GPT-SoVITS#1829]
启动推理Webui会出现
Traceback (most recent call last):
  File "/mnt/drive-d/AIs/GPT-SoVITS/GPT_SoVITS/inference_webui.py", line 92, in <module>
    from tools.my_utils import load_audio
ModuleNotFoundError: No module named 'tools.my_utils'

Python 3.9.20 | packaged by conda-forge 
Archlinux

**Comment by XXXXRT666** [comment]
tools不是pypi packages

**Comment by RVC-Boss** [comment]
inference_webui.py开头加上
import sys
sys.path.append("/mnt/drive-d/AIs/GPT-SoVITS")
