### ISSUE TITLE
v2到最后一步为什么不能变声啊

### ISSUE THREAD

**Issue by 2464634492** [RVC-Boss/GPT-SoVITS#1833]
![SharedScreenshot](https://github.com/user-attachments/assets/e0fc2281-0721-4b46-bf85-fa86743227be)

**Comment by SummerXIATIAN** [comment]
因为变声和克隆的原理是有点矛盾的。快速克隆要求GPT的结果token里包含说话人的声学信息（当然更主要是语义信息），帮助vits重建音色；而变声要求GPT的outputs里尽可能不带有声学信息，最好只有语义信息，然后再用纯vits来提取说话人信息变声。

**Comment by 2464634492** [comment]
请问那怎么解决啊，最后一步怎么弄啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月18日(周三) 凌晨0:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RVC-Boss/GPT-SoVITS] v2到最后一步为什么不能变声啊 (Issue #1833)




 
因为变声和克隆的原理是有点矛盾的。快速克隆要求GPT的结果token里包含说话人的声学信息（当然更主要是语义信息），帮助vits重建音色；而变声要求GPT的outputs里尽可能不带有声学信息，最好只有语义信息，然后再用纯vits来提取说话人信息变声。

**Comment by XXXXRT666** [comment]
没开放
