### ISSUE TITLE
推理时卡住了，请问是什么原因？

### ISSUE THREAD

**Issue by WeimianLI** [RVC-Boss/GPT-SoVITS#1839]
![企业微信截图_1733902520245](https://github.com/user-attachments/assets/40bcc830-5f41-4970-ba7e-6416c84cbd42)

服务收到请求后，处理过程中一直卡在这里，请问是什么原因，要怎么解决？感谢！

**Comment by adot08** [comment]
音频生成了吗？音频生成就没问题。进度条的步数被硬编码成1500了，实际上中途就停了。

**Comment by WeimianLI** [comment]
> 音频生成了吗？音频生成就没问题。进度条的步数被硬编码成1500了，实际上中途就停了。

确实是，感谢，我还以为是卡住了
