### ISSUE TITLE
api_v2.py 如何关闭推理进度条

### ISSUE THREAD

**Issue by selfnat** [RVC-Boss/GPT-SoVITS#1840]
api_v2.py 如何关闭推理进度条， 运行久了看到进度条会报错， 有开关可以直接关闭进度条的输出，或者关闭日志也可以

**Comment by selfnat** [comment]
'tqdm' object has no attribute 'sp'， 不知道什么原因会报这个

**Comment by luxiongx** [comment]
把tqdm（）删了就行。for text in tqdm(batch_texts)改成for text in batch_texts
