### ISSUE TITLE
大佬们我想训练英文的语音训练模型需要换吗？

### ISSUE THREAD

**Issue by flyice8** [RVC-Boss/GPT-SoVITS#1846]
大佬们我想训练英文的语音训练模型需要换吗？
我已经打标成功的英文的list，但是在训练的时候报告错误，是不是要换训练模型？
具体错误信息如下，谢谢！
![1](https://github.com/user-attachments/assets/fed8a76b-4c13-4260-b1ac-0d9d23b83035)
![2](https://github.com/user-attachments/assets/a4eabb8c-a4e8-4340-a6ce-fa11b98459ff)

**Comment by XXXXRT666** [comment]
根据nltk报错指示执行代码

**Comment by flyice8** [comment]
> 根据nltk报错指示执行代码

您好~nltk也没有提示怎么执行，可以教一下吗，谢谢！

**Comment by flyice8** [comment]
哦搞定了下载哪个英文的生成包就好了

**Comment by RVC-Boss** [comment]
不需要更换代码，只需要把nltk的安装搞定，一般是因为墙内下不了
