### ISSUE TITLE
文字一长就不行了吗？RuntimeError: The size of tensor a (857) must match the size of tensor b (512) at non-singleton dimension 1

### ISSUE THREAD

**Issue by gg22mm** [RVC-Boss/GPT-SoVITS#1850]
报错：
File "/home/data/miniconda3/envs/gptts/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 216, in forward
    embeddings += position_embeddings
RuntimeError: The size of tensor a (857) must match the size of tensor b (512) at non-singleton dimension 1

文本如下：

在当下这个充满变革与机遇的时代，越来越多的人开始关注创业加盟这条道路。而在众多创业平台中，咸鱼平台以其独特的魅力和优势，吸引了众多创业者的目光。那么，咸鱼平台好做吗？本文将从多个角度为您剖析咸鱼平台的创业机会与好处，助您轻松把握商机，实现财富梦想。一、咸鱼平台的市场前景广阔，咸鱼平台作为一个集二手交易、拍卖、竞拍等多功能于一体的综合性电商平台，具有巨大的市场潜力。随着人们消费观念的转变，越来越多的人开始注重资源的循环利用和价值的最大化。咸鱼平台正好迎合了这一市场需求，为广大消费者提供了一个便捷的二手交易场所。同时，随着移动互联网的普及和电子商务的快速发展，咸鱼平台的市场前景可谓一片光明。二、咸鱼平台的创业门槛低，相对于传统创业模式而言，咸鱼平台的创业门槛相对较低。无需投入大量资金购买存货、租赁场地等，只需通过简单的注册流程，即可成为咸鱼平台的创业者。此外，咸鱼平台还提供了一系列完善的营销工具和推广策略，帮助创业者快速积累人气和粉丝，降低创业风险。三、咸鱼平台的创业支持体系完善，咸鱼平台非常注重创业者的成长与发展，为创业者提供了一整套完善的支持体系。包括新手指导、培训课程、运营策略等在内的一系列服务，帮助创业者快速掌握平台运营技巧，提升经营能力。此外，咸鱼平台还与多家金融机构合作，为创业者提供低息贷款、融资担保等金融服务，助力创业者轻松实现创业梦想。四、咸鱼平台的创业回报可观，在咸鱼平台创业，只要您具备一定的市场洞察力和经营能力，就能够在短时间内获得可观的回报。随着您在平台上的信誉度不断提升，您的店铺和商品也会受到更多消费者的关注和认可。同时，咸鱼平台还定期举办各类促销活动和优惠政策，为创业者带来更多利润空间。综上所述，咸鱼平台作为一个充满机遇和优势的创业平台，不仅市场前景广阔、创业门槛低、支持体系完善，而且创业回报可观。因此，对于想要创业加盟的人士来说，咸鱼平台无疑是一个值得考虑的选择。只要您勇于尝试、敢于创新，相信在咸鱼平台上一定能够找到属于自己的创业之路，实现财富和梦想的双赢。

**Comment by XXXXRT666** [comment]
换切割方法

**Comment by gg22mm** [comment]
非常感谢 ~~

**Comment by gg22mm** [comment]
我发现 一切 情感也不统一 有这个问题 ~~
