### ISSUE TITLE
Whisper didn’t use System Agent to download | Whisper模型下载不走系统代理

### ISSUE THREAD

**Issue by Luke2049** [RVC-Boss/GPT-SoVITS#1851]
Whisper模型在整合包里没有吗？怎么要下载，我选的medium.en. float32 
我看是从hugging face下载的，这个不是要魔法吗，不走系统代理咋下的......最后 Clash 开了个TUN模式解决的 : (

**Comment by XXXXRT666** [comment]
用的是镜像站

**Comment by XXXXRT666** [comment]
hf mirror不是hf

**Comment by XXXXRT666** [comment]
hf mirror可以直连

**Comment by Luke2049** [comment]
> hf mirror可以直连

ok，我的问题😅

**Comment by RVC-Boss** [comment]
楼上正解
