### ISSUE TITLE
流式推理启动速度

### ISSUE THREAD

**Issue by ZxnSnowy** [RVC-Boss/GPT-SoVITS#1873]
使用流式推理，第一次生成比第二次生成的时间慢很多。这是什么原因呢？第一次推理会有一些警告，与这些警告有关系吗？
模型加载：
![image](https://github.com/user-attachments/assets/c7f73b39-fdd0-44e7-b7a2-140d2c038c1e)
第一次的输出：
![image](https://github.com/user-attachments/assets/ffc50128-954d-4f5e-9d09-c594603fd314)
第二次无警告：
![image](https://github.com/user-attachments/assets/38ac8c4d-84b1-48ea-b89e-54a078066c40)

**Comment by yitenghao** [comment]
不光是流式推理，只要加载模型就存在这个问题，我的理解是加载模型并没有加载起完整的模型，需要推理一次才会把一些变量对象创建好，下次推理就省了创建的步骤。所以我是改了api_v2.py，在启动api服务前随便拿个文本推理了一次，后面调用接口的耗时就正常了

**Comment by nantatian** [comment]
> 不光是流式推理，只要加载模型就存在这个问题，我的理解是加载模型并没有加载起完整的模型，需要推理一次才会把一些变量对象创建好，下次推理就省了创建的步骤。所以我是改了api_v2.py，在启动api服务前随便拿个文本推理了一次，后面调用接口的耗时就正常了

大佬可以分享一下怎么改动api_v2.py，让它先推理一次吗

**Comment by yitenghao** [comment]
> > 不光是流式推理，只要加载模型就存在这个问题，我的理解是加载模型并没有加载起完整的模型，需要推理一次才会把一些变量对象创建好，下次推理就省了创建的步骤。所以我是改了api_v2.py，在启动api服务前随便拿个文本推理了一次，后面调用接口的耗时就正常了
> 
> 大佬可以分享一下怎么改动api_v2.py，让它先推理一次吗


`def test_tts(text):
    try:
        request=TTS_Request()
        request.text=text
        req = request.dict()
        start = datetime.datetime.now()
        print(start)
        asyncio.run(tts_handle(req))
        now = datetime.datetime.now()
        time_expenses = now - start
        print(time_expenses.total_seconds())
    except Exception as e:
        print(f"An error occurred: {e}")
    return 

if __name__ == "__main__":
    try:
        if host == "None":  # 在调用时使用 -a None 参数，可以让api监听双栈
            host = None
        # print("asyncio.run")
        test_tts("现将您已出账单中9658.49元进行24期分期")
        uvicorn.run(app=APP, host=host, port=port, workers=1)
    except Exception:
        traceback.print_exc()
        os.kill(os.getpid(), signal.SIGTERM)
        exit(0)
`
