### ISSUE TITLE
请问推理时，如何增加句子间的停顿时间呢？

### ISSUE THREAD

**Issue by WinSure** [RVC-Boss/GPT-SoVITS#1881]
如何增加句子间的停顿时间呢？ 比如我要增加一秒，两秒这个样子

**Comment by RVC-Boss** [comment]
如果是非标点而是换行的不同句子，可以https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/inference_webui.py#L424把0.3提高（这个是句子之间停多少秒）
如果是每一行内部不同标点的不同句子，可以试试重复加标点

**Comment by Chi8wah** [comment]
> 重复加标点好像不行,我记得会去除重复的标点来着

对，英文的话会合并多个字符替换为首个字符，所以导致省略号相当于句号。
