### ISSUE TITLE
logs下面的文件能删吗？

### ISSUE THREAD

**Issue by Lixi20** [RVC-Boss/GPT-SoVITS#1882]
模型训练结束之后，logs下面的文件能删吗？里面的文件组成是什么样子的，主要是磁盘占用太大了。如果后续需要接着训练，有哪些文件是需要保留的，哪些文件又是可以删掉的

**Comment by XXXXRT666** [comment]
可以全删,后续需要训练的话就别删对应模型名

**Comment by Lixi20** [comment]
就是如果要接着训练，就不能删除logs下面对应的文件嘛

**Comment by Strive-for-excellence** [comment]
> 就是如果要接着训练，就不能删除logs下面对应的文件嘛

都能删，大不了重新跑数据处理就是了

**Comment by RVC-Boss** [comment]
如果要继续训练则都保留，可以跳过数据提取阶段。
如果只推理，可以删。
