### ISSUE TITLE
更新代码后训练好慢好慢

### ISSUE THREAD

**Issue by martjay** [RVC-Boss/GPT-SoVITS#191]
就今天刚刚git pull最新代码，整个训练过程好慢好慢，而且显存占用没有问题，为什么？

![6666](https://github.com/RVC-Boss/GPT-SoVITS/assets/44982189/a7e74580-090c-4dc0-9d9f-b4248b3d2c41)

**Comment by martjay** [comment]
到底是为什么呢？真的慢了很多很多，参数我都没动啊。

之前我都是2it/S，现在变成了1it/S

**Comment by martjay** [comment]
刚才我点终止训练，还蓝屏了，第一次遇到这个问题

**Comment by martjay** [comment]
我可能是在运行的时候git pull，所以有文件没有被更新，我下载完整代码覆盖后就正常了，我的问题

**Comment by RVC-Boss** [comment]
好的。
