### ISSUE TITLE
会支持中英结合语音合成吗

### ISSUE THREAD

**Issue by bank010** [RVC-Boss/GPT-SoVITS#192]

**Comment by RVC-Boss** [comment]
会

**Comment by KakaruHayate** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/pull/179

可以先试试

**Comment by bank010** [comment]
> 会

合成效果很棒，期待！！！

**Comment by bank010** [comment]
> #179
> 
> 可以先试试

ok，谢谢！

**Comment by bank010** [comment]
> > #179
> > 可以先试试
> 
> ok，谢谢！

prompt:
在未来的几天内，国内的家庭基本都会特别开心，The author does not have any control over the software.
https://github.com/RVC-Boss/GPT-SoVITS/assets/107624041/e69af4b1-3920-4a35-abc6-e2d5c67c338a

效果不错~，感觉读英文有点杂音

**Comment by XM233333333** [comment]
作者不是说了以后支持中英文混合嘛，您怎么实现一句话中实现中英文混合的？

**Comment by bank010** [comment]
> 作者不是说了以后支持中英文混合嘛，您怎么实现一句话中实现中英文混合的？

上面消息有个大佬做了一下判断，可以把文件替换一下

**Comment by RVC-Boss** [comment]
> 作者不是说了以后支持中英文混合嘛，您怎么实现一句话中实现中英文混合的？

@XM233333333 已支持，更新一下最新的代码
