### ISSUE TITLE
请问能公布一下训练集的范围吗？

### ISSUE THREAD

**Issue by metacarbon** [RVC-Boss/GPT-SoVITS#193]
我测试一下星铁和三国，发现星铁的zero-shot很不错，但是三国的zero-shot就比较差。
我认为应该训练集覆盖面的问题，请问能公布一下用了哪些数据吗？这样就能知道哪些类型的语音需要微调，哪些可以直接转了。

**Comment by RVC-Boss** [comment]
没有星铁，也没有三国
我们不保证zero shot效果的，就是个玩具，5s可能像可能不像，具体都得你自己试，通用的结论就是默认配置训练1~30min的训练集都可以得到不错的效果。
