### ISSUE TITLE
使用整合包时训练正常，但合成语音时输出的音频文件无声且未报错

### ISSUE THREAD

**Issue by Thunder-Prod** [RVC-Boss/GPT-SoVITS#202]
GPU: GTX 1660Ti
Windows 10 22H2
在AutoDL使用官方镜像加载本地训练的模型可正常合成语音。

**Comment by XXXXRT666** [comment]
16系卡没有半精度，去把is_half关了

**Comment by RVC-Boss** [comment]
config.py   is_half=True    ->   is_half=False
训练需要训练时的2个config     改fp32
