### ISSUE TITLE
Support for creating dataset text files from English and Japanese audio too. 

### ISSUE THREAD

**Issue by nekogecko2** [RVC-Boss/GPT-SoVITS#203]
Sorry if it's already on your todo list. The ASR tool can read english audio _ok_ but it's not as good as whisper. It would be convenient if whisper or something was added to it so everything could be done in the same program. I use another program for creating dataset txt files right now. 

Also for any English users reading this, 

> This tool is actually LEGIT. It only takes a few minutes **to** train a model on my RTX 3060.  Like this is finally a **REALLY** real for real open source alternative to eleven labs. 

Here's a example with Finn's voice from adventure time

https://vocaroo.com/133yE3LKENkT
https://vocaroo.com/1aYbqO6yxatg

**Comment by RVC-Boss** [comment]
I'm planning to introduce whipser.

**Comment by company8** [comment]
@nekogecko2 Hey sorry to bother you, I also encountered the same issue you encountered. The ASR tool didn't do a bad job but wasn't great either. Btw I used to watch A.T daily and Finn is spot on I love your results :D 

Could you share how you achieved this and the process ? Thank you man :)
