### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by forwiat** [RVC-Boss/GPT-SoVITS#206]
hello Boss, What an amazing project! It helps me too much, which leads to build creatative product!
If convenient, I wonder how many hours dataset used to training the base model:)

**Comment by forwiat** [comment]
Motivation: I want to use wavlm_sv to encode speech to timbre vector, which can optimize zero-shot results?(maybe), anyway, experiments will prove the guess:)

**Comment by RVC-Boss** [comment]
chinese+english+japanese=2k hours

**Comment by forwiat** [comment]
Thanks for answer, I prepare to do some extra experiments based on GPT-SoVITS, I will share results If benefits from some extra modules:)
