### ISSUE TITLE
请问是否可以把声音修改的更雄厚

### ISSUE THREAD

**Issue by 1044690543** [RVC-Boss/GPT-SoVITS#207]
我使用中年男人的数据集，克隆出来的声音有些稚气，中年男人那种雄厚的感觉有些不足，请问代码中有没有可以修改底层引用库的地方，改为中年男人的类型呢

**Comment by RVC-Boss** [comment]
选更雄厚更低沉的参考音频。如果微调训练集不包含那建议不微调，试试zero shot，如果也不行，那只能录雄厚的素材去微调。
