### ISSUE TITLE
最后的推理过程，为啥进度条不是100%

### ISSUE THREAD

**Issue by yeloveyou** [RVC-Boss/GPT-SoVITS#219]
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/51388802/f48e9463-5f81-447a-8810-6408bf32a2e1)
在最后的应用模型进行ttl推理时候，进度条每次都走不完就会显示ok，这是正常的吗？还是哪里出了问题？

**Comment by RVC-Boss** [comment]
是正常的。

**Comment by RVC-Boss** [comment]
因为GPT预测出来是不定长的，所以进度条本身是不可控的，就写死一个比较大的数值1500.
