### ISSUE TITLE
uvr5预处理很吃内存吗？16GB一下子就崩了

### ISSUE THREAD

**Issue by liaozhi0520** [RVC-Boss/GPT-SoVITS#228]
![Snipaste_2024-01-27_03-55-19](https://github.com/RVC-Boss/GPT-SoVITS/assets/74309923/9cdbc91d-0926-4bd6-b5ff-19e29c227f84)

**Comment by RVC-Boss** [comment]
你音频太长了，我一般建议10分钟~20分钟一切。长了确实吃内存哈，你跑原版UVR5的GUI一样太长了系统会非常卡。
