### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled on M2 MAC

### ISSUE THREAD

**Issue by manojkr19** [RVC-Boss/GPT-SoVITS#231]
Hi I'm getting this error in M2 MAC when I run web.ui.

AssertionError: Torch not compiled with CUDA enabled

Are there any instructions on how to use the pre-trained models?

Thanks

**Comment by zhouhao27** [comment]
Got the same error.

**Comment by Lion-Wu** [comment]
Replacing the code:
```python
gpu_name = torch.cuda.get_device_name(0) 
if (
         ("16" in gpu_name and "V100" not in gpu_name.upper())
         or "P40" in gpu_name.upper()
         or "P10" in gpu_name.upper()
         or "1060" in gpu_name
         or "1070" in gpu_name
         or "1080" in gpu_name 
):
                  is_half=False
```
with `is_half=False`  in config.py may solve the issue.
I've noticed a [pull request](https://github.com/RVC-Boss/GPT-SoVITS/pull/236) to fix this issue.
As more modifications and new features are added, compatibility on Mac may be affected. If any errors occur later, feel free to ask me!

**Comment by RVC-Boss** [comment]
Merge to main brach now. 
You can fix the issue by updating config.py
