### ISSUE TITLE
  WSL  ubuntu 训练报错

### ISSUE THREAD

**Issue by skyantao** [RVC-Boss/GPT-SoVITS#239]
首先非常感谢分享，我测试了Windows版本，效果非常好!
考虑在Linux 下应用，在进行微调训练时，无论 s1_train 还是 s2_train 都要报错。

  File "/root/miniconda3/envs/gptsovit/lib/python3.10/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/root/miniconda3/envs/gptsovit/lib/python3.10/multiprocessing/connection.py", line 593, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported
deug info : /mnt/e/wsldata/code/GPT-SoVITS/TEMP/pymp-hd3wzc1h/listener-vs02o2rv

debuginfo 是我 输出的 bind 的address， 我觉得是分布式训练引起的。
环境如下：
python 3.10   torch 2.1.2 + CU118

(gptsovit) root@DESKTOP-BE2FPE6:~# pip list
Package                   Version
------------------------- ------------
absl-py                   2.1.0
accelerate                0.26.1
addict                    2.4.0
aiofiles                  23.2.1
aiohttp                   3.9.1
aiosignal                 1.3.1
aliyun-python-sdk-core    2.14.0
aliyun-python-sdk-kms     2.16.2
altair                    5.2.0
annotated-types           0.6.0
anyio                     4.2.0
async-timeout             4.0.3
attrs                     23.2.0
audioread                 3.0.1
auto-gptq                 0.6.0+cu118
cachetools                5.3.2
certifi                   2023.11.17
cffi                      1.16.0
chardet                   5.2.0
charset-normalizer        3.3.2
click                     8.1.7
cn2an                     0.5.22
colorama                  0.4.6
coloredlogs               15.0.1
contourpy                 1.2.0
crcmod                    1.7
cryptography              42.0.1
cycler                    0.12.1
Cython                    0.29.37
datasets                  2.16.1
decorator                 5.1.1
deepspeed                 0.13.0
dill                      0.3.7
Distance                  0.1.3
dropout-layer-norm        0.1
editdistance              0.6.2
einops                    0.7.0
exceptiongroup            1.2.0
fastapi                   0.109.0
ffmpeg-python             0.2.0
ffmpy                     0.3.1
filelock                  3.13.1
flash-attn                2.3.2
flatbuffers               23.5.26
fonttools                 4.47.2
frozenlist                1.4.1
fsspec                    2023.10.0
funasr                    0.8.7
fused-dense-lib           0.0.0
fused-softmax-lib         0.0.0
future                    0.18.3
g2p-en                    2.1.0
gast                      0.5.4
gekko                     1.0.6
google-auth               2.27.0
google-auth-oauthlib      1.2.0
gradio                    3.38.0
gradio_client             0.8.1
grpcio                    1.60.0
h11                       0.14.0
hdbscan                   0.8.33
hjson                     3.1.0
httpcore                  1.0.2
httpx                     0.26.0
huggingface-hub           0.20.3
humanfriendly             10.0
idna                      3.6
importlib-metadata        7.0.1
importlib-resources       6.1.1
inflect                   7.0.0
jaconv                    0.3.4
jamo                      0.4.1
jieba                     0.42.1
jieba-fast                0.53
Jinja2                    3.1.3
jmespath                  0.10.0
joblib                    1.3.2
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kaldiio                   2.18.0
kiwisolver                1.4.5
librosa                   0.9.2
lightning-utilities       0.10.1
linkify-it-py             2.0.2
llvmlite                  0.39.1
Markdown                  3.5.2
markdown-it-py            2.2.0
MarkupSafe                2.1.4
matplotlib                3.8.2
mdit-py-plugins           0.3.3
mdurl                     0.1.2
modelscope                1.10.0
mpmath                    1.3.0
multidict                 6.0.4
multiprocess              0.70.15
networkx                  3.2.1
ninja                     1.11.1.1
nltk                      3.8.1
numba                     0.56.4
numpy                     1.23.5
oauthlib                  3.2.2
onnxruntime               1.16.3
optimum                   1.16.2
orjson                    3.9.12
oss2                      2.18.4
packaging                 23.2
pandas                    2.2.0
peft                      0.7.1
pillow                    10.2.0
pip                       23.3.1
platformdirs              4.1.0
pooch                     1.8.0
proces                    0.1.7
protobuf                  4.23.4
psutil                    5.9.8
py-cpuinfo                9.0.0
pyarrow                   15.0.0
pyarrow-hotfix            0.6
pyasn1                    0.5.1
pyasn1-modules            0.3.0
pycparser                 2.21
pycryptodome              3.20.0
pydantic                  2.5.3
pydantic_core             2.14.6
pydub                     0.25.1
Pygments                  2.17.2
pynvml                    11.5.0
pyopenjtalk               0.3.3
pyparsing                 3.1.1
pypinyin                  0.50.0
python-dateutil           2.8.2
python-multipart          0.0.6
pytorch-lightning         2.1.3
pytorch-wpe               0.0.1
pytz                      2023.3.post1
PyYAML                    6.0.1
referencing               0.32.1
regex                     2023.12.25
requests                  2.31.0
requests-oauthlib         1.3.1
resampy                   0.4.2
rich                      13.7.0
rotary-emb                0.1
rouge                     1.0.1
rpds-py                   0.17.1
rsa                       4.9
ruff                      0.1.14
safetensors               0.4.1
scikit-learn              1.4.0
scipy                     1.12.0
semantic-version          2.10.0
sentencepiece             0.1.99
setuptools                68.2.2
shellingham               1.5.4
simplejson                3.19.2
six                       1.16.0
sniffio                   1.3.0
sortedcontainers          2.4.0
soundfile                 0.12.1
starlette                 0.35.1
sympy                     1.12
tensorboard               2.15.1
tensorboard-data-server   0.7.2
threadpoolctl             3.2.0
tokenizers                0.15.1
tomli                     2.0.1
tomlkit                   0.12.0
toolz                     0.12.0
torch                     2.1.2+cu118
torch-complex             0.4.3
torchaudio                2.1.2+cu118
torchmetrics              1.3.0.post0
torchvision               0.16.2+cu118
tqdm                      4.66.1
transformers              4.37.0
triton                    2.1.0
typer                     0.9.0
typing_extensions         4.9.0
tzdata                    2023.4
uc-micro-py               1.0.2
umap                      0.1.1
urllib3                   2.1.0
uvicorn                   0.27.0
websockets                11.0.3
Werkzeug                  3.0.1
wheel                     0.41.2
xentropy-cuda-lib         0.1
xxhash                    3.4.1
yapf                      0.40.2
yarl                      1.9.4
zipp                      3.17.0

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/issues/172
同类问题，我没有测试环境，如果有其他朋友遇到类似的问题并且解决了可以分享下解决方案。

**Comment by skyantao** [comment]
感谢作者，解决了。

tmp = os.path.join(now_dir, "TEMP")   windows可以，WSL 异常。把这句换成下一句 ， 我觉得可能是系统权限的问题。 确实不能把临时的目录 放在 挂载的盘上

tmp = os.path.normpath("/tmp/RVC")
