### ISSUE TITLE
TTS推理阶段出现全nan情况

### ISSUE THREAD

**Issue by Randolph87cb** [RVC-Boss/GPT-SoVITS#24]
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/20552978/33ce8f94-c400-4420-afe8-331809855be5)

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/20552978/2fee0c00-4f0f-4812-ade6-fbcb8112c0ef)

代码中打印decode得到的audio tensor，但是全都是nan，然后输出的音频都是空的，直接用pretrain的模型也会出现这样的问题，请问需要修改什么

**Comment by RVC-Boss** [comment]
显卡型号是？

**Comment by Randolph87cb** [comment]
1660S

**Comment by RVC-Boss** [comment]
16系的推理不支持半精度

**Comment by RVC-Boss** [comment]
同时注意这可能消耗更多显存

**Comment by Randolph87cb** [comment]
OK了，可以运行，不过我发现要合成的句子如果太短，会生成参考音频的内容

**Comment by Randolph87cb** [comment]
done
