### ISSUE TITLE
sovits部分是否可以不依赖打标文件进行训练？

### ISSUE THREAD

**Issue by VINK77aaaa** [RVC-Boss/GPT-SoVITS#243]
能不能跳过标注步骤，直接用大量未标注的数据训练SoVits？因为我的训练集比较多，这样一来既能省掉不少精修的工作量，还能完善模型处理音色的能力。这个想法能不能行得通。

**Comment by RVC-Boss** [comment]
目前还不可以，因为sovits部分也注入了音素。也许后面会尝试补注入音素的sovits版本，那个是可以无限加无标注训练集的

**Comment by VINK77aaaa** [comment]
> 目前还不可以，因为sovits部分也注入了音素。也许后面会尝试补注入音素的sovits版本，那个是可以无限加无标注训练集的

收到👌
