### ISSUE TITLE
很遗憾你没有支持的显卡来训练

### ISSUE THREAD

**Issue by Jeru2023** [RVC-Boss/GPT-SoVITS#244]
在第二个tab中看到这个提示，很奇怪，我的显卡是4090，为何找不到呢？

**Comment by kigner** [comment]
可能是集成包中的对应pytorch与您的4090 cuda12版本不匹配；手动安装并使用更高版本的pytorch试试。

**Comment by Jeru2023** [comment]
> 可能是集成包中的对应pytorch与您的4090 cuda12版本不匹配；手动安装并使用更高版本的pytorch试试。

是的，我已经手工重新装了pytorch

**Comment by RVC-Boss** [comment]
需要安装合适的pytorch版本。

**Comment by AurevoirXavier** [comment]
4090 on 2024-05-12.

```
pip uninstall torch
pip install torch --index-url https://download.pytorch.org/whl/cu121
```
