### ISSUE TITLE
ffmpeg安装正常，也部署了路径，但是每次调用都报错，求大神指导

### ISSUE THREAD

**Issue by hjorthXu** [RVC-Boss/GPT-SoVITS#258]
我没有基础，属于小白级别的
现在的问题是最后合成的音频不能播放，我看了程序报错在进入推理界面的时候，有大量的报错，提示要安装ffmpeg。我猜想最后合成音频没有声音的原因，就是因为没办法调用ffmpeg，求大神指导。

**Comment by RVC-Boss** [comment]
没有声音可能是因为你的卡是16系
如果是在torchaudio里面的ffmpeg报错不影响功能使用

**Comment by hjorthXu** [comment]
> 没有声音是因为你的卡是16系如果是在torchaudio里面的ffmpeg报错不影响功能使用

我的显卡是GTX1650 这个是16系的意思吗，请问大神，这个应该怎么解决

**Comment by RVC-Boss** [comment]
更新最新的github代码或者整合包就行了。

**Comment by hjorthXu** [comment]
> 更新最新的github代码或者整合包就行了。

感谢大佬的回答。新年快乐。
