### ISSUE TITLE
文档中说的：将ffmpeg.exe放在sovits根目录中，这个怎么放

### ISSUE THREAD

**Issue by hjorthXu** [RVC-Boss/GPT-SoVITS#260]
小白求教，我安装了ffmpeg文件，然后怎么操作，直接吧exe文件拖入到sovits根目录吗？
还有我的ffmpet点击就闪退，目前sovits大量报错：无法调用ffmpeg 要我安装。。。但我已经安装了，也设置了路径。

**Comment by RVC-Boss** [comment]
你如何下载的是win整合包就不需要
如果是linux就是apt install安装
如果是win系统自己装，把ffmpeg.exe放到gpt-sovits根目录或者C-windows-system32下
总之确保在当前目录输入ffmpeg命令是可以执行的就行
