### ISSUE TITLE
macOS 发生 CUDA 相关保错

### ISSUE THREAD

**Issue by xurenfei** [RVC-Boss/GPT-SoVITS#264]
Config.py 第32行，由于 Mac 没有 CUDA，运行至直接报错：
```python
gpu_name = torch.cuda.get_device_name(0)
```
目前我加了一个try……except……跳过这段逻辑后才能够正常启动webUI，请作者大大检查。
```python
try:
    gpu_name = torch.cuda.get_device_name(0)
except:
    gpu_name = "None"
```

**Comment by RVC-Boss** [comment]
这个问题奇怪的，是不是你那没到最新版本
https://github.com/RVC-Boss/GPT-SoVITS/blob/main/config.py#L18
如果没有cuda的mac，infer_device就不会是cuda，不会去get_device_name

**Comment by xurenfei** [comment]
> 这个问题奇怪的，是不是你那没到最新版本 https://github.com/RVC-Boss/GPT-SoVITS/blob/main/config.py#L18 如果没有cuda的mac，infer_device就不会是cuda，不会去get_device_name

感谢您的回复，我检查了源码，确实存在差别。浪费了您的时间深感抱歉😭

应该是Gitee上的版本和Github上不一致造成的：
```python
gpu_name = torch.cuda.get_device_name(0)
if (
        ("16" in gpu_name and "V100" not in gpu_name.upper())
        or "P40" in gpu_name.upper()
        or "P10" in gpu_name.upper()
        or "1060" in gpu_name
        or "1070" in gpu_name
        or "1080" in gpu_name
):
```
