### ISSUE TITLE
公链分享的问题

### ISSUE THREAD

**Issue by Phrixus2023** [RVC-Boss/GPT-SoVITS#265]
config.py里的is_share设置为True后还是生成不了公链，不知道是哪里的问题。

**Comment by RVC-Boss** [comment]
连不上gradio的服务器？

**Comment by Phrixus2023** [comment]
> 连不上gradio的服务器？

应该不是，我分别尝试了开着梯子连接，和替换了gradio的api链接都不行，可能是程序代码的问题。我用fooocus就能正常生成链接。

**Comment by company8** [comment]
> > 连不上gradio的服务器？
> 
> 应该不是，我分别尝试了开着梯子连接，和替换了gradio的api链接都不行，可能是程序代码的问题。我用fooocus就能正常生成链接。

`    app.queue(concurrency_count=511, max_size=1022).launch(
        server_name="0.0.0.0",
        inbrowser=True,
        share=True, # Change this to True and you will have a public link
        server_port=webui_port_main,
        quiet=True,
    )`

**Comment by Phrixus2023** [comment]
> > > 连不上gradio的服务器？
> > 
> > 
> > 应该不是，我分别尝试了开着梯子连接，和替换了gradio的api链接都不行，可能是程序代码的问题。我用fooocus就能正常生成链接。
> 
> ` share=True, # Change this to True and you will have a public link`

你这个是webui里改的吗？我改完运行还是没用

**Comment by company8** [comment]
> > > > 连不上gradio的服务器？
> > > 
> > > 
> > > 应该不是，我分别尝试了开着梯子连接，和替换了gradio的api链接都不行，可能是程序代码的问题。我用fooocus就能正常生成链接。
> > 
> > 
> > ` share=True, # Change this to True and you will have a public link`
> 
> 你这个是webui里改的吗？我改完运行还是没用

Yeah that's how I get a public link for training in the cloud. You would do the same for "inference_webui.py" and another one I forgot. Just change it to "share=True," at the end of the python script and you should get a public gradio link. There was a another script where you had to edit it in 2 places from "False" to "True" to get a public link but I don't remember the name of the python script.

For webui.py just change `share=is_share,` to `share=True,` at the end of the script. For inference_webui.py I just checked, I think on 2 places. "Line 39 is_share = os.environ.get("is_share", "False")" to "is_share = os.environ.get("is_share", "True") and at the bottom of the script `share=is_share,` to `share=True,`

**Comment by Phrixus2023** [comment]
> > > > > 连不上gradio的服务器？
> > > > 
> > > > 
> > > > 应该不是，我分别尝试了开着梯子连接，和替换了gradio的api链接都不行，可能是程序代码的问题。我用fooocus就能正常生成链接。
> > > 
> > > 
> > > ` share=True, # Change this to True and you will have a public link`
> > 
> > 
> > 你这个是webui里改的吗？我改完运行还是没用
> 
> Yeah that's how I get a public link for training in the cloud. You would do the same for "inference_webui.py". Just change it to "share=True," at the end of the python script and you should get a public gradio link. There was a another script where you had to edit it in 2 places from "False" to "True" to get a public link but I don't remember the name of the python script.
> 
> For webui.py just change `share=is_share,` to `share=True,` at the end of the script. For inference_webui.py I just checked, I think on 2 places. "Line 39 is_share = os.environ.get("is_share", "False")" to "is_share = os.environ.get("is_share", "True") and at the bottom of the script `share=is_share,` to `share=True,`

D:\BaiduNetdiskDownload\GPT-SoVITS-beta\GPT-SoVITS>runtime\python.exe webui.py
Running on local URL:  http://0.0.0.0:9874

Setting up a public link... we have recently upgraded the way public links are generated. If you encounter any problems, please report the issue and downgrade to gradio version 3.13.0
.

Could not create share link, please check your internet connection.
"D:\BaiduNetdiskDownload\GPT-SoVITS-beta\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/inference_webui.py
D:\BaiduNetdiskDownload\GPT-SoVITS-beta\GPT-SoVITS\runtime\lib\site-packages\transformers\utils\hub.py:123: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
"D:\BaiduNetdiskDownload\GPT-SoVITS-beta\GPT-SoVITS\runtime\python.exe" tools/subfix_webui.py --load_list "D:\RVC1006\GPT-SoVITS\raw\xxx.list" --webui_port 9871 --is_share True
<All keys matched successfully>
Number of parameter: 77.49M
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\GPT-SoVITS-beta\GPT-SoVITS\tools\subfix_webui.py", line 310, in <module>
    set_global(args.load_json, args.load_list, args.json_key_text, args.json_key_path, args.g_batch)
  File "D:\BaiduNetdiskDownload\GPT-SoVITS-beta\GPT-SoVITS\tools\subfix_webui.py", line 295, in set_global
    b_load_file()
  File "D:\BaiduNetdiskDownload\GPT-SoVITS-beta\GPT-SoVITS\tools\subfix_webui.py", line 274, in b_load_file
    b_load_list()
  File "D:\BaiduNetdiskDownload\GPT-SoVITS-beta\GPT-SoVITS\tools\subfix_webui.py", line 244, in b_load_list
    with open(g_load_file, 'r', encoding="utf-8") as source:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\RVC1006\\GPT-SoVITS\\raw\\xxx.list'
DEBUG:root:Using proactor: IocpProactor
DEBUG:root:Using proactor: IocpProactor
"D:\BaiduNetdiskDownload\GPT-SoVITS-beta\GPT-SoVITS\runtime\python.exe" tools/uvr5/webui.py "cuda" True 9873 True
Running on local URL:  http://0.0.0.0:9872

Setting up a public link... we have recently upgraded the way public links are generated. If you encounter any problems, please report the issue and downgrade to gradio version 3.13.0
.
Running on local URL:  http://0.0.0.0:9873

Setting up a public link... we have recently upgraded the way public links are generated. If you encounter any problems, please report the issue and downgrade to gradio version 3.13.0
.

Could not create share link, please check your internet connection.

Could not create share link, please check your internet connection.

I ended up failing, I don't know what the problem is, my internet should be fine

**Comment by karry12138** [comment]
【同样的公链问题】我用的是windows打包版项目，在本地运行，gradio3.14.0
我在修改了config.py中is_share=True后，遇到了同样的问题，但还没能解决。
```
Could not create share link, please check your internet connection.
```
(虽然但是，在audodl上用镜像创建的项目能够正常创建公链分享)
### 1 尝试回退版本
首先，按照报错提示回退到gradio3.13是不行的。在复制粘贴了3.13版本以及其他依赖库到site-package后，本地连接能够启动，但无法创建公链。(中国开发者永远的痛，访问不了gradio服务器)
```
*** Failed to connect to ec2.gradio.app:22: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连 接尝试失败。
```
尝试使用warp这个网络连接工具，也不行。
```
paramiko.ssh_exception.SSHException:Error reading SSH protocol banner
***Failed to connect to ec2.gradio.app:22:Error reading SSH protocol banner
```
### 2 尝试在本版本解决
在搜索报错信息后，这个问题似乎和gradio本身有关，新版本的gradio在通过pip安装后不会再自带frpc工具(这是一个反向代理工具，比如gradio目录下的frpc_windows_amd64_v0.2)，需要手动下载

**Comment by karry12138** [comment]
【喜报，我解决了】
就是gradio3.14.0及之后的版本不包含frpc工具的问题。
但是，你的机器必须要有能够访问外网(gradio服务器)的能力，访问不了也白搭。
外网问题，我使用c l a s h的TUN模式成功了。全局(GLOBAL)和规则(RULE)都不行。

下面是手动下载frpc并装到gradio包里的步骤
参考资料：
1.https://github.com/THUDM/ChatGLM-6B/issues/959
关键信息:
```
我也遇到一样的问题，有人知道怎么解决么？
只要能访问外网，手动下载frpc工具就好了。比如这个：
/root/miniconda3/lib/python3.9/site-packages/gradio/frpc_linux_amd64_v0.2
路径换成对应的，frpc_linux_amd64_v0.2是从/root/miniconda3/lib/python3.9/site-packages/gradio/tunneling.py文件可以
看出这个文件名。
```
2.https://blog.csdn.net/qq_42531954/article/details/133901919
关键信息：
```
Running on local URL: http://127.0.0.1:7860

Could not create share link. Missing file: E:\MyDown\qqdata\374591069\FileRecv\Silent-Face-Anti-Spoofing-master\venv\lib\site-packages\gradio\frpc_windows_amd64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 

1. Download this file: [frpc_windows_amd64.exe](https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_windows_amd64.exe)
2. Rename the downloaded file to: `frpc_windows_amd64_v0.2`
3. Move the file to this location: `E:\venv\lib\site-packages\gradio`

```
遵从链接1确定你要下载的frpc的版本和系统环境(windows/linux)，比如我是win，在gradio文件夹下tunneling.py中确定VERSION = "0.1"
然后根据版本和系统环境到下面的hugglingface下载一个frpc，下载链接源形如
```
https://cdn-media.huggingface.co/frpc-gradio-0.1/frpc_windows_amd64.exe
```
其中"0.1"和“windows”按你的来。linux用户把"windows"改成"liunx"。我没试过用0.2行不行。

再遵从链接2将其重命名后塞到gradio文件夹下面就行。

![成功开启gradio外链](https://github.com/RVC-Boss/GPT-SoVITS/assets/66634899/2a062ff9-3da2-4cb7-b161-26df4e1ef884)

**Comment by karry12138** [comment]
关于外网工具-2：只要能够管得到cmd的流量转发就行。

**Comment by Phrixus2023** [comment]
靠，我一直以为他会提示缺少frpc所以根本没考虑，我现在看看，另外我分享给你一个国内我自己用的公链api链接：https://api.videosreel.com/tunnel-request

**Comment by karry12138** [comment]
感谢。祝你能排查出问题。

**Comment by Phrixus2023** [comment]
> https://cdn-media.huggingface.co/frpc-gradio-0.1/frpc_windows_amd64.exe

解决了。。。感谢你的详细说明，我一开始是复制的其他版本gradio的frpc，后来我仔细看你的说明，全部按老版本来才成功生成链接。

**Comment by karry12138** [comment]
能帮到你就好，我就感觉这里的frpc版本有坑（）

**Comment by karry12138** [comment]
不过我也有一个问题。使用你给的api后，我启动此项目的webui和打标webui确实不需要梯子，能开启外链了。但在启动推理webui的时候http请求又从跑到了api.gradio.app上，导致外链生成不出来。有什么使用限制吗？

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/66634899/da9f09e1-48cf-4688-9520-2777d4fb5153)

**Comment by Phrixus2023** [comment]
> 不过我也有一个问题。使用你给的api后，我启动此项目的webui和打标webui确实不需要梯子，能开启外链了。但在启动推理webui的时候http请求又从跑到了api.gradio.app上，导致外链生成不出来。有什么使用限制吗？
> 
> ![image](https://private-user-images.githubusercontent.com/66634899/300760256-da9f09e1-48cf-4688-9520-2777d4fb5153.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTA1NTEsIm5iZiI6MTcwNjYxMDI1MSwicGF0aCI6Ii82NjYzNDg5OS8zMDA3NjAyNTYtZGE5ZjA5ZTEtNDhjZi00Njg4LTk1MjAtMjc3N2Q0ZmI1MTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDEwMjQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0N2U4OTlmMjliYjllYmIxZjdhZTVkYTllMmNjZmY0Y2E3MDMyZGU2M2MwODVkN2Q3ZjlhZjE1MzA5ZDljMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ziu1RYdQqpdOlX3qmwh-io5frkQfBaJn4k6iDFsPKeo)
> 
> [最后推理webui在本地上运行] ![image](https://private-user-images.githubusercontent.com/66634899/300760882-7c17f2c7-1730-4a71-b053-b9ae256cdee5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTA1NTEsIm5iZiI6MTcwNjYxMDI1MSwicGF0aCI6Ii82NjYzNDg5OS8zMDA3NjA4ODItN2MxN2YyYzctMTczMC00YTcxLWIwNTMtYjlhZTI1NmNkZWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDEwMjQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMmYwNjgwODQ2NDYzYWJjMDEyZGY5NDFlOTFhMDFhMmQxMDMyMjQxNTg4OGY3ZmU2MDliYmJkMDU1OWM5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DuACjwI1lmfhoir4NIqGztSCCl2pPtHtzXLYG2zIhro)

没有限制，我刚测试的是你要提前打开所有web页面，全部都生成了公链

**Comment by karry12138** [comment]
没事了，是GPT_SoVITS/inference_webui.py中的launch函数需要手动添加share参数（藏得还挺深）。我只改了外面的config.py.
感谢分享
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/66634899/c81121c9-835a-4e5a-bd3a-8088f38ceebf)

**Comment by Phrixus2023** [comment]
> inference_webui.py

inference_webui.py的share参数好像在该文件头部改就行，不用自己添加

**Comment by karry12138** [comment]
应该是我用的win打包版比较老，这个部分的webui当时作者没加share参数。我手动加上就好了。难怪只有推理webui没公链。
感谢提示。

【此部分的最新代码，有share参数】
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/66634899/bf170a2d-ab5f-4959-a3c5-1ef79671692b)

**Comment by licycle** [comment]
linux 上需要加上权限：
进入python环境site-packages/gradio/目录，输入以下命令
chmod +x frpc_linux_amd64_v0.1
