### ISSUE TITLE
webui.bat报错

### ISSUE THREAD

**Issue by xiaoxu66609** [RVC-Boss/GPT-SoVITS#272]
webui.bat报错未找到python.exe运行后无反应

**Comment by RVC-Boss** [comment]
确认你的runtime文件夹下是否有python.exe这个文件

**Comment by xiaoxu66609** [comment]
下载的zip文件中解压后没有runtime


| |
xujiayang2009119
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年1月29日 11:13 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [RVC-Boss/GPT-SoVITS] webui.bat报错 (Issue #272) |

确认你的runtime文件夹下是否有python.exe这个文件

**Comment by xiaoxu66609** [comment]
下载的zip文件解压后没有runtime
