### ISSUE TITLE
GPT训练，3090ti训练都不够为什么?

### ISSUE THREAD

**Issue by yeloveyou** [RVC-Boss/GPT-SoVITS#275]
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/51388802/4968e0ab-7a83-44fc-bb1c-9d43353fbe6b)
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/51388802/387d4c2f-6ef8-46d2-8a6c-fa8b29fe6d09)
gpt训练卡顿，并且进度条不显示，占用率100%，这是为什么呢？（我的训练文件就两个，合起来1分钟左右）

**Comment by BlacknoSheep** [comment]
打开cmd，输入 `nvidia-smi` 看看具体是哪些进程在占显存，我 batch_size=16 时SoVITS 约占 13.5G 显存，GPT 约占 14.5G 显存。
显存不够就等SoVITS训练完了再训练GPT。

**Comment by bfloat16** [comment]
切片太长，共享显存占用严重

**Comment by RVC-Boss** [comment]
楼上正解。需要关闭共享显存。https://www.bilibili.com/read/cv27436189
参考这个，找到你调用的python.exe关闭一下。
