### ISSUE TITLE
在尝试训练的时候发生了一个致命错误

### ISSUE THREAD

**Issue by KOKOMI12345** [RVC-Boss/GPT-SoVITS#280]
RuntimeError: cuFFT doesn't support signals of half type with compute capability less than SM_53, but the device containing input half tensor only has SM_52

**Comment by LuweiLee** [comment]
你是什么显卡呢，我也提示这个，我的是gtx970

**Comment by RVC-Boss** [comment]
同志你的显卡太老了

**Comment by hixuanyu** [comment]
显卡太老了，cuda不支持我的是 tesla m40 的也报同样的错误，换成 tesla p100 后解决了该问题

**Comment by KOKOMI12345** [comment]
噢，原来如此




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月20日(星期二) 晚上7:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RVC-Boss/GPT-SoVITS] 在尝试训练的时候发生了一个致命错误 (Issue #280)





 
显卡太老了，cuda不支持我的是 tesla m40 的也报同样的错误，换成 tesla p100 后解决了该问题
