### ISSUE TITLE
生成语音时，可否控制语速，这个相关参数在哪里

### ISSUE THREAD

**Issue by iloveming** [RVC-Boss/GPT-SoVITS#283]

**Comment by zhuangzhuangliu2345** [comment]
mark

**Comment by RVC-Boss** [comment]
现在只能通过参考语音。后面想加语速滑竿的

**Comment by ISDHN** [comment]
似乎可以通过修改noise_scale来调整语速

**Comment by iloveming** [comment]
好的

**Comment by maxadc** [comment]
> 似乎可以通过修改noise_scale来调整语速
noise_scale是什么？在哪里控制？

**Comment by maxadc** [comment]
> 现在只能通过参考语音。后面想加语速滑竿的
等待大佬出此功能！！！

**Comment by ISDHN** [comment]
> > 现在只能通过参考语音。后面想加语速滑竿的
> > 等待大佬出此功能！！！

GPT-SoVITS\GPT_SoVITS\module\models.py里 类型SynthesizerTrn的decode方法  
但是如此操作在调整过度的情况下会导致结果失真。
