### ISSUE TITLE
mac下执行webui.py出现错误提示

### ISSUE THREAD

**Issue by shellddd** [RVC-Boss/GPT-SoVITS#29]
您好，请教一下，我使用的是mac系统，按照安装说明搭建完环境以后，执行webui.py出现以下的错误提示，请问这是哪里出现了问题呢？希望您抽空回覆，不胜感激。（另使用您在B站提供的整合包，运行依然是提示如下的错误。）

```
By default, 'file' is written in the MIFF image format.  To
specify a particular image format, precede the filename with an image
format name and a colon (i.e. ps:image) or specify the image type as
the filename suffix (i.e. image.ps).  Specify 'file' as '-' for
standard input or output.
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1302.
: command not found 
./webui.py: line 4: syntax error near unexpected token `"ignore"'
'/webui.py: line 4: `warnings.filterwarnings("ignore")

```

**Comment by shellddd** [comment]
终于找到原因了，在终端里第一次运行webui.py时，会提示没有权限，然后我开启权限后，就会出现上面的错误。和windows里面不能使用管理员打开命令好像是一样的。
解决方法是：在根目录里新建一个webui.sh来执行webui.py命令。
```
#!/bin/bash
python /这里替换为你自己的目录地址/GPT-SoVITS-mac/webui.py
```

**Comment by hydra-li** [comment]
> 终于找到原因了，在终端里第一次运行 webui.py 时，会提示没有权限，然后我开启权限后，就会出现上面的错误。和windows里面不能使用管理员打开命令好像是一样的。 解决方法是：在根目录里新建一个 webui.sh 来执行 webui.py 命令。
> 
> ```
> #!/bin/bash
> python /这里替换为你自己的目录地址/GPT-SoVITS-mac/webui.py
> ```

能具体说一下mac如何启动吗

**Comment by shellddd** [comment]
> > 终于找到原因了，在终端里第一次运行 webui.py 时，会提示没有权限，然后我开启权限后，就会出现上面的错误。和windows里面不能使用管理员打开命令好像是一样的。 解决方法是：在根目录里新建一个 webui.sh 来执行 webui.py 命令。
> > ```
> > #!/bin/bash
> > python /这里替换为你自己的目录地址/GPT-SoVITS-mac/webui.py
> > ```
> 
> 能具体说一下mac如何启动吗

先在程序根目录下新建一个webui的文件，后缀名为.sh，填写上面的内容，然后保存，在终端里进入程序根目录，执行下面的命令：
`./webui.sh`

**Comment by hydra-li** [comment]
> > > 终于找到原因了，在终端里第一次运行 webui.py 时，会提示没有权限，然后我开启权限后，就会出现上面的错误。和windows里面不能使用管理员打开命令好像是一样的。解决方法是：在根目录里新建一个 webui.sh 来执行 webui.py 命令。
> > > ```
> > > #!/bin/bash
> > > python /这里替换为你自己的目录地址/GPT-SoVITS-mac/webui.py
> > > ```
> > 
> > 
> > 能具体说一下mac如何启动吗
> 
> 先在程序根目录下新建一个webui的文本文件，后缀名为.sh，填写上面的内容，然后保存，在终端里进入程序根目录，执行下面的命令： `./webui.sh`

我这里面总是提示
  File "/Users/xxxxxxx/GPT-SoVITS/webui.py", line 25, in <module>
    from i18n.i18n import I18nAuto
ModuleNotFoundError: No module named 'i18n.i18n'
方便加个联系方式交流吗？QQ462914533

**Comment by wshangguan** [comment]
不知道你的问题解决了没有, 我运行tools/uvr5/webui.py的时候遇到了一样的问题, 运行根目录下的那个就好了.
