### ISSUE TITLE
更快的模型下载

### ISSUE THREAD

**Issue by Lion-Wu** [RVC-Boss/GPT-SoVITS#292]
对于国内用户，我可以把模型文件传到iCloud上，其他用户都可以以更快的速度下载，直接进网页就可以下载的那种，而且经测试是能够跑满宽带的，参考我在#165 中给出的项目下载链接，不知道作者是否需要？

**Comment by RVC-Boss** [comment]
你可以加在readme mac用户那个位置

**Comment by ShengPengYu** [comment]
很好，我觉得需要，因为我下载这个模型用了很长时间。

**Comment by Lion-Wu** [comment]
已完成：[PR#311](https://github.com/RVC-Boss/GPT-SoVITS/pull/311)
