### ISSUE TITLE
长文本会出很多错，各位童鞋如何解决这个问题？

### ISSUE THREAD

**Issue by qianlong1688** [RVC-Boss/GPT-SoVITS#294]
长文本输入进去，会掉语句或者一个句子读几遍，能否用其它方法解决，最好是输进文本，然后只用等待就好

**Comment by hyhuc0079** [comment]
我今天更新了一下（我并不知道实际最近的release是哪天）
现在长文本支持的已经很好了基本没有掉句子
而且电音也没有了，不过我这次训练没有用默认的32k采样率不知道有没有关系

**Comment by magicmagicspider** [comment]
文本多的时候会报错
RuntimeError: torch.cat(): expected a non-empty list of Tensors
这是什么原因，求解

**Comment by hyhuc0079** [comment]
ls你看看你是不是选错语言了？

**Comment by magicmagicspider** [comment]
> ls你看看你是不是选错语言了？

哦哦发现了是我文本的问题，文本中有很多“，这个貌似会出问题，替换掉之后就没出问题了

**Comment by RVC-Boss** [comment]
找一个你模型习惯的切割方式。现在已经不需要先手工切割再喂进去推理点2下了。

**Comment by venusyob** [comment]
请问AI模型读不出A字母发音
