### ISSUE TITLE
英文数据集的训练和推理

### ISSUE THREAD

**Issue by RoversX** [RVC-Boss/GPT-SoVITS#296]
想请问一下现在支持英文数据集的微调和推理了吗？
看README支持了English dataset fine tune training.

**Comment by RVC-Boss** [comment]
支持了，但是文本标注还没加，要自己想办法

**Comment by RoversX** [comment]
> 支持了，但是文本标注还没加，要自己想办法

请问那个pretrain模型是中文的也可以吗？ 这方面不太了解。

**Comment by potatoker** [comment]
试了一下，虽然使用的 model 仍然是GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large和GPT_SoVITS/pretrained_models/chinese-hubert-base，但是英文音频数据训练出来的中英文都还行（英文稍微有股洋腔洋调）。不知道英文数据下强行这么用pretrain Model是不是推荐的。

**Comment by RoversX** [comment]
> 试了一下，虽然使用的 model 仍然是GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large和GPT_SoVITS/pretrained_models/chinese-hubert-base，但是英文音频数据训练出来的中英文都还行（中文稍微有股洋腔洋调）。不知道英文数据下强行这么用pretrain Model是不是推荐的。

英文效果如何？

**Comment by potatoker** [comment]
> > 试了一下，虽然使用的 model 仍然是GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large和GPT_SoVITS/pretrained_models/chinese-hubert-base，但是英文音频数据训练出来的中英文都还行（中文稍微有股洋腔洋调）。不知道英文数据下强行这么用pretrain Model是不是推荐的。
> 
> 英文效果如何？

蛮好的，没有大问题（没有泛化测试的情况下）
