### ISSUE TITLE
GPT训练出现FileNotFoundError: Could not find module

### ISSUE THREAD

**Issue by gangirl** [RVC-Boss/GPT-SoVITS#300]
GPT训练不出现模型，报错显示FileNotFoundError: Could not find module 'E:\tool\GPT-SoVITS-beta0128\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by RVC-Boss** [comment]
不要紧。
