### ISSUE TITLE
在colab打开，第一步建立环境的时候，出现这个错误WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead怎么解决呢？

### ISSUE THREAD

**Issue by lishu44275** [RVC-Boss/GPT-SoVITS#302]
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead

请问，纯小白

**Comment by RVC-Boss** [comment]
不重要。

**Comment by lishu44275** [comment]
> 不重要。

可是进行不下去了呢？难道直接进行第二步嘛？谢谢回答
