### ISSUE TITLE
MacOS MPS issue

### ISSUE THREAD

**Issue by Wiphone** [RVC-Boss/GPT-SoVITS#306]
在推理之前的所有步骤都正常运行，但是到了开始跑推理时，一直报错如下：
<img width="1493" alt="image" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/3424236/32453cc1-77c5-47a2-9046-29a70f4ec5a0">

**Comment by XXXXRT666** [comment]
你这好像没啥问题，能生成音频吗
