### ISSUE TITLE
No module named 'torch'

### ISSUE THREAD

**Issue by fedavinci** [RVC-Boss/GPT-SoVITS#307]
照着README的 For Mac Users 部分做的

```
conda create -n GPTSoVits python=3.9
conda activate GPTSoVits

pip install -r requirements.txt
pip uninstall torch torchaudio
pip3 install --pre torch torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

python webui.py
```

结果报错
```
Traceback (most recent call last):
  File "/Users/taoxu/Desktop/GPT-SoVITS/webui.py", line 4, in <module>
    import json,yaml,warnings,torch
ModuleNotFoundError: No module named 'torch'
```

**Comment by Lion-Wu** [comment]
重新安装一遍`pip3 install --pre torch torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu`试试，确保安装成功

**Comment by fedavinci** [comment]
> 重新安装一遍`pip3 install --pre torch torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu`试试，确保安装成功

下午重装过两遍都不行，刚才重装了一下 好了

**Comment by skyceo121** [comment]
我安装了 但是启动 就会爆这样的错误(base) (venv) skyceo@skyceodeMacBook-Pro GPT-SoVITS % python3 webui.py
Traceback (most recent call last):
  File "/Users/skyceo/GPT-SoVITS/webui.py", line 4, in <module>
    import json,yaml,warnings,torch
ModuleNotFoundError: No module named 'yaml'
我是苹果系统m2  是不是没有吧模型下载过来。
