### ISSUE TITLE
这个

### ISSUE THREAD

**Issue by inkjhhh** [RVC-Boss/GPT-SoVITS#313]
C:\Users\Administrator\Desktop\GPT-SoVITS-main>runtime\python.exe webui.py
系统找不到指定的路径。

C:\Users\Administrator\Desktop\GPT-SoVITS-main>pause
请按任意键继续. . .

**Comment by RVC-Boss** [comment]
确保runtime下存在python.exe这个文件
压缩包里这个文件是有的。
