### ISSUE TITLE
Docker部署 webui无法弹出

### ISSUE THREAD

**Issue by partnerSun** [RVC-Boss/GPT-SoVITS#324]
`docker run --name="GPT-SoVITS" --gpus=all \
  --env=is_half=False \
  -v /mnt/sdb1/GPT-SoVITS/output:/workspace/output \
  -v /mnt/sdb1/GPT-SoVITS/infiles:/workspace/infiles \
  -v /mnt/sdb1/GPT-SoVITS/logs:/workspace/logs \
  -v /mnt/sdb1/GPT-SoVITS/SoVITS_weights:/workspace/SoVITS_weights \
  -v /mnt/sdb1/GPT-SoVITS/pretrained_models:/workspace/pretrained_models \
  --workdir=/workspace \
  -p 9870:9870 \
  -p 9871:9871 \
  -p 9872:9872 \
  -p 9873:9873 \
  -p 9874:9874 \
  --shm-size="16G" \
  -d breakstring/gpt-sovits:dev-20240127`

所有webui选项都没有响应
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/35442573/2533cb5a-0878-4751-9ba9-5234a9a75ddd)
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/35442573/4d2989bd-62c0-4cc7-9305-52e9e71ac156)

没有日志，远程访问 非本地访问

**Comment by RVC-Boss** [comment]
docker不会自动弹出，要自己映射url拼出来网页打开

**Comment by partnerSun** [comment]
> docker不会自动弹出，要自己映射url拼出来网页打开

请问拼接规范是什么

**Comment by partnerSun** [comment]
> docker不会自动弹出，要自己映射url拼出来网页打开

我悟了，不同端口号
