### ISSUE TITLE
开启打标webUi时，未弹出新页面

### ISSUE THREAD

**Issue by SimpleTangLong** [RVC-Boss/GPT-SoVITS#325]
![1706689892539](https://github.com/RVC-Boss/GPT-SoVITS/assets/112692042/a87fce8b-b288-4d4a-885d-0a770e606fd1)

好像是没有文件夹的权限，这种情况如何处理呢？

**Comment by RVC-Boss** [comment]
填.list文件路径，别填文件夹。
