### ISSUE TITLE
ASR不自动生成文件夹和.list文件

### ISSUE THREAD

**Issue by Stanley-baby** [RVC-Boss/GPT-SoVITS#327]
- 进行 asr 预处理时在output 文件夹里不生成文件夹和.list文件
- 终端显示：
![CleanShot 2024-01-31 at 17 38 48@2x](https://github.com/RVC-Boss/GPT-SoVITS/assets/58399659/29ec27e4-ea8f-4c38-85c5-0ea09c5658e9)

**Comment by MiracleSia** [comment]
自己的环境也是一样的问题，用打包的就没事。。。

**Comment by MiracleSia** [comment]
更新funasr和modelscope，funasr>=1.0.0, modelscope>=1.11.1 ，然后重新down一下tools/damo_asr/models文件

**Comment by RVC-Boss** [comment]
楼上正解。
