### ISSUE TITLE
怎么使用？

### ISSUE THREAD

**Issue by PangXitong** [RVC-Boss/GPT-SoVITS#330]
按照Readme文件整好后运行这个
cd /Users/mac/Desktop/GPT-SoVITS
conda activate GPTSoVits
python /Users/mac/Desktop/GPT-SoVITS/webui.py
然后显示一个网页，然后怎么用啊？
<img width="2048" alt="截屏2024-01-31 20 21 39" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/112756665/31337f3d-ebfe-4abc-a917-ae312e70b875">

**Comment by RVC-Boss** [comment]
可以看教程
https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e
