### ISSUE TITLE
推理延迟太高

### ISSUE THREAD

**Issue by tuotuoshao** [RVC-Boss/GPT-SoVITS#339]
试了下，3070 ti，100多个字pred_semantic的生成占大头，达十多秒，如果拆分时间应该会更久。
之前用vits还有bert-vits2，几百个字基本都在两三秒内完成，字多显存多罢了。
该怎么提高推理速度？

**Comment by RVC-Boss** [comment]
节后的模型速度会double，模型小容量版
剩下的则需要工程硬件推理优化了

**Comment by tuotuoshao** [comment]
收到

**Comment by stevin-dong** [comment]
> 节后的模型速度会double，模型小容量版 剩下的则需要工程硬件推理优化了

作者大佬，现在速度有提高了吗？
