### ISSUE TITLE
will support base models retraining? 

### ISSUE THREAD

**Issue by gray4what** [RVC-Boss/GPT-SoVITS#344]
retrain the base models: huberts, roberta, etc from scratch with other languages?

**Comment by RVC-Boss** [comment]
train-from-scratch: https://github.com/RVC-Boss/GPT-SoVITS/wiki/%E4%BB%8E%E9%9B%B6%E8%AE%AD%E7%BB%83(train-from-scratch)

how to train the models with other languages: https://github.com/RVC-Boss/GPT-SoVITS/wiki/%E8%AE%AD%E7%BB%83%E6%96%B0%E8%AF%AD%E8%A8%80(how-to-train-the-models-with-other-languages)

**Comment by RVC-Boss** [comment]
hubert training is not supported by gpt-sovits
