### ISSUE TITLE
施工中，请静候佳音

### ISSUE THREAD

**Issue by wangwenjie1314** [RVC-Boss/GPT-SoVITS#349]
我现在 打开显示 施工中，请静候佳音

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/4018406/6211ec61-95c1-4c1b-8542-13b25a303828)

但是我在哔哩哔哩上看到 博主可以操作啊？ 

https://www.bilibili.com/video/BV1Ap4y1U7jW/?spm_id_from=333.999.0.0&vd_source=102779c9d18746204930fe574c2e5e57

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/4018406/262229fe-286e-45d5-b732-acbba906173e)

**Comment by GuanTou12138** [comment]
一个是文本转语音，一个是变声，现在变声还没出来。。

**Comment by wangwenjie1314** [comment]
> 一个是文本转语音，一个是变声，现在变声还没出来。。

但是你看 哔哩哔哩的博主 操作出第三步了，你看看我截图，我都看到他 让狂徒张三 去读文本了


![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/4018406/8bb505aa-135e-4252-babe-af8fd8bf7b70)

**Comment by GuanTou12138** [comment]
打一段话，让他读出来，就是tts文本转语音，视频里的up主做的也是这个。而在施工中的，是把一段音频里一个人的声音换成另一个人的声音，就像那些AI唱歌

**Comment by wangwenjie1314** [comment]
> 打一段话，让他读出来，就是tts文本转语音，视频里的up主做的也是这个。而在施工中的，是把一段音频里一个人的声音换成另一个人的声音，就像那些AI唱歌

但是你有没有发现，他读的时候是用的 训练出来的音色去读的，这一块是我不知道怎么实现的。

**Comment by wangwenjie1314** [comment]
> > 打一段话，让他读出来，就是tts文本转语音，视频里的up主做的也是这个。而在施工中的，是把一段音频里一个人的声音换成另一个人的声音，就像那些AI唱歌
> 
> 但是你有没有发现，他读的时候是用的 训练出来的音色去读的，这一块是我不知道怎么实现的。

我又仔细看了下，他是在第二个tab下点击的TTS推理，我知道了，多谢，还是刚开始学。

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/4018406/35d4771c-c952-42f2-98ee-53c1999c5513)

**Comment by huangxu1991** [comment]
> 一个是文本转语音，一个是变声，现在变声还没出来。。

变声参考这个：https://github.com/huangxu1991/GPT-SoVITS-VC

**Comment by ningxiaofeifei** [comment]
转歌声是在哪里搞呀哥，找到了吗
