### ISSUE TITLE
runtime报错

### ISSUE THREAD

**Issue by xiaoxu66609** [RVC-Boss/GPT-SoVITS#358]
没有runtime文件夹
![屏幕截图 2024-02-02 203632](https://github.com/RVC-Boss/GPT-SoVITS/assets/158005210/b24983f8-86c4-433b-81f9-8f161f219415)

**Comment by RVC-Boss** [comment]
确保runtime下存在python.exe文件

**Comment by vonjunyi** [comment]
> 确保runtime下存在python.exe文件
zip包里都没有runtime
