### ISSUE TITLE
ModuleNotFoundError: No module named 'feature_extractor'

### ISSUE THREAD

**Issue by a614349007** [RVC-Boss/GPT-SoVITS#370]
在conda环境中跑api.py文件，报错找不到feature_extractor'模块。用pip安装后依旧报错找不到。
`(GPTSoVits) E:\GPT-SoVITS\GPT-SoVITS-beta>python .\api.py
Traceback (most recent call last):
  File "E:\GPT-SoVITS\GPT-SoVITS-beta\api.py", line 118, in <module>
    from feature_extractor import cnhubert
ModuleNotFoundError: No module named 'feature_extractor'`

**Comment by xiaolongww** [comment]
大佬后来是怎么解决的，同样问题+1 :)

**Comment by zhudisha** [comment]
同这个问题
