### ISSUE TITLE
我找到暫時的解法了

### ISSUE THREAD

**Issue by fgod999** [RVC-Boss/GPT-SoVITS#378]
我找到暫時的解法了
打開GPT-SoVITS\runtime\lib\site-packages\torch\distributed\rendezvous.py
找到這行start_daemon = rank == 0大約在175行
下方增加一行hostname = "localhost"就可以了

已加入，仍然無效

**Comment by RVC-Boss** [comment]
你指的是对于什么问题的解法？

**Comment by fgod999** [comment]
> ```
>           我找到暫時的解法了
> ```
> 
> 打開GPT-SoVITS\runtime\lib\site-packages\torch\distributed\rendezvous.py 找到這行start_daemon = rank == 0大約在175行 下方增加一行hostname = "localhost"就可以了
> 
> 已加入，仍然無效
不知道為何會另開主題
文章在這
https://github.com/RVC-Boss/GPT-SoVITS/issues/48
