### ISSUE TITLE
多角色音频训练集一起训练和单角色音频分开训练的区别

### ISSUE THREAD

**Issue by ruokbb** [RVC-Boss/GPT-SoVITS#382]
把多角色的音频放到一起训练出来的模型，通过不同角色的参考音频来切换音色，和单角色分开训练模型，效果上会有区别吗？哪个会更好？

多角色音频放到一起训练模型，是不是更像底模？可以更加适配训练的那些角色音色吗

**Comment by RVC-Boss** [comment]
可以多角色一起训练，通过参考音频选音色。
更建议单角色训练。

**Comment by ruokbb** [comment]
> 可以多角色一起训练，通过参考音频选音色。 更建议单角色训练。

好嘞，感谢
