### ISSUE TITLE
上传1分钟的参考语音和文字。推理出来直接静音。

### ISSUE THREAD

**Issue by luyao-cv** [RVC-Boss/GPT-SoVITS#385]

**Comment by RVC-Boss** [comment]
这个几天前已经禁止上传超过10秒的参考音频了。

**Comment by luyao-cv** [comment]
是模型不允许上传10s的音频吗？我把上传超过10s的那段raise代码去掉了，推出来是静音。

**Comment by luyao-cv** [comment]
> 这个几天前已经禁止上传超过10秒的参考音频了。

是模型不允许上传10s的音频吗？我把上传超过10s的那段raise代码去掉了，推出来是静音。
