### ISSUE TITLE
请问参考语音不能超过10s的原理是什么？如果强行设置成1min，推出来会是静音

### ISSUE THREAD

**Issue by luyao-cv** [RVC-Boss/GPT-SoVITS#386]

**Comment by luyao-cv** [comment]
太容易吃字了。我强行上传30s语音。很多字都被吃了。
![51c748011859a78a8a33e5fde3da8cbf](https://github.com/RVC-Boss/GPT-SoVITS/assets/29787866/5de1dbf0-be6f-4f2c-a5b8-b9d81c2ec642)

**Comment by RVC-Boss** [comment]
仅仅是因为训练集没见过。
