### ISSUE TITLE
新手期待出一个整合包

### ISSUE THREAD

**Issue by angenet** [RVC-Boss/GPT-SoVITS#4]
对于新手来说，自己搭建配置环境太复杂，要是有大大能出一个整合包，感激不尽

**Comment by tumuidle** [comment]
https://www.bilibili.com/video/BV12g4y1m7Uw

**Comment by RoversX** [comment]
作者AutoDL上面发了整合包了

https://www.codewithgpu.com/i/RVC-Boss/GPT-SoVITS/GPT-SoVITS

**Comment by RVC-Boss** [comment]
Foreigner friends can use this:
https://huggingface.co/lj1995/GPT-SoVITS-windows-package/resolve/main/GPT-SoVITS-beta.7z?download=true
