### ISSUE TITLE
ASR 报错 KeyError: 'funasr-pipeline is not in the pipelines registry group auto-speech-recognition. 

### ISSUE THREAD

**Issue by hhucchenyixiao** [RVC-Boss/GPT-SoVITS#40]
我按照下面放了模型，但是运行仍然报错
![图片](https://github.com/RVC-Boss/GPT-SoVITS/assets/96377023/17b7cee5-0fb3-436f-a973-d542c8a83dcb)

```
modelscope - WARNING - ('PIPELINES', 'auto-speech-recognition', 'funasr-pipeline') not found in ast index file
Traceback (most recent call last):
  File "D:\ai\GPT-SoVITS\tools\damo_asr\cmd-asr.py", line 9, in <module>
    inference_pipeline = pipeline(
  File "D:\software\miniconda\envs\GPTSoVits\lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "D:\software\miniconda\envs\GPTSoVits\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "D:\software\miniconda\envs\GPTSoVits\lib\site-packages\modelscope\utils\registry.py", line 198, in build_from_cfg
    raise KeyError(
KeyError: 'funasr-pipeline is not in the pipelines registry group auto-speech-recognition. Please make sure the correct version of ModelScope library is used.'
```

**Comment by quicksandznzn** [comment]
我也是一样的问题 
funasr 0.8.8  
modelscope 1.11.0

**Comment by wickedvalley** [comment]
+1

**Comment by liuyiheng001** [comment]
+1

**Comment by 1713172499** [comment]
我也卡在这了

**Comment by 1713172499** [comment]
参考这里修改，重新运行会自动下载到C盘，就解决了。
https://github.com/RVC-Boss/GPT-SoVITS/issues/26#issuecomment-1895420620

**Comment by selfboot** [comment]
> 参考这里修改，重新运行会自动下载到C盘，就解决了。 [#26 (comment)](https://github.com/RVC-Boss/GPT-SoVITS/issues/26#issuecomment-1895420620)

我参考这里改了，重新走网络下载，报一样的错误

**Comment by 1713172499** [comment]
> > 参考这里修改，重新运行会自动下载到C盘，就解决了。 [#26 (comment)](https://github.com/RVC-Boss/GPT-SoVITS/issues/26#issuecomment-1895420620)
> 
> 我参考这里改了，重新走网络下载，报一样的错误

我重下之后就好了，或者你降级funasr试试，重下前我也执行了降级。
pip install funasr==0.8.7
pip install modelscope==1.10.0

**Comment by selfboot** [comment]
> pip install modelscope==1.10.0

降级modelscope就可以了

**Comment by hhucchenyixiao** [comment]
试了试，最后通过 https://github.com/RVC-Boss/GPT-SoVITS/issues/26#issuecomment-1895420620 修改文件，加上降级
pip install funasr==0.8.7
pip install modelscope==1.10.0
成功运行了。
但是这样会在用户目录下 `~\.cache\modelscope\hub\damo` 重新下载了 3 个模型，而不是调用手动下载到 `.\tools\damo_asr\models`  的模型

**Comment by quicksandznzn** [comment]
> 我也是一样的问题 funasr 0.8.8 modelscope 1.11.0

和楼下一样用whisper处理了

**Comment by hyhuc0079** [comment]
我看阿里那边的反馈应该是asr更新以后推荐使用新的加载方式
https://github.com/alibaba-damo-academy/FunASR/issues/1238
所以应该是降级就可以用
估计是作者测试的时候自己的环境还没有更新所以没遇到错误，所以他给的asr安装步骤也是直接安装最新
大家可以先用刘悦那个asr转写工具，我看他的requirement里限定了版本号，funasr应该不会报错
这边应该后续迭代的时候会修复
不过刘悦的我没测试，我装的时候我把版本号去掉了所以我用刘悦那个也会报这个错

**Comment by hyhuc0079** [comment]
测了一下他那个没问题，可以先用他的生成转写文件，这边先暂时等更新，以后没准直接整合那边的过来呢

**Comment by hhucchenyixiao** [comment]
> > 试了试，最后通过 [#26 (comment)](https://github.com/RVC-Boss/GPT-SoVITS/issues/26#issuecomment-1895420620) 修改文件，加上降级 pip install funasr==0.8.7 pip install modelscope==1.10.0 成功运行了。 但是这样会在用户目录下 `~\.cache\modelscope\hub\damo` 重新下载了 3 个模型，而不是调用手动下载到 `.\tools\damo_asr\models` 的模型
> 
> 降级的话，应该不用修改文件，直接用本地下载的就行了的

我把文件改回去了，把下载到C盘的模型移到工程目录下了的确可以用，不知道为啥最开始光降级没用

**Comment by bruce2233** [comment]
> > > 参考这里修改，重新运行会自动下载到C盘，就解决了。 [#26 (comment)](https://github.com/RVC-Boss/GPT-SoVITS/issues/26#issuecomment-1895420620)
> > 
> > 
> > 我参考这里改了，重新走网络下载，报一样的错误
> 
> 我重下之后就好了，或者你降级funasr试试，重下前我也执行了降级。 pip install funasr==0.8.7 pip install modelscope==1.10.0

不行

**Comment by potatoker** [comment]
> > 我也是一样的问题 funasr 0.8.8 modelscope 1.11.0
> 
> 和楼上一样用whisper处理了

请问用whisper的话输出格式是whisper的带时间戳的json文件吗

**Comment by quicksandznzn** [comment]
> > > 我也是一样的问题 funasr 0.8.8 modelscope 1.11.0
> > 
> > 
> > 和楼上一样用whisper处理了
> 
> 请问用whisper的话输出格式是whisper的带时间戳的json文件吗

看下cmd-asr的源码 改成whisper就行

**Comment by Postroggy** [comment]
> > > 参考这里修改，重新运行会自动下载到C盘，就解决了。 [#26 (comment)](https://github.com/RVC-Boss/GPT-SoVITS/issues/26#issuecomment-1895420620)
> > 
> > 
> > 我参考这里改了，重新走网络下载，报一样的错误
> 
> 我重下之后就好了，或者你降级funasr试试，重下前我也执行了降级。 pip install funasr==0.8.7 pip install modelscope==1.10.0

成功运行，感谢

**Comment by LauraGPT** [comment]
Solution: https://github.com/RVC-Boss/GPT-SoVITS/issues/194#issuecomment-1910205929

**Comment by RVC-Boss** [comment]
Fixed by merging https://github.com/RVC-Boss/GPT-SoVITS/pull/135.
