### ISSUE TITLE
windows整合包 numpy和 rotary_embedding_torch报错

### ISSUE THREAD

**Issue by einsflash** [RVC-Boss/GPT-SoVITS#402]
![1](https://github.com/RVC-Boss/GPT-SoVITS/assets/73737253/134d40d3-9516-40a6-bf7c-a31e6a02dbcb)
使用整合包的时候打开asr，tts推理的时候都报错了，怎么解决呀

**Comment by suonian** [comment]
numpy 版本不对吧！

**Comment by einsflash** [comment]
> numpy 版本不对吧！

是的，但我没看出来应该是哪个版本
还有就是整合包里的环境按理说不会出问题吧

**Comment by RVC-Boss** [comment]
可能是系统自带其他python环境混淆了？

**Comment by einsflash** [comment]
都能用了，虽然还是显示包有冲突




E:\1_AI_Voice\GPT-SoVITS-beta>.\runtime\python.exe -m pip install -U rotary_embedding_torch
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting rotary_embedding_torch
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0d/e1/1f9f7aebd2e424e750c495d2b253baba8db69759ee355801e368cb1d9bb2/rotary_embedding_torch-0.5.3-py3-none-any.whl (5.3 kB)
Collecting beartype (from rotary_embedding_torch)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/70/1a/1833bea6f648d301b24b265c5b41f6979ff321a0f607b0db6d721a0ad7a0/beartype-0.17.0-py3-none-any.whl (866 kB)
     ---------------------------------------- 866.1/866.1 kB 608.3 kB/s eta 0:00:00
Requirement already satisfied: einops>=0.7 in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (from rotary_embedding_torch) (0.7.0)
Requirement already satisfied: torch>=2.0 in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (from rotary_embedding_torch) (2.0.0+cu118)
Requirement already satisfied: filelock in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (from torch>=2.0->rotary_embedding_torch) (3.10.0)
Requirement already satisfied: typing-extensions in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (from torch>=2.0->rotary_embedding_torch) (4.4.0)
Requirement already satisfied: sympy in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (from torch>=2.0->rotary_embedding_torch) (1.11.1)
Requirement already satisfied: networkx in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (from torch>=2.0->rotary_embedding_torch) (2.8.8)
Requirement already satisfied: jinja2 in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (from torch>=2.0->rotary_embedding_torch) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (from jinja2->torch>=2.0->rotary_embedding_torch) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (from sympy->torch>=2.0->rotary_embedding_torch) (1.2.1)
Installing collected packages: beartype, rotary_embedding_torch
Successfully installed beartype-0.17.0 rotary_embedding_torch-0.5.3

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: E:\1_AI_Voice\GPT-SoVITS-beta\runtime\python.exe -m pip install --upgrade pip

E:\1_AI_Voice\GPT-SoVITS-beta>E:\1_AI_Voice\GPT-SoVITS-beta\runtime\Scripts\pip.exe install --upgrade numpy
Fatal error in launcher: Unable to create process using '"E:\codes\py39\test-20230416b\RVC-beta-v2-0528\runtime\python.exe"  "E:\1_AI_Voice\GPT-SoVITS-beta\runtime\Scripts\pip.exe" install --upgrade numpy': ???????????


E:\1_AI_Voice\GPT-SoVITS-beta>.\runtime\python.exe -m pip install --upgrade numpy
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: numpy in c:\users\zhuya\appdata\roaming\python\python39\site-packages (1.22.4)
Collecting numpy
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b5/42/054082bd8220bbf6f297f982f0a8f5479fcbc55c8b511d928df07b965869/numpy-1.26.4-cp39-cp39-win_amd64.whl (15.8 MB)
     ---------------------------------------- 15.8/15.8 MB 7.9 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4
  WARNING: The script f2py.exe is installed in 'E:\1_AI_Voice\GPT-SoVITS-beta\runtime\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'C:\\Users\\zhuya\\AppData\\Roaming\\Python\\Python39\\site-packages\\~umpy\\.libs\\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: E:\1_AI_Voice\GPT-SoVITS-beta\runtime\python.exe -m pip install --upgrade pip

E:\1_AI_Voice\GPT-SoVITS-beta>.\runtime\python.exe -m pip install --upgrade numpy
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: numpy in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (1.23.5)
Collecting numpy
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b5/42/054082bd8220bbf6f297f982f0a8f5479fcbc55c8b511d928df07b965869/numpy-1.26.4-cp39-cp39-win_amd64.whl (15.8 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
  WARNING: The script f2py.exe is installed in 'E:\1_AI_Voice\GPT-SoVITS-beta\runtime\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fairseq 0.12.2 requires hydra-core<1.1,>=1.0.7, but you have hydra-core 1.3.2 which is incompatible.
fairseq 0.12.2 requires omegaconf<2.1, but you have omegaconf 2.3.0 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.26.4 which is incompatible.
scipy 1.9.3 requires numpy<1.26.0,>=1.18.5, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: E:\1_AI_Voice\GPT-SoVITS-beta\runtime\python.exe -m pip install --upgrade pip

E:\1_AI_Voice\GPT-SoVITS-beta>.\runtime\python.exe -m pip install numpy==1.23.5
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting numpy==1.23.5
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/08/36/6589c7d5fc4fecda63de4453fefff7c58f6de2b1bb7dfbe7fa807bf85c46/numpy-1.23.5-cp39-cp39-win_amd64.whl (14.7 MB)
     ---------------------------------------- 14.7/14.7 MB 9.6 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  WARNING: The script f2py.exe is installed in 'E:\1_AI_Voice\GPT-SoVITS-beta\runtime\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fairseq 0.12.2 requires hydra-core<1.1,>=1.0.7, but you have hydra-core 1.3.2 which is incompatible.
fairseq 0.12.2 requires omegaconf<2.1, but you have omegaconf 2.3.0 which is incompatible.
Successfully installed numpy-1.23.5

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: E:\1_AI_Voice\GPT-SoVITS-beta\runtime\python.exe -m pip install --upgrade pip

E:\1_AI_Voice\GPT-SoVITS-beta>E:\1_AI_Voice\GPT-SoVITS-beta\runtime\Scripts\python.exe -m pip install "hydra-core<1.1,>=1.0.7" "omegaconf<2.1"
'E:\1_AI_Voice\GPT-SoVITS-beta\runtime\Scripts\python.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

E:\1_AI_Voice\GPT-SoVITS-beta>.\runtime\python.exe -m pip install "hydra-core<1.1,>=1.0.7" "omegaconf<2.1"
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting hydra-core<1.1,>=1.0.7
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/5f/2a/9c698daa12ed6e09e7629e6908528f043fa9de8a441c56cc13608d765fb2/hydra_core-1.0.7-py3-none-any.whl (123 kB)
     ---------------------------------------- 123.8/123.8 kB 191.1 kB/s eta 0:00:00
Collecting omegaconf<2.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d0/eb/9d63ce09dd8aa85767c65668d5414958ea29648a0eec80a4a7d311ec2684/omegaconf-2.0.6-py3-none-any.whl (36 kB)
Collecting antlr4-python3-runtime==4.8 (from hydra-core<1.1,>=1.0.7)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/56/02/789a0bddf9c9b31b14c3e79ec22b9656185a803dc31c15f006f9855ece0d/antlr4-python3-runtime-4.8.tar.gz (112 kB)
     ---------------------------------------- 112.4/112.4 kB 650.7 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: PyYAML>=5.1.* in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (from omegaconf<2.1) (6.0)
Requirement already satisfied: typing-extensions in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (from omegaconf<2.1) (4.4.0)
Building wheels for collected packages: antlr4-python3-runtime
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.8-py3-none-any.whl size=141217 sha256=c8917840a8813c897676f1ec33f2b72a7da0a6b57512d81f3a24419c0f425039
  Stored in directory: c:\users\zhuya\appdata\local\pip\cache\wheels\ca\f8\40\218f8352de306c7febac08533df409791668006d2c0bbc8275
Successfully built antlr4-python3-runtime
Installing collected packages: antlr4-python3-runtime, omegaconf, hydra-core
  Attempting uninstall: antlr4-python3-runtime
    Found existing installation: antlr4-python3-runtime 4.9.3
    Uninstalling antlr4-python3-runtime-4.9.3:
      Successfully uninstalled antlr4-python3-runtime-4.9.3
  Attempting uninstall: omegaconf
    Found existing installation: omegaconf 2.3.0
    Uninstalling omegaconf-2.3.0:
      Successfully uninstalled omegaconf-2.3.0
  Attempting uninstall: hydra-core
    Found existing installation: hydra-core 1.3.2
    Uninstalling hydra-core-1.3.2:
      Successfully uninstalled hydra-core-1.3.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
funasr 1.0.0 requires hydra-core>=1.3.2, but you have hydra-core 1.0.7 which is incompatible.
Successfully installed antlr4-python3-runtime-4.8 hydra-core-1.0.7 omegaconf-2.0.6

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: E:\1_AI_Voice\GPT-SoVITS-beta\runtime\python.exe -m pip install --upgrade pip

E:\1_AI_Voice\GPT-SoVITS-beta>.\runtime\python.exe -m pip install "hydra-core>=1.3.2"
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting hydra-core>=1.3.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c6/50/e0edd38dcd63fb26a8547f13d28f7a008bc4a3fd4eb4ff030673f22ad41a/hydra_core-1.3.2-py3-none-any.whl (154 kB)
     ---------------------------------------- 154.5/154.5 kB 188.6 kB/s eta 0:00:00
Collecting omegaconf<2.4,>=2.2 (from hydra-core>=1.3.2)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e3/94/1843518e420fa3ed6919835845df698c7e27e183cb997394e4a670973a65/omegaconf-2.3.0-py3-none-any.whl (79 kB)
     ---------------------------------------- 79.5/79.5 kB 887.9 kB/s eta 0:00:00
Collecting antlr4-python3-runtime==4.9.* (from hydra-core>=1.3.2)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/3e/38/7859ff46355f76f8d19459005ca000b6e7012f2f1ca597746cbcd1fbfe5e/antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
     ---------------------------------------- 117.0/117.0 kB 757.4 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: packaging in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (from hydra-core>=1.3.2) (22.0)
Requirement already satisfied: PyYAML>=5.1.0 in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (from omegaconf<2.4,>=2.2->hydra-core>=1.3.2) (6.0)
Building wheels for collected packages: antlr4-python3-runtime
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144578 sha256=0c849a52e17b62873533e43b5fd2ca4dfdaf98b475527242688443e2ea3243cf
  Stored in directory: c:\users\zhuya\appdata\local\pip\cache\wheels\b9\0a\c0\fc0de68aa14c7066272aed9fdf29080aad637f3530d865ac86
Successfully built antlr4-python3-runtime
Installing collected packages: antlr4-python3-runtime, omegaconf, hydra-core
  Attempting uninstall: antlr4-python3-runtime
    Found existing installation: antlr4-python3-runtime 4.8
    Uninstalling antlr4-python3-runtime-4.8:
      Successfully uninstalled antlr4-python3-runtime-4.8
  Attempting uninstall: omegaconf
    Found existing installation: omegaconf 2.0.6
    Uninstalling omegaconf-2.0.6:
      Successfully uninstalled omegaconf-2.0.6
  Attempting uninstall: hydra-core
    Found existing installation: hydra-core 1.0.7
    Uninstalling hydra-core-1.0.7:
      Successfully uninstalled hydra-core-1.0.7
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fairseq 0.12.2 requires hydra-core<1.1,>=1.0.7, but you have hydra-core 1.3.2 which is incompatible.
fairseq 0.12.2 requires omegaconf<2.1, but you have omegaconf 2.3.0 which is incompatible.
Successfully installed antlr4-python3-runtime-4.9.3 hydra-core-1.3.2 omegaconf-2.3.0

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: E:\1_AI_Voice\GPT-SoVITS-beta\runtime\python.exe -m pip install --upgrade pip

E:\1_AI_Voice\GPT-SoVITS-beta>E:\1_AI_Voice\GPT-SoVITS-beta\runtime\python.exe -m pip install --upgrade pip
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pip in e:\1_ai_voice\gpt-sovits-beta\runtime\lib\site-packages (23.1.2)
Collecting pip
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8a/6a/19e9fe04fca059ccf770861c7d5721ab4c2aebc539889e97c7977528a53b/pip-24.0-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 1.1 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
  WARNING: The scripts pip.exe, pip3.9.exe and pip3.exe are installed in 'E:\1_AI_Voice\GPT-SoVITS-beta\runtime\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-24.0
