### ISSUE TITLE
运行API.PY报错：ModuleNotFoundError: No module named 'jieba_fast'

### ISSUE THREAD

**Issue by jiangfan99** [RVC-Boss/GPT-SoVITS#407]
报错后安装jieba_fast,但是无法安装成功，请大佬看看有没有遇到过这个问题，如何解决的，跪谢（头点地）
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/109214143/4624b374-f558-42de-bab7-8ca3e157be3b)
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/109214143/d048fa34-6c46-497a-8906-027b3e8e0dcf)

**Comment by shaoqing404** [comment]
更新过程中，jieba_fast安装失败的小伙伴到这里下载对应的轮子，丢到项目目录的runtime目录下，然后在这个目录中打开cmd，用
python.exe pip install (你下载的文件名，比如jieba_fast-0.53-cp311-cp311-linux_armv7l.whl) 进行安装，装完了删掉就行

https://www.piwheels.org/project/jieba-fast/

**Comment by shaoqing404** [comment]
如果你用的是别的环境，不是runtime中自带的python环境，那就在你的环境中安装，不用去管runtime的环境。

**Comment by jiangfan99** [comment]
非常感谢两位大佬的解答，目前安装完VS后就能安装JIEBA-FAST了
