### ISSUE TITLE
可能是爆内存了，康康你的内存

### ISSUE THREAD

**Issue by landones** [RVC-Boss/GPT-SoVITS#423]
可能是爆内存了，康康你的内存
2楼的告警不重要。

_Originally posted by @RVC-Boss in https://github.com/RVC-Boss/GPT-SoVITS/issues/399#issuecomment-1931412956_
            内存是什么意思？系统内存还是显存？我这配置16G运存，4060 8G显存，可是开2都会出现这种报错欸

**Comment by Atopona** [comment]
内存，可能是内存不够，我看第一张图显示DefaultCPUAllocator: not enough memory: you tried to allocate 2099200 bytes
Pytorch 默认CPU分配器(DefaultCPUAllocator): 内存不足

**Comment by Atopona** [comment]
可以任务管理器看一下有什么占内存的应用给关闭一下
