### ISSUE TITLE
卡在gpt训练

### ISSUE THREAD

**Issue by chenxiaobin3000** [RVC-Boss/GPT-SoVITS#431]
我用的整合包，按视频教程操作，在开启GPT训练以后就卡住了。机器内存32G，显卡4060Ti 16G。请问是什么原因？
命令行日志：
D:\AI\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/s1_train.py --config_file "D:\AI\GPT-SoVITS\TEMP/tmp_s1.yaml"
Seed set to 1234
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
<All keys matched successfully>
ckpt_path: None
[rank: 0] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
然后就一直卡住，没有任何反应，有一次点重试，页面出现0/530.7，然后等它跑，一直超过530还在不停的跑，不会停。

**Comment by RVC-Boss** [comment]
win10？

**Comment by chenxiaobin3000** [comment]
对，按另一个up的回复，修复了。

西佩特up
这是win10 1909的bug，打开 项目根目录\runtime\Lib\site-packages\lightning_fabric\utilities\distributed.py中的第290行。把
torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
改为
torch.distributed.init_process_group(backend=torch_distributed_backend,init_method='tcp://localhost:23456', world_size=world_size, rank=global_rank)

即可正常运行了。
如果还不行就重装系统为win10 22H2或win11。

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/commit/59f35adad85815df27e9c6b33d420f5ebfd8376b
理论上该commit修复了楼主的问题。如果还不行试试楼上强制指定分布式地址localhost的方法。
