### ISSUE TITLE
请教在colab中配置问题

### ISSUE THREAD

**Issue by qimlisky** [RVC-Boss/GPT-SoVITS#434]
![Screenshot_2024-02-07-21-58-36-306_mark.via.png](https://github.com/RVC-Boss/GPT-SoVITS/assets/68430938/781c0dc3-cb8c-45d7-93e5-9c00e0f9dde9)

在下载模型环节中运行完，会崩一下，在semantics token
extraction，speech-to-text环节中出错，FileNotFoundError: [Errno 2] No such file or directory: 'logs/hello/6-name2semantic-0.tsv'
FileNotFoundError: [Errno 2] No such file or directory: 'logs/hello/2-name2text-0.txt'

**Comment by v3ucn** [comment]
这是bug，你把'logs/hello/2-name2text-0.txt改为'logs/hello/2-name2text-1.txt 即可，因为colab的显卡编号有的时候是从1开始的

**Comment by qimlisky** [comment]
不，没有logs/hello/2-name2text-0.txt这个文件
