### ISSUE TITLE
Preferred sample rate?

### ISSUE THREAD

**Issue by kexul** [RVC-Boss/GPT-SoVITS#44]
Then slicer tool samples the input files at 32000 Hz, is this a preferred sample rate for finetuning the model? My original audio has sample rate at 44100 Hz, should I keep it as 44100 or resampled it to 32000 Hz?
https://github.com/RVC-Boss/GPT-SoVITS/blob/9619223bc38f31933eaa9eb50d6ca055a6317ee3/tools/slice_audio.py#L17-L24
Many thanks!

**Comment by RVC-Boss** [comment]
You should resample your audio to 32k hz, if you want to use your own dataset.
