### ISSUE TITLE
铸币问题，有关webui端口

### ISSUE THREAD

**Issue by Roelatriper** [RVC-Boss/GPT-SoVITS#452]
`
E:\Coding\sovits>runtime\python.exe webui.py
Traceback (most recent call last):
  File "E:\Coding\sovits\runtime\lib\site-packages\gradio\networking.py", line 120, in start_server
    s.bind((LOCALHOST_NAME, server_port))
PermissionError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Coding\sovits\webui.py", line 786, in <module>
    app.queue(concurrency_count=511, max_size=1022).launch(
  File "E:\Coding\sovits\runtime\lib\site-packages\gradio\blocks.py", line 1347, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
  File "E:\Coding\sovits\runtime\lib\site-packages\gradio\networking.py", line 123, in start_server
    raise OSError(
OSError: Port 9874 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().
`

有大佬帮忙看看嘛？是权限不够？但是开了管理员又无法识别python了。。

**Comment by Roelatriper** [comment]
端口使用netstat查看没有被占用

**Comment by Roelatriper** [comment]
https://github.com/gradio-app/gradio/issues/3675

可能参考到了这个？也许是一个bug！

**Comment by Roelatriper** [comment]
是windows懒人包

**Comment by RVC-Boss** [comment]
之前linux上试过关闭gradio的py进程，端口命令看上去没有占用，但是重启webui gradio仍然提示有占用
win上没试出来过，关掉cmd后再双击bat文件从来没遇到过，除非是其他进程占用了端口
可以看看有没有其他朋友遇到过你的问题

**Comment by motto1** [comment]
我不关闭cmd直接重启也会出现这个问题，需要修改config.py的端口解决。

**Comment by breakstring** [comment]
遇到过类似的问题，docker compose down关掉容器后，重新up会说端口还被占用着

**Comment by Roelatriper** [comment]
是的，很烦，要手动修改一个从未使用的端口。。

**Comment by breakstring** [comment]
我刚尝试复现，最终发现docker compose上的端口占用错误不是它造成的，我的失误。。。汗

**Comment by Roelatriper** [comment]
问题解决了一半，现在可以跑了，但是每跑一次就要换端口。。。
也许是gradio的特性？
有builder可以尝试修复吗？

**Comment by xfl888** [comment]
Try this:
net stop winnat
net start winnat
netsh interface ipv4 show excludedportrange protocol=tcp

make sure 9874/9873/9872/9871 is not in the exclusive list.
