### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by anthonyyuan** [RVC-Boss/GPT-SoVITS#458]
DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Successfully loaded FFmpeg6
DEBUG:git.cmd:Popen(['git', 'version'], cwd=/home/anthony/work/third/GPT-SoVITS, universal_newlines=False, shell=None, istream=None)
DEBUG:git.cmd:Popen(['git', 'version'], cwd=/home/anthony/work/third/GPT-SoVITS, universal_newlines=False, shell=None, istream=None)
DEBUG:wandb.docker.auth:Trying paths: ['/home/anthony/.docker/config.json', '/home/anthony/.dockercfg']
DEBUG:wandb.docker.auth:No config file found
DEBUG:sentry_sdk.errors:[Tracing] Create new propagation context: {'trace_id': '55955792359748fa8327192d2f6e1b29', 'span_id': '965aedb81ea1c343', 'parent_span_id': None, 'dynamic_sampling_context': None}

**Comment by anthonyyuan** [comment]
/home/anthony/miniconda3/envs/p10/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "/home/anthony/work/third/GPT-SoVITS/api.py", line 273, in <module>
    vq_model = SynthesizerTrn(
TypeError: module.models.SynthesizerTrn() argument after ** must be a mapping, not DictToAttrRecursive

**Comment by RVC-Boss** [comment]
去GPT_SoVITS目录的inference_webui.py下，把DictToAttrRecursive这个函数替换掉api.py的，再试试
