### ISSUE TITLE
希望增加对俄语的支持

### ISSUE THREAD

**Issue by tsavpyn** [RVC-Boss/GPT-SoVITS#464]
希望可以接受俄语训练并生成俄语tts

**Comment by Autumn-Whisper** [comment]
俄语不太好找标注好的语料吧

**Comment by tsavpyn** [comment]
我觉得还好，虽然没有想英语那么多，或许我可以找一下

在 2024年2月18日，00:18，Autumn-Whisper ***@***.***> 写道：

﻿

俄语不太好找标注好的语料吧

**Comment by Autumn-Whisper** [comment]
而且俄语和中日英发音区别比较大吧，在这种情况下需要的语料可不是一个小数目。
而且你考虑过算力问题咩、
花佬是用autodl训的，家里有矿也经不住这么个烧啊

**Comment by tsavpyn** [comment]
确实没考虑，感谢，静待以后慢慢更新，本issue关闭

在 2024年2月18日，00:26，Autumn-Whisper ***@***.***> 写道：

﻿

而且俄语和中日英发音区别比较大吧，在这种情况下需要的语料可不是一个小数目。
而且你考虑过算力问题咩、
花佬是用autodl训的，家里有矿也经不住这么个烧啊
