### ISSUE TITLE
2-GPT-SoVITS变声 提示：施工中，请静候佳音？

### ISSUE THREAD

**Issue by terryzhang2021** [RVC-Boss/GPT-SoVITS#476]
2-GPT-SoVITS变声 提示：施工中，请静候佳音？
是安装问题吗？直接解压的

**Comment by huangxu1991** [comment]
变声参考这个：https://github.com/huangxu1991/GPT-SoVITS-VC

**Comment by yuanhuachao** [comment]
> 变声参考这个：https://github.com/huangxu1991/GPT-SoVITS-VC

你好，使用GPT-SoVITS-VC上传两个声音，点击合成报错：
RuntimeError: Calculated padded input size per channel: (0). Kernel size: (1). Kernel size can't be greater than actual input size
麻烦问下什么原因，如何修改？感谢！

**Comment by huangxu1991** [comment]
> > 变声参考这个：https://github.com/huangxu1991/GPT-SoVITS-VC
> 
> 你好，使用GPT-SoVITS-VC上传两个声音，点击合成报错： RuntimeError: Calculated padded input size per channel: (0). Kernel size: (1). Kernel size can't be greater than actual input size 麻烦问下什么原因，如何修改？感谢！

参考的语音是不是太短了？

**Comment by yuanhuachao** [comment]
应该是

**Comment by huangxu1991** [comment]
@ZBzibing 目前整个框架都是基于 32kHz 训练，两种方法：
1. 全部推倒用 44.1kHz 重新训，训练集都采用 44.1kHz 音频，该法能明显提升音质
2. 保持 32kHz 不变，后处理插值提升采样率，但显然对提升音质意义不大
