### ISSUE TITLE
codewithgpu中测试时发现不完整，是还在做吗？

### ISSUE THREAD

**Issue by iou3344** [RVC-Boss/GPT-SoVITS#479]
2-GPT-SoVITS-变声这一块显示    施工中，请静候佳音
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/14129104/afd5b045-d4df-4a32-8a80-f08e29e87c0a)

**Comment by lazycg0427** [comment]
是的，教程中有写

**Comment by RVC-Boss** [comment]
在做了
