### ISSUE TITLE
一键三连中途报错

### ISSUE THREAD

**Issue by lionshen** [RVC-Boss/GPT-SoVITS#493]
![ero](https://github.com/RVC-Boss/GPT-SoVITS/assets/103938352/fa60dcd0-fe75-4093-9ac0-3bb67976c53f)
![ero2](https://github.com/RVC-Boss/GPT-SoVITS/assets/103938352/5d025fd7-72a8-47e8-a6ae-084648f20e83)
小白一窍不通。

**Comment by SapphireLab** [comment]
没有可用显卡用于训练，目前只支持 Nvidia GPU 和 Mac，可以考虑线上方案 AutoDL/Colab，[在线文档](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e)

**Comment by RVC-Boss** [comment]
楼上正解，你的显卡目前不支持训练。
