### ISSUE TITLE
更新2月15日版本后 离线批量ASR 报错 AutoModel

### ISSUE THREAD

**Issue by gaoxigang** [RVC-Boss/GPT-SoVITS#494]
"E:\GPT-SoVITS\runtime\python.exe" tools/asr/funasr_asr.py -i "E:\GPT-SoVITS\output\slicer_opt" -o "output/asr_opt" -s large -l zh -p float16
Traceback (most recent call last):
  File "E:\GPT-SoVITS\tools\asr\funasr_asr.py", line 8, in <module>
    from funasr import AutoModel
ImportError: cannot import name 'AutoModel' from 'funasr' (E:\GPT-SoVITS\runtime\lib\site-packages\funasr\__init__.py)

git pull 更新到2月15日版本后 离线批量ASR 报错，请问大佬这是什么情况哈？运行环境需要重新下载么

**Comment by RVC-Boss** [comment]
runtime\python.exe -m pip install funasr==1.0.0

**Comment by gaoxigang** [comment]
好的 感谢大佬 更新后可以了~
