### ISSUE TITLE
Windows 整合包 如何更新？

### ISSUE THREAD

**Issue by xieyan110** [RVC-Boss/GPT-SoVITS#501]
很久之前 在 https://huggingface.co/lj1995/GPT-SoVITS-windows-package/tree/main  下载了 整合包，
不过项目一直在更新，
有没有更新脚本或者什么简单的更新方法，不是很想重新下载

**Comment by angle1592** [comment]
+1

**Comment by RVC-Boss** [comment]
github下载最新代码直接覆盖，
然后在根目录下执行runtime\python.exe -m pip install -r requirements.txt
更新依赖

**Comment by feiyihx** [comment]
我也想问有没有简单一点的方法，因为是弄给我爸用的。他是搞设计的，科学上网、Github和命令号对于他来说有点复杂了。

**Comment by SapphireLab** [comment]
> 我也想问有没有简单一点的方法，因为是弄给我爸用的。他是搞设计的，科学上网、Github和命令号对于他来说有点复杂了。

已经有增量更新包了啊，看[文档](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e?#)

**Comment by feiyihx** [comment]
> > 我也想问有没有简单一点的方法，因为是弄给我爸用的。他是搞设计的，科学上网、Github和命令号对于他来说有点复杂了。
> 
> 已经有增量更新包了啊，看[文档](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e?#)整合包教程部分

啊啊啊啊！看到了，非常感谢！！！
