### ISSUE TITLE
训练完成，呑字比较严重过

### ISSUE THREAD

**Issue by vbqgyy** [RVC-Boss/GPT-SoVITS#51]
经常会出现有的字词没念，有的字词重复的样子。是我一个人有这样的问题吗？

**Comment by RoversX** [comment]
目前没有遇到，有没有可能是输入的语音有问题？

**Comment by jax-explorer** [comment]
GPT换底模试试

**Comment by RVC-Boss** [comment]
一个是参考音频和参考音频的打标很重要，
二是微调不能太久，1~40分钟的素材默认轮数就好，更多的还要降低轮数。

**Comment by selfboot** [comment]
训练好中文的，里面就一个英文单词都不行吗？

**Comment by 1713172499** [comment]
确实，输入中文里面的英文单词会忽略掉

**Comment by CloudTronUSA** [comment]
@jax-explorer 哥们细说
我怀疑也是GPT那部分可能有点问题，参考我在这里面描述情况 -> #70 
可能换一个GPT底模会有改善？

**Comment by jax-explorer** [comment]
@CloudTronUSA  应该你GPT换成底模，不要训练GPT，可能可以解决，引入GPT会引入 下1个token的预测推理

**Comment by CloudTronUSA** [comment]
@jax-explorer 但没有训练GPT的话语气不怎么像欸，我试试用少量gpt finetune试试
我还以为你的意思是换一个GPT Basemodel

**Comment by vbqgyy** [comment]
昨天没顾上看，谢谢大佬们的回复。

**Comment by CloudTronUSA** [comment]
@RVC-Boss 您好，大概 200分钟 的语言大概跑多少轮比较好？
我用的是 Warma 爆炸电台的语言，质量挺高的，自动打标的输出也八九不离十。
目前测试了 SVC 在 epoch 2-3 比较好，GPT在 epoch 3-4 比较好，但还是有少量的漏字，字读音混在一起，和电流音的问题。

还有就是那个 “文本模块学习率权重” 怎么调比较好？我目前是 0.45

==== 实验数据 ====
* Converted to MP4 so they can be uploaded to github *
Reference Audio: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/ec791c48-2b4f-4f8e-b0dd-a8b8eeef67f5
Reference Text: 我先试一下啊，就是，为了方便倒回来之后可以念的比较顺利，所以我应该念的慢一点点，就是这样。

with GPT-E4 / SVC-E2-S300:
Text: 如果不踏进气势恢宏的“欧庇克莱歌剧院”，或许他乡的旅人无法理解，此地的神明为何会被冠以“大明星”的称谓。\n无论是演出或是审判，她总按时出现在观众上方的专属座位，嬉笑怒骂，歇斯底里，往往比舞台上的内容还要令人印象深刻。\n众人买票入场，为的是饱满与新奇的情感体验，在这方面，芙宁娜显然比绝对公正的那维莱特更加讨喜。
Output: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/37cff628-549f-476f-8d75-e7a1396134ea

**Comment by fl1906** [comment]
> GPT-E1 / SVC-E1-S150

GPT-E1 / SVC-E1-S150 这个是啥意思？ 
<img width="1212" alt="image" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/73702449/60df3660-4f1f-403c-95ad-1565d64829fa">
怎么跟这边参数对应呢？

**Comment by RVC-Boss** [comment]
> @RVC-Boss 您好，大概 200分钟 的语言大概跑多少轮比较好？ 我用的是 Warma 爆炸电台的语言，质量挺高的，自动打标的输出也八九不离十。 目前测试了 SVC 在 epoch 2-3 比较好，GPT在 epoch 3-4 比较好，但还是有少量的漏字，字读音混在一起，和电流音的问题。
> 
> 还有就是那个 “文本模块学习率权重” 怎么调比较好？我目前是 0.45
> 
> ==== 实验数据 ==== * Converted to MP4 so they can be uploaded to github *
> 
> Reference Audio: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/ec791c48-2b4f-4f8e-b0dd-a8b8eeef67f5 Reference Text: 我先试一下啊，就是，为了方便倒回来之后可以念的比较顺利，所以我应该念的慢一点点，就是这样。
> 
> Text: 如果不踏进气势恢宏的“欧庇克莱歌剧院”，或许他乡的旅人无法理解，此地的神明为何会被冠以“大明星”的称谓。\n无论是演出或是审判，她总按时出现在观众上方的专属座位，嬉笑怒骂，歇斯底里，往往比舞台上的内容还要令人印象深刻。\n众人买票入场，为的是饱满与新奇的情感体验，在这方面，芙宁娜显然比绝对公正的那维莱特更加讨喜。
> 
> with GPT-E4 / SVC-E1-S150 (Text Encoder Weight=0.45): Output: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/b77ac40a-5682-4c1d-8078-6a1ebf003e7a
> 
> with GPT-E4 / SVC-E2-S300 (Text Encoder Weight=0.45): Output: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/37cff628-549f-476f-8d75-e7a1396134ea
> 
> with GPT-E4 / SVC-E3-S450 (Text Encoder Weight=0.45): Output: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/31d67012-e3df-488d-b7f5-4a79de413269
> 
> with GPT-E3 / SVC-E1-S150 (Text Encoder Weight=0.45): Output: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/c0b235fa-5b60-49d4-9dea-02d37558d3d6
> 
> with GPT-E1 / SVC-E1-S150 (Text Encoder Weight=0.45): Output: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/6de70abb-3abf-4661-bea8-b4e4f7df766f * 多次吞字（尤其是最前面）、错字
> 
> with GPT-E4 / SVC-E1-S150 (Text Encoder Weight=0.55): ****Preferred Setting** Output1: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/409aa8d5-9446-4d6e-8736-a50857cd6d30 Output2: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/a700eb4c-b597-4a2d-a4f2-8e9201b8577e
> 
> with GPT-E4 / SVC-E2-S300 (Text Encoder Weight=0.55): Output: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/97a40a53-1010-404a-a359-1798ea652ec9
> 
> with GPT-E3 / SVC-E1-S150 (Text Encoder Weight=0.55): Output: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/a8c2364f-0a17-4785-9a3c-c218cec9d7a1
> 
> with GPT-E3 / SVC-E2-S300 (Text Encoder Weight=0.55): Output: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/026c6d34-aada-4afd-b2b0-72741bc66d51 * 有开头吞字
> 
> with GPT-E2 / SVC-E1-S150 (Text Encoder Weight=0.55): Output: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/d15331d1-5029-49c1-8ca9-762043711870 * 多次吞字（尤其是最前面）、错字
> 
> with GPT-E2 / SVC-E2-S300 (Text Encoder Weight=0.55): Output: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/0830c411-12bb-4658-afca-62c68503980f * 有吞字（尤其是最前面）
> 
> with GPT-E1 / SVC-E1-S150 (Text Encoder Weight=0.55): Output: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/0f08f71e-e361-4b96-a629-99c5fbbe69ad * 多次吞字（尤其是最前面）、错字、多次过长间隔
> 
> with GPT-E1 / SVC-E2-S300 (Text Encoder Weight=0.55): Output: https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/e8c66403-24dc-4618-bef8-2a138c548401 * 有吞字（尤其是最前面）、错字、过长间隔、慢

这里建议参考音频不要超过10秒，最好最多2句（逗号句号算一句）

**Comment by RVC-Boss** [comment]
> 训练好中文的，里面就一个英文单词都不行吗？

@selfboot @1713172499 中英混合已支持

**Comment by RVC-Boss** [comment]
念的慢一点点  要改为    念的，慢一点点    因为中间有停顿

**Comment by CloudTronUSA** [comment]
好的，我再去检查一下
哦对了 还有一个比较大的问题就是，电流音蛮严重的，是什么原因呢？
