### ISSUE TITLE
请问有Linux的教程吗？

### ISSUE THREAD

**Issue by caizhuoyue77** [RVC-Boss/GPT-SoVITS#518]
在README.md中没有看到诶

**Comment by RVC-Boss** [comment]
Quick Install with Conda就是面向linux的吧

**Comment by fengyunzaidushi** [comment]
[https://blog.csdn.net/fengxiaoyangfeng/article/details/136328022](https://blog.csdn.net/fengxiaoyangfeng/article/details/136328022)
