### ISSUE TITLE
autodl云端运行faster whisper打标提示无组件

### ISSUE THREAD

**Issue by tanke0101** [RVC-Boss/GPT-SoVITS#520]
报错之后直接使用了命令python -m pip install faster_whisper 进行安装，但是安装后还是提示moduleNotFoundError:
module faster_whisper No named “faster_whisper”。我是在autodl的根目录直接pip安装的，是不是需要切换到gpt目录里面进行安装才可以？
![5158932c496ae52735e673e06642827b](https://github.com/RVC-Boss/GPT-SoVITS/assets/160379181/3fc68538-03c9-476d-ab25-abae5a2af7e3)

**Comment by tanke0101** [comment]
![5158932c496ae52735e673e06642827b](https://github.com/RVC-Boss/GPT-SoVITS/assets/160379181/267c25bb-0d1d-426b-9d79-75189f82f1c6)

**Comment by tanke0101** [comment]
![f1796408b84d8e14c3188944b1d326f3](https://github.com/RVC-Boss/GPT-SoVITS/assets/160379181/8bac3a7d-6800-4d25-9e7b-b4439714fd2a)

**Comment by RVC-Boss** [comment]
source activate GPTSoVits && cd ~/GPT-SoVITS/ && pip install -r requirements.txt
我去更新一下镜像。
