### ISSUE TITLE
通过github源码，conda环境requirement安装，但是不能识别显卡

### ISSUE THREAD

**Issue by sdcarterchen** [RVC-Boss/GPT-SoVITS#522]
我显卡是3070ti ,cuda 版本 12.2，我在Python源码中加上输出torch获取显卡信息，结果是False。
我下载了整合包，结果能正确识别

**Comment by kingki663** [comment]
请问这个问题是如何解决的？

**Comment by mythzhang8** [comment]
我也是这个问题

**Comment by XXXXRT666** [comment]
PyTorch.org
安装pytorch不能用pypi

**Comment by mythzhang8** [comment]
> [PyTorch.org](PyTorch.org) 安装pytorch不能用pypi

requirements.txt没有直接安装pytorch的，请问一下怎么该如何正确安装呢
