### ISSUE TITLE
关于Gradio库的concurrency_count参数

### ISSUE THREAD

**Issue by akm-m24** [RVC-Boss/GPT-SoVITS#527]
会出现如下报错：
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\GPT-SoVITS-main\webui.py", line 837, in <module>
    app.queue(concurrency_count=511, max_size=1022).launch(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\blocks.py", line 1789, in queue
    raise DeprecationWarning(
DeprecationWarning: concurrency_count has been deprecated. Set the concurrency_limit directly on event listeners e.g. btn.click(fn, ..., concurrency_limit=10) or gr.Interface(concurrency_limit=10). If necessary, the total number of workers can be configured via `max_threads` in launch().

**Comment by akm-m24** [comment]
我尝试把这个参数直接去除就可以运行了，不知会不会影响程序运行

**Comment by SapphireLab** [comment]
Gradio 4.0+ 去掉了这个参数，如果你想保留可以回退版本，在requirements.txt里是 3.38

**Comment by RVC-Boss** [comment]
楼上正解
