### ISSUE TITLE
3连后1Ba-SoVITS报错

### ISSUE THREAD

**Issue by ujasssyc** [RVC-Boss/GPT-SoVITS#538]
RuntimeError: cuFFT doesn't support signals of half type with compute capability less than SM_53, but the device containing input half tensor only has SM_52

**Comment by SapphireLab** [comment]
半精度 cuFFT 需要 GPU 架构至少是 SM_53 以上，应该是你的显卡算力不够，所以可以考虑换个设备或者线上方案。

**Comment by RVC-Boss** [comment]
What's your GPU?
