### ISSUE TITLE
加载微调的模型报错

### ISSUE THREAD

**Issue by T0L0ve** [RVC-Boss/GPT-SoVITS#539]
加载微调后保存在logs文件夹下的GPT和VITS模型或报错，但又不影响输出推理结果。
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/38580985/8704d084-6d8d-417b-9daa-d6831a958223)
但加载自动保存在weights下的模型就没有该错误，但weights下的模型效果不如logs文件夹下的。
而且加载weights的模型推理后再重新加载logs文件夹下的模型推理生成的音频文件音色相同，重启推理webui后直接加载logs文件夹下的模型推理生成的音频又会与上述音频的音色不同。

**Comment by RVC-Boss** [comment]
inference_webui里面写的加载代码，是加载2个weights文件夹下的模型的代码，不是logs下的，logs下的是给下次需要接着继续训练用的
