### ISSUE TITLE
请问标注文件如何合并

### ISSUE THREAD

**Issue by werran2** [RVC-Boss/GPT-SoVITS#544]
增加了很多新的音频
不想每次都重新标注一遍，工作量太大了
简单地把文本文件合并在一起就可以吗
中间那个变量是文件名，需不需要统一修改？比如我第一个文件内容是
*.wav|slicer_opt|ZH|文本
第二个内容是*.wav|slicer_opt_rec3|ZH|文本

|slicer_opt| 和 |slicer_opt_rec3| 起到的作用是什么，需要修改吗

**Comment by RVC-Boss** [comment]
第二是角色名，兼容bert-vits2多人训练格式的，gpt-sovits用不到，随便写啥占位就行

合并直接2个.list文件全选复制黏贴到同一个文件里就行了吧。注意接缝。
