### ISSUE TITLE
Vscode api.py  500 Internal Server Error   RuntimeError: The size of tensor a (1268) must match the size of tensor b (512) at non-singleton dimension 1

### ISSUE THREAD

**Issue by xiaolongww** [RVC-Boss/GPT-SoVITS#546]
问题：在vscode中启动api.py，使用apifox调用接口出现报错，报错日志见下方txt
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/86103538/42edf39d-7681-45a9-b510-1ff290379662)
推测：字数太长导致，接口在132字下工作正常。但是网页端推理时能够使用长文本（试过1320字）正常合成
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/86103538/62bfff9f-1492-4b6f-94f2-a2c2feeeb280)
[报错.txt](https://github.com/RVC-Boss/GPT-SoVITS/files/14338796/default.txt)

请问大家有遇到类似问题吗，求解答，感激不尽！

**Comment by xiaolongww** [comment]
知道了，如果当成1句来合成会报错，当选择四句一切就正常了

**Comment by RVC-Boss** [comment]
文本太长bert提取会出错。
不行，我得限制文本长度强制切分。
感谢楼主提供的最大492字的信息。
