### ISSUE TITLE
执行asr 报错 funasr-pipeline 

### ISSUE THREAD

**Issue by gaoleihero** [RVC-Boss/GPT-SoVITS#55]
执行asr 报错 
KeyError: 'funasr-pipeline is not in the pipelines registry group auto-speech-recognition. Please make sure the correct version of ModelScope library is used.'
怎么解决

**Comment by selfboot** [comment]
参考 https://github.com/RVC-Boss/GPT-SoVITS/issues/40 ，降级 `modelscope` ：

> pip install modelscope==1.10.0

**Comment by gaoleihero** [comment]
降级了也还是不行。我是通过
inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='tools/damo_asr/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
    vad_model='tools/damo_asr/models/speech_fsmn_vad_zh-cn-16k-common-pytorch',
    punc_model='tools/damo_asr/models/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
)
改成

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
    vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
    punc_model='damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
)

**Comment by noob3004** [comment]
> 降级了也还是不行。我是通过 inference_pipeline = pipeline( task=Tasks.auto_speech_recognition, model='tools/damo_asr/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch', vad_model='tools/damo_asr/models/speech_fsmn_vad_zh-cn-16k-common-pytorch', punc_model='tools/damo_asr/models/punc_ct-transformer_zh-cn-common-vocab272727-pytorch', ) 改成
> 
> inference_pipeline = pipeline( task=Tasks.auto_speech_recognition, model='damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch', vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch', punc_model='damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch', )

我将两个都降级了,不改cmd也行

**Comment by bruce2233** [comment]
全降级依然不行

**Comment by daocodedao** [comment]
升级 funasr
pip install funasr==1.0.0

**Comment by RVC-Boss** [comment]
Fixed by merging https://github.com/RVC-Boss/GPT-SoVITS/pull/135.
