### ISSUE TITLE
发现一个较大问题。 但训练声音为男声， 但参考音频为女声时， 推理输出结果完全走样。

### ISSUE THREAD

**Issue by philiz76** [RVC-Boss/GPT-SoVITS#551]
环境： 本地docker部署

**Comment by RVC-Boss** [comment]
不要参考音频和微调训练集使用差异很大的音色
因为合成的音频的音色会参考参考音频音色的，然后模型参数上，又是微调训练集的音色
混搭会产生什么奇怪的东西我不确定，同性混合还能叫声线融合，男女混合我也不晓得这叫啥
