### ISSUE TITLE
linux系统命令行方法如何进行一键三连和模型训练？

### ISSUE THREAD

**Issue by hanhechong** [RVC-Boss/GPT-SoVITS#552]
感谢作者的无私分享，我注意到在github上讲解了如何使用命令行方法进行音频切割以及asr，那么下一步的一键三连和模型训练如何具体地使用命令行方法执行呢？谢谢！

**Comment by RVC-Boss** [comment]
先在webui上跑通全流程，每一步都能在控制台看见对应的命令行。
