### ISSUE TITLE
user-specified model revision: v2.0.4 无法下载模型

### ISSUE THREAD

**Issue by mhe014** [RVC-Boss/GPT-SoVITS#553]
在0c-中文批量离线ASR工具，点击开启批量ASR后，到
2024-02-20 19:19:30,224 - modelscope - INFO - Use user-specified model revision: v2.0.4
没有反应，始终停留在0%，尝试了代理也无效，始终没有进度前进。
<img width="854" alt="屏幕截图 2024-02-20 192107" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/131150286/f3cdee86-6428-44fc-a425-3ec585256630">
Windows 11 专业版

**Comment by RVC-Boss** [comment]
看看是不是多等等就行了，他下载进度条一格需要等待的时间比较长

**Comment by huckyos** [comment]
解决了吗？我也遇到了相同的问题

**Comment by Jianwenqu** [comment]
我也遇到了这个问题，有相应的解决方法吗？

**Comment by Pettysc** [comment]
换网络就好了 我是这样的
