### ISSUE TITLE
使用inference_webui.py中的change_sovits_weights加载微调的pth模型，报no module named 'utils'错误，只有使用原有的s2D488k.pth才可以，并且通过get_tts_wav推理的结果无声音。如何解决？

### ISSUE THREAD

**Issue by viking-man** [RVC-Boss/GPT-SoVITS#554]
[GPT_SoVITS-1.0.tar.gz](https://github.com/RVC-Boss/GPT-SoVITS/files/14343756/GPT_SoVITS-1.0.tar.gz)
这是我自己打的包

**Comment by viking-man** [comment]
def text_to_speech(text: str, lang: str, external: InferenceWebUI):
        # gpt微调权重
        external.change_gpt_weights(gpt_path=external.gpt_path)
        # sovits微调权重
        external.change_sovits_weights(sovits_path=external.sovits_path)
        # 生成wav
        synthesis_result = external.get_tts_wav(ref_wav_path=EXAMPLE_WAV,
                                                prompt_text=EXAMPLE_TEXT,
                                                prompt_language=EXAMPLE_TEXT_LANG,
                                                text=text,
                                                text_language=lang)

        result_list = list(synthesis_result)

        if result_list:
            last_sampling_rate, last_audio_data = result_list[-1]
            output_wav_path = os.path.join(OUTPUT_WAV_PATH, "output.wav")
            sf.write(output_wav_path, last_audio_data, last_sampling_rate)

            result = "Audio saved to " + output_wav_path

        logging.info(f"合成完成！输出路径：{OUTPUT_WAV_PATH}")
        logging.info("处理结果：\n" + result)

把GPT_SOVITS打包后，在其他项目中使用的代码如上

**Comment by viking-man** [comment]
已找到原因，需要在自己的项目中导入utils模块

**Comment by douhaohaode** [comment]
我遇到和你一样的错误但是导入utils并没有成功，请问还需要其他什么设置吗

**Comment by douhaohaode** [comment]
> 我遇到和你一样的错误但是导入utils并没有成功，请问还需要其他什么设置吗

解决了

**Comment by lililuya** [comment]
> > 我遇到和你一样的错误但是导入utils并没有成功，请问还需要其他什么设置吗
> 
> 解决了

您好，我也碰到了相似的问题，可以请教一下是怎么解决的嘛
