### ISSUE TITLE
中文训练好，会丢失里面混杂的英语

### ISSUE THREAD

**Issue by selfboot** [RVC-Boss/GPT-SoVITS#56]
<img width="1561" alt="image" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/2769831/fb54d4b7-b604-4cc1-bbc1-004bc477ddf8">

这里训练好的模型，对于ms，response 这些都是直接不说的。虽然训练预料里也有英文部分。

**Comment by RVC-Boss** [comment]
后面会支持中日英多语言前端，现在还只支持单语种的
