### ISSUE TITLE
question: 参考音频的作用是什么

### ISSUE THREAD

**Issue by xiaolibuzai-ovo** [RVC-Boss/GPT-SoVITS#563]
我在训练模型的时候，和提供的参考音频使用了不同的音色，但是发现生成的音频和提供的参考音频很像，而与前面训练的模型音色无关，请问生成的音色参考来自于哪里？如果是参考音频的话，那前面训练的模型的作用是什么呢？

**Comment by sinopec** [comment]
我有同样的疑问...   题主自己关了是有答案了么。。。
