### ISSUE TITLE
基础模型的训练

### ISSUE THREAD

**Issue by csu-roycheng** [RVC-Boss/GPT-SoVITS#570]
想问一下基础模型都是用完全不带噪声的语音数据集训练的吗？
如果能用足够多的语音数据集训练基础模型的话，是不是不需要微调模型都能够达到较好的克隆呢？

**Comment by RVC-Boss** [comment]
可能有很小的背景噪声和底噪，有些开源训练集还是有噪声的

不一定的，全人类的语音完全覆盖……只能说训练集覆盖越全，用户用更少数据得到好的效果的概率越大
