### ISSUE TITLE
无法调用tools/damo_asr/models路径已有的模型

### ISSUE THREAD

**Issue by YYYYangtuotuoer** [RVC-Boss/GPT-SoVITS#574]
打包文件中tools/damo_asr/models路径已有damo模型，但是执行ASR时还是会联网自动下载模型到user/.cache目录

**Comment by SapphireLab** [comment]
damo_asr/models 文件夹在二月九号之后修改为 asr/models 了，建议更新代码后再进行尝试。

**Comment by RVC-Boss** [comment]
楼上正解
