### ISSUE TITLE
内存占用可以优化下？

### ISSUE THREAD

**Issue by selfboot** [RVC-Boss/GPT-SoVITS#58]
训练好模型后，只是开页面，gpu 显存也都占用 3 个多 G，这里理论上可以不占用显存？

<img width="887" alt="image" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/2769831/a147a430-f1b3-4caa-8355-752f12b6b15c">

**Comment by RVC-Boss** [comment]
主WebUI不吃显存，所有吃显存的进程都通过命令行调用另起，如果要释放勾选关闭。

**Comment by selfboot** [comment]
> 主WebUI不吃显存，所有吃显存的进程都通过命令行调用另起，如果要释放勾选关闭。

感谢感谢，我再试试
