### ISSUE TITLE
tts中英文推理时候，英文单词一个一个字母读出来

### ISSUE THREAD

**Issue by lonngxiang** [RVC-Boss/GPT-SoVITS#586]
选择的合成是中英混合，怎么让英文单词不分开

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/40717349/f761fbd3-c873-4e90-918d-e5719dd13238)

**Comment by juntaosun** [comment]
拼写改成：Nvidia

**Comment by lonngxiang** [comment]
> 拼写改成：Nvidia

多谢，必须是小写或者Nvidia 第一个字母大写才行吗；全部大写就会出错

**Comment by juntaosun** [comment]
大小写拼读规则：
（1）需要单个发音就大写，比如：USA，USB，ChartGPT。
（2）其它情况正常拼读，就按正常拼写。比如你这个：Nvidia ， Cuda。

**Comment by guoyunqiao** [comment]
> TTS语音合成大小写拼读规则： （1）需要单个发音就大写，比如：USA，USB，ChatGPT。 （2）其它情况正常拼读，就按正常拼写。比如你这个：Nvidia ， Cuda 或者全小写 （nvidia ， cuda ）

你好，我想问一下，为什么我训练的模型，当A在开头的时候，它会读成’额‘，A在彼得字母中间的时候，就会读A

**Comment by HaoTang1** [comment]
> > TTS语音合成大小写拼读规则： （1）需要单个发音就大写，比如：USA，USB，ChatGPT。 （2）其它情况正常拼读，就按正常拼写。比如你这个：Nvidia ， Cuda 或者全小写 （nvidia ， cuda ）
> 
> 你好，我想问一下，为什么我训练的模型，当A在开头的时候，它会读成’额‘，A在彼得字母中间的时候，就会读A

遇到同样问题，尝试加AI EY1 AY1到engdict-hot.rep但是效果还是很不好
