### ISSUE TITLE
预训练模型s2D488k.pth、s2G488k.pth是如何训练出来的

### ISSUE THREAD

**Issue by xuancaiqisehua** [RVC-Boss/GPT-SoVITS#590]
如果想增加其他语种，就需要重新训练模型，请问这两个模型是如何训练出来的

**Comment by Rosy-Clouds** [comment]
我也想了解这块，有没有群，一起交流

**Comment by Rosy-Clouds** [comment]
要不我拉个qq群，兄弟们qq号给我，拉个多语言、基地模型训练交流群，交流模型结构和训练数据等问题？

**Comment by xuancaiqisehua** [comment]
> 要不我拉个qq群，兄弟们qq号给我，拉个多语言、基地模型训练交流群，交流模型结构和训练数据等问题？

**Comment by xuancaiqisehua** [comment]
> 要不我拉个qq群，兄弟们qq号给我，拉个多语言、基地模型训练交流群，交流模型结构和训练数据等问题？

可以把群号发出来，需要的加入

**Comment by Rosy-Clouds** [comment]
560663448，有兴趣一起讨论base模型如何训练

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年02月29日 10:36 |
| 收件人 | RVC-Boss/GPT-SoVITS ***@***.***> |
| 抄送人 | Rosy-Clouds ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [RVC-Boss/GPT-SoVITS] 预训练模型s2D488k.pth、s2G488k.pth是如何训练出来的 (Issue #590) |

要不我拉个qq群，兄弟们qq号给我，拉个多语言、基地模型训练交流群，交流模型结构和训练数据等问题？

可以把群号发出来，需要的加入

**Comment by benlaitang** [comment]
这个有知道的吗？

**Comment by GeleiaComPepino** [comment]
For anyone that need this recently, to train the pretrain s2 you need to use this repository: https://github.com/innnky/ar-vits
Make sure you have enough data and gpus for training! Good luck!
