### ISSUE TITLE
适当的数据集大小用于微调

### ISSUE THREAD

**Issue by speedybonder** [RVC-Boss/GPT-SoVITS#596]
你好，非常感谢所有参与这个令人兴奋的项目的贡献者。

我想问一下关于微调的数据集大小。项目页面表示微调只需要1分钟的音频，我想知道这是最小要求还是推荐数量。

我有高质量的单一发言人数据集，包含几小时的音频。在微调时使用这么大的数据集对这个模型有价值吗？

提前感谢您

如果这里的写作不佳，我向您道歉，我是一个使用翻译的英语使用者。这里是原文，以防它提供更多清晰度：https://pastebin.com/raw/GBrpGMCd

**Comment by RVC-Boss** [comment]
最小要求，不是推荐数量
minimial requirment, not recommended quantity
更多的时长，例如几小时，如果标注质量高，那么ok，效果可能更好
More duration, e.g. several hours. It's ok if the text annotation quality is good.
