### ISSUE TITLE
当前底模是多大的数据集训练的？

### ISSUE THREAD

**Issue by faceair** [RVC-Boss/GPT-SoVITS#60]
感谢开源。想了解一下当前底模训练相关的一些信息，如题大概是多大的数据集在什么配置规格下需要训练多久？可以自己训练更多语言的底模吗？

**Comment by kexul** [comment]
作者在b站评论区说是2k小时

**Comment by TinaChen95** [comment]
同好奇~数据的来源是什么呀？需要高音质、精确标注么？

**Comment by RVC-Boss** [comment]
参考https://github.com/RVC-Boss/GPT-SoVITS/issues/217
