### ISSUE TITLE
Can you change your stage 1 implementation reference to Feiteng Li's VALL-E

### ISSUE THREAD

**Issue by feng-yufei** [RVC-Boss/GPT-SoVITS#608]
Hello GPT-SOVITS Authors,
Can you change the Stage 1 reference to Feiteng's VALLE? currently it is yufei/shared_debugging_code, which gets removed and our code sourced from feiteng's [valle](https://github.com/lifeiteng/vall-e).
Thanks

**Comment by RVC-Boss** [comment]
> Hello GPT-SOVITS Authors, Can you change the Stage 1 reference to Feiteng's VALLE? currently it is yufei/shared_debugging_code, which gets removed and our code sourced from feiteng's [valle](https://github.com/lifeiteng/vall-e). Thanks

@feng-yufei 我搜了一下lifeiteng的valle的仓库代码，发现代码结构变化挺大的，文件无法一一对应上
我这么修改，你看可不可以
改为：
第一行：https://github.com/lifeiteng/vall-e
第二行：https://github.com/yangdongchao/SoundStorm/tree/master/soundstorm/s1/AR/xxxxx具体的代码路径

**Comment by feng-yufei** [comment]
sure thanks :)

**Comment by RVC-Boss** [comment]
done
https://github.com/RVC-Boss/GPT-SoVITS/commit/4496426896157f441ef090ecca11c759369f8a37
