### ISSUE TITLE
ASR faster whisper can't support EN datasets properly

### ISSUE THREAD

**Issue by 18930215187** [RVC-Boss/GPT-SoVITS#616]
Faster Whisper ASR large模型，生成的list文件里面出现大量的重复字段，例如：
`G:\Datasets\GuYunAGI\VerinAudio\slice\12.flac_0011459520_0011566720.wav|slice|EN|And the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is, and the time the outside world is `

**Comment by RVC-Boss** [comment]
试试其他几个大小的en whisper模型试试？或者手工修改少量bad case…
ASR不是本项目研究主线

**Comment by 18930215187** [comment]
> 试试其他几个大小的en whisper模型试试？或者手工修改少量bad case… ASR不是本项目研究主线

TT  这可不是少量啊，1200句语音里重复的占了可能20%，手工已经累死了（
