### ISSUE TITLE
推理过程中“远程主机强迫关闭了一个现有的连接”

### ISSUE THREAD

**Issue by norsizu** [RVC-Boss/GPT-SoVITS#62]
合成语音的时候总进度条是1500，但是总是走到3、400的时候就结束了，然后现实
`handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。`
但是语音转换还是完成了，总觉得效果不太好是因为这个进度条没走完吗

**Comment by hyhuc0079** [comment]
我也是进度条没走完
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
 14%|███████████▏                                                                   | 212/1500 [00:02<00:13, 95.10it/s]T2S Decoding EOS [87 -> 303]
 14%|███████████▍                                                                   | 216/1500 [00:02<00:14, 89.89it/s]
 
 关闭连接那个应该是用了edge-tts，因为我们转换的文本是先用edge-tts转换成语音再附加音色，这个你用rvc，bert，sovits都会这样不用担心

**Comment by SPY-Ming** [comment]
同样的问题，请问解决了吗？求 flow

**Comment by norsizu** [comment]
> 同样的问题，请问解决了吗？求 flow

看楼上的答案，似乎这样是正常的，不是有问题。

**Comment by SPY-Ming** [comment]
> > 同样的问题，请问解决了吗？求 flow
> 
> 看楼上的答案，似乎这样是正常的，不是有问题。

现在我这边的问题是，合成的语音句子都不连贯。比如：
想合成：“通过输入一个5秒的人声样本,用户可以立即体验到文字转语音的功能。同时,只需1分钟的训练数据,就可以对模型进行微调,从而提高语音相似性和真实感。 ”
合成的音频为：“”通过输入一个5秒的，验到文字转语音的功，同时,只需1分钟的训练数据以对模型进行“。
你要是这样的么？

**Comment by hyhuc0079** [comment]
都这样，你可以多执行几次试试，提高训练集质量也可以降低这种出错概率

**Comment by norsizu** [comment]
> > > 同样的问题，请问解决了吗？求 flow
> > 
> > 
> > 看楼上的答案，似乎这样是正常的，不是有问题。
> 
> 现在我这边的问题是，合成的语音句子都不连贯。比如： 想合成：“通过输入一个5秒的人声样本,用户可以立即体验到文字转语音的功能。同时,只需1分钟的训练数据,就可以对模型进行微调,从而提高语音相似性和真实感。 ” 合成的音频为：“”通过输入一个5秒的，验到文字转语音的功，同时,只需1分钟的训练数据以对模型进行“。 你要是这样的么？

提供的示例音频对这个影响很大

**Comment by HildaM** [comment]
不影响使用，可能是程序bug吧

**Comment by RVC-Boss** [comment]
不影响使用。
