### ISSUE TITLE
multilingual training

### ISSUE THREAD

**Issue by Rothfive** [RVC-Boss/GPT-SoVITS#64]
Hi! This project seems extremely promising. I was wondering whether you would in the future support scripts/instructions to train models to perform in other languages (non-english). For example, there are multiple bert versions in my native tongue, but none of them which could output mel tokens based on a trained dataset. 

Would you recommend options on how to accomplish this in the scope of this project? Could try to figure out a code for it myself also and then share my findings also if i manage to figure it out. Do you have any discord server where there would be a possibility to i could discuss further how this TTS - pipeline process works?

Love what you guys have done with this project.

**Comment by RVC-Boss** [comment]
Multilingual training is supported now. Here is the dataset format for different language.
https://github.com/RVC-Boss/GPT-SoVITS?tab=readme-ov-file#dataset-format

Also you can add your own languague in https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/text/cleaner.py
