### ISSUE TITLE
打开整合包显示找不到显卡，以及整合包的torchvision版本问题

### ISSUE THREAD

**Issue by 0Umekawa0** [RVC-Boss/GPT-SoVITS#646]
使用的是整合包0217，但是所需的cuda版本是多少？我试了11.6，11.7，11.8，nvcc都显示了对应的版本，说明安装完成，但是webui上都提示找不到显卡。我的显卡是4070ti，并且没有核显，gpu0就是4070ti
以及在打开推理webui的时候提示如下信息，搜了一下说是torchvision版本不对，但我觉得是整合包的话应该不是版本问题，所以来问一下
![QQ截图20240302144808](https://github.com/RVC-Boss/GPT-SoVITS/assets/125868650/57e559fa-8c44-4284-81f0-a99ceff1a1ab)
![QQ截图20240302144813](https://github.com/RVC-Boss/GPT-SoVITS/assets/125868650/2ccdd4f8-0b20-4c52-9faf-af7e537da2a2)
![QQ截图20240302144819](https://github.com/RVC-Boss/GPT-SoVITS/assets/125868650/6422af58-6fdc-42d4-9518-4326869ffff8)
![QQ截图20240302145016](https://github.com/RVC-Boss/GPT-SoVITS/assets/125868650/12e2a2ba-5809-4d0d-bfc7-821410b3325e)

**Comment by 0Umekawa0** [comment]
我也不知道怎么就好了。解决办法可能是先把cuda卸载了，然后重新解压整合包？

**Comment by SapphireLab** [comment]
大概率是解压整合包出错了吧(用7zip/bandizip确保不出错

**Comment by RVC-Boss** [comment]
不需要安装cuda
你的系统是win多少？

**Comment by 0Umekawa0** [comment]
> 不需要安装cuda 你的系统是win多少？

win10
之前解压的时候我电脑上都有cuda，最后一次应该是卸载了，然后就没报错了
