### ISSUE TITLE
开启推理WebUI失败，提示“ [Errno 10048] error while attempting to bind on address ('0.0.0.0', 9872): 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。”

### ISSUE THREAD

**Issue by NBholmes** [RVC-Boss/GPT-SoVITS#650]
开启推理WebUI失败，提示“ [Errno 10048] error while attempting to bind on address ('0.0.0.0', 9872): 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。”

**Comment by BlacknoSheep** [comment]
9872端口被占用了，可能是因为上次运行webui后未完全关闭。
可以参考[这个链接](https://www.runoob.com/w3cnote/windows-finds-port-usage.html)手动结束占用端口的进程。

**Comment by RVC-Boss** [comment]
楼上正解。
