### ISSUE TITLE
scaling up the GPT model

### ISSUE THREAD

**Issue by MujiKemp** [RVC-Boss/GPT-SoVITS#652]
Dear authors,

Thank you for this awesome project! 

I was wondering if it's possible to scale the base GPT model since some words are missing or repeating during synthesis. 

How could I do that? Do you have code for training the base GPT model from scratch?

**Comment by RVC-Boss** [comment]
You can use the codes in this repo.
change the s1_longer.html file to change the GPT config

**Comment by KamioRinn** [comment]
Is it a problem with the pronunciation of words？

**Comment by MujiKemp** [comment]
> You can use the codes in this repo. change the s1_longer.html file to change the GPT config

Gotcha, do you have a rough idea of how long it took to train on your 2kh data?

**Comment by MujiKemp** [comment]
> Is it a problem with the pronunciation of words？

It's more of repeating/missing words, but some mispronunciations as well. I think scaling might help since this project is similar to Vall-E?

**Comment by KamioRinn** [comment]
> It's more of repeating/missing words, but some mispronunciations as well. I think scaling might help since this project is similar to Vall-E?

**repeating/missing words:**
1、Try update source code and check “是否开启dpo训练选项(实验性)” before start GPT training.(But make sure ASR results are correct)
2、Adjust top_k,top_p,temperature to get the best inference result.

**mispronunciations:**
1、Add right pronunciation to “GPT_SoVITS/text/engdict-hot.rep”.(Use International Phonetic Alphabet, IPA)
2、Delete “GPT_SoVITS/text/engdict_cache.pickle”.

**Comment by chris-calo** [comment]
> **mispronunciations:** 1、Add right pronunciation to “GPT_SoVITS/text/engdict-hot.rep”.(Use International Phonetic Alphabet, IPA) 2、Delete “GPT_SoVITS/text/engdict_cache.pickle”.

Thanks @KamioRinn this is what I was looking for. That said, worth noting, that the `engdict-hot.rep` file is actually written in [ARPAbet](https://en.wikipedia.org/wiki/ARPABET) and not IPA.
