### ISSUE TITLE
推理 一句话如果是三个以上的“啊”，会报错

### ISSUE THREAD

**Issue by X-T-E-R** [RVC-Boss/GPT-SoVITS#655]
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/82741331/0dcc49dc-e120-4b2c-a1f8-efb0940a7040)
对于 啊啊啊、啊啊啊啊、啊啊啊啊啊……之类的，都会报错

**Comment by X-T-E-R** [comment]
哦有的时候啊啊啊不会报错，但是 啊啊啊啊啊啊 必报错

**Comment by KamioRinn** [comment]
Fix https://github.com/RVC-Boss/GPT-SoVITS/pull/658

**Comment by juntaosun** [comment]
问题已修复，升级一下：

```
pip install LangSegment>=0.2.4 -i https://pypi.org/simple

```

**Comment by RVC-Boss** [comment]
fixed by 楼上

**Comment by XM233333333** [comment]
你小子克隆啊、啊啊啊、干啥
