### ISSUE TITLE
当输入的内容包含“知道”两个字的时候会被识别为日文

### ISSUE THREAD

**Issue by Hwangkop** [RVC-Boss/GPT-SoVITS#663]
当输入的内容包含“知道”两个字的时候会被识别为日文，比如 “知道吗？”

**Comment by RVC-Boss** [comment]
@Hwangkop 你先用仅中文模式跑下，auto我去问问分词库同学

**Comment by KamioRinn** [comment]
能否提供完整例子？
<img width="478" alt="image" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/63162909/3a1f7253-4012-4a4e-aee3-4c6f69e8deaa">

**Comment by juntaosun** [comment]
升级一下LangSegment版本：

```
pip install LangSegment>=0.2.5 -i https://pypi.org/simple

```
