### ISSUE TITLE
中英混合bug，chatGpt他的t会读两次

### ISSUE THREAD

**Issue by JavaAndPython55** [RVC-Boss/GPT-SoVITS#665]
换了3个模型都是发现t有问题
没错，它就是风靡全球的网红ChatGPT。
他会读2遍T

我试过，换模型
也试过chat GPT,以及chat G-P-T 还有chat g-p-t 。还有chat G P T都没用，T都会读2次

尤其是末尾没有汉字，只有英文的。他会读好几次。

**Comment by JavaAndPython55** [comment]
我试了很多种，读的都有问题
“言归正传，这个chatgpt到底是什么呢？”

sovits我部署过，他用微软tts做的音色替换，英文效果非常好，有没有集成上去的想法？

**Comment by manhere** [comment]
测试有同样问题

**Comment by XXXXRT666** [comment]
> 我试了很多种，读的都有问题
> 
> “言归正传，这个chatgpt到底是什么呢？”
> 
> 
> 
> 其实他读单词还ok，就是这种专有名词不行，迫切【希望】能加一个支持让他【英文读**单个字母**】的方法或者标签。

`GPT_SoVITS/text/engdict-hot.rep`可以改，改完记得把pickle删了

**Comment by KamioRinn** [comment]
@JavaAndPython55 @manhere 
“言归正传，这个chat GPT到底是什么呢？”
需要按单词读的使用小写，需要读字母的使用大写。或者直接GPT_SoVITS/text/engdict-hot.rep里添加chatgpt这个单词的ipa读音

**Comment by JavaAndPython55** [comment]
改了hot，删了cache，然后重新启动发现他的读音还是不正确，还是重复读了多个t

**Comment by JavaAndPython55** [comment]
hot里面应该也可以大写吧，比如GPT 后面加ipa发音

**Comment by JavaAndPython55** [comment]
里面读音改写了，【生效了】，读音变化成功了，【但是】他的末尾还是会【出现多读】的情况。中英混合。换了模型和预测音频都是无效的。@KamioRinn 你可以测测

**Comment by KamioRinn** [comment]
这个chatgpt到底是什么呢?[](url)

**Comment by KamioRinn** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/assets/63162909/5e13da81-8aa2-4757-a2a5-b19ea2c5b9ee

**Comment by qieqieplus** [comment]
英文模式下如果带全角逗号句号，就会有一些奇奇怪怪的问题。
现在中英混合下面，会默认给没有分割符的句尾加全角标点，就比较容易复现。

**Comment by nogodfox** [comment]
> @JavaAndPython55 @manhere “言归正传，这个chat GPT到底是什么呢？” 需要按单词读的使用小写，需要读字母的使用大写。或者直接GPT_SoVITS/text/engdict-hot.rep里添加chatgpt这个单词的ipa读音

请问一下，这个IPA读音可以在哪里查到，直接搜索的都是音标
