### ISSUE TITLE
请教：GPT模型和SoVITS模型之间的关系

### ISSUE THREAD

**Issue by xvease** [RVC-Boss/GPT-SoVITS#668]
我目前的情况是这样的
- TTS推理的时候，只用GPT模型也能得到很好的结果
- GPT模型和SoVITS模型一起使用的时候，全是噪音
---
1. 请问，这两个模型，分别的作用是什么？
2. 假如只用GPT或SoVITS，会有什么问题吗？

**Comment by RVC-Boss** [comment]
TTS推理的时候，只用GPT模型也能得到很好的结果：底模自带根据参考音频习得口癖和音色的功能，只是微调后会更香
GPT模型和SoVITS模型一起使用的时候，全是噪音：sovits轮数太高，训崩了
1、GPT：语调、停顿、说话习惯，sovits：口癖咬字、音色
2、只用一个另一个默认是用的底模兜底
