### ISSUE TITLE
我感觉可能需要一个SSML标签

### ISSUE THREAD

**Issue by JavaAndPython55** [RVC-Boss/GPT-SoVITS#678]
有没有小伙子愿意一起给他加ssml标签的。我想去做，但是我没有想好思路。
假如用ffmpeg或者sox，去处理的话，会比较消耗资源，复杂度也会比较高，而且处理的效果可能不好。

大家有啥好的思路建议吗？
我想的是从生成语音去支持，那就是改代码，而不是加代码了。难度会大许多。

大家的看法呢？是从业务处理新增还是改代码。如果改，从哪里看

**Comment by X-T-E-R** [comment]
见：https://github.com/X-T-E-R/GPT-SoVITS-Inference 

在这个fork里把推理单独分离了出来（https://github.com/X-T-E-R/TTS-for-GPT-soVITS）

这个推理都基于一个统一的api接口，现已实现快速切换人物、流式传输，可以将ssml内置

**Comment by JavaAndPython55** [comment]
我写完ssml方法后，可以把方法推到你的分支里。我是基于api.py上改的，思路大体就是切分，然后不断的推理（调用api的推理）在合并，我也没有太好的方法做ssml。可能需要你改一下调用api推理的部分改成你自己的，估计下个月开始弄ssml。
@X-T-E-R

**Comment by JavaAndPython55** [comment]
我实现了，多音字，sub替换标签，音量，但是没有ssml基础上改。是写了后端代码，调用之前进行的处理

**Comment by wukongbuku** [comment]
> 我实现了，多音字，sub替换标签，音量，但是没有ssml基础上改。是写了后端代码，调用之前进行的处理

老哥，这个代码，pr过去了么

**Comment by X-T-E-R** [comment]
初步实现了，在GSVI里

https://github.com/X-T-E-R/GPT-SoVITS-Inference/blob/stable/Inference/src/ssml_dealer.py
