### ISSUE TITLE
整合包的开启离线批量ASR 

### ISSUE THREAD

**Issue by chenkangwo** [RVC-Boss/GPT-SoVITS#683]
代码有误，路径写错，导致第一次运行需要重新下载模型
<img width="876" alt="微信图片_20240306011536" src="https://github.com/RVC-Boss/GPT-SoVITS/assets/77577505/8fd7536b-f3ae-4eef-890c-fd91a473cfd6">

**Comment by SapphireLab** [comment]
damo_asr 文件夹是重命名为 asr  了. #442 

之前旧版本如果是自己将模型放置在 damo_asr 那应该要手动迁移;
否则应该是下载到 Users/.cache/modelscope/iic 里, 不会影响新版本调用.

**Comment by RVC-Boss** [comment]
楼上正解
