### ISSUE TITLE
在一键三连时报错valueerro：not enough values to unpack该怎么处理？

### ISSUE THREAD

**Issue by DimSterne** [RVC-Boss/GPT-SoVITS#684]
![QQ图片20240306012154](https://github.com/RVC-Boss/GPT-SoVITS/assets/138013343/9667f9a5-bb8e-4d76-bc9a-d3ce027b0d33)

**Comment by SapphireLab** [comment]
图片没有传上来.

**Comment by RVC-Boss** [comment]
楼上正解。每行3个|，不是3个|的会报错+忽略该行数据
