### ISSUE TITLE
error in GPT_SoVITS/text/tone_sandhi.py in func: _merge_yi(): 

### ISSUE THREAD

**Issue by kingfener** [RVC-Boss/GPT-SoVITS#687]
when I try GPT_SoVITS , an error occur in func: _merge_yi
The fixed function is here: (note: only delete line: " and pos == "v")

test sentence is: 是的好主意不过或许咱们该出去把车挪一挪免得车被砸出坑来 
挪一挪 will error  if not fix.

************************* ok *************************
def _merge_yi(self, seg: List[Tuple[str, str]]) -> List[Tuple[str, str]]:
        new_seg = []
        # function 1
        for i, (word, pos) in enumerate(seg):
            if (
                i - 1 >= 0
                and word == "一"
                and i + 1 < len(seg)
                and seg[i - 1][0] == seg[i + 1][0]
                and seg[i - 1][1] == "v"
            ):
                new_seg[i - 1][0] = new_seg[i - 1][0] + "一" + new_seg[i - 1][0]
            else:
                if (
                    i - 2 >= 0
                    and seg[i - 1][0] == "一"
                    and seg[i - 2][0] == word
                    # and pos == "v"
                ):
                    continue
                else:
                    new_seg.append([word, pos])
        seg = new_seg
        new_seg = []
        # function 2
        for i, (word, pos) in enumerate(seg):
            if new_seg and new_seg[-1][0] == "一":
                new_seg[-1][0] = new_seg[-1][0] + word
            else:
                new_seg.append([word, pos])
        return new_seg

**Comment by kingfener** [comment]
last fix method not work for sentence: 你们二十多个人一人三千里并肩造反我可受不了

change : # and pos == "v"
to : and (pos == "v" or pos == "ns")

is ok .

**Comment by KamioRinn** [comment]
在之前的版本里已经修复，请拉取最新源码
