### ISSUE TITLE
目前选择中文会支持中英混合吗？

### ISSUE THREAD

**Issue by jax-explorer** [RVC-Boss/GPT-SoVITS#689]
目前选择中文会支持中英混合吗？选择中文后貌似不支持中英混合。

**Comment by RVC-Boss** [comment]
确定只有中文，建议选择中文
确定有中文+英文，建议选择中英混合
已知条件越多进行更精准的限制，语种切分也会更准
选择中文会把英文也当做中文来看就是空，相当于miss掉了
