### ISSUE TITLE
Why GPT?

### ISSUE THREAD

**Issue by BankNatchapol** [RVC-Boss/GPT-SoVITS#691]
Thank you for your incredible work! 
I'm curious about your choice to use GPT instead of BERT. Do you have specific reasons for this decision? 
I appreciate your insights in advance.

**Comment by RVC-Boss** [comment]
BERT is also used. 
https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/AR/models/t2s_model.py#L54
