### ISSUE TITLE
界面没有反应

### ISSUE THREAD

**Issue by JesseZZZZZ** [RVC-Boss/GPT-SoVITS#693]
大佬好！如果我没有训练，只是想用别人训练好的模型进行测试的话，为什么在点击
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/128620656/dbecbabb-080d-4515-baf1-8cbe6070a435)
后显示路径不存在呢？我已经在上面把模型路径换成我自己上传上去的模型了，为啥还会显示默认的路径不存在呢，谢谢大佬！
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/128620656/2e8d8034-0405-472c-94f8-e04103381df2)

**Comment by SapphireLab** [comment]
缺少了预训练模型无法推理.
1. 可以从[此处](https://www.icloud.com.cn/iclouddrive/056y_Xog_HXpALuVUjscIwTtg#GPT-SoVITS_Models)下载然后放在相应文件夹位置. 参考[文档](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e/znoph9dtetg437xb).
2. 直接下载整合包, 避免出现其他问题.

**Comment by JesseZZZZZ** [comment]
> 缺少了预训练模型无法推理.
> 
> 1. 可以从[此处](https://www.icloud.com.cn/iclouddrive/056y_Xog_HXpALuVUjscIwTtg#GPT-SoVITS_Models)下载然后放在相应文件夹位置. 参考[文档](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e/znoph9dtetg437xb).
> 2. 直接下载整合包, 避免出现其他问题.

好的！看来只测试不训练也需要下载预训练模型...
