### ISSUE TITLE
Windows的整合包该如何更新？

### ISSUE THREAD

**Issue by supwang** [RVC-Boss/GPT-SoVITS#706]
Hi, All:

下载了Windows的整合包，请问怎么进行后续的更新？
谢谢！

**Comment by RVC-Boss** [comment]
1、增量更新
一般是github下载最新代码覆盖，再runtime\python -m pip install -r requirements.txt可以更新
2、会一直更新最新的稳定的整合包，在原来的网盘地址

**Comment by supwang** [comment]
> 1、增量更新 一般是github下载最新代码覆盖，再runtime\python -m pip install -r requirements.txt可以更新 2、会一直更新最新的稳定的整合包，在原来的网盘地址

谢谢！
