### ISSUE TITLE
有试了zeroshot的朋友，反馈一下效果如何吗？

### ISSUE THREAD

**Issue by lucasjinreal** [RVC-Boss/GPT-SoVITS#71]
zeroshot机械音比较重，基本不可用，fewshot有人试了效果如何吗

**Comment by kexul** [comment]
B站有很多视频：https://www.bilibili.com/video/BV1aQ4y1w7bF https://www.bilibili.com/video/BV1Hw411J7aA

**Comment by selfboot** [comment]
我自己训练了个，给不同人听，有的说很像，有的说不像。

录了 1 分钟多音频，但是声音质量有点差，有噪音在里面。用默认参数训练，我觉得还挺像

**Comment by lucasjinreal** [comment]
@kexul 这几个感觉都是几个小时的数据训练的 啊。

@selfboot 挺像 但是声音质量有点差是啥意思

**Comment by selfboot** [comment]
> @kexul 这几个感觉都是几个小时的数据训练的 啊。
> 
> @selfboot 挺像 但是声音质量有点差是啥意思

就是我样本采集的时候，有轻微背景噪音，我也没去噪音。

**Comment by kexul** [comment]
> > @kexul 这几个感觉都是几个小时的数据训练的 啊。
> > 
> > @selfboot 挺像 但是声音质量有点差是啥意思
> 
> 就是我样本采集的时候，有轻微背景噪音，我也没去噪音。

有啥好办法去噪么？我现在是用audacity手动搞的，费劲

**Comment by company8** [comment]
> > > @kexul 这几个感觉都是几个小时的数据训练的 啊。
> > > @selfboot 挺像 但是声音质量有点差是啥意思
> > 
> > 
> > 就是我样本采集的时候，有轻微背景噪音，我也没去噪音。
> 
> 有啥好办法去噪么？我现在是用audacity手动搞的，费劲

[UVR5 ](https://github.com/Anjok07/ultimatevocalremovergui)

**Comment by lucasjinreal** [comment]
@kexul 你是自己标注了6分钟数据训练的吗，有没有音频听一下看看

**Comment by kexul** [comment]
> @kexul 你是自己标注了6分钟数据训练的吗，有没有音频听一下看看

我用webui里面的打标工具搞的，里面是调用了阿里的funasr来做asr，然后手动检查了一下文本。感觉需要修改的地方主要是断句，加了一些标点符号。

我这边差不多收集了30多分钟的音频。效果我不知道能不能分享，收集的一个知名解说的直播视频，感觉会有版权问题...

**Comment by kexul** [comment]
刚刚试了一下只用6分钟左右来微调，感觉效果还是不太行，比之前半小时的数据差距很明显。估计数据还是越多越好。
