### ISSUE TITLE
英文发音”A“不准确

### ISSUE THREAD

**Issue by Yuyu-Liu11037** [RVC-Boss/GPT-SoVITS#717]
感谢大佬的辛苦工作。我用大约十多分钟的中英混合文本（几乎全是中文，有个别英文小写字母）的语料微调。但是模型在读”A“时读的是”啊“ 而不是 ”诶“。比如，"... AI..."读的就是 ”啊 埃“。目前暂时没有发现其他读音错误，请问有什么解决办法吗？非常感谢。

**Comment by porUnaCabeza-nine** [comment]
大佬 这个问题解决了吗

**Comment by KamioRinn** [comment]
A的读音非常多，只能根据标注词组来传入正确发音。
1、在GPT_SoVITS/text/engdict-hot.rep中添加一行AI EY1 AY1
2、删除GPT_SoVITS/text/engdict_cache.pickle
3、重新启动推理界面
4、确保文本框内的ai是小写（大写字母会拆个单字母发音。无法识别为词组）

**Comment by KamioRinn** [comment]
A的读音非常多，只能根据标注词组来传入正确发音。
1、在GPT_SoVITS/text/engdict-hot.rep中添加一行AI EY1 AY2
2、删除GPT_SoVITS/text/engdict_cache.pickle
3、重新启动推理界面
4、确保文本框内的ai是小写（大写字母会拆个单字母发音。无法识别为词组）

**Comment by 7yilink** [comment]
这个规则怎么标，都是什么意义？
AI EY1 AY2

比如我想它读出所有的字母 A B C D这样，应当怎么改？

我查看了系统里的文件，当前内容是：
CHATGPT CH AE1 T JH IY1 P IY1 T IY1

**Comment by Yuyu-Liu11037** [comment]
这个是ARPABET，可以在
http://www.speech.cs.cmu.edu/cgi-bin/cmudict/?in=CHATGPT&stress=-s 查询。

7yilink ***@***.***> 于2024年3月21日周四 20:53写道：

**Comment by HaoTang1** [comment]
我加了AI EY1 AY2到engdict-hot.rep里，但是如果是中英文连续读的话，还是会发音不对，比如
**学习ai制作教案的过程**
这里的ai还是会被吞音，除非我改成

**学习，ai，制作教案的过程**
这样才能听出一些ai这个词的读音，但是停顿很奇怪

请问大佬们还有没有更好的解决办法？

我也尝试过用中文文字代替ai这两个字，用了“诶哎”，但是这个“诶”经常是三声。不知道有没有什么方法可以改成一声

**Comment by Heey731** [comment]
> 我加了AI EY1 AY2到engdict-hot.rep里，但是如果是中英文连续读的话，还是会发音不对，比如 **学习ai制作教案的过程** 这里的ai还是会被吞音，除非我改成
> 
> **学习，ai，制作教案的过程** 这样才能听出一些ai这个词的读音，但是停顿很奇怪
> 
> 请问大佬们还有没有更好的解决办法？
> 
> 我也尝试过用中文文字代替ai这两个字，用了“诶哎”，但是这个“诶”经常是三声。不知道有没有什么方法可以改成一声

请问大佬目前解决这个问题了吗？

**Comment by KamioRinn** [comment]
更新到最新版本代码可解决

**Comment by Heey731** [comment]
> 更新到最新版本代码可解决

您好！请问是3hours前更新的部分吗？我今天上午重新更新了代码还是出现了问题

**Comment by KamioRinn** [comment]
> > 更新到最新版本代码可解决
> 
> 您好！请问是3hours前更新的部分吗？我今天上午重新更新了代码还是出现了问题

应该是英文部分太短了，导致推理出来的语速太快了

**Comment by hao-vizseek** [comment]
> > 我加了AI EY1 AY2到engdict-hot.rep里，但是如果是中英文连续读的话，还是会发音不对，比如 **学习ai制作教案的过程** 这里的ai还是会被吞音，除非我改成
> > **学习，ai，制作教案的过程** 这样才能听出一些ai这个词的读音，但是停顿很奇怪
> > 请问大佬们还有没有更好的解决办法？
> > 我也尝试过用中文文字代替ai这两个字，用了“诶哎”，但是这个“诶”经常是三声。不知道有没有什么方法可以改成一声
> 
> 请问大佬目前解决这个问题了吗？

用了[#1175](https://github.com/RVC-Boss/GPT-SoVITS/issues/1175)大佬们的方法，修改代码后，AI我就直接写成了诶{1}哎，至少这个词效果还不错

其他的英文缩写我也没尝试。我最终流程里面大部分用了GPT-SoVITS，小部分效果不好的语句改用了ChatTTS+RVC的方式。

**Comment by Heey731** [comment]
> > > 更新到最新版本代码可解决
> > 
> > 
> > 您好！请问是3hours前更新的部分吗？我今天上午重新更新了代码还是出现了问题
> 
> 应该是英文部分太短了，导致推理出来的语速太快了



> > > 更新到最新版本代码可解决
> > 
> > 
> > 您好！请问是3hours前更新的部分吗？我今天上午重新更新了代码还是出现了问题
> 
> 应该是英文部分太短了，导致推理出来的语速太快了

感谢您的回复，我的问题就是AI的读音，我文本中改成了",ai"，大部分会都正确，会有少部分还是读音有问题

**Comment by Heey731** [comment]
> > > 更新到最新版本代码可解决
> > 
> > 
> > 您好！请问是3hours前更新的部分吗？我今天上午重新更新了代码还是出现了问题
> 
> 应该是英文部分太短了，导致推理出来的语速太快了

或许也有可能是我训练数据的单一性产生的问题，我目前的训练素材是1min左右纯中文音频，请问大佬是不是加入AI等相关的英文字母训练可以提高效果呢？

**Comment by KamioRinn** [comment]
> 
> 感谢您的回复，我的问题就是AI的读音，我文本中改成了",ai"，大部分会都正确，会有少部分还是读音有问题

如果用小写的话，肯定会读成 “AY1” 的（英文字典原因）。只有在大写情况下才会按单个字母发音读成“EY1 AY1”。经过测试，在混合模式下英文短词前添加一个停顿符号确实有助于更好的发音，不会被前面的句子带着吞。
