### ISSUE TITLE
ASR 过程中进度不动

### ISSUE THREAD

**Issue by GrootLiu** [RVC-Boss/GPT-SoVITS#724]
"/home/jss41/miniconda3/envs/GPTSoVits/bin/python" tools/asr/funasr_asr.py -i "/home/jss41/liuao/GPT-SoVITS/output/slicer_opt" -o "output/asr_opt" -s large -l zh -p float16

tables:

-----------    ** dataset_classes **    --------------
| class name   | class location                               |
| AudioDataset | funasr/datasets/audio_datasets/datasets.py:7 |
-----------    ** index_ds_classes **    --------------
| class name   | class location                               |
| IndexDSJsonl | funasr/datasets/audio_datasets/index_ds.py:9 |
-----------    ** batch_sampler_classes **    --------------
| class name   | class location                               |
| BatchSampler | funasr/datasets/audio_datasets/samplers.py:7 |
-----------    ** frontend_classes **    --------------
| class name        | class location                       |
| WavFrontend       | funasr/frontends/wav_frontend.py:78  |
| WavFrontendOnline | funasr/frontends/wav_frontend.py:216 |
-----------    ** encoder_classes **    --------------
| class name            | class location                                        |
| BranchformerEncoder   | funasr/models/branchformer/encoder.py:294             |
| ConformerChunkEncoder | funasr/models/bat/conformer_chunk_encoder.py:315      |
| ConformerEncoder      | funasr/models/conformer/encoder.py:286                |
| DFSMN                 | funasr/models/fsmn_vad_streaming/encoder.py:232       |
| EBranchformerEncoder  | funasr/models/e_branchformer/encoder.py:177           |
| FSMN                  | funasr/models/fsmn_vad_streaming/encoder.py:161       |
| SANMEncoder           | funasr/models/sanm/encoder.py:161                     |
| SANMEncoderChunkOpt   | funasr/models/scama/encoder.py:162                    |
| SANMVadEncoder        | funasr/models/ct_transformer_streaming/encoder.py:148 |
| TransformerEncoder    | funasr/models/transformer/encoder.py:139              |
-----------    ** predictor_classes **    --------------
| class name     | class location                                     |
| CifPredictor   | funasr/models/paraformer/cif_predictor.py:15       |
| CifPredictorV2 | funasr/models/paraformer/cif_predictor.py:141      |
| CifPredictorV3 | funasr/models/bicif_paraformer/cif_predictor.py:95 |
-----------    ** model_classes **    --------------
| class name             | class location                                     |
| BiCifParaformer        | funasr/models/bicif_paraformer/model.py:37         |
| Branchformer           | funasr/models/branchformer/model.py:6              |
| CAMPPlus               | funasr/models/campplus/model.py:30                 |
| CTTransformer          | funasr/models/ct_transformer/model.py:30           |
| CTTransformerStreaming | funasr/models/ct_transformer_streaming/model.py:27 |
| Conformer              | funasr/models/conformer/model.py:8                 |
| ContextualParaformer   | funasr/models/contextual_paraformer/model.py:43    |
| EBranchformer          | funasr/models/e_branchformer/model.py:6            |
| Emotion2vec            | funasr/models/emotion2vec/model.py:34              |
| FsmnVADStreaming       | funasr/models/fsmn_vad_streaming/model.py:267      |
| MonotonicAligner       | funasr/models/monotonic_aligner/model.py:24        |
| Paraformer             | funasr/models/paraformer/model.py:26               |
| ParaformerStreaming    | funasr/models/paraformer_streaming/model.py:37     |
| SANM                   | funasr/models/sanm/model.py:13                     |
| SCAMA                  | funasr/models/scama/model.py:38                    |
| SeacoParaformer        | funasr/models/seaco_paraformer/model.py:45         |
| Transformer            | funasr/models/transformer/model.py:20              |
| UniASR                 | funasr/models/uniasr/model.py:26                   |
-----------    ** decoder_classes **    --------------
| class name                                 | class location                                     |
| ContextualParaformerDecoder                | funasr/models/contextual_paraformer/decoder.py:103 |
| DynamicConvolution2DTransformerDecoder     | funasr/models/transformer/decoder.py:588           |
| DynamicConvolutionTransformerDecoder       | funasr/models/transformer/decoder.py:527           |
| FsmnDecoder                                | funasr/models/sanm/decoder.py:198                  |
| FsmnDecoderSCAMAOpt                        | funasr/models/scama/decoder.py:197                 |
| LightweightConvolution2DTransformerDecoder | funasr/models/transformer/decoder.py:465           |
| LightweightConvolutionTransformerDecoder   | funasr/models/transformer/decoder.py:404           |
| ParaformerSANDecoder                       | funasr/models/paraformer/decoder.py:529            |
| ParaformerSANMDecoder                      | funasr/models/paraformer/decoder.py:204            |
| TransformerDecoder                         | funasr/models/transformer/decoder.py:355           |
-----------    ** normalize_classes **    --------------
| class name   | class location                             |
| GlobalMVN    | funasr/models/normalize/global_mvn.py:11   |
| UtteranceMVN | funasr/models/normalize/utterance_mvn.py:8 |
-----------    ** specaug_classes **    --------------
| class name | class location                       |
| SpecAug    | funasr/models/specaug/specaug.py:14  |
| SpecAugLFR | funasr/models/specaug/specaug.py:104 |
-----------    ** tokenizer_classes **    --------------
| class name    | class location                        |
| CharTokenizer | funasr/tokenizer/char_tokenizer.py:10 |

2024-03-09 07:03:31,133 - modelscope - INFO - PyTorch version 2.2.1 Found.
2024-03-09 07:03:31,133 - modelscope - INFO - Loading ast index from /home/jss41/.cache/modelscope/ast_indexer
2024-03-09 07:03:31,158 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 b7c2b149387f4a2e3ca2b94846f1ba09 and a total number of 946 components indexed
2024-03-09 07:03:31,588 - modelscope - INFO - Use user-specified model revision: v2.0.4
Downloading:   0%|                                                                                                                                                                     | 0.00/840M [00:00<?, ?B/s]

**Comment by GrootLiu** [comment]
从后台查看日志，发现一直卡在 Downloading，怀疑是被墙，但是目前不知道是python还是什么其他的在Downloading，所以不知道该给谁挂代理，请问有知道的同学吗？

**Comment by GrootLiu** [comment]
过了好一阵自己动了，没事了😂

**Comment by 2268190072** [comment]
你好，我和你一样半天不动，后来下一个进度动了，第一个还是0%。这是为什么？需要挂代理？

**Comment by 2268190072** [comment]
后续进度反复卡住失败。2060 6g ，请问您是什么配置

**Comment by Zbin0519** [comment]
我一直在这个地方卡住了，现在有解决办法了吗

**Comment by GrootLiu** [comment]
我之后是卡了半个小时就动了，有点莫名其妙就好了的感觉发自我的 iPhone在 2024年4月29日，02:09，Zbin0519 ***@***.***> 写道：﻿
我一直在这个地方卡住了，现在有解决办法了吗

**Comment by qian1qing** [comment]
as the png,the speed only 60-70KB/s ,but the longth is 3.09GB
![ image of the speed](https://github.com/qian1qing/image_bed/blob/main/programing/snowly_asr_of_GPT-SoVITS.png)
