### ISSUE TITLE
能否优化下，生产音频时候的逻辑

### ISSUE THREAD

**Issue by aloxc** [RVC-Boss/GPT-SoVITS#726]
1.生成音频后把temp目录下上传的参考音频删除
2。生成音频后，从页面上下载生成的音频文件重命名下，以当前模型作为前嘴，比如当前模型是aaa，那生成的音频文件命名为aaa_随机值或者时间，
3.

**Comment by ben0oil1** [comment]
这个自己写一两行代码的事情
