### ISSUE TITLE
一键三联报错GPT_SoVITS/pretrained_models/chinese-hubert-base and are newly initialized: ['encoder.pos_conv_embed.conv.parametrizations.weight.original0'

### ISSUE THREAD

**Issue by gaoleihero** [RVC-Boss/GPT-SoVITS#73]
一键三联是报错
Some weights of HubertModel were not initialized from the model checkpoint at GPT_SoVITS/pretrained_models/chinese-hubert-base and are newly initialized: ['encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
我的模型是提前下载好的

**Comment by RoversX** [comment]
这个算警告，不算报错

**Comment by huangxu1991** [comment]
@RVC-Boss 所以下面这两个 weight：
encoder.pos_conv_embed.conv.weight_v 
encoder.pos_conv_embed.conv.weight_g
只使用随机初始化，是符合预期的吗？
