### ISSUE TITLE
Permission denied in Labeling

### ISSUE THREAD

**Issue by Louis24** [RVC-Boss/GPT-SoVITS#731]
Permission denied  in opening the  [0d-语音文本校对标注工具]
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/18719360/1fbd574b-187b-47d1-a367-2330e6beadf7)

Try to change folder and give the authority，but still not working

Platform = win10

**Comment by RVC-Boss** [comment]
You should input the .list file path. The postfix is .list

**Comment by mak996** [comment]
hai can I know how to input the .list file path? sorry I am totally new in programming

**Comment by XXXXRT666** [comment]
Copy the path of list, or type it manually

**Comment by mak996** [comment]
> Copy the path of list, or type it manually

do you mean just copy the path address and type .list at the back?

**Comment by XXXXRT666** [comment]
Copy the path of the list, which contains the name of the lists and the list extension suffix

**Comment by mak996** [comment]
![1](https://github.com/RVC-Boss/GPT-SoVITS/assets/169814490/15c1e5e8-7090-4569-a57d-20d06e98ac90)
am i correct, i try to do it like this 
D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\output\asr_opt\file_paths.list

**Comment by mak996** [comment]
I get this, sorry i have a lot problem

 
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\tools\subfix_webui.py", line 310, in <module>
    set_global(args.load_json, args.load_list, args.json_key_text, args.json_key_path, args.g_batch)
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\tools\subfix_webui.py", line 295, in set_global
    b_load_file()
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\tools\subfix_webui.py", line 274, in b_load_file
    b_load_list()
  File "D:\GPT-SoVITS-beta\GPT-SoVITS-beta0217\tools\subfix_webui.py", line 244, in b_load_list
    with open(g_load_file, 'r', encoding="utf-8") as source:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\GPT-SoVITS-beta\\GPT-SoVITS-beta0217\\output\\asr_opt\\file_paths.list'
