### ISSUE TITLE
中文asr项目中未提供目录结构，有大佬可以贴一下吗？

### ISSUE THREAD

**Issue by SongDI911** [RVC-Boss/GPT-SoVITS#736]
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/50285788/7369e9c2-8c4c-4d9d-beb5-3084b81ace0e)

**Comment by BankNatchapol** [comment]
@RVC-Boss If possible, could you please provide the configuration or script for training from scratch? There are several aspects in the current script that I'm unsure about, such as the best configuration for parameters like the learning rate (currently, lr in the script is locked at 0.002) and determining which is the SoVITS encoder layers that needed to unfreeze.

**Comment by SapphireLab** [comment]
`damo_asr` 文件夹换成 `asr` 文件夹, 相应路径可以在 `tools/asr/funasr_asr.py` 中开头找到, 如下

![code](https://github.com/RVC-Boss/GPT-SoVITS/assets/36986837/eec730d9-861e-4093-b5c2-d3c085ef7b16)


![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/36986837/074b12f7-b041-420e-a06a-a8583e577512)

**Comment by SongDI911** [comment]
> `damo_asr` 文件夹换成 `asr` 文件夹, 相应路径可以在 `tools/asr/funasr_asr.py` 中开头找到, 如下
> 
> ![code](https://private-user-images.githubusercontent.com/36986837/311602025-eec730d9-861e-4093-b5c2-d3c085ef7b16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzgwNjEsIm5iZiI6MTcxMDEzNzc2MSwicGF0aCI6Ii8zNjk4NjgzNy8zMTE2MDIwMjUtZWVjNzMwZDktODYxZS00MDkzLWI1YzItZDNjMDg1ZWY3YjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA2MTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMmFjNzA1NzQ1YzYxN2E3NmMwZmUyZjY2YWZmNzNlYjI0YjQzNWZkNjgyNmVkY2IwY2Q3NDU0YThmOGNjMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Marjiq0ucd72avGbFQU77ievuLEjhmyJ4uHgWydpcCs)
> 
> ![image](https://private-user-images.githubusercontent.com/36986837/311601861-074b12f7-b041-420e-a06a-a8583e577512.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzgwNjEsIm5iZiI6MTcxMDEzNzc2MSwicGF0aCI6Ii8zNjk4NjgzNy8zMTE2MDE4NjEtMDc0YjEyZjctYjA0MS00MjBlLWEwNmEtYTg1ODNlNTc3NTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA2MTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZmYwNjcxNTgxNDEwYTBiNmY0NTg5NTIyMDFmMmM4MTc5ZDQ0YmEyYTQwZTg0MGY3OTY0ZmVkOWFjNmM4Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KLFU0sBFk_4mLgrtkL6--w2GeeTorPYaXRzJAPTpDNo)

非常感谢！！
