### ISSUE TITLE
格式化数据集时，英文的内容录音，3-bert 没有内容，中文的内容录音，没有问题

### ISSUE THREAD

**Issue by meicale** [RVC-Boss/GPT-SoVITS#737]
同标题！目前没有找到其他的不同点！

**Comment by SapphireLab** [comment]
因为 `GPT_SoVITS/prepare_datasets/1-get-text.py` 中 3-bert 特征 `bert_feature` 是仅对中文处理. 其他语言将没有文件.
在训练 GPT 部分, 没有该文件时, 相应的 `bert_feature` 将为 `None`.

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/36986837/16571f92-3bae-4f04-ab87-e70147280632)

**Comment by RVC-Boss** [comment]
没有是正常的。

**Comment by RVC-Boss** [comment]
正常的。
