### ISSUE TITLE
两步训练中vq不一致的疑惑

### ISSUE THREAD

**Issue by NiHaoUCAS** [RVC-Boss/GPT-SoVITS#747]
有个疑惑请教一下， 我看在s1_train的数据处理中用到了预训练的vq，然后在s2_train里面会load预训练的vq模型，然后微调vq， 如果按照s1 --> s2的顺序来微调， 岂不是会发生两步的vq不匹配？

**Comment by ChasonJiang** [comment]
> 有个疑惑请教一下， 我看在s1_train的数据处理中用到了预训练的vq，然后在s2_train里面会load预训练的vq模型，然后微调vq， 如果按照s1 --> s2的顺序来微调， 岂不是会发生两步的vq不匹配？

在fine tuning的时候，vq是固定的，不产生loss。
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/46401978/78fa9e1e-2487-4ffc-abee-7f6c6f8dbc1c)
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/46401978/b8ca7026-ca61-4557-b02e-157958a86f15)

**Comment by NiHaoUCAS** [comment]
> > 有个疑惑请教一下， 我看在s1_train的数据处理中用到了预训练的vq，然后在s2_train里面会load预训练的vq模型，然后微调vq， 如果按照s1 --> s2的顺序来微调， 岂不是会发生两步的vq不匹配？
> 
> 在fine tuning的时候，vq是固定的，不产生loss。 ![image](https://private-user-images.githubusercontent.com/46401978/312021004-78fa9e1e-2487-4ffc-abee-7f6c6f8dbc1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMzY1NDIsIm5iZiI6MTcxMDIzNjI0MiwicGF0aCI6Ii80NjQwMTk3OC8zMTIwMjEwMDQtNzhmYTllMWUtMjQ4Ny00ZmZjLWFiZWUtN2Y2YzZmOGRiYzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA5MzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MmY5MzcwMzE3Mzk0OWZiNmYyNGFjZGVlYTFhNTc3ZmZlNmRhODg0MmM3YjEyMDFjMDkyM2I4MjQyYmYyOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vtcDDsQjDd1yxZPZKzjAsSTArx0yo4NbhybMUFQxnX4) ![image](https://private-user-images.githubusercontent.com/46401978/312021676-b8ca7026-ca61-4557-b02e-157958a86f15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMzY1NDIsIm5iZiI6MTcxMDIzNjI0MiwicGF0aCI6Ii80NjQwMTk3OC8zMTIwMjE2NzYtYjhjYTcwMjYtY2E2MS00NTU3LWIwMmUtMTU3OTU4YTg2ZjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA5MzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkN2YxYTVmYWFlYzQwNmFiY2E0MTJiYmU5Mjk3ODA0YzNkNTU4ZGVhMTgyM2QyYjA3MTI5Mjc1ZmRjOWM1Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-c2yrd42DpprBkSet0nkDviyL9YxH4Un-7dPdE6oH8I)

requires_grad_ 为False只能保证codebook不通过梯度来更新，在代码中，codebook是通过register_buffer来注册的，本身就没有梯度。 然而，codebook还可能通过类似batch norm中的running_mean类似的方式来更新，也就是用一个新的值来覆盖原来的值，事实上，这种情况也确实发生了，发生在这里https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/module/core_vq.py#L229 。

**Comment by RVC-Boss** [comment]
这问题看起来有点大。
就是说s1train完，再trains2的decoder，会出问题…

**Comment by NiHaoUCAS** [comment]
self.quentizer.eval()应该能解决，只有在self.training = true的时候才会更新权重。

**Comment by RVC-Boss** [comment]
> self.quentizer.eval()

https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/module/models.py#L896
大佬看看现在还会变更吗@NiHaoUCAS

**Comment by edward-io** [comment]
Shouldn't this be `self.quantizer.eval()`, not `self.quentizer.eval`?

**Comment by NiHaoUCAS** [comment]
> > self.quentizer.eval()
> 
> https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/module/models.py#L896 大佬看看现在还会变更吗@NiHaoUCAS

这样应该不行，因为train_and_evaluate时，会执行net_g.train()，这样queantizer也会随之train(), 我临时解决办法是在SynthesizerTrn的forward中，添加if self.freeze_quantizer: self.quantizer.eval()。

**Comment by RVC-Boss** [comment]
@NiHaoUCAS https://github.com/RVC-Boss/GPT-SoVITS/pull/953 现在再看看呢

**Comment by RVC-Boss** [comment]
此案可结了，楼上修复后，commit_loss是0，修复前的微调，0<commit_loss<1

**Comment by xinge333** [comment]
花佬，maybe_no_grad = torch.no_grad() if self.freeze_quantizer else contextlib.nullcontext
这儿是不是漏了个括号👀()，with contextlib.nullcontext():
