### ISSUE TITLE
s1_train训练步数的问题

### ISSUE THREAD

**Issue by NiHaoUCAS** [RVC-Boss/GPT-SoVITS#750]
我在使用多卡训练的时候，发现1个epoch的step数并不是和gpu数量呈线性变化，而是指数变化。怀疑数据处理部分可能有个bug。

dataloader中调用了DistributedBucketSampler来做负载均衡，同时把数据切成ngpu份。

然而使用了pytorch_lighting作为Trainer，我查了一些文档，发现pytorch_lighting不需要在dataloader中把数据做切分，它会自动切，这样就导致训练数据被切了两次， 这样训练一轮的steps = num_samples/ngpu/ngpu，和我观察的现象一致。

**Comment by 1nlplearner** [comment]
看起来实际每张卡的batch size应该是batch*ngpu

**Comment by NiHaoUCAS** [comment]
> 看起来实际每张卡的batch size应该是batch*ngpu

应该不是，如果这样的话，8卡训练显存早就爆了

**Comment by huangxu1991** [comment]
这里有个 bug，我本地已经修复了，过几天提个 pr

**Comment by RVC-Boss** [comment]
对，一直有发现这个问题，epoch多了个节点倍数的误差，有点离谱，之前怀疑是pytorchlightning的问题，不过一直没仔细看

**Comment by huangxu1991** [comment]
@NiHaoUCAS @RVC-Boss
Hi, I've created a new PR to solve this problem. The solution is quite simple!
See here: https://github.com/RVC-Boss/GPT-SoVITS/pull/756/commits

**Comment by huangxu1991** [comment]
> @NiHaoUCAS @RVC-Boss Hi, I've created a new PR to solve this problem. The solution is quite simple! See here: https://github.com/RVC-Boss/GPT-SoVITS/pull/756/commits

虽然但是，还是花了一个晚上。。。

**Comment by huangxu1991** [comment]
> > @NiHaoUCAS @RVC-Boss Hi, I've created a new PR to solve this problem. The solution is quite simple! See here: https://github.com/RVC-Boss/GPT-SoVITS/pull/756/commits #756
> 
> @huangxu1991 会遇到什么其他的问题吗，比如显存占用、消耗增加，训练时间变长之类的

Hi 我测试下来没有任何问题，你们要是碰到问题尽管提出来 @RVC-Boss @NiHaoUCAS

**Comment by 1nlplearner** [comment]
> > @NiHaoUCAS @RVC-Boss Hi, I've created a new PR to solve this problem. The solution is quite simple! See here: https://github.com/RVC-Boss/GPT-SoVITS/pull/756/commits #756
> 
> @huangxu1991 会遇到什么其他的问题吗，比如显存占用、消耗增加，训练时间变长之类的

8卡训练的，修改代码之后一个epoch的迭代步数x8，训练时长大概x6

**Comment by huangxu1991** [comment]
> > > @NiHaoUCAS @RVC-Boss Hi, I've created a new PR to solve this problem. The solution is quite simple! See here: https://github.com/RVC-Boss/GPT-SoVITS/pull/756/commits #756
> > 
> > 
> > @huangxu1991 会遇到什么其他的问题吗，比如显存占用、消耗增加，训练时间变长之类的
> 
> 8卡训练的，修改代码之后一个epoch的迭代步数x8，训练时长大概x6

符合预期，未修改之前其实训练数据很多没用到，导致 step 跟计算的对不上，修改后训练数据全部用上，说明是对的。

**Comment by huangxu1991** [comment]
#756 没问题的话，可以合并了 @RVC-Boss
