### ISSUE TITLE
一些奇怪的Error

### ISSUE THREAD

**Issue by zjy1412** [RVC-Boss/GPT-SoVITS#752]
“啊啊”，“灼热”这些词会直接导致Error，还有一些奇奇怪怪的吞句子，是那种不管执行多少次都会吞的神奇Error。

**Comment by RVC-Boss** [comment]
版本为？

**Comment by zjy1412** [comment]
> 版本为？

文件夹名是GPT-SoVITS-beta0217。

**Comment by RVC-Boss** [comment]
楼上正解，升级langseg库。
