### ISSUE TITLE
英文发音错误

### ISSUE THREAD

**Issue by yinjie1949** [RVC-Boss/GPT-SoVITS#760]
https://github.com/RVC-Boss/GPT-SoVITS/assets/88878773/ab71bedc-9a5a-4eda-97f4-99fb0a2a653a

英文发音错误，把red 读成read了

**Comment by KamioRinn** [comment]
RED和READ都是/rɛd/

**Comment by yinjie1949** [comment]
read一般来说读/riːd/ 这里的red没有读成/rɛd/，而是读成/riːd/ 了

**Comment by qieqieplus** [comment]
现在的en g2p没有处理英文多音字。g2p_en实际是可以处理多音字的，但现在只有不在词典的词才会调用g2p_en。
