### ISSUE TITLE
[Bug]labelling WebU 修改文本Save似乎是失败的

### ISSUE THREAD

**Issue by alphazhugit** [RVC-Boss/GPT-SoVITS#771]

**Comment by SapphireLab** [comment]
是按照“勾选右侧复选框并点击上侧的submit text”进行操作的吗?

**Comment by alphazhugit** [comment]
> 是按照“勾选右侧复选框并点击上侧的submit text”进行操作的吗?

害，那就没问题，我是点的save file，新版第一次用，抱一丝~😄
