### ISSUE TITLE
我遇到了一段让我大多数模型都抽风的话

### ISSUE THREAD

**Issue by Hwangkop** [RVC-Boss/GPT-SoVITS#787]
使用参考音频 + 参考文本
这段话是 “可以是不完美的，你一是不有我的知头，你就看向我，你种倒影着夏夜绚烂的眼眶，会热的吸引，竟让看水被心化，你的存在治愈我也慢的沉埃”

大家可以试试有没有抽风

**Comment by SapphireLab** [comment]
? 歌词是吧
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/36986837/32a67f6b-fdf9-489c-a5d9-facae8614d54)
