### ISSUE TITLE
0c-中文批量离线ASR工具-报错

### ISSUE THREAD

**Issue by thomastian** [RVC-Boss/GPT-SoVITS#792]
系统MACOS 14.4 M2 Mac mini 
ImportError: dlopen(/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/hdbscan/_hdbscan_linkage.cpython-39-darwin.so, 0x0002): tried: '/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/hdbscan/_hdbscan_linkage.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/hdbscan/_hdbscan_linkage.cpython-39-darwin.so' (no such file), '/opt/anaconda3/envs/GPTSoVits/lib/python3.9/site-packages/hdbscan/_hdbscan_linkage.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))

**Comment by Lion-Wu** [comment]
请下载arm版本的annaconda，不要下载x86，官网有选的

**Comment by thomastian** [comment]
通过arch或uname -m 命令发现系统环境不对，换成系统自带终端就正常了，有问题的包 重新安装即可：ARCHFLAGS="-arch arm64" pip install hdbscan  --compile --no-cache-dir，大概就是这样的。
