### ISSUE TITLE
API多語言合成問題

### ISSUE THREAD

**Issue by asadfgglie** [RVC-Boss/GPT-SoVITS#794]
我想請問一下
可以讓API呼叫時也可以使用多語言混和合成功能嗎?

**Comment by Lion-Wu** [comment]
#641 加入了此功能，不过暂时还没merge

**Comment by asadfgglie** [comment]
了解!
那我先用 https://github.com/RVC-Boss/GPT-SoVITS/pull/641 作替代

**Comment by KamioRinn** [comment]
API已更新 https://github.com/RVC-Boss/GPT-SoVITS/commit/4afecd1950845a974350cd2d8dc8dcf12398fba9
