### ISSUE TITLE
fast wisper下载的模型路径，不方便迁移，是否能指定现有文件？

### ISSUE THREAD

**Issue by nanoTiO2** [RVC-Boss/GPT-SoVITS#796]
经研究，现在下载的模型在这个目录里面，
```
C:\Users\Administrator\.cache\huggingface\hub\models--Systran--faster-whisper-small\snapshots\536b0662742c02347bc0e980a01041f333bce120
```
想请作者大大添加一个功能，可以自定义调用本地已有的模型文件，只要提供 下含四个文件的文件夹，就能实现调用。请作者大大有时间的时候考虑一下哈
```
config.json"
model.bin"
tokenizer.json"
vocabulary.txt"
```

**Comment by SapphireLab** [comment]
目前支持的做法是将 `models--Systran--faster-whisper-small\snapshots\536b0662742c02347bc0e980a01041f333bce120` 这个模型文件夹移动并重命名为 `tools/asr/models/faster-whisper-small`

重启WebUI就能在下拉选单中看到small多了后缀-local. 表示本地

PS：之前有写过在终端显示文件路径和迁移方式，不过未合并，有需要的话我可以改改再提交一次。

**Comment by nanoTiO2** [comment]
谢谢作者大大，回去迁移文件
