### ISSUE TITLE
变声参考这个：https://github.com/huangxu1991/GPT-SoVITS-VC

### ISSUE THREAD

**Issue by yuanhuachao** [RVC-Boss/GPT-SoVITS#801]
变声参考这个：https://github.com/huangxu1991/GPT-SoVITS-VC

_Originally posted by @huangxu1991 in https://github.com/RVC-Boss/GPT-SoVITS/issues/476#issuecomment-1990907349_
            你好，使用GPT-SoVITS-VC上传两个声音，点击合成报错：
RuntimeError: Calculated padded input size per channel: (0). Kernel size: (1). Kernel size can't be greater than actual input size
麻烦问下什么原因，如何修改？感谢！

**Comment by huangxu1991** [comment]
可能是你给的参考语音太短，注意看告警信息。

**Comment by yuanhuachao** [comment]
嗯，应该是，这两天没来得及试，后面试下，感谢回复！

**Comment by 2453995079** [comment]
我测试出现过这种情况，这个问题的核心是你输入的文本中有错误的字符，例如\n\n这种情况就会出现上面的问题
