### ISSUE TITLE
推理多次跑满1500

### ISSUE THREAD

**Issue by XXXXRT666** [RVC-Boss/GPT-SoVITS#806]
我当时在测试全半角符号的影响，选取了 #665 中的语句 `没错，它就是风靡全球的网红chat GPT。`，切法多次更换，多次推理跑满1500，使用的是两个底膜进行推理，经测试，全半角符号对于T的重复问题影响挺大
其中一段日志

```
实际输入的参考文本: 细细品味，才能理解其中风雅。
实际输入的目标文本: 。没错，它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错,它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.
实际输入的目标文本(切句后): 。没错，它就是风靡全球的网红chat GPT。没错，
它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错，
它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错,
它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.没错,
它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.
实际输入的目标文本(每句): 。没错，它就是风靡全球的网红chat GPT。没错，
['。没错，它就是风靡全球的网红', 'chat G P T。 ', '没错，']
['zh', 'en', 'zh']
前端处理后的文本(每句): .没错,它就是风靡全球的网红chat G P T。 没错,
 10%|████                                    | 150/1500 [00:02<00:24, 55.18it/s]T2S Decoding EOS [90 -> 244]
 10%|████                                    | 153/1500 [00:02<00:23, 57.72it/s]
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
实际输入的目标文本(每句): 它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错，
['它就是风靡全球的网红', 'chat G P T。 ', '没错，它就是风靡全球的网红', 'chat G P T。 ', '没错，']
['zh', 'en', 'zh', 'en', 'zh']
前端处理后的文本(每句): 它就是风靡全球的网红chat G P T。 没错,它就是风靡全球的网红chat G P T。 没错,
100%|███████████████████████████████████████| 1500/1500 [00:42<00:00, 35.33it/s]
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
实际输入的目标文本(每句): 它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错,
['它就是风靡全球的网红', 'chat G P T。 ', '没错，它就是风靡全球的网红', 'chat G P T。 ', '没错,']
['zh', 'en', 'zh', 'en', 'zh']
前端处理后的文本(每句): 它就是风靡全球的网红chat G P T。 没错,它就是风靡全球的网红chat G P T。 没错,
100%|███████████████████████████████████████| 1500/1500 [00:43<00:00, 34.79it/s]
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
实际输入的目标文本(每句): 它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.没错,
['它就是风靡全球的网红', 'chat G P T. ', '没错,它就是风靡全球的网红', 'chat G P T. ', '没错,']
['zh', 'en', 'zh', 'en', 'zh']
前端处理后的文本(每句): 它就是风靡全球的网红chat G P T. 没错,它就是风靡全球的网红chat G P T. 没错,
100%|███████████████████████████████████████| 1500/1500 [00:43<00:00, 34.20it/s]
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
实际输入的目标文本(每句): 它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.
['它就是风靡全球的网红', 'chat G P T. ', '没错,它就是风靡全球的网红', 'chat G P T. ', '没错,它就是风靡全球的网红', 'chat G P T. ']
['zh', 'en', 'zh', 'en', 'zh', 'en']
前端处理后的文本(每句): 它就是风靡全球的网红chat G P T. 没错,它就是风靡全球的网红chat G P T. 没错,它就是风靡全球的网红chat G P T. 
100%|███████████████████████████████████████| 1500/1500 [00:38<00:00, 38.85it/s]
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
1.316	188.003	38.612	15.007
```

**Comment by XXXXRT666** [comment]
不使用底膜则不出现

**Comment by Downupanddownup** [comment]
这个项目有多个底模吗？有啥区别呢？

**Comment by LLLYF** [comment]
> 我当时在测试全半角符号的影响，选取了 #665 中的语句 `没错，它就是风靡全球的网红chat GPT。`，切法多次更换，多次推理跑满1500，使用的是两个底膜进行推理，经测试，全半角符号对于T的重复问题影响挺大 其中一段日志
> 
> ```
> 实际输入的参考文本: 细细品味，才能理解其中风雅。
> 实际输入的目标文本: 。没错，它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错,它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.
> 实际输入的目标文本(切句后): 。没错，它就是风靡全球的网红chat GPT。没错，
> 它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错，
> 它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错,
> 它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.没错,
> 它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.
> 实际输入的目标文本(每句): 。没错，它就是风靡全球的网红chat GPT。没错，
> ['。没错，它就是风靡全球的网红', 'chat G P T。 ', '没错，']
> ['zh', 'en', 'zh']
> 前端处理后的文本(每句): .没错,它就是风靡全球的网红chat G P T。 没错,
>  10%|████                                    | 150/1500 [00:02<00:24, 55.18it/s]T2S Decoding EOS [90 -> 244]
>  10%|████                                    | 153/1500 [00:02<00:23, 57.72it/s]
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> 实际输入的目标文本(每句): 它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错，
> ['它就是风靡全球的网红', 'chat G P T。 ', '没错，它就是风靡全球的网红', 'chat G P T。 ', '没错，']
> ['zh', 'en', 'zh', 'en', 'zh']
> 前端处理后的文本(每句): 它就是风靡全球的网红chat G P T。 没错,它就是风靡全球的网红chat G P T。 没错,
> 100%|███████████████████████████████████████| 1500/1500 [00:42<00:00, 35.33it/s]
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> 实际输入的目标文本(每句): 它就是风靡全球的网红chat GPT。没错，它就是风靡全球的网红chat GPT。没错,
> ['它就是风靡全球的网红', 'chat G P T。 ', '没错，它就是风靡全球的网红', 'chat G P T。 ', '没错,']
> ['zh', 'en', 'zh', 'en', 'zh']
> 前端处理后的文本(每句): 它就是风靡全球的网红chat G P T。 没错,它就是风靡全球的网红chat G P T。 没错,
> 100%|███████████████████████████████████████| 1500/1500 [00:43<00:00, 34.79it/s]
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> 实际输入的目标文本(每句): 它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.没错,
> ['它就是风靡全球的网红', 'chat G P T. ', '没错,它就是风靡全球的网红', 'chat G P T. ', '没错,']
> ['zh', 'en', 'zh', 'en', 'zh']
> 前端处理后的文本(每句): 它就是风靡全球的网红chat G P T. 没错,它就是风靡全球的网红chat G P T. 没错,
> 100%|███████████████████████████████████████| 1500/1500 [00:43<00:00, 34.20it/s]
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> 实际输入的目标文本(每句): 它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.没错,它就是风靡全球的网红chat GPT.
> ['它就是风靡全球的网红', 'chat G P T. ', '没错,它就是风靡全球的网红', 'chat G P T. ', '没错,它就是风靡全球的网红', 'chat G P T. ']
> ['zh', 'en', 'zh', 'en', 'zh', 'en']
> 前端处理后的文本(每句): 它就是风靡全球的网红chat G P T. 没错,它就是风靡全球的网红chat G P T. 没错,它就是风靡全球的网红chat G P T. 
> 100%|███████████████████████████████████████| 1500/1500 [00:38<00:00, 38.85it/s]
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> 1.316	188.003	38.612	15.007
> ```

您好，很抱歉打扰您，所以您的测试结果是全部替换成中文符号就不容易跑满对吗，那这样的话也就需要到源码中把一些正则给处理掉对吗？

**Comment by XXXXRT666** [comment]
已修复
