### ISSUE TITLE
1B训练结束保存模型报错，前面的Issue说Fixed now.但仍然有错，作者再看一下

### ISSUE THREAD

**Issue by aigcun** [RVC-Boss/GPT-SoVITS#817]
Fixed now.

_Originally posted by @RVC-Boss in https://github.com/RVC-Boss/GPT-SoVITS/issues/141#issuecomment-1913563734_

INFO:snape_0319:====> Epoch: 7
16it [00:08,  1.79it/s]
INFO:snape_0319:Saving model and optimizer state at iteration 8 to logs/snape_0319/logs_s2\G_233333333333.pth
Traceback (most recent call last):
  File "D:\Git\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 600, in <module>
    main()
  File "D:\Git\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 56, in main
    mp.spawn(
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 202, in start_processes
    while not context.join():
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\serialization.py", line 619, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\serialization.py", line 853, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
RuntimeError: [enforce fail at inline_container.cc:593] . PytorchStreamWriter failed writing file data/167: file write failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 74, in _wrap
    fn(i, *args)
  File "D:\Git\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 254, in run
    train_and_evaluate(
  File "D:\Git\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 470, in train_and_evaluate
    utils.save_checkpoint(
  File "D:\Git\GPT-SoVITS\GPT_SoVITS\utils.py", line 87, in save_checkpoint
    my_save(
  File "D:\Git\GPT-SoVITS\GPT_SoVITS\utils.py", line 73, in my_save
    torch.save(fea,tmp_path)
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\serialization.py", line 620, in save
    return
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\serialization.py", line 466, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:424] . unexpected pos 162256064 vs 162255952

**Comment by aigcun** [comment]
代码在24年3，18日才更新的，
另外pip install faster-whisper==0.10.1用了这个版本
麻烦看一下

**Comment by aigcun** [comment]
重装了torch,cuda
重拉了代码，
第四轮保存成功，但最终的却保存失败

(GPTSoVits) D:\Git\GPT-SoVITS>python.exe webui.py
Running on local URL:  http://0.0.0.0:9874
"D:\anaconda3\envs\GPTSoVits\python.exe" GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py
"D:\anaconda3\envs\GPTSoVits\python.exe" GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py
D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Some weights of the model checkpoint at GPT_SoVITS/pretrained_models/chinese-hubert-base were not used when initializing HubertModel: ['encoder.pos_conv_embed.conv.weight_g', 'encoder.pos_conv_embed.conv.weight_v']
- This IS expected if you are initializing HubertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing HubertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at GPT_SoVITS/pretrained_models/chinese-hubert-base were not used when initializing HubertModel: ['encoder.pos_conv_embed.conv.weight_g', 'encoder.pos_conv_embed.conv.weight_v']
- This IS expected if you are initializing HubertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing HubertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of HubertModel were not initialized from the model checkpoint at GPT_SoVITS/pretrained_models/chinese-hubert-base and are newly initialized: ['encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of HubertModel were not initialized from the model checkpoint at GPT_SoVITS/pretrained_models/chinese-hubert-base and are newly initialized: ['encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
"D:\anaconda3\envs\GPTSoVits\python.exe" GPT_SoVITS/s2_train.py --config "D:\Git\GPT-SoVITS\TEMP/tmp_s2.json"
INFO:snape_0319:{'train': {'log_interval': 100, 'eval_interval': 500, 'seed': 1234, 'epochs': 8, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 6, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 20480, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'text_low_lr_rate': 0.4, 'pretrained_s2G': 'GPT_SoVITS/pretrained_models/s2G488k.pth', 'pretrained_s2D': 'GPT_SoVITS/pretrained_models/s2D488k.pth', 'if_save_latest': True, 'if_save_every_weights': True, 'save_every_epoch': 4, 'gpu_numbers': '0'}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 32000, 'filter_length': 2048, 'hop_length': 640, 'win_length': 2048, 'n_mel_channels': 128, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 300, 'cleaned_text': True, 'exp_dir': 'logs/snape_0319'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 8, 2, 2], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 512, 'semantic_frame_rate': '25hz', 'freeze_quantizer': True}, 's2_ckpt_dir': 'logs/snape_0319', 'content_module': 'cnhubert', 'save_weight_dir': 'SoVITS_weights', 'name': 'snape_0319', 'pretrain': None, 'resume_step': None}
phoneme_data_len: 13
wav_data_len: 91
100%|███████████████████████████████████████████████████████████████████████████████| 91/91 [00:00<00:00, 33855.03it/s]
skipped_phone:  0 , skipped_dur:  0
total left:  91
D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
ssl_proj.weight not requires_grad
ssl_proj.bias not requires_grad
INFO:snape_0319:loaded pretrained GPT_SoVITS/pretrained_models/s2G488k.pth
<All keys matched successfully>
INFO:snape_0319:loaded pretrained GPT_SoVITS/pretrained_models/s2D488k.pth
<All keys matched successfully>
D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\optim\lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
0it [00:00, ?it/s]D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:868.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:868.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:868.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:868.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:868.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:868.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
[W reducer.cpp:1353] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator ())
D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:868.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\functional.py:650: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\EmptyTensor.cpp:32.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\autograd\__init__.py:251: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [1, 9, 96], strides() = [46368, 96, 1]
bucket_view.sizes() = [1, 9, 96], strides() = [864, 96, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:334.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
INFO:snape_0319:Train Epoch: 1 [0%]
INFO:snape_0319:[2.7193689346313477, 2.5070364475250244, 9.74919605255127, 22.169567108154297, 0.42936840653419495, 2.4000439643859863, 0, 9.99875e-05]
16it [00:22,  1.38s/it]
INFO:snape_0319:====> Epoch: 1
16it [00:13,  1.19it/s]
INFO:snape_0319:====> Epoch: 2
16it [00:13,  1.19it/s]
INFO:snape_0319:====> Epoch: 3
16it [00:13,  1.20it/s]
INFO:snape_0319:Saving model and optimizer state at iteration 4 to logs/snape_0319/logs_s2\G_233333333333.pth
INFO:snape_0319:Saving model and optimizer state at iteration 4 to logs/snape_0319/logs_s2\D_233333333333.pth
INFO:snape_0319:saving ckpt snape_0319_e4:Success.
INFO:snape_0319:====> Epoch: 4
16it [00:13,  1.19it/s]
INFO:snape_0319:====> Epoch: 5
16it [00:13,  1.21it/s]
INFO:snape_0319:====> Epoch: 6
4it [00:03,  1.15it/s]INFO:snape_0319:Train Epoch: 7 [25%]
INFO:snape_0319:[2.811215877532959, 2.2096385955810547, 7.309819221496582, 20.39468002319336, 0.40301427245140076, 0.8250619769096375, 100, 9.991253280566489e-05]
16it [00:13,  1.18it/s]
INFO:snape_0319:====> Epoch: 7
16it [00:13,  1.20it/s]
INFO:snape_0319:Saving model and optimizer state at iteration 8 to logs/snape_0319/logs_s2\G_233333333333.pth
Traceback (most recent call last):
  File "D:\Git\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 600, in <module>
    main()
  File "D:\Git\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 56, in main
    mp.spawn(
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 202, in start_processes
    while not context.join():
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\serialization.py", line 619, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\serialization.py", line 853, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
RuntimeError: [enforce fail at inline_container.cc:593] . PytorchStreamWriter failed writing file data/1323: file write failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\multiprocessing\spawn.py", line 74, in _wrap
    fn(i, *args)
  File "D:\Git\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 254, in run
    train_and_evaluate(
  File "D:\Git\GPT-SoVITS\GPT_SoVITS\s2_train.py", line 470, in train_and_evaluate
    utils.save_checkpoint(
  File "D:\Git\GPT-SoVITS\GPT_SoVITS\utils.py", line 87, in save_checkpoint
    my_save(
  File "D:\Git\GPT-SoVITS\GPT_SoVITS\utils.py", line 73, in my_save
    torch.save(fea,tmp_path)
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\serialization.py", line 620, in save
    return
  File "D:\anaconda3\envs\GPTSoVits\lib\site-packages\torch\serialization.py", line 466, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:424] . unexpected pos 118142912 vs 118142804

**Comment by XXXXRT666** [comment]
是不是盘里没空间了

**Comment by aigcun** [comment]
> 是不是盘里没空间了

确实空间不多了，但2G还是有的

**Comment by RVC-Boss** [comment]
gpt和sovits中途保存的模型，每个人物加起来可能是会略微超过2G需求
