### ISSUE TITLE
对gpu驱动版本要求是？

### ISSUE THREAD

**Issue by v-yunbin** [RVC-Boss/GPT-SoVITS#83]
`RuntimeError: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new versi        on from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled         with your version of the CUDA driver.`

**Comment by hyhuc0079** [comment]
我测过118 121都可以使用

**Comment by RVC-Boss** [comment]
楼上正解。readme里面写了我测过可以跑通的环境。
楼主的信息应该是pytorch版本（太新）和你装的n卡驱动（太老）不匹配
