### ISSUE TITLE
[bug]请问一下，一键三连的时候，出现了如下的错误：ValueError: not enough values to unpack (expected 4, got 1)

### ISSUE THREAD

**Issue by lckj2009** [RVC-Boss/GPT-SoVITS#832]
训练前的一键三连阶段，出现了如下错误，请问一下该怎么办呀？

![一键三连](https://github.com/RVC-Boss/GPT-SoVITS/assets/52185194/f5033745-ea3f-4fe7-88a5-53d5b66e5e9b)

"E:\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"E:\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"E:\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py
"E:\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py
"E:\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/3-get-semantic.py
"E:\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/3-get-semantic.py
 Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 101, in <module>
    wav_name, spk_name, language, text = line.split("|")
ValueError: not enough values to unpack (expected 4, got 1)

 Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\1-get-text.py", line 118, in <module>
    wav_name, spk_name, language, text = line.split("|")
ValueError: not enough values to unpack (expected 4, got 1)

<All keys matched successfully>
 Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\3-get-semantic.py", line 88, in <module>
    wav_name, spk_name, language, text = line.split("|")
ValueError: not enough values to unpack (expected 4, got 1)

<All keys matched successfully>
"E:\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
"E:\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/1-get-text.py
 Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\1-get-text.py", line 118, in <module>
    wav_name, spk_name, language, text = line.split("|")
ValueError: not enough values to unpack (expected 4, got 1)

"E:\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py
"E:\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py
 Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\2-get-hubert-wav32k.py", line 101, in <module>
    wav_name, spk_name, language, text = line.split("|")
ValueError: not enough values to unpack (expected 4, got 1)

"E:\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/3-get-semantic.py
"E:\GPT-SoVITS-beta0217\runtime\python.exe" GPT_SoVITS/prepare_datasets/3-get-semantic.py
<All keys matched successfully>
 Traceback (most recent call last):
  File "E:\GPT-SoVITS-beta0217\GPT_SoVITS\prepare_datasets\3-get-semantic.py", line 88, in <module>
    wav_name, spk_name, language, text = line.split("|")
ValueError: not enough values to unpack (expected 4, got 1)

<All keys matched successfully>

**Comment by SapphireLab** [comment]
> 检查你的 .list 文件, 里面每行应该是 `音频路径|说话人|语言|对应文本` 的格式, 分隔符号是 `|`.

#684

**Comment by RVC-Boss** [comment]
楼上正解

**Comment by lgkt** [comment]
没错，每行应该是output开头，肯定是在打标时，文本加了回车
