### ISSUE TITLE
运行webui.py后不显示gradio地址

### ISSUE THREAD

**Issue by nogodfox** [RVC-Boss/GPT-SoVITS#838]
使用了autodl的GPT-SoVITS语音合成官方镜像V9版本。然后pull了一下新的代码。
再运行webui就不显示gradio地址了。
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/38777518/65cbd47e-0ea1-46c0-a548-b5f709e13b92)

**Comment by RVC-Boss** [comment]
config.py里面改一下share=True

**Comment by nogodfox** [comment]
@RVC-Boss 已经改过了的，在webui里面也print了确保是true。仍然不显示。
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/38777518/e3c73c88-ecb2-4e5f-bbd0-a3375d010305)
