### ISSUE TITLE
Synthesize text can't work with short text?

### ISSUE THREAD

**Issue by tungthncc** [RVC-Boss/GPT-SoVITS#84]
Hi guys, I am trying to run the inference web UI follows demo, but I noticed that  when the text is short, the inference voice is the same with the reference voice. Did I do something wrong here?

https://github.com/RVC-Boss/GPT-SoVITS/assets/128009347/c160c479-f661-41e2-a84d-d39fd6f9f481

**Comment by juntaosun** [comment]
Temporary workaround to shorten the reference audio to less than 5 seconds

**Comment by RVC-Boss** [comment]
Fixed now.
