### ISSUE TITLE
load audio or ssl error!!!!!! error in Mac SoViTs training 

### ISSUE THREAD

**Issue by OswaldoBornemann** [RVC-Boss/GPT-SoVITS#846]
So when i try to train the SoViTs, I got the error `load audio or ssl error!!!!!!`

**Comment by XXXXRT666** [comment]
full error or screen shot please

**Comment by XXXXRT666** [comment]
Maybe you could check whether FFmpeg is installed using `ffmpeg -version`

**Comment by Song367** [comment]
我的报错是这个：  0it [00:00, ?it/s]Traceback (most recent call last):
  File "E:\workplace\GPT-SoVITS\GPT_SoVITS\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "E:\workplace\GPT-SoVITS\venvs\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "E:\workplace\GPT-SoVITS\venvs\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "D:\compile\python\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\compile\python\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 1455] 页面文件太小，无法完成操作。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\workplace\GPT-SoVITS\GPT_SoVITS\module\data_utils.py", line 111, in get_audio_text_speaker_pair
    spec, wav = self.get_audio("%s/%s" % (self.path5, audiopath))
  File "E:\workplace\GPT-SoVITS\GPT_SoVITS\module\data_utils.py", line 128, in get_audio
    audio_array = load_audio(filename, self.sampling_rate)  # load_audio的方法是已经归一化到-1~1之间的，不用再/32768
  File "E:\workplace\GPT-SoVITS\GPT_SoVITS\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [WinError 1455] 页面文件太小，无法完成操作。
Traceback (most recent call last):
  File "E:\workplace\GPT-SoVITS\GPT_SoVITS\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "E:\workplace\GPT-SoVITS\venvs\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

**Comment by Song367** [comment]
> 我的报错是这个： 0it [00:00，？it / s] Traceback（最近一次调用最后一次）： 文件“ E：\ workplace \ GPT-SoVITS \ GPT_SoVITS \ my_utils.py”，第 14 行，在 load_audio ffmpeg.input（file，threads = 0） 文件“ E：\ workplace \ GPT-SoVITS \ venvs \ lib \ site-packages \ ffmpeg_run.py”，第 313 行，在 run process = run_async（ 文件“ E：\ workplace \ GPT-SoVITS \ venvs \ lib \ site-packages \ ffmpeg_run.py”，第 284 行，在 run_async 中 返回 subprocess.Popen（ 文件“ D：\ compile \ python \ lib \ subprocess.py”，第 969 行，在**init** self._execute_child（args，executable，preexec_fn，close_fds， 文件“ D：\ compile \ python \ lib \ subprocess.py”，行1438，在 _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, OSError: [WinError 1455] 页面文件太小，无法完成操作。
> 
> 在处理上述异常的过程中，又发生了另一个异常：
> 
> 回溯（最近一次调用最后一次）： 文件“E:\workplace\GPT-SoVITS\GPT_SoVITS\module\data_utils.py”，第 111 行，在 get_audio_text_speaker_pair 规范中，wav = self.get_audio（“％s/％s”％（self.path5，audiopath）） 文件“E:\workplace\GPT-SoVITS\GPT_SoVITS\module\data_utils.py”，第 128 行，在 get_audio audio_array = load_audio（filename，self.sampling_rate）# load_audio 的方法已经归一化到-1~1之间的，不用再/32768 文件“E:\workplace\GPT-SoVITS\GPT_SoVITS\my_utils.py”，第 19 行，在 load_audio 中 引发 RuntimeError（f“无法加载音频：{e}”） RuntimeError：无法加载音频：[WinError 1455] 页面文件太小，无法完成操作。 Traceback (most recent call last): 文件“E:\workplace\GPT-SoVITS\GPT_SoVITS\my_utils.py”, 第 14 行，在 load_audio 中 ffmpeg.input(file,threads=0) 文件“E:\workplace\GPT-SoVITS\venvs\lib\site-packages\ffmpeg_run.py”, 第 325 行，在运行中 引发错误('ffmpeg', out, err) ffmpeg._run.Error: ffmpeg 错误（有关详细信息，请参阅 stderr 输出）
> 
> 在处理上述异常的过程中，又发生了另一个异常：

我昨天跑的成功了，今天训练就不行了。我的音频大概12分钟
