### ISSUE TITLE
关于训练集中文掺杂英文的情况

### ISSUE THREAD

**Issue by hyhuc0079** [RVC-Boss/GPT-SoVITS#870]
在一些中文声音样本中经常会混杂一些英文，比如人名，设备型号之类的。
例如下面这种：
tommy我的iphone呢？
你开的是一辆GTR吗？

这种情况list文件中的英文单词会影响训练结果吗？我是说比如bert还是什么里面我记得如果你的标注内容有英文，它在生成注音文件的时候会直接跳过，GPT-sovit里需要处理这些样本吗？比如说改成下面这样,或者直接去掉含英文的样本？
托米我的哀凤呢？
你开的是一辆寄替二吗？

**Comment by RVC-Boss** [comment]
目前训练集还不支持中英混合
