### ISSUE TITLE
关于合成的音频的速度控制，合成时候的音频选项

### ISSUE THREAD

**Issue by RevelationCollection** [RVC-Boss/GPT-SoVITS#871]
问题：
1、合成的音频的语速怎么控制，现在合成出来的音频感觉总是比较快
2、top_k,top_p,temperature这三个参数都是分别控制什么的呢？

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/22661383/d72f1fea-d595-446f-9da5-e9a2477500d6)

**Comment by upseem** [comment]
Top-k 采样
这就像是从一袋糖果中挑选糖果吃。如果袋子里有100种糖果，但你只允许自己从中挑最喜欢的10种（Top-k）来选择。这样做，你很可能挑到你比较喜欢的糖果，但同时也减少了尝试不常吃或新奇糖果的机会。在语音合成中，Top-k 采样帮助模型在生成时从最可能的选项中选择，从而使生成的语音更加连贯和可理解，但也可能减少其多样性。

Top-p (Nucleus) 采样
假设你现在不是只从最喜欢的糖果中选择，而是决定只从能让你满意度超过一定阈值的糖果中选择。这意味着如果很多糖果都很吸引你，你可能会从很多种中选择；但如果只有几种让你满意，你就只从这几种中选择。这种方式更加灵活，可以根据实际情况调整选择的范围。在语音合成中，Top-p 采样让模型根据当前的情况决定考虑多少可能的选项，既保持了内容的相关性，又允许了一定程度的创新和多样性。

温度（Temperature）
想象你正在做菜时调味。温度就像是你加盐的量。如果你加得太少（低温度），菜可能会味道不足，太单调。如果你加得太多（高温度），菜可能会味道过重，难以预测它会有多咸。所以，适量的调味（温度设为 1.0）通常能做出既不单调也不过分的菜。在语音合成中，温度帮助控制生成的多样性和预测性：低温度让语音听起来更加自然和一致，而高温度让语音更加多样和不可预测。
