### ISSUE TITLE
cpu训练，vits模型权重保存时，疑似文件损坏

### ISSUE THREAD

**Issue by wjddd** [RVC-Boss/GPT-SoVITS#878]
使用[s2_train.py](https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/s2_train.py)训练：
GPU环境，G模型文件大小为584.69MB，pth模型文件大小为81MB；
CPU环境，G模型文件大小为584.65MB，pth模型文件大小为80.99MB。

是CPU环境下训练会导致模型文件损坏？

**Comment by XXXXRT666** [comment]
推理时能否加载？

**Comment by wjddd** [comment]
> 推理时能否加载？

能，但合成的音频有问题

**Comment by wjddd** [comment]
@Lion-Wu 请问您之前训练的时候有碰到过这个问题吗？

**Comment by Lion-Wu** [comment]
没有吧，我的sovits模型大小都是84.9MB的，生成的音频都是正常的，你重新训练试试？

**Comment by XXXXRT666** [comment]
也许是保存的偶发性问题

**Comment by XXXXRT666** [comment]
在训练一个epoch保存说不定就行

**Comment by wjddd** [comment]
@XXXXRT666 @Lion-Wu 二位好，我发现问题不在vits模型，而在gpt模型了，是gpt模型训练有问题导致合成的音频有问题，而且我用现成的gpt模型+单独微调的vits模型，合成出来的音频效果更好。感谢二位的答复~
