### ISSUE TITLE
预处理中 SSL 对很多音频输出 Nan 导致大量音频没有被加入训练集

### ISSUE THREAD

**Issue by CloudTronUSA** [RVC-Boss/GPT-SoVITS#89]
在 GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py 里面的这部分
```
ssl=model.model(tensor_wav16.unsqueeze(0))["last_hidden_state"].transpose(1,2).cpu()#torch.Size([1, 768, 215])
if np.isnan(ssl.detach().numpy()).sum()!= 0:
    return
```
SSL对很多音频返回了 nan 的 tensor 数组 导致很多音频被跳过没有加入训练集中

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/96151994/fd48794b-fa98-4743-9f87-7cea7bad1b8e)

@RVC-Boss 请问这是正常的吗？还是说对音频有特殊要求？

**Comment by CloudTronUSA** [comment]
解决了，是半精度带来的问题。看来即使是 4090 也最好关掉半精度，对速度和显存占用基本没影响。

**Comment by CloudTronUSA** [comment]
解决了，是半精度带来的问题。看来即使是 4090 也最好关掉半精度，对速度和显存占用基本没影响。

**Comment by RVC-Boss** [comment]
> 解决了，是半精度带来的问题。看来即使是 4090 也最好关掉半精度，对速度和显存占用基本没影响。

看起来，hubert提取步骤出现nan的人还挺多的，我强行单精度好了。

**Comment by Hardwell99** [comment]
这个会不会就是导致一键三连后 logs/XXX/6-name2semantic.tsv 文件没有内容，继而导致微调时出现 ZeroDivisionError ？的原因？
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/104831430/e1c7d085-69b3-4d7b-9309-3e7f3f563877)
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/104831430/b1ae5fa0-d8c7-476a-9b82-38873757ea26)
