### ISSUE TITLE
推理到最后直接输出Error

### ISSUE THREAD

**Issue by showkeyjar** [RVC-Boss/GPT-SoVITS#891]
如题，更新到最新的版本后，点击“合成语音”，推理完成后不再显示语音播放面板，直接输出Error

console 未显示任何错误输出

更新日期  2024-03-30
更新版本 6ccfd362e98390a92775fc134e04b66ac05b705e

**Comment by RVC-Boss** [comment]
这个信息太少了，判断不了

**Comment by SapphireLab** [comment]
show us the cmd

**Comment by showkeyjar** [comment]
cmd: python GPT_SoVITS/inference_webui.py

console里显示的就是合成语音的最后一句，没有别的内容

**Comment by showkeyjar** [comment]
更新到最新版本 4afecd1950845a974350cd2d8dc8dcf12398fba9 ，问题解决
