### ISSUE TITLE
关于ASR模型下载的问题

### ISSUE THREAD

**Issue by quark-mac** [RVC-Boss/GPT-SoVITS#897]
1.整合包使用fast whisper 模型时从huggingface下载模型，但由于国内网络原因**无法下载**
2.模型**会自动下载到c盘占用系统空间**，希望能保存到整合包路径下

**Comment by SapphireLab** [comment]
临时处理方案：手动移动：#796 or 自动下载：#861

1. 已经加过镜像 `https://hf-mirror.com` 应当能正常下载才对，可以访问 `https://hf-mirror.com/Systran/faster-whisper-large-v3/tree/main` 试试。
2. 一开始是考虑到可能存在多个项目都使用whisper模型可以直接从cache读取，所以没有写成强制下载到整合包路径。
现在的话就看是增加一个迁移的可选项，直接从cache目录移动到整合包还是按照 861 直接下载到整合包内。

**Comment by RVC-Boss** [comment]
楼上正解
faster whisper理论上应该已经换了hf到国内镜像源了，或者手工下载再指定hf模型路径

**Comment by quark-mac** [comment]
> 临时处理方案：手动移动：#796 or 自动下载：#861
> 
> 1. 已经加过镜像 `https://hf-mirror.com` 应当能正常下载才对，可以访问 `https://hf-mirror.com/Systran/faster-whisper-large-v3/tree/main` 试试。
> 2. 一开始是考虑到可能存在多个项目都使用whisper模型可以直接从cache读取，所以没有写成强制下载到整合包路径。
>    现在的话就看是增加一个迁移的可选项，直接从cache目录移动到整合包还是按照 861 直接下载到整合包内。

感谢回复，希望早日添加迁移选项到webui
