### ISSUE TITLE
Python 3.11.8版本无法安装requirements

### ISSUE THREAD

**Issue by RXLX-CHINA** [RVC-Boss/GPT-SoVITS#899]
RuntimeError: Cannot install on Python version 3.11.8; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by SapphireLab** [comment]
选择自己配高版本环境就需要修改一些包的版本，比如numba，直到没有冲突。

**Comment by XXXXRT666** [comment]
推荐使用3.9进行安装依赖

**Comment by RVC-Boss** [comment]
楼上和楼上上正解
