### ISSUE TITLE
Pretrained models language

### ISSUE THREAD

**Issue by Weroxig** [RVC-Boss/GPT-SoVITS#901]
The filenames for the pretrained models include "Chinese" specifically. Would it be better for other languages to use a different version of these models?
For example if i wanted to run GPT-SoVITS on english should I replace these?
 chinese-hubert-base ->https://huggingface.co/facebook/hubert-base-ls960
 chinese-roberta-wwm-ext-large -> https://huggingface.co/FacebookAI/roberta-large

**Comment by RVC-Boss** [comment]
Maybe it will be better. And you should train your own base model using your proposed hubert and bert models.
