### ISSUE TITLE
新增SP5停顿失败

### ISSUE THREAD

**Issue by fangg2024** [RVC-Boss/GPT-SoVITS#902]
我在symobls.py文件的pu_symbols后面加了个“SP5”，然后对训练集（就是有.list文件那个）一键三连报异常：

  File "/home/fangg/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
	size mismatch for enc_p.text_embedding.weight: copying a param with shape torch.Size([322, 192]) from checkpoint, the shape in current model is torch.Size([323, 192]).
Traceback (most recent call last):
  File "/home/fangg/tts/GPT-SoVITS-main/webui.py", line 647, in open1abc
    with open(semantic_path, "r",encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/SP184/6-name2semantic-0.tsv'

![SP5](https://github.com/RVC-Boss/GPT-SoVITS/assets/165561558/f553eb21-7d19-4944-95e1-8d8c3448a5e2)

如果不加这个“SP5”是可以生成6-name2semantic-0.tsv文件的，我想知道加这个“SP5”后需要改哪里？我查了“SP2”，就两个地方有，但使用时没有问题，哎，这个代码感觉好脆……

**Comment by KamioRinn** [comment]
底膜没有，不能改

**Comment by fangg2024** [comment]
感谢回答……
意思是需要底模有这个“SP5”？底模是哪个？如果改不了真的很受限制啊，有别的办法么？

**Comment by KamioRinn** [comment]
改不了

**Comment by RVC-Boss** [comment]
目前只能省省，就这几个名额orz

**Comment by fangg2024** [comment]
好吧，感谢回答，但这个项目真的很好啊……

**Comment by zhouxuan-home** [comment]
请问能实现（1s）这种增加停顿吗，有没有方法想亲自实现一下
