### ISSUE TITLE
推理界面是否可以自动列出所有参考音频？

### ISSUE THREAD

**Issue by rickyrick2002** [RVC-Boss/GPT-SoVITS#905]
如下图所示，链接 https://huggingface.co/spaces/XzJosh/Ruo-GPT-SoVITS 

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/106572242/91d95337-2c00-4892-803f-39e150a3fda6)

这个能列出所有参考音频（应该就是切分后的音频）的功能，是项目本身自带的，还是这个up自己制作的呢？

如果是自带的，想问下怎么样可以在推理界面用到呢？因为这样就不用每次手动在文件夹里选参考音频，然后输入文字，再推理了。

**Comment by vvip2u** [comment]
这个可以自己写个界面来完成

**Comment by rickyrick2002** [comment]
问了是别人自己改的
