### ISSUE TITLE
是否可以将录制好的音频文件变声？

### ISSUE THREAD

**Issue by tsavpyn** [RVC-Boss/GPT-SoVITS#925]
我有一段录制好的人声音频，是否可以用GPT-SoVITS用已有的模型对它变声？

感谢

**Comment by XXXXRT666** [comment]
暂时不支持

**Comment by dvdcjw** [comment]
这是tts，text to speech

**Comment by ben0oil1** [comment]
有个骚操作。
你用asr把你录制好的内容转化成文本；
然后用这个项目训练一个声音模型，然后用上一步生成的文本进行再一次的合成，并使用你自己录好的音频作为参考音频。
当然，鉴于本项目目前的合成结果吞字的质量问题，这个显然是有点夸张了，就是个脑洞

你应该考虑一下变声器相关的项目。

**Comment by SapphireLab** [comment]
#639 可以使用此方式。
