### ISSUE TITLE
请问需要多少G的显卡可以跑呢？

### ISSUE THREAD

**Issue by xihajun** [RVC-Boss/GPT-SoVITS#934]
如题

**Comment by XXXXRT666** [comment]
6G以上最佳

**Comment by siliverwolf** [comment]
128MB显存路过

**Comment by XXXXRT666** [comment]
> 128MB显存路过

这，开个浏览器看视频都有点费劲吧

**Comment by siliverwolf** [comment]
> > 128MB显存路过
> 
> 这，开个浏览器看视频都有点费劲吧

显存不是内存

**Comment by XXXXRT666** [comment]
> > > 128MB显存路过
> > 
> > 这，开个浏览器看视频都有点费劲吧
> 
> 显存不是内存

视频编码解码

**Comment by siliverwolf** [comment]
> > > > 128MB显存路过
> > > 
> > > 这，开个浏览器看视频都有点费劲吧
> > 
> > 显存不是内存
> 
> 视频编码解码

用CPU跑，还有就是显卡有8G的融合内存

**Comment by xihajun** [comment]
谢谢
