### ISSUE TITLE
参考音应用场景一点思考，例如喜怒哀乐的参考音，在项目中该如何实施（让一个人录制喜怒哀乐的一些参考音，对普通人来说感觉也是比较苦难的）

### ISSUE THREAD

**Issue by daliang0222** [RVC-Boss/GPT-SoVITS#940]
如标题所讲，最近在思考一个问题，看一些作者分享的模型包中包含一些息怒了哀乐的参考，如果我想在实际项目中结合ai判定人物情绪，然后使用对应的情绪的参考音进行tts，那么问题就来，复刻一个人的声音，想让一个普通人像播音员一样录制几段喜怒哀乐的参考音，感觉不太现实，所以这种喜怒哀乐的参考，实际应用的场景应该是什么呢？有哪位哥们交流解惑吗

**Comment by X-T-E-R** [comment]
方法1：左AI踩右AI上天，反正你有数据，再练一个RVC，用RVC转换标准参考音频成新的参考音频（想法来自@是林克不是塞尔达）

方法2：右转Bert Vits

**Comment by daliang0222** [comment]
感觉不错的想法  我去试试
