### ISSUE TITLE
遇到一个bug，求大佬解决！！！！

### ISSUE THREAD

**Issue by lwc8699793** [RVC-Boss/GPT-SoVITS#951]
问题描述：
我尝试用tts去将三字经的注释翻译，遇到一部分内容会卡住，无法合成语音。
然后我发现文本被切分后会高频出现这种问题，可能是一些字导致的。
例如：历史上称为隋文帝。他的儿子隋炀帝杨广即位后，荒淫无道，
这一段中“荒淫无道”无法被合成
类似的情况还有许多。
截图如下：
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/51874230/56f38689-0023-4511-a84b-016caaf80775)

**Comment by SapphireLab** [comment]
更新一下整合包到 0306 试试(类似问题 #854 #918 #928
