### ISSUE TITLE
[BUG]中文批量离线ASR工具[使用Faster Whisper (多语种)模型]读取含有中文文件夹路径会生成一个0kb list文件

### ISSUE THREAD

**Issue by Maolaohei** [RVC-Boss/GPT-SoVITS#955]
达摩ASR在中文路径中能够正常生成list文件
使用Faster Whisper large-v3及其Faster Whisper其他模型
在输入文件夹路径中如果还有中文
就会出现这种情况
![图片](https://github.com/RVC-Boss/GPT-SoVITS/assets/24179463/27443e95-4d80-4df7-8f82-79ade43e228c)
改成英文路径就能正常ASR了。是Faster Whisper不支持中文路径吗？
版本是:git clone Apr 6, 2024

**Comment by SapphireLab** [comment]
做了尝试没测出来。

![Image_1712737810962.jpg](https://github.com/RVC-Boss/GPT-SoVITS/assets/36986837/78538887-01cc-4f39-a6b9-f0377b12523c)

**Comment by Maolaohei** [comment]
![图片](https://github.com/RVC-Boss/GPT-SoVITS/assets/24179463/a6589ab4-58dc-4cf2-92bb-b9d6bffe610d)
会不会是多级和中文目录有关:比如我的是 C:\中文1\中文2

**Comment by SapphireLab** [comment]
哦，因为出现了特殊字符[]，和中文关系不大，faster-whisper的遍历是按原作者用了glob匹配，特殊字符需要转义，funasr就不是，所以出现此问题。现在就修。

**Comment by Maolaohei** [comment]
可以读取[xx]文件夹了
