### ISSUE TITLE
语言支持是否能扩展？

### ISSUE THREAD

**Issue by renwei-work** [RVC-Boss/GPT-SoVITS#957]
请问语言支持除了中英日，还能支持其他的如西班牙语法语吗？
或者要扩展的话如何扩展?

**Comment by XXXXRT666** [comment]
加入对应语言g2p和字典，最好重新训练底膜

**Comment by RVC-Boss** [comment]
也可以不完整训练底模，但是新语种数据量要比微调大一些，至少几个小时量级得有
g2p一定得加
