### ISSUE TITLE
asr模型重复下载？

### ISSUE THREAD

**Issue by NaughtDZ** [RVC-Boss/GPT-SoVITS#970]
我已经下载了faster-whisper-large-v3模型并把model.bin放到了GPT-SoVITS\tools\asr\models下，但是离线ASR这一步依然在下载，而且每次都下载不成功。

**Comment by NaughtDZ** [comment]
总算下载成功了，控制台打印：
I:\GPT-SoVITS\runtime\lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Naught\.cache\huggingface\hub\models--Systran--faster-whisper-large-v3. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development


也就是说，明明我asr\models有模型，它还是重复下了一遍放到“C:\Users\Naught\.cache\huggingface\hub\models--Systran--faster-whisper-large-v3”这里。。。

还是说我要创建GPT-SoVITS\tools\asr\models\models--Systran--faster-whisper-large-v3这个目录，然后把模型放进去？
如果是后者那教程里写的就不够清楚，
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/37768911/642cceec-fb2e-4d1c-893d-fa6847564e80)

**Comment by SapphireLab** [comment]
#897

**Comment by XXXXRT666** [comment]
下载模型包后应该解压将整个文件夹放进去

**Comment by RVC-Boss** [comment]
楼上正解
