### ISSUE TITLE
Python 3.10 & Python 3.9 install broken

### ISSUE THREAD

**Issue by TheGermanEngie** [RVC-Boss/GPT-SoVITS#989]
I have attempted to install and run this program with your suggested environment when I am running CUDA 12.3: `Python 3.10.13, PyTorch 2.1.2, CUDA 12.3` and I get an ffmpeg error "module 'ffmpeg' has no attribute 'input'" when running the "Start audio slicer".

When I try and run what you have in the Linux install `conda create -n GPTSoVits python=3.9`, everything works up until the second step "Start Batch ASR", when I get this error: `Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file`.

I have gotten this error before on a previous project, and it means that it requires CUDA version 11 rather than CUDA 12. I would suggest updating your instructions so that people running the "default" linux install (with just python=3.9) who have CUDA 12 do not run into the same problem as me. Please fix the project so that when people use the Python 3.10 environment they don't run into the ffmpeg error.

**Comment by Dako2** [comment]
Also having this issue with cuda 12.1 and python 3.9
