### ISSUE TITLE
一个关于LangSegment库的神奇bug

### ISSUE THREAD

**Issue by wavetao2010** [RVC-Boss/GPT-SoVITS#990]
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/45758593/690b5543-e814-4a09-b355-cf6d3488c2eb)
只要遇到”加分！加分！“两个连续就会出现空的结果，导致报错。而单独的”加分！“却不会导致结果报错。
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/45758593/d271ed19-af00-4459-909b-f00bfd97e9a2)
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/45758593/0734a094-65c8-445b-b6e4-5e7fb99604d0)
所以大家在使用的时候，如果出现报空的情况下，还是得多加一层判断，保证正确执行。

**Comment by SapphireLab** [comment]
成功复现了，只要两个加分之间存在任意(数量)标点就会被识别为阿拉伯语 (ar)，然后被默认过滤器过滤掉

![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/36986837/2293e522-1053-40fa-99fe-8f180abd06a2)

**Comment by RVC-Boss** [comment]
ok，我去打一个新的整合包

**Comment by YowFung** [comment]
你们都能安装 LangSegment 0.3.3 版本的吗？我咋看到官方最新版本是 0.2.0 呢？

**Comment by maolintao** [comment]
> 你们都能安装 LangSegment 0.3.3 版本的吗？我咋看到官方最新版本是 0.2.0 呢？

解决了吗，咋安装0.3.3

**Comment by lhhssd** [comment]
> > 你们都能安装 LangSegment 0.3.3 版本的吗？我咋看到官方最新版本是 0.2.0 呢？
> 
> 解决了吗，咋安装0.3.3

解决了嘛？大佬我也是这个没有setLangfilters函数

**Comment by YowFung** [comment]
破案了，LangSegement 现在 PyPi 上只有 0.2.0 这一个版本，之前最新的是 0.3.5，后面被覆盖了。可能是原作者误上传了旧版的把最新的那些版本覆盖了。

**Comment by lhhssd** [comment]
> 破案了，LangSegement 现在 PyPi 上只有 0.2.0 这一个版本，之前最新的是 0.3.5，后面被覆盖了。可能是原作者误上传了旧版的把最新的那些版本覆盖了。

哇，那真是这样，希望原作赶紧上传上一个版本吧0.0
