### ISSUE TITLE
想请问一下GPT模型和SOVITS模型在输出音频中起到了什么样的作用？如果我拿两个不同的数据集做出来的模型混合使用会怎么样呢？

### ISSUE THREAD

**Issue by BOCEAN-FENG** [RVC-Boss/GPT-SoVITS#996]
比如A的GPT模型和B的SOVITS模型混用

**Comment by XXXXRT666** [comment]
TTS推理的时候，只用GPT模型也能得到很好的结果：底模自带根据参考音频习得口癖和音色的功能，只是微调后会更香
GPT模型和SoVITS模型一起使用的时候，全是噪音：sovits轮数太高，训崩了
1、GPT：语调、停顿、说话习惯，sovits：口癖咬字、音色
2、只用一个另一个默认是用的底模兜底

**Comment by Downupanddownup** [comment]
> TTS推理的时候，只用GPT模型也能得到很好的结果：底模自带根据参考音频习得口癖和音色的功能，只是微调后会更香 GPT模型和SoVITS模型一起使用的时候，全是噪音：sovits轮数太高，训崩了 1、GPT：语调、停顿、说话习惯，sovits：口癖咬字、音色 2、只用一个另一个默认是用的底模兜底

关于sovits轮数这点，我的使用体验倒是和你的不太一样。sovits轮数我拉到100，配合gpt底模使用，感觉没什么问题。但是gpt轮数拉高了，却特别容易出现复读、吞字、参考泄露的问题。我之前拿一段100分钟的素材进行训练，比较了底模、10、20、30、40、50轮的gpt模型，感觉上还是底模和10轮的gpt效果比较好。然后关于噪音的问题，我感觉上和参考音频关系很大，推理的过程中，参考音频的一些特性会被放大，如果参考音频上有些许噪音，推理之后生成的音频的噪音会更加明显。

**Comment by AIliang-1103** [comment]
> > TTS推理的时候，只用GPT模型也能得到很好的结果：底模自带根据参考音频习得口癖和音色的功能，只是操纵后会更香GPT模型和SoVITS模型一起使用的时候，全部是噪音：sovits轮数太高，训崩了 1、GPT：语调、停顿、说话习惯，sovits：口癖咬字、音色 2、只用另一个默认是用的底模兜底
> 
> 关于so​​vits轮数这一点，但是我的使用体验倒是和你不太一样。sovits轮数我拉到100，打gpt底模使用，感觉没什么问题。gpt轮数拉高了，却特别容易出现复读、吞字、大概泄露的问题。我之前拿一段100分钟的素材进行训练，比较了底模、10、20、30、40、50轮的gpt模型，感觉还是上底模和10轮的gpt效果比较好。然后关于噪音的问题，我感觉上和参考音频关系很大，推理的过程中，参考音频的一些特性会被放大，如果音频参考上一些许噪音，推理之后生成的音频的噪音会比较多明显。

请教一下sovits轮数为什么我只能拉到25,。包括情感能否训练出来?

**Comment by RVC-Boss** [comment]
> > TTS推理的时候，只用GPT模型也能得到很好的结果：底模自带根据参考音频习得口癖和音色的功能，只是微调后会更香 GPT模型和SoVITS模型一起使用的时候，全是噪音：sovits轮数太高，训崩了 1、GPT：语调、停顿、说话习惯，sovits：口癖咬字、音色 2、只用一个另一个默认是用的底模兜底
> 
> 关于sovits轮数这点，我的使用体验倒是和你的不太一样。sovits轮数我拉到100，配合gpt底模使用，感觉没什么问题。但是gpt轮数拉高了，却特别容易出现复读、吞字、参考泄露的问题。我之前拿一段100分钟的素材进行训练，比较了底模、10、20、30、40、50轮的gpt模型，感觉上还是底模和10轮的gpt效果比较好。然后关于噪音的问题，我感觉上和参考音频关系很大，推理的过程中，参考音频的一些特性会被放大，如果参考音频上有些许噪音，推理之后生成的音频的噪音会更加明显。

嗯，复读漏字这些是GPT影响的。第一个问题前面的漏都提到了，第二个问题会同时具备2个模型的对应的一些的特征。
